keep-network/keep-core

solidity/contracts/KeepRandomBeaconService.sol
solidity/contracts/examples/KeepRandomBeaconServiceUpgradeExample.sol
solidity/test/random_beacon_service/TestUpgrade.js

See https://github.com/keep-network/keep-ecdsa/pull/327
Previously, we initialized the implementation contract in the first step of the upgrade and that was giving us some possibility to interact with the new contract before it should actually be used. In the worst case, this could work as an upgrade backdoor on our side allowing us to upgrade the
system faster, without keeping the one day delay promise.
Here, we move the initialization call to complete upgrade function.
We use mapping to store implementation initialization data as it is allocating storage based on keccak256 hash of the key and entry so it lowers the possibility of clashing with implementation fields. See: https://solidity.readthedocs.io/en/v0.5.15/miscellaneous.html#mappings-and-dynamic-arrays
Complete upgrade function …

Service contract implementation initialization call moved to the complete upgrade step

---

solidity/contracts/TokenStaking.sol
solidity/test/token_stake/TestTokenStake.js

Fixes: #1520 
In `recoverStake()` we were not checking if undelegation block is non-zero. As a result, the require for undelegation period to be over was always `true` when the stake hasn't been undelegated first:
```
block.number > operatorParams.getUndelegationBlock().add(undelegationPeriod)
```
This allowed owner to recover the stake without undelegating it first.
We fix this problem in this PR adding a non-zero check for undelegation block in `recoverStake()`.
Bonus: grouped `cancelStake`, `recoverStake`, and `delegate` tests in three `describe`s.

Do not allow to recover stake without first undelegating

---

solidity/contracts/libraries/operator/DKGResultVerification.sol
solidity/test/random_beacon_operator/TestDkgMisbehavior.js
solidity/test/random_beacon_operator/TestPublishDkgResult.js

Closes: #1524
Three additional validations added to `bytes` input parameters in `DKGResultVerification.verify` to limit the possibility of arbitrarily moving bytes between `groupPubKey` and `misbehaved` by the submitter:
- `groupPubKey` must have exactly `128` bytes
It is altbn128 G2 point in uncompressed form; it must have `128` bytes.
- `misbehaved` can be up to `group_size - signature_threshold` bytes
`misbehaved` can be empty or can have some elements but it can never have more elements than the group size minus the minimum DKG result signature threshold. No group member will vote on the result where it is marked as misbehaving. If the result is going to be accepted, it must have at least the minimum signature threshold. Hence, the maximum number of members indicated as misbehaving is …

DKGResultVerification.verify byte inputs validation

---

solidity/contracts/cryptography/AltBn128.sol
solidity/contracts/stubs/AltBn128Stub.sol
solidity/test/TestBLS.js
solidity/test/altbn128/TestAltBn128.js
solidity/test/altbn128/TestAltBn128.sol

Fixes: #1522
There were two potential issues with `AltBn128` functions and `BLS` as an effect:
- `g1Unmarshal` could be reading out-of-bounds of the signature from dirty memory.
- `g1Unmarshal` could be reading all of the signature. If more than 64 bytes were supplied, they were ignored for the purposes of signature validation.
A similar problem was with `g2Unmarshal` reading group public key and `g2Decompress`.
Here we ensure each of those functions in `AltBn128.sol` properly validates input length.
As a result, `BLS.verify` and `BLS.verifyBytes` are now safe.
All invalid input length cases are covered with unit tests both for `AltBn128` and `BLS`. Although all the requires are in `AltBn128` library and are covered by unit tests for `AltBn128`, this is such an important requirement that …

Validate length of G1 and G2 bytes for AltBn128

---

go.mod
go.sum
pkg/chain/ethereum/utility.go
solidity/contracts/IRandomBeacon.sol
solidity/contracts/KeepRandomBeaconServiceImplV1.sol
solidity/contracts/examples/CallbackContract.sol
solidity/scripts/request-relay-entry-with-callback.js
solidity/test/random_beacon_service/TestPricing.js
solidity/test/random_beacon_service/TestPricingFees.js
solidity/test/random_beacon_service/TestRelayRequestCallback.js

Closes: #1527 
See https://github.com/keep-network/keep-common/pull/22
See https://github.com/keep-network/keep-ecdsa/pull/339
Instead of allowing the customer to pass callback signature of their choice, we now expect that the callback contract delcares public `__beaconCallback(uint256)` function.
Previously, `KeepRandomBeaconServiceImplV1` allowed senders to specify an arbitrary method that would receive a callback once the beacon generated a relay entry. Arbitrary callbacks could be used to force the service contract to execute many functions within the keep contract system. For example, functions with `onlyServiceContract` modifier in the operator contract.
We still allow specifying an address of the callback contract. This could be beneficial in a situations where one contract pays …

__beaconCallback(uint256)

---

.circleci/config.yml
solidity/dashboard/Dockerfile
solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/dashboard/src/contracts.js
solidity/package.json

This PR represents an adjustment to how we manage cross-repository
versioning, package publishing, and dependency package and contract
references. Here are the major changes:
- `package.json` for Solidity contracts is set to `<version>-pre`, with no
numeric suffix.
- A new Circle job, `publish_npm_package`, runs on master merge. This
This job updates the package version to `-pre.<number>`, where `<number>`
represents a new, unpublished version.
- Contract artifacts from the contract migration are copied to an `artifacts/`
subdirectory and included in the package.
- The package is published to the main npm repository (not the GitHub
package repository).
- We trigger a downstream build (placeholder, didn't get a chance to hook this
up yet, plus we should wait until this build strategy …

Version Tether: Continuous packaging and versioning

---

docs/keep-client-quickstart.adoc

In some cases previously-set variables can contain spaces, so if these
parameters aren't wrapped in quotes you can get unexpected and
hard-to-track-down docker errors.

You Can Quote Me On That: Add quotes to quickstart volume and env parameters

---

solidity/contracts/TokenStaking.sol
solidity/contracts/stubs/DelegatedAuthorityStub.sol
solidity/test/token_stake/TestDelegatedAuthority.js

Refs: #1490 
In #1519 individual keeps can't ask the factory to place locks on operators on their behalf, because only one lock per operator contract is permitted. To get around this, keep factories need a way to delegate their authority to keeps. The method in this PR lets keeps claim delegated authorization, which is verified by calling the factory. After authorization has been delegated, the keep's authorization status matches that of the factory, covering approval and panic button status in the registry and individual operators' authorization.

Add delegated authorization functionality

---

infrastructure/terraform/keep-dev/dns.tf

Here we provide two public domains for use in the keep-dev environment
if we need them.  It may be that we want to expose applications to the
internet from our dev env for testing or sharing.  The immediate need
here was to expose the tbtc dapp with certificate so some testing could
be done.  That uses the dev.tbtc.network domain.  I went ahead and added
dev.keep.network while I was in here.
These domains are sub-domains which are NS aliased to their respective
parents on Cloudflare, keep.network and tbtc.network.

keep-dev: dev.*.network hosted zones

---

infrastructure/kube/keep-dev/keep-dapp-token-dashboard-deployment.yaml
infrastructure/kube/keep-dev/keep-dapp-token-dashboard-ingress.yaml
infrastructure/kube/keep-dev/keep-dapp-token-dashboard-service.yaml
infrastructure/kube/keep-test/keep-dapp-token-dashboard-deployment.yaml
infrastructure/kube/keep-test/keep-dapp-token-dashboard-ingress.yaml
infrastructure/kube/keep-test/keep-dapp-token-dashboard-service.yaml

This turned it a bit of an adventure but here we are.  We're working on hardware wallet support for the token-dashboard, as part of that we need a proper SSL connection.
I screwed around with self-signed certs for a bit which works but decided to go ahead and just put  ourselves behind Cloudflare. 
This took upgrading our Cloudflare setup to support custom hostnames, which we've done.  This does mean that we can't use our Google Hosted Zone subdomains for frontends that need secure connections, but I'll be looking into how to handle this via Terraform (in a later step).
- Moved the dapp deployment behind an ingress using Cloudflare
- Separated service/ingress configs into separate files.  We've been organizing configuration file scope around configuring a single object type for a given …

keep-dev/test: Token Dashboard SSL

---

.circleci/config.yml

We use openzeppelin test environment with its own version of ganache.

Remove redundant CircleCI step

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/dashboard/src/contracts.js

This PR bumps a `@keep-network/keep-core` dependency to `>0.13.0-pre <0.13.0-rc`. Also, commit(db18ca4) was a test commit and shouldn't be merged to the master and this PR fixes it and imports artifacts from the `@keep-network/keep-core` package.

Fix @keep-core/keep-network dependency- dapp

---

solidity/dashboard/src/components/DataTable.jsx

In the previous implementation, the `DataTable` component was saving the` renderContent` property in the local state in the `componentDidMount` hook. Thus the 'renderContent' always pointed to the function passed to the component at the beginning. Because of this, the [authorization function](https://github.com/keep-network/keep-core/blob/master/solidity/dashboard/src/pages/AuthorizerPage.jsx#L30) fails.

Fix table rendering- dapp

---

solidity/dashboard/src/components/DataTable.jsx

Backporting the change from https://github.com/keep-network/keep-core/pull/1574:
> In the previous implementation, the `DataTable` component was saving the `renderContent` property in the local state in the `componentDidMount` hook. Thus the `renderContent` always pointed to the function passed to the component at the beginning. Because of this, the authorization function fails.

v0.12.0-rc backport of table rendering fix

---

docs/run-random-beacon.adoc

Extracted and slightly reworked some parts from https://github.com/keep-network/keep-core/pull/1455 to cover KEEP token dashboard terms, staking, and authorizations.

Run Random Beacon Docs: section about staking in KEEP token dashboard

---

go.mod
go.sum
solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/package-lock.json
solidity/package.json

The procedure:
- Updated `keep-common` dependency to `v0.2.0-rc`.
- Bumped up Solidity contracts version to `0.13.0-rc`, published to NPM registry
- Set `keep-core` contract dependency version in dashboard to `0.13.0-rc.0`, tagged `v0.13.0-rc`
- Bumped up Solidity contracts version to `0.14.0-pre`
We will update dashboard contract dependency to `>0.14.0-pre <0.14.0-rc` separately, once we publish contracts to NPM registry.

v0.13.0-rc release preparation

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json

After we released `0.13.0-rc` and the first `0.14.0-pre` has been deployed to NPM package registry, we can update KEEP token dashboard contract dependency to point to the most recent version.
See https://github.com/keep-network/keep-core/pull/1593

Setting keep-core contracts dependency to >0.14.0-pre <0.14.0-rc

---

pkg/chain/ethereum/ethereum.go

Refs: https://github.com/keep-network/keep-core/issues/1598
In this PR we increase the delay to 1 sec. between retries (10) to fetch selected participants in case of Infura's synchronization issue.

Increasing the delay to 1 sec and up to 10 retries to get participants

---

solidity/dashboard/src/components/AuthorizationHistory.jsx
solidity/dashboard/src/components/AuthorizeContracts.jsx

Fixes incorrect links in the "Authorize Contracts" and "Authorization History" blocks in the web interface.
Fixes #1577

fixed link "View in Block Explorer"

---

solidity/contracts/ManagedGrantFactory.sol
solidity/contracts/TokenGrant.sol
solidity/test/helpers/grantTokens.js
solidity/test/token_grant/TestManagedGrantFactory.js

Refs: #1529 
Using `abi.decode` instead of tightly packed `_extraData` in `receiveApproval` adds a slight overhead of unnecessary calldata bytes, but makes the parsing of the arguments simpler.
Providing a dual interface of `receiveApproval` which doesn't return values, and `createManagedGrant` which returns the managed grant address, but requires prior setup in the token, accommodates both on-chain and dApp use-cases without requiring workarounds.

Dual interface + `abi.decode` for managed grants

---

solidity/contracts/IRandomBeacon.sol
solidity/contracts/examples/CallbackContract.sol

Refs: #1537
We have `IRandomBeacon` interface for requesting entries from Keep Random Beacon but we had no interface allowing to indicate the given contract is beacon consumer and to ensure the correctness of `__beaconCallback(uint256)` signature. Adding this interface here.

Interface for beacon consumers: IRandomBeaconConsumer

---

docs/run-random-beacon.adoc

Updating contract addresses to the ones deployed for `0.13.0-rc`.
See: https://www.npmjs.com/package/@keep-network/keep-core/v/0.13.0-rc.0

Updated Ropsten contract addresses for 0.13.0-rc

---

.circleci/config.yml

We've been rolling on `latest` image publishes across our keep-dev and keep-test environments for awhile.  While this is fine for our dev environment, it's time we work against properly versioned images for our test/Ropsten environment.
Circle builds that run against a git tag generate a Circle env var `CIRCLE_TAG`.  This is perfect for our Docker image tagging needs.  However, the `CIRCLE_TAG` enviroment variable isn't generated for builds that don't run on a tag.  e.g. all keep-dev / master builds.  We already use environment based Circle contexts to factor out environment specific configs from the Circle config space, so it's a natural fit to handle this in the same way.  The Circle Context environment variable is `DOCKER_IMAGE_TAG`.  For keep-dev it's set to `latest`, and for …

Docker Publish: Contextual Tagging

---

cmd/network.go
cmd/start.go
pkg/firewall/firewall.go
pkg/net/key/ethereum_key.go
pkg/net/libp2p/authenticated_connection.go
pkg/net/libp2p/authenticated_connection_test.go
pkg/net/libp2p/channel.go
pkg/net/libp2p/libp2p.go
pkg/net/libp2p/libp2p_test.go
pkg/net/libp2p/transport.go
pkg/net/libp2p/unicast_channel_test.go
pkg/net/local/local.go
pkg/net/net.go
pkg/net/watchtower/watchtower.go
pkg/net/watchtower/watchtower_test.go
solidity/migrations/2_deploy_contracts.js

Refs https://github.com/keep-network/keep-core/issues/1588
So far we had just one rule we had to enforce when establishing a connection: the remote peer needs to have a minimum stake and the minimum stake has to be maintained for the entire lifetime of the connection.
It is still the case but we are discovering that more rules are needed and that we need exceptions from some of the rules in certain circumstances.
For example, for ECDSA client, we should require a minimum stake if the client has no active keeps. If the given client does no longer have a minimum stake but it has a number of active keeps we should let the client join the network and execute signing for those remaining keeps.
To do that, we introduce `net.Firewall` interface which is a facade behind which we can hide even the …

Firewall: define your own rules for connections with remote peers

---

solidity/contracts/ManagedGrantFactory.sol
solidity/contracts/TokenGrant.sol
solidity/migrations/2_deploy_contracts.js
solidity/test/token_grant/TestManagedGrantFactory.js

Provide the policy as an argument when creating a grant, and also return a grant's staking policy address in its unlocking schedule.

Customize managed grant staking policy

---

infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/provision-keep-client.js

Off by a bit here, we're staking 20M KEEP for each keep-client
deployment.  WHile this is normally fine we'll run out of tokens before
we can get to the desired number of clients for scaling tests against
Ropsten.

GCP Staking: One too many zeros

---

pkg/beacon/beacon.go
pkg/beacon/relay/event/events_tracking.go
pkg/beacon/relay/event/events_tracking_test.go

Refs https://github.com/keep-network/keep-core/issues/1608
In this PR we add tracking functionality for `GroupSelectionStarted` and `RelayEntryRequested` events. In prevents from receiving duplicate events that sometimes happen during the Infura deployment.

Events tracking functionality

---

solidity/dashboard/src/services/token-grants.service.js

We no longer need to pack parameters, we switched from `abi.encodePacked()` to `abi.encode()` in the grant contract.

Update create grant params

---

pkg/beacon/relay/dkg/result/integration_test.go
pkg/beacon/relay/dkg/result/submission.go
pkg/beacon/relay/dkg/result/submission_test.go
pkg/beacon/relay/gjkr/integration_test.go
solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/libraries/operator/DKGResultVerification.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorDKGResultStub.sol
solidity/test/random_beacon_operator/TestDkgMisbehavior.js
solidity/test/random_beacon_operator/TestPublishDkgResult.js

Close https://github.com/keep-network/keep-core/issues/1585
In this PR we are increasing the DKG nofail signature threshold to 75%.  It gives us a 25% safety margin for relay entry signing.

Adding signature safety margin on DKG result

---

solidity/contracts/Registry.sol
solidity/contracts/stubs/RegistryStub.sol
solidity/test/TestRegistry.js

Closes: #1600
We now allow specifying a panic button per operator contract. Such individual panic buttons can be disabled what makes the operator contract permanently approved. There is a default panic button value that is assigned to each new operator contract.
The only role which can disable a panic button for operator contract is governance. We don't want the registry keeper to have a power of permanently approving operator contracts if this action can not be later undone.

Panic button per operator contract with a possibility of being disabled

---

docs/run-random-beacon.adoc

We ran a redeployment of v0.13.0-rc today so that we could refresh the
token supply.  Here we reference those new contract addresses.

run-random-beacon: Ropsten Contract Update

---

cmd/start.go

Currently, the keep client immediately exits unsuccessfully if the operator address does not meet the following conditions:
- operator address in the configuration is correct and it has KEEP tokens delegated
- operator contract has been authorized to operate on stake
This is not ideal for certain use cases. To handle those use cases I would like the node to wait for a specified amount of time to allow the address to meet the conditions above before crashing.
This PR adds a `-w`/`--wait-for-stake` integer flag which will cause the node to crash after that number of minutes if the address is still in violation of any conditions listed above. Until the stake is found or the timeout is reached, every minute the node will log a WARN-level message about the missing stake.
If the flag is …

Add stake-timeout flag to keep-client start

---

go.mod
go.sum
pkg/net/libp2p/libp2p.go

Closes  #1639 
Here we introduce some tweaks related to peer discovery:
- Reduced the DHT refresh round period from `1 hour` to `30 minutes`. This change should make peer discovery a bit faster especially for edge peers. Also, this value should not harm performance with too frequent refreshes.
- Increased bootstrap round period from `10 seconds` to the default value of `30 seconds`. This change should help for problems with `libp2p` dial backoffs which can occur when an offline peer is dialled to often by frequent bootstrap rounds. Also, there are no benefits from running bootstrap round every `10 seconds` so `30 seconds` seems to be a reasonable value.
- Adjusted code to the new`go-libp2p-bootstrap` library version.

Peer discovery tweaks

---

go.mod
go.sum
pkg/firewall/firewall.go
pkg/firewall/firewall_test.go

For every connection handshake, we store in a time cache the result of `HasMinimumStake` call for the particular operator to minimize Ethereum client calls in case that operator has no minimum stake and tries to connect with us all the time.
Closes: https://github.com/keep-network/keep-core/issues/1627
Depends on: https://github.com/keep-network/keep-common/pull/32

Cache stake

---

infrastructure/gcp/keep-test/google-functions/keep-faucet/deploy-faucet.sh
infrastructure/gcp/keep-test/google-functions/keep-faucet/issue-grant.js
infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json

We did a fresh migration of `v0.13.0` against Ropsten.  Here we update the faucet to use that new version.  This is already deployed.
---
In addition to the roll forward we've limited the number of faucet invocations that can be run at a time and made grants revocable with a cliff.  This is to help mitigate scripts draining token supply.

ropsten-faucet: Roll forward and friends

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/libraries/operator/Groups.sol
solidity/migrations/2_deploy_contracts.js
solidity/test/random_beacon_operator/TestGroupExpiration.js
solidity/test/random_beacon_operator/TestGroupTermination.js

We had a bug in `expireOldGroups` function of `Groups` library allowing the `expiredGroupOffset` to go too far and read from groups array at non-existing index. It resulted in blocking the beacon forever by `requestRelayEntry` reverting every single time it was called.
There are a couple of improvements here to fix this problem.
First of all, we fix the loop so that it never reads from groups array with an index equal or greater to groups array length. Secondly, in `selectGroup` function, we first `expireOldGroups` before checking if we have any active groups to proceed with. Last but not least, in `genesis` function we now run group expiration before checking the number of active groups.
There is still a little chicken and egg problem here addressed with appropriate documentation on …

Group expiration off-by-one bugfix

---

pkg/altbn128/altbn128.go
pkg/beacon/beacon.go
pkg/beacon/relay/node.go
pkg/net/libp2p/channel_manager.go
pkg/net/libp2p/libp2p.go
pkg/net/local/local.go
pkg/net/net.go

Closes #1641
Here we introduce a new behavior of the client which now subscribes to all broadcast channels and relays received messages to connected peers. This way the client acts as an auxiliary node even if they don't take part in given protocol execution. This change should make the network
more robust.

Broadcast channel relay

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/migrations/2_deploy_contracts.js
solidity/test/helpers/initContracts.js
solidity/test/random_beacon_service/TestPricingFees.js

Refs: #1545 
- Group member base reward: `1000000 * 1e11 wei = 1M Gwei`. 
It gives group reward of `64*1M Gwei`.
- Group active time: `86400 * 7 / 15 blocks = ~7 days`.
- Stake initialization period: `43200 seconds = 12 hours`.
- Stake undelegation period: `7776000 seconds = 3 months`.
- DKG contribution margin: `5%`.
- Result publication block step stays at `3 blocks`.

On-chain system parameters update

---

solidity/contracts/KeepRandomBeaconOperator.sol

1M gwei is 1,000,000 * 1e9. The previous group reward was expressed as a multiple of 100 gwei,
and the 1e11 unit remained in the new calculation of #1653

Fix typo in group reward

---

.circleci/config.yml
solidity/dashboard/Dockerfile

This step ensures that the latest contract version will be resolved even
if docker layer caching is in place. It also makes it so that new
releases can bump the contract build and dashboard build both, knowing
the dashboard build will correctly resolve the contract build.
Also included: running keep-test builds on release branches, which start
with `releases\/`.
---------
After this, I think the release process for keep-core is this:
- Create a new release branch.
- Bump the changes.
- Commit + push.
- Approve the build.
- *PR optional.*

Upgradeable Dashboard: Add contract resolution step to dashboard build

---

.circleci/config.yml

This doesn't work the way we expect with tag builds so I'm reverting for now.  Will pick this up soon with a proper solution.
Namely - Using the Circle context to try and set `$DOCKER_IMAGE_TAG=$CIRCLE_TAG` takes the literal `$CIRCLE_TAG`

Circle: Kill Docker image tagging

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json

After tagging `v0.15.0-rc` and deploying `0.15.0-pre` contracts to NPM
registry we can update the dependency in KEEP token dashboard.

Set keep-core contracts dependency to >0.15.0-pre <0.15.0-rc

---

solidity/contracts/TokenGrant.sol

I have not changed anything in the content and only adjusted the
formatting to use `@notice` and `///`. Other contracts either already
follow this scheme or will follow it in the future (more PRs to come).

Consistent formatting of function docs in TokenGrant

---

pkg/beacon/relay/node.go
pkg/net/libp2p/libp2p.go

Refs #1652
Current settings of the channel forwarder can cause an uncontrolled message propagation because forwarders live for `1` hour and libp2p `pubsub` cache holds seen messages only for `2` minutes. Because of that, a message can continuously flow in the network even if it is no longer relevant for anyone. If we have a significant number of `keep-core` clients in the network and there is a high rate of messages in general, the network can be congested. As a consequence, clients will experience resource usage peaks which can be deadly in certain environments. To prevent such problems we:
- remove broadcast channel messages forwarding for DKG
- reduce broadcast channel messages forwarders TTL for relay entries from `1` hour to `90` seconds

Broadcast channel forwarder tweaks

---

pkg/beacon/relay/entry/entry.go

Simple change allowing to debug connectivity/availability problems of group members:
```
11:20:05.796  INFO keep-regis: group [0x26069ab14237c4870153eecf613b4cbd1eab36b876ac35f80600172df11f3cac25cb2999fcf35689769e326ae8d513167aad0284001cffd2739f288de6921ccc14e7da53a2256e935463ea1f1ed9c5ef345cad8504d7c966b01a5c430faf9635075534842e0afb3af30cc906cb9f0d3be1a3bc3dcf4000b4e6ad8c0f2a7f1528] loaded with [25] members groups.go:162
11:20:26.628  INFO keep-relay: monitoring chain for a new relay entry relay.go:48
11:20:26.628  INFO keep-beaco: new relay entry requested at block [2998] from group [0x26069ab14237c4870153eecf613b4cbd1eab36b876ac35f80600172df11f3cac25cb2999fcf35689769e326ae8d513167aad0284001cffd2739f288de6921ccc14e7da53a2256e935463ea1f1ed9c5ef345cad8504d7c966b01a5c430faf9635075534842e0af …
```

Log number of valid signature shares received for timed out relay entry

---

solidity/contracts/AdaptiveStakingPolicy.sol
solidity/test/token_grant/TestStakingPolicy.js

Customize stakeahead (in seconds and whether it considers cliff), and set the policy minimum as a multiple of the staking contract minimum.

Add adaptive staking policy

---

solidity/test/token_stake/TestTokenStakeLock.js

We had two PRs merged one after another - one PR added additional test
using `magpie` name and another PR renamed `magpie` to `beneficiary` so
when they both landed in `master`, that new test started failing.

Fixed failing test after renaming magpie to beneficiary

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/libraries/operator/DelayFactor.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorPricingRewardsWithdrawStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorPricingStub.sol
solidity/migrations/2_deploy_contracts.js
solidity/test/helpers/initContracts.js

The mail goal is to expose the information allowing to resume relay entry signing after client crash. With the changes here, the client can call `isEntryInProgress()`, and then looking at
`currentEntryStartBlock`, `currentRequestGroupIndex`, and `currentRequestPreviousEntry` join the signing process.
This was not straightforward and I was head-slapped by operator contract size problem. To be able to make the mentioned information public, I had to do two changes to reduce operator contract size:
- Extracted delay factor calculation to a library. It let me save `~78 bytes`.
- Eliminated `SigningRequest` struct. It let me save `~286 bytes`.
At overall, with all the changes here, the operator contract size increased from `24728` to `24887`, as computed with:
```
let bytecode = …
```

Expose information allowing to resume entry signing, reduce contract size

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/Registry.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorCallbackStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorDKGResultStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorGroupSelectionStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorPricingRewardsWithdrawStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorPricingStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorRewardsStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorStub.sol
solidity/migrations/2_deploy_contracts.js
solidity/test/TestRegistry.js
solidity/test/helpers/initContracts.js
solidity/test/random_beacon_operator/TestManageServiceContracts.js
solidity/test/random_beacon_operator/TestRelayEntryTimeout.js
solidity/test/random_beacon_service/TestSelectOperator.js

Some operator contracts, such as `KeepRandomBeaconOperator`, may want to specify a list of service contracts they want to work with. Service contracts can be added and removed from that list.
Previously, `KeepRandomBeaconOperator` contract had an owner which could add and remove contracts from that list and owner was set to the address which deployed the contract.
We do not want to have our contracts ownable so here we introduce service contract keeper role, set per the operator contract. Service Contract Keeper is authorized to manage service contract list for the given operator contract. Specifically, `KeepRandomBeaconOperator` checks if the address calling `addServiceContract` and `removeServiceContract` is the service contract keeper.

Service Contract Keeper and non-ownable KeepRandomBeaconOperator contract

---

solidity/dashboard/src/contracts.js

We renamed Registry contract to KeepRegistry in #1687. Having a new version
published to NPM registry, we can now update KEEP Token Dashboard.

Update Registry->KeepRegistry in KEEP token dashboard

---

solidity/contracts/AdaptiveStakingPolicy.sol
solidity/contracts/GrantStakingPolicy.sol
solidity/contracts/GuaranteedMinimumStakingPolicy.sol
solidity/contracts/KeepRegistry.sol
solidity/contracts/KeepToken.sol
solidity/contracts/PermissiveStakingPolicy.sol
solidity/contracts/StakeDelegatable.sol
solidity/contracts/TokenGrant.sol
solidity/contracts/TokenGrantStake.sol
solidity/contracts/TokenStaking.sol

In https://github.com/keep-network/keep-core/commit/fe158f77cec0a56178f93e3210e3fa7bc5688132 I updated `_extraData` parameter documentation making information about the expected content of `_extraData` byte array up to date.
Everything else here is an update of documentation format to be the same as in
`keep-ecdsa` ([example](https://github.com/keep-network/keep-ecdsa/blob/master/solidity/contracts/BondedECDSAKeep.sol)) and `tbtc` ([example](https://github.com/keep-network/tbtc/blob/master/solidity/contracts/deposit/Deposit.sol)) with no content changes.

Tiny fix for stake function documentation and larger fix for documentation format.

---

solidity/contracts/ManagedGrantFactory.sol

`start` should go before `cliff`. The order in the code is right, it's just about incorrect docs.

Fixed order of parameters in ManagedGrantFactory.receiveApproval docs

---

solidity/contracts/ManagedGrantFactory.sol
solidity/contracts/TokenGrant.sol

Sometimes `cliff` stood for timestamp, and sometimes for duration.
Rename cliff durations to `cliffDuration` and clarify the documentation.

Remove ambiguity between cliff durations and timestamps

---

solidity/contracts/TokenGrant.sol

This is a security-critical action so it is worth having some sort of a notification we can watch for.

Emit an event when staking contract is authorized in TokenGrant

---

solidity/package-lock.json
solidity/package.json

We published `1.0.0` so it's time for `1.1.0-pre`.
See `releases/mainnet/v1.0.0` @ a0a44da42a488d561cd0f68fa3d62e51577b103d

Bumping up contracts version to 1.1.0-pre

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json

See https://github.com/keep-network/keep-core/pull/1701
After releasing 1.0.1 we are bumping up keep-core contracts dependency version to `>1.1.0-pre <1.1.0-rc`.

Bumping up dashboard dependency to keep-core contracts to >1.1.0-pre <1.1.0-rc

---

CODEOWNERS

Setting @Shadowfiend and @pdyraga as code owners for `keep-core` smart contracts deployed to mainnet in 1.0.1 release.

CODEOWNERS for smart contracts

---

pkg/beacon/relay/entry/entry.go

Closes #1690 
When member jumps outside the message loop, it has enough valid shares and can complete the signature in the next step. Because of that, share exchange context can be cancelled at this stage because there is no more sense to continue the communication with other members. This way we can save some resources and eliminate useless message retransmissions.

Cancel share exchange context before completing signature

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/libraries/operator/Groups.sol
solidity/test/random_beacon_operator/TestSlashing.js

We decided to use a conservative relay entry timeout punishment for the first months of the network so that we can give time to operators to properly configure their clients and learn how to monitor their health.
The rules are as follows:
- 1% of the minimum stake for the first 3 months
- 50% of the minimum stake between the first 3 and 6 months
- 100% of the minimum stake after the first 6 months.
This change affects only relay entry timeout, all the other cases of misbehavior are still on 100% of the minimum stake.

Conservative relay entry timeout punishment for the first months

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/KeepRandomBeaconServiceImplV1.sol
solidity/test/random_beacon_service/TestRelayRequestCallback.js

Make sure not to spend more than 2 million gas on a callback. This is to protect members from relay entry failure and potential slashing in case of any changes in .call() gas limit.

Hardcode callback gas limit

---

infrastructure/gcp/keep-test/google-functions/keep-faucet/issue-grant.js
infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json
infrastructure/gcp/keep-test/google-functions/keep-faucet/package.json

Here we do a few things:
- Roll the faucet forward to `v0.14.0-rc` contracts
- Update `approveAndCall` to work with ^
- Include a cliff and `revocable` status for faucet grants to help combat script kiddies (by allowing us to revoke grants)

Roll faucet forward to v0.14.0-rc

---

docs/run-random-beacon.adoc

We have a public repo for Docker images now.  Here we document that.

run-random-beacon: Add Docker Hub

---

solidity/contracts/IRandomBeacon.sol
solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/KeepRandomBeaconService.sol
solidity/contracts/KeepRandomBeaconServiceImplV1.sol
solidity/contracts/libraries/operator/DKGResultVerification.sol
solidity/contracts/libraries/operator/DelayFactor.sol
solidity/contracts/libraries/operator/GroupSelection.sol
solidity/contracts/libraries/operator/Groups.sol
solidity/contracts/libraries/operator/Reimbursements.sol

We want to use the same format of documentation as in the rest of Keep contracts.
No major content changes, just log formatting.

Beacon smart contracts docs reformatted

---

cmd/start.go

Fixed a mistake that got through in the last PR. There are two objects supplied to a string with 1 template. This will fix it.

Fix wait-for-stake log

---

pkg/beacon/relay/entry/entry.go

Refs #1690 
We added `cancelCtx()` call to cancel signature shares retransmission if the current member has enough shares to reconstruct signature. From a selfish perspective of that member it absolutely makes sense but from a broader perspective it does not and it slows down relay entry submission.
Specifically, if members 10-64 collected enough shares to reconstruct entry, they stop broadcasting. If members 1-9 still do not have enough shares, none of them will be able to publish the result and we'll have to wait until member 10 is eligible.
Retransmitting shares until the entry is on-chain makes sense.

Do not cancel the context before entry makes it to the chain

---

solidity/migrations/2_deploy_contracts.js

Closes #1660 
Quoting from the referenced issue:
> 5% gives 1/20 behavior in the worst-case scenario where all submitters use the maximum gas. If submitters use less gas we generate more groups and become time-constrained faster. Assuming money spent on ticket submission uses the same average gas price as DKG submission, this doesn't have unexpected adverse effects on staker finances which are calculated on a max-gas basis (or specifically, the average-case ticket submission costs will mirror the worst-case costs proportionally).
>
> Normal gas costs tend to be in the range of 6 ~ 12 gwei, meaning that 1 ~ 2% would give expected behavior most of the time but increase the entry frequency required for the system to stay up without intervention by 2.5 ~ 5x in the worst-case. We do not …

DKG contribution margin set to 3%

---

go.mod
go.sum

This version points to the same code as the commit hash we used but
it's nicer to refer to a released version instead of some magical
commit.

Updating keep-common dependency to v0.3.1-rc

---

pkg/beacon/relay/groupselection/groupselection.go
pkg/beacon/relay/groupselection/groupselection_test.go
solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorDKGResultStub.sol
solidity/test/random_beacon_operator/TestPricingRewards.js
solidity/test/random_beacon_operator/TestPublishDkgResult.js

6 blocks result publication step gives an operator one hour to react before the relay entry timeout happens. It should also help to minimize ETH expenses by avoiding the situation when two or more members submit at the same time because of slow new block times.
Same about ticket submission round duration which has been adjusted accordingly to 6 blocks with 12 blocks mining lag.

Set result publication block step to 6 blocks

---

solidity/contracts/KeepRandomBeaconOperator.sol

In` startGroupSelection` we return the costs of the previous failed - group selection to the service contract. We were obtaining the service contract reference with `ServiceContract(msg.sender)`. It works fine only when `msg.sender` is a service contract which is not a case for genesis. Instead of `msg.sender` we should use `groupSelectionStarterContract` that is set for this exact purpose in `genesis` and `createGroup` both calling the internal `startGroupSelection`.

Use groupSelectionStarterContract to reimburse for failed DKG

---

solidity/artifacts

This PR removes an accidentally merged symlink which was used for local development.

Removing a symlink for local development

---

solidity/package-lock.json
solidity/package.json

We tagged `1.1.0-rc` so it is time to bump up contracts to `1.2.0-pre`.
See https://github.com/keep-network/keep-core/pull/1722

Bumping up contracts version to 1.2.0-pre

---

infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json
infrastructure/gcp/keep-test/google-functions/keep-faucet/package.json

The faucet will use the latest release of keep-core `1.1.0-rc`.
It's already up and running.

Updated keep-core dependency to 1.1.0-rc for faucet

---

docs/run-random-beacon.adoc

Updated addresses of the testnet contracts to the ones deployed as part
of `1.1.0-rc` ropsten migrations.

Updated contracts addresses to deployed in 1.1.0-rc

---

pkg/chain/ethereum/ethereum.go

Experience shows that this situation happens very often on Infura-like deployments and ERRORs produced there were adding too much noise. Especially that in almost all cases the second attempt was successful. 
We do not want to clutter logs with ERRORs that are not really errors - we need to accept
that it's how most ETH clients load balancers work.

Log getting selected participant retries on info level

---

infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json
infrastructure/gcp/keep-test/google-functions/keep-faucet/package.json

Updated faucet keep-core dependency to use contracts deployed with version 1.1.1-rc.

Updated faucet to use 1.1.1-rc contracts

---

solidity/contracts/KeepRandomBeaconOperator.sol

There are 78 blocks for ticket submission, not 39.

Minor fix to ticket submission procedure docs

---

docs/run-random-beacon.adoc

Updated doc with addresses of contracts deployed for 1.1.1-rc version.

Updated doc with 1.1.1-rc contracts addresses

---

infrastructure/gcp/keep-test/google-functions/keep-faucet/issue-grant.js

We were missing `t` at the end of the parameter.

Fixed tiny spelling error in faucet response message

---

solidity/dashboard/package.json

Changing version because caret ^ bumped it to 2.25.1 which throws an error described [here](https://github.com/moment/moment/issues/5484)

Changing version of moment to a fixed 2.24.0

---

pkg/beacon/relay/registry/groups.go

We added some more context to the stale groups check loggers. Now the message will contain the public key of the group to help identify for which group the problem occurred.

Improved stale group errors logging

---

solidity/scripts/pricing-test.js

We can use operator contract balance check to make sure the value of
rewards stored in the contract matches the total ETH balance stored on
the contract.

Added operator contract balance checks to the pricing test script

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/migrations/2_deploy_contracts.js

The current (`master`) value of DKG contribution margin is 3% and group active time is ~one week. Here we propose to set DKG contribution margin to 1% and increase group active time to ~two weeks.
Operator contract uses gas price ceiling to calculate fee required for executing
a new group selection and DKG. With a gas price ceiling of `30Gwei`, the fee is:
`30000000000 * (200000+ 1740000) = 58200000000000000`
Assuming the actual gas price is `20Gwei`, operator spends
`(30000000000 * 200000) + (20000000000 * 1740000) = 40800000000000000`
on triggering group selection and DKG result submission (start group selection
reimbursement of `200k` gas is always multiplied by the price ceiling).
As a result, `58200000000000000 - 40800000000000000 = 17400000000000000` is
returned back to the service …

DKG contribution fee set to 1% and group active time to ~2 weeks

---

go.mod
go.sum
pkg/beacon/relay/registry/groups.go
pkg/beacon/relay/registry/groups_test.go
pkg/beacon/relay/registry/storage.go

Depends on https://github.com/keep-network/keep-common/pull/34
When we save membership in the storage, we execute `GroupPublicKeyBytesCompressed()` on the membership passed as a parameter so that we can evaluate the name of the directory where we want to put the serialized membership.
Groups registry, on the other hand, holds group public key in an uncompressed form so that memberships can be quickly fetched from the registry when on-chain events occur.
When the group registry was asking the storage to archive group, it was passing uncompressed public key and the storage could not locate the directory to archive.
It is fixed here - storage expects compressed public key in archive function and group registry passes group public key in compressed form. 
I have also updated error handling in …

Group archival fix

---

infrastructure/terraform/keep-prd/ip.tf
infrastructure/terraform/keep-prd/variables.tf

Before we can setup Service and Ingress configurations we need to have some static ip's available to assign to these resources.  Here we do that for services going live next week.
- Regional IP for Electrum LoadBalancer Service
- Global IP for tbtc-dapp Ingress
- Global IP for token-dashboard
GCP requires a global IP for Ingress resources.  I believe this is because an Ingress object is region agnostic.
All of these are applied to the environment and are available.

keep-prd: Service/Ingress Static IPs

---

configs/config.toml.SAMPLE
pkg/net/libp2p/channel_manager.go
pkg/net/libp2p/libp2p.go

We introduced message dissemination to handle cases when nodes from the
same topic are not connected with each other and topic messages are not
relayed between them. It helped with message delivery but also caused
problems with throttled message validation on slow clients.
Message dissemination is enabled only for relay entries and given that:
- we have now 6 * 64 blocks to submit entry before the timeout,
- client tries to connect to all bootstrap nodes from the list,
- in most cases, dissemination is not needed and it's just a last-resort
option when something goes wrong with the network,
we should enable it only on selected bootstrap nodes. All clients tries
to connect to all bootstrap nodes so dissemination on bootstrap nodes
should be enough. Even more, since bootstrap nodes also try …

Message dissemination is disabled by default and can be configured

---

go.mod
go.sum

The referenced code is the same but it's nicer to refer to tagged release for mainnet.

keep-common dependency updated to the most recent release

---

docs/run-random-beacon.adoc

A few housekeeping items here:
1. `docker run` command cleanup.  Here we set an entrypoint to explicitly override the `ENTRYPOINT` set in the `Dockerfile`.  Without it you will have two `--config` flags set on the running process running the command provided in this doc.  Somehow we've turned out ok here but it's caused some confusion with testers.  Also removed the `-it` arguments from the command as they're not strictly required unless you're overriding `ENTRYPOINT` with `bash` or `sh`.
2. Some syntax highlighting motivated by the comments in https://github.com/keep-network/keep-ecdsa/pull/396
3. Small text for bootstrap peers.  `docs.keep.network` renders the peers on multiple lines without this option set.

Docs: run-random-beacon Update

---

infrastructure/terraform/keep-prd/backend.tf
infrastructure/terraform/keep-prd/base.tf
infrastructure/terraform/keep-prd/nats.tf
infrastructure/terraform/keep-prd/variables.tf

Here we setup 3 NAT's across us-central1 to provide egress traffic routing for GKE and private subnet instances.
- 3 static IP's for each NAT
- us-central1-a/b/c NAT instance deployment
- Network routes for nat routing - included as network tags for devices that need to route through the NATs
- NAT firewall rules

keep-prd: NATs

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml

Here we update the Deployment to fetch token-dashboard version 1.0.0 from our public Dockerhub repo.
This went out as part of the Random Beacon deploy.

keep-prd: Full Token Dashboard Deploy

---

docs/run-random-beacon.adoc

The Beacon deployment was wrapped up today and we can now include mainnet addresses needed for running the keep-client :tada:.  These were lifted from the migration script log that was uploaded to Keybase by Kuba.

Docs: run-random-beacon Mainnet Addresses

---

solidity/dashboard/src/components/ChooseWallet.jsx
solidity/dashboard/src/components/Web3ContextProvider.jsx

Refs: #1761
If the user selects the ledger wallet and closes modal and then selects the trezor wallet, it will see the accounts from a ledger wallet because they were stored in the web3 context state. This update fixes it and stores the available accounts in the component state.

Fix a list of accounts to select from a hardware wallet

---

.circleci/config.yml

We've hit a new phase of the system and as a result won't be iterating as frequently on contracts.  To save build time and some build failure frustration we need to work through I'm disabling `migrate_contracts` and associated jobs in the keep-dev workflow.
We'll be preserving client build / publish jobs.
All against the keep-dev workflow
- Separated the `keep-client` and `initcontainer-provision-keep-client` publish steps into separate jobs.  We need to be able to publish only the keep-client image for keep-dev as of this PR.  To accommodate that we split the publish step.
- Renamed the keep-dev workflow to remove `migrate`
- Removed `migrate_contracts`
- Removed `build_initcontainer`
- Removed `trigger_downstream_builds`
- Removed `publish_npm_package`
- Removed `publish_contract_data` …

Circle: Disable keep-dev migrations

---

docs/run-random-beacon.adoc

Updating the doc to reference v1.2.0-rc contracts.

run-random-beacon: Update Ropsten Contracts

---

solidity/dashboard/src/connectors/utils.js

The hardware wallet providers require a `chainId` param as a number but the `getChainId` function returned this param as a string. This update addresses it and makes that a `getChainId` function returns a number.

Return the chanID as a number

---

CODEOWNERS

After releasing 1.1.2 and deploying random beacon contracts to mainnet
we want to make sure we do not accidentally modify those files. Having
CODEOWNERS on them will help with that.

Adding 1.1.2 mainnet contracts to CODEOWNERS

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/dashboard/src/components/AuthorizeContracts.jsx
solidity/dashboard/src/components/BondingSection.jsx
solidity/dashboard/src/contracts.js
solidity/dashboard/src/services/tbtc-authorization.service.js

This PR comments out a few of the bits and pieces around bond funding to allow it to be deployable despite tBTC contracts not yet being deployed. This will allow bootstrapping of available bonds and keep-ecdsa nodes so that once tBTC goes live, operators will already be available to back deposits.
Additionally, this fixes a few small bugs:
- Non-operators don't see the option to set available bond on their own address.
- Owners with grants properly see their operators in the bonding list.

TBTC-less bonding: Allow bonding before tBTC is out

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml

Patch release of the token-dashboard that includes ETH bonding and `BondedECDSAKeepFactory` Authorization for keep-ecdsa operators.

Roll forward to v1.0.2

---

cmd/network.go
cmd/start.go
pkg/net/gen/pb/handshake.pb.go
pkg/net/gen/pb/handshake.proto
pkg/net/libp2p/authenticated_connection.go
pkg/net/libp2p/authenticated_connection_test.go
pkg/net/libp2p/libp2p.go
pkg/net/libp2p/libp2p_test.go
pkg/net/libp2p/transport.go
pkg/net/libp2p/unicast_channel_test.go
pkg/net/security/handshake/connection_handshake.go
pkg/net/security/handshake/connection_handshake_test.go
pkg/net/security/handshake/marshaling.go
pkg/net/security/handshake/marshaling_test.go

There are two protocols run by Keep network: `keep-beacon` and `keep-ecdsa`. Both initiator and responder are expected to pass the protocol identifier during the handshake. This change lets to eliminate an honest, misconfigured nodes from the subnetwork they do not support.
This is what we should expect when a node not sending protocol identifier tries to connect to node expecting the protocol identifier:
> 22:10:29.446  INFO     swarm2: got error on dial: failed to negotiate security protocol: connection handshake failed: [read tcp4 127.0.0.1:3922->127.0.0.1:3921: read: connection reset by peer] swarm_dial.go:420
>   [/ip4/127.0.0.1/tcp/3921] failed to negotiate security protocol: connection handshake failed: [read tcp4 127.0.0.1:3922->127.0.0.1:3921: read: connection reset by peer]] …

Pass protocol identifier during the handshake

---

go.mod
go.sum

The updated version contains the same code as the previously referenced commit hash. We are preparing for a new RC so we are setting the dependency to a particular version instead of a commit hash.
See https://github.com/keep-network/keep-common/releases/tag/v1.1.0

Updated keep-commons dependency to 1.1.0

---

scripts/macos-setup.sh

Update "brew install solidity" to "brew install solidity@5". It installs the correct version of Solidity (0.5.17) to compile the SCs in keep-core code base.

Update to solidity@5 | macos-setup.sh

---

solidity/dashboard/src/css/typography.less

This PR fixes the positioning of the arrow icon in the link. This problem occurs on the production build only.
Bug:
Fix:

Fix the positioning of the arrow icon in the link

---

solidity/dashboard/src/services/tbtc-authorization.service.js

It is possible that the operator is in multiple bonds (see [KeepBonding contract](https://github.com/keep-network/keep-ecdsa/blob/master/solidity/contracts/KeepBonding.sol#L32)). In that case the `bondedEth` value should be the sum of all locked bonds for a given operator.

Fix the bonded eth amount

---

docs/run-random-beacon.adoc

After spending some time doing targeted testing with single client deployments across providers it feels safe to lower the instance type recommendations here.  Worth noting that depending on how you deploy your keep-client, particularly if you're in a containerized environment sharing VM resources across multiple applications, be sure to take that into consideration when selecting a machine.

Reduce instance type recommendations

---

docs/run-random-beacon.adoc
infrastructure/kube/keep-test/keep-client-1-statefulset.yaml
infrastructure/kube/keep-test/keep-client-2-statefulset.yaml
infrastructure/kube/keep-test/keep-client-3-statefulset.yaml
infrastructure/kube/keep-test/keep-client-4-statefulset.yaml
infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/provision-keep-client.js
solidity/package.json
solidity/scripts/circleci-migrate-contracts.sh
solidity/truffle-config.js

It's been awhile since we've cut a Ropsten release, this PR includes a couple extra updates as a result.
- `truffle-config.json`: Move `ropsten` network ETH hostname to env var.  Now that we're open source we shouldn't expose Infura accounts to source control
- `circleci-migrate-contracts.js`:  Forklift `ETH_HOSTNAME` from Circle Context to utility box.   This is so the truffle config has a value for the env var set.
- `keep-test/keep-client-*-statefulset`:  Moving to a  config where we read the Infura host from a Secret, again to obfuscate from source control.

Release: 1.2.3-rc (Ropsten)

---

docs/run-random-beacon.adoc

We are having problems with GCP bootstrap peers so we are temporarily
removing them from testnet bootstrap peers list. We still have two boar.network
bootstraps there so we should be good with the redundancy we have.

Temporarily removed GCP bootstrap peers

---

pkg/chain/gen/Makefile

Fixes: #1854
Running `go run github.com/ethereum/go-ethereum/cmd/abigen` should run the package-specific version of abigen and we can avoid problems with incompatible `abigen` versions this way.
My initial fix was based on extracting right version of abigen into keep-common, but after re-checking  on a clean environment seems like much simpler approach works too. Not sure what was wrong previously...

Use package-specific version of abigen

---

solidity/contracts/TokenStaking.sol
solidity/contracts/stubs/TokenStakingSlashingStub.sol
solidity/contracts/stubs/TokenStakingStub.sol
solidity/migrations/2_deploy_contracts.js
solidity/test/RolesLookupTest.js
solidity/test/helpers/initContracts.js
solidity/test/token_grant/TestManagedGrant.js
solidity/test/token_grant/TestManagedGrantFactory.js
solidity/test/token_grant/TestStakingPolicy.js
solidity/test/token_grant/TestTokenGrant.js
solidity/test/token_grant/TestTokenGrantRevoke.js
solidity/test/token_grant/TestTokenGrantStake.js
solidity/test/token_grant/TestTokenGrantWithdraw.js
solidity/test/token_stake/TestDelegatedAuthority.js
solidity/test/token_stake/TestMinimumStake.js
solidity/test/token_stake/TestPunishment.js
solidity/test/token_stake/TestTokenStake.js
solidity/test/token_stake/TestTokenStakeLock.js

`TokenStaking` needs to resolve grant ID when stake is delegated from a grant so that it can later deposit undelegated tokens in `TokenStakingEscrow` with the original grant's unlocking parameters. This is needed to implement stake top-ups properly.

Added TokenGrant as a constructor parameter of TokenStaking

---

solidity/contracts/cryptography/AltBn128.sol

ECMUL address is `0x07`, not `0x70`.

Fixed typo in ECMUL precompile address

---

infrastructure/kube/keep-test/eth-network-ropsten-configmap.yaml
infrastructure/kube/keep-test/keep-client-0-statefulset.yaml
infrastructure/kube/keep-test/keep-client-1-statefulset.yaml
infrastructure/kube/keep-test/keep-client-2-statefulset.yaml
infrastructure/kube/keep-test/keep-client-3-statefulset.yaml
infrastructure/kube/keep-test/keep-client-4-statefulset.yaml
infrastructure/kube/keep-test/keep-network-ropsten-relay-request-cronjob.yaml
solidity/dashboard/src/config/config.json

We want a way to protect ETH hosts from source control.   We already support `eth-network-<network-name>` Secrets for envs, so we're moving the hosts there.
- Switch to Alchemy for hosting (for now)
- Move `rpc-url` and `ws-url` from `ConfigMap` `eth-network-ropsten` to `Secret` `eth-network-ropsten`
- Change `KeyRef` for `ETH_RPC_URL` and `ETH_WS_URL` from `ConfigMap` to `Secret`
- Deploy `keep-client-0` and `keep-client-1` against the new setup.

keep-test: Move ETH host to Secret

---

pkg/altbn128/altbn128.go
solidity/contracts/utils/ModUtils.sol

Tonelli-shanks algorithm only works when p is a prime, and the Legendre symbol is only defined for odd primes. Since both functions are internal, we should be fine with just making the expectations about p clear in the documentation.
Also, removed incorrect `p == 2` condition in `modSqrt` implementation. This value of `p` is not a valid input.

Improved modsqrt documentation

---

solidity/contracts/TokenStakingEscrow.sol
solidity/test/random_beacon_operator/TestInitialization.js
solidity/test/token_stake/TestTokenStakingEscrow.js

Added `withdrawRevoked` function allowing to withdraw the entire amount that is still deposited in `TokenStakingEscrow` in case the grant has been revoked. Anyone can call this function and the entire amount is transferred back to the grant manager.
`TokenStakingEscrow` does not implement an unlocking scheme for revoked grants and always returns the entire, not-yet-withdrawn amount to the grant manager. The reason for that is that it's very hard (if possible at all) to calculate the amount that should belong to the grantee of a revoked grant and that still remains in the escrow. If really needed, we leave this to the grant manager.

Let the grant manager to withdraw from escrow deposit for revoked grant

---

solidity/contracts/ManagedGrant.sol
solidity/contracts/libraries/RolesLookup.sol

This PR introduces two updates:
- Adds missing import in `ManagedGrant` contract
- Updates `RolesLookup` expected staking contract type to `StakeDelegatable` as this is the contract defining `ownerOf` function required b the function. There is no need to define it as `TokenStaking` which is much broader contract. 
Refs: keep-network/keep-ecdsa#483

Roles Lookup and Managed Grant updates

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/package-lock.json

Problem seems to be in `web3-provider-engine` and `web3`. Because of the `^` before the version number, it updated to latest versions which broke the dependencies.
- `web3` to fixed 1.2.7 (changed because of the `Error: Cannot find module 'scrypt-shim`)
- `web3-provider-engine` to fixed 15.0.6 (changed because of the `Error: Cannot find module eth-json-rpc-filter`)

Fixing eth-json-rpc-filter

---

pkg/beacon/relay/gjkr/integration_test.go
pkg/beacon/relay/gjkr/protocol.go
pkg/beacon/relay/gjkr/protocol_reconstructions_test.go
pkg/beacon/relay/integration_test.go

Until now, the reconstruction of the public key share of an inactive/disqualified member was performed only when such member was part of the QUAL set (i.e. their shares broadcasted in phase 3 were valid). Unfortunately, this approach had an uncovered edge case when a member becomes inactive/disqualified exactly in phase 9. In that case, an inactive/disqualified member belongs to the QUAL set, it is selected for reconstruction and its reconstructed public key share is added to the group public key. But, becoming inactive/disqualified in phase 9 means that the member also provided valid public key share during phase 7 which are also added to the group public key. As a result, the group public key becomes invalid and causes errors while signing. The proposed fix improves the …

Improvements for DKG reconstruction phase

---

docs/run-random-beacon.adoc
infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json
infrastructure/gcp/keep-test/google-functions/keep-faucet/package.json
infrastructure/kube/keep-test/keep-client-2-statefulset.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/package.json

Here's a collection of changes to facilitate migration and deploying the keep-test environment against keep-core v1.2.4-rc.  We did this one slightly different in that we've left keep-client-0 and keep-client-1 running against the previous deployment, to not disturb operation while we roll the new release out.
Please do not merge this PR until all checkboxes in `Tasks` are checked.
https://app.circleci.com/pipelines/github/keep-network/keep-core/7186/workflows/294eb7ae-b2c9-431d-a2cd-4cce96ec52d7
~~- [ ] Enable relay request submitter~~  I'm going to scratch this for now, continuing to test relay requests manually.

Release: v1.2.4-rc (Ropsten)

---

Dockerfile

This cuts the final Docker image size down by 90% from 391MB (v1.2.0) to 36.9MB.

Use alpine as the runtime container since Go binaries are self-contained

---

CODEOWNERS

@nkuba owns staking contracts and `LockUtils` is a part of staking contracts.

Added nkuba as a code owner of LockUtils library

---

cmd/start.go

Removed unnecessary error return type from metric initialization function.

Remove unnecessary error return type from metric initialization function

---

CODEOWNERS

In the last few PRs we split some functionality of the `TokenStaking` into separate libraries. We need to update `CODEOWNERS` to reflect those changes.

Updated CODEOWNERS after staking contract changes

---

cmd/start.go

Added missing return to metrics `initializeMetrics` function in case metrics are not configured properly.

Add missing return to metrics initialization

---

solidity/dashboard/src/pages/TokensPageContainer.jsx

This PR fixes:
* subscription to the `Staked` event. `Staked` event's params have changed. Currently, a `Staked` event emits: `owner, operator, beneficiary, value`, instead of `from, value`.

Update KEEP token dashboard for subscribing to `Staked` event

---

pkg/firewall/firewall.go
pkg/firewall/firewall_test.go

Closes  #1895
Introduced cache for negative minimum stake check results in the same way as for positive results.

Cache negative minimum stake check results

---

solidity/dashboard/src/connectors/ledger.js

This commit fixes the `MULTIPLE_OPEN_CONNECTIONS_DISALLOWED` error. The problem was that the user could only send one transaction after connected to wallet.

Fix a ledger bug

---

solidity/contracts/TokenStaking.sol
solidity/contracts/libraries/staking/GrantStaking.sol
solidity/contracts/libraries/staking/TopUps.sol
solidity/migrations/2_deploy_contracts.js
solidity/test/helpers/delegateStake.js
solidity/test/helpers/initContracts.js
solidity/test/token_grant/TestTokenGrantStake.js
solidity/test/token_stake/TestTokenStake.js
solidity/test/token_stake/TestTopUps.js

The idea behind a top-up is to let the staker add KEEP tokens to existing delegations. This is a two-step process: first, staker
initiates a top-up, locking new KEEPs in the staking contract. Once the initialization period is over, staker (or anyone else)
can commit the top-up, increasing operator's stake.
From the smart contract's perspective, top-ups are performed using the same interface as delegations: `receiveApproval` on `TokenStaking` contract. If the given operator is active, tokens are treated as a top-up. If the given operator is not known, tokens are used to create a new delegation.
Operators who have their stake undelegated cannot have their stake topped-up. It means that we still enforce operator's uniqueness - operator address cannot be reused after delegating and recovering …

Stake top-ups

---

solidity/contracts/Authorizations.sol
solidity/contracts/TokenStaking.sol
solidity/contracts/libraries/staking/TopUps.sol
solidity/contracts/stubs/TokenStakingSlashingStub.sol
solidity/contracts/stubs/TokenStakingStub.sol
solidity/migrations/2_deploy_contracts.js
solidity/test/RolesLookupTest.js
solidity/test/helpers/initContracts.js
solidity/test/token_grant/TestManagedGrant.js
solidity/test/token_grant/TestManagedGrantFactory.js
solidity/test/token_grant/TestStakingPolicy.js
solidity/test/token_grant/TestTokenGrant.js
solidity/test/token_grant/TestTokenGrantRevoke.js
solidity/test/token_grant/TestTokenGrantStake.js
solidity/test/token_grant/TestTokenGrantWithdraw.js
solidity/test/token_stake/TestDelegatedAuthority.js
solidity/test/token_stake/TestMinimumStake.js
solidity/test/token_stake/TestPunishment.js
solidity/test/token_stake/TestStakingGrant.js
solidity/test/token_stake/TestTokenStake.js
solidity/test/token_stake/TestTokenStakeLock.js
solidity/test/token_stake/TestTopUps.js

Refs https://github.com/keep-network/keep-core/issues/1883
~~Depends on https://github.com/keep-network/keep-core/pull/1893~~
Extracting stake locks to a separate library (https://github.com/keep-network/keep-core/pull/1888) provided some space in `TokenStaking` bytecode but we quickly used all of that space for the implementation of top-ups (https://github.com/keep-network/keep-core/pull/1893). In this PR, we are doing small changes, one by one, to reduce the bytecode size to allow for stake bridge implementation (https://github.com/keep-network/keep-core/issues/1883). This PR reduces the bytecode from `24596` to `24270` (`-326` bytes) and will let us add just a few lines of code, an absolute minimum needed for the stake bridge implementation.
I recommend reviewing this PR …

Reduce bytecode size of TokenStaking contract

---

pkg/beacon/relay/gjkr/protocol.go
pkg/beacon/relay/gjkr/protocol_accusations_test.go

In the resolve secret shares accusation phase and resolve public key share points accusations phase, we were checking whether the accused member ID does not exceed the group size. We were not, however, checking if it's non-zero which could result in returning an error from GJKR protocol.

Check if the accused member ID is non-zero

---

solidity/contracts/TokenStakingEscrow.sol
solidity/test/token_stake/TestTokenStakingEscrow.js

We do have a `require` making sure tokens come from the `TokenStaking` contract (at least they are declared as such) but a malicious third party could still call `receiveApproval` directly passing `TokenStaking` (`owner()`) in `from` parameter.
We now ensure that no one but KEEP token can call `receiveApproval` of `TokenStakingEscrow`.

Make sure only KEEP token can call escrow's receiveApproval

---

solidity/contracts/TokenStakingEscrow.sol
solidity/test/token_stake/TestTokenStakingEscrow.js

We were not respecting the amount of redelegated tokens in `TokenStakingEscrow.redelegate`, and as a result, someone could migrate more tokens than they should have available even draining the escrow to zero.

Respect redelegated tokens when migrating between escrows

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/test/random_beacon_operator/TestPublishDkgResult.js
solidity/test/random_beacon_service/TestRelayRequestCallback.js

Closes: #1896 
Relay entry fee estimate with no callback price difference:
- For `60 Gwei` ceiling, entry fee is `81964000000000000 wei = 0.081964 ETH`
- For `50 Gwei` ceiling, entry fee is `78970000000000000 wei = 0.07897 ETH`
- For `40 Gwei` ceiling, entry fee is `75976000000000000 wei = 0.075976 ETH`
- For `30 Gwei` ceiling, entry fee is `72982000000000000 wei = 0.072982 ETH`
[Analyzing the historical data](https://docs.google.com/spreadsheets/d/18gXkpBe1Qfpn6vaZ5jIfiMo8zfjvzXJb3-3e42V9FWU/edit#gid=911342864) from https://etherscan.io/chart/gasprice, the gas price values are as follows:
- `13/7/2019 - 13/7/2020` median is `14364979897 wei`
- `13/7/2019 - 13/7/2020` average is `22031400877 wei`
- `1/1/2020 - 13/7/2020` median is `13439926391 wei`
- `1/1/2020 - 13/7/2020` average is …

Increased gas price ceiling to 60Gwei

---

solidity/contracts/TokenStaking.sol
solidity/test/token_stake/TestTokenStake.js

Closes: #1900 
~~Depends on #1906 (I had to make sure we are not running into out-of-gas problems again but it seems that #1902 saved us)~~
For the first two months after the deployment of `TokenStaking` contract, the undelegation period is two weeks and it goes back to two months once two months after the deployment passes.
The staking contract guarantees that an undelegated operator’s stakes will stay locked for a period of time after undelegation, and thus available as collateral for any work the operator is engaged in. Two weeks is the absolute minimum given that the beacon group's active time is also two weeks. Changing undelegation period does not affect `keep-ecdsa` deposits since the stake is locked by the sanctioned application until all deposits the given staker has are redeemed …

Undelegation period set to two weeks for the first two months after TokenStaking deployment

---

solidity/dashboard/src/components/ChooseWallet.jsx
solidity/dashboard/src/pages/TokenGrantsPage.jsx
solidity/dashboard/src/pages/TokenOverviewPage.jsx
solidity/dashboard/src/reducers/tokens-page.reducer.js
solidity/dashboard/src/services/tokens-page.service.js

Closes: #1911 
This PR fixes a bug with a total balance of grants on the overview page.
Before:
* total balance of grants- `1 000 000` KEEP,
* delegate `100 000` KEEP,
* total balance of grants on the overview page- `1 100 000` KEEP- which was not correct.
Currently: 
* total balance of grants- `1 000 000` KEEP,
* delegate `100 000` KEEP,
* we are able to observe `1 000 000` KEEP and `10%` Staked in `Granted Tokens` card.

Fix total balance of grants- KEEP token dashboard overview page

---

CODEOWNERS

@nkuba is already a code owner of token staking contract and related libraries.
`OperatorParams` seems to be the last one staking-related code file where  he is not yet an owner.
We found it when working on #1929 - although @nkuba approved the code, he could not merge it.

Added nkuba as a code owner of OperatorParams.sol

---

solidity/contracts/TokenStaking.sol
solidity/contracts/stubs/OperatorParamsStub.sol
solidity/contracts/utils/OperatorParams.sol
solidity/test/TestOperatorParams.js
solidity/test/token_stake/TestTokenStake.js
solidity/test/token_stake/TestTopUps.js

Closes: #1931 
~~Depends on #1915 (it is not really a dependency on functionality; I want to keep an eye on out-of-gas issues this way to avoid post-merge surprises)~~
In case the stake is still in the initialization period, we add tokens immediately but we also reset the stake initialization time counter.
This change allows for two things:
- Staker no longer has to pay for two transactions to achieve the same result (cancel + stake) and operator address uniqueness is no longer a problem.
- If the stake has been undelegated from multiple operators and is scattered in the escrow, staker may perform a delegation and top-up as many times as needed, right after the delegation. Multiple transactions have to be sent to the chain but staker does no longer needs to suffer from the initialization …

Allow to top-up a stake during initialization period

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/libraries/operator/Groups.sol

Rewards don't play particularly nice with blockheights, so we need to use timestamps. To avoid out-of-gas issues with deployments, a couple of library functions need to be made public instead of internal. Group registration times are packed in a separate storage slot to avoid creating additional instructions for registration block accesses.

Get operator contract ready for rewards, for real this time

---

solidity/contracts/TokenStakingEscrow.sol
solidity/test/token_stake/TestTokenStakingEscrow.js

`TokenStakingEscrow` was not respecting redelegated tokens in `withdrawRevoked` function. As a result, a grant manager could withdraw more tokens from the escrow than they should be allowed and even drain the escrow to zero in the most pessimistic case.
The solution is to call `availableAmount` function to evaluate the number of tokens available for withdrawal from a revoked grant, just like we do during the migration of tokens between escrows.

Respect redelegated tokens when withdrawing revoked grant from escrow

---

solidity/contracts/TokenStakingEscrow.sol
solidity/test/token_stake/TestStakingGrant.js

In case someone calls `cancelStake` twice they can have their information about the deposit lost and tokens locked in the escrow. We prevent it by reverting the transaction if the deposit for the given operator is already in the escrow. The same situation and the same fix is for calling `recoverStake` twice. This change affects only grant stakes since liquid token stakes are returned straight to the owner.

TokenStakingEscrow reverts if it already has a deposit

---

scripts/ubuntu-setup.sh

Refs: https://github.com/keep-network/local-setup/pull/12
During the work on the aforementioned pull request, we developed some Ubuntu environment provisioning scripts. Here we introduce them as `ubuntu-setup.sh` as an alternative for `macos-setup.sh`.

Add ubuntu-setup.sh

---

solidity/dashboard/src/services/slashed-tokens.service.js

The issue could result in not presenting information about slashing / seizing in a dashboard under some specific conditions (when transaction hash is neither in slashedTokensGroupedByTxtHash nor in seizedTokensGroupedByTxtHash). As the result user would observe correct total number of staked tokens with no explanation why it is lesser than used to be. 
Actual fix consists of two parts: 
- skipping uninitialized punishmentData-s 
- properly filling 'amount' (unrelated to my original issue but might result in similar behaviour if not fixed too)
@pdyraga @sthompson22 - it resolved my issue with 'missing 1k & no slashes'

Fix for not presenting slashes

---

solidity/contracts/TokenStakingEscrow.sol
solidity/test/token_stake/TestStakingGrant.js

This event will help to locate staking relationships created by escrow redelegations. The flow to locate all stakes could be as follows:
At the same time:
- Fetch `TokenGrant.TokenGrantStaked` events by `grantID`, read `operator`,
- Fetch `TokenStakingEscrow.DepositRedelegated` events by `grantID`, read `operator`,
then:
- Fetch `TokenStaking.Staked` event by the `operator`.

Added DepositRedelegated event to TokenStakingEscrow

---

solidity/contracts/TokenStaking.sol
solidity/contracts/TokenStakingEscrow.sol
solidity/contracts/libraries/staking/TopUps.sol
solidity/test/token_grant/TestTokenGrantStake.js
solidity/test/token_stake/TestStakingGrant.js
solidity/test/token_stake/TestTokenStakingEscrow.js

After we added a feature allowing to top-up in the initialization period (https://github.com/keep-network/keep-core/pull/1929) we unconsciously introduced a path allowing to redelegate to the operator from which the delegation has been canceled. It should not be allowed as it leads to rejecting the deposit by the escrow when undelegating/canceling that second delegation.
There are two scenarios when top-up can be performed on a canceled delegation:
Scenario 1: Someone tries to re-delegate from the escrow to operator that already has a deposit in the escrow:
```
delegate operator A -> escrow ->
redelegate operator B -> escrow ->
redelegate operator A -> escrow (TX reverted!)
```
This scenario is now prohibited from happening by `TokenStakingEscrow.hasDeposit` check in redelegate function. …

Do not allow to redelegate to an operator from which a delegation has been cancelled

---

infrastructure/scripts/download-gke-secrets.sh

Letting my commit message stand for the PR description here, not much more to say.
----
This is about as rudimentary as it gets but here's a thing to download
each secret from a cluster.
It expects you to be on the correct kube context and VPN for the
environment you want to download the secrets from. Key values are base64
encoded but the secret metadata should have the actuals.
Frankly, this is a messy way to work with secrets, but if you don't want
to maintain a clean / plaintext representation of the configurations in
a secure location, this is the way.

Kube: Download Secrets

---

infrastructure/kube/keep-test/keep-client-0-statefulset.yaml
infrastructure/kube/keep-test/keep-client-1-statefulset.yaml
infrastructure/kube/keep-test/keep-client-2-statefulset.yaml
infrastructure/kube/keep-test/keep-client-3-statefulset.yaml
infrastructure/kube/keep-test/keep-client-4-statefulset.yaml

This is a keep-test/keep-client dedicated Alchemy app so that we can track keep-client usage in isolation on testnet.

keep-test: Separate ETH host

---

infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/package.json
infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/provision-keep-client.js

We've started running into web3 errors during InitContainer runs for both keep-client and keep-ecdsa.  Rolling the containers forward to a newer version of web3 addresses the issue.  Along with the upgrade we've had to adjust how we call a contract objects address, as the `.address` parameter has been wrapped under a new `options` object.
For posterity, here's a sample of the error we've been seeing:
```
<<<<<<<<<<<< Authorizing Operator Contract 0xe7BF8421fBE80c3Bf67082370D86C8D81D1D77F4 >>>>>>>>>>>>
Authorizing Operator Contract 0xe7BF8421fBE80c3Bf67082370D86C8D81D1D77F4 for operator account 0x3ff855895ef4ac833c32ab6a0d6c7fbfa137e26e
undefined
{ error:
Error: Invalid method parameter(s).
at /tmp/node_modules/web3-provider-engine/subproviders/provider.js:18:36
at …
```

keep-client:  Init with  non-ancient web3

---

cmd/start.go
config/config_test.go
configs/config.toml.SAMPLE
go.mod
go.sum

In https://github.com/keep-network/keep-common/pull/44 we removed ethereum address from the config file. In this PR we handle this change in keep-core client. After loading the ethereum key we are able to get the address from it.
Depends on: https://github.com/keep-network/keep-common/pull/44
Closes: keep-network/keep-core#1968

Removed ethereum account address from config

---

solidity/contracts/TokenStaking.sol
solidity/contracts/libraries/staking/TopUps.sol
solidity/test/token_stake/TestTopUps.js

Having the minimum stake restriction on delegation makes perfect sense but users may want to top-up less than the minimum stake. It makes sense in two cases:
- As long as we slash 1% or 50% of the minimum stake (first 3 months and the next 3 months), users may delegate e.g. 100k KEEP and then to-up 1k KEEP to have 1% safety margin in case of slashing.
- Sortition pool weights by stake and if the `poolWeightDivisor` is lower than the minimum stake, having 101K KEEP delegated gives better chances of being selected than having 100k KEEP delegated.
Props to @r-czajkowski for finding this.

Allow to top-up less than the minimum stake

---

solidity/scripts/lcl-client-config.js

The config file contains now new properties stored as numbers: `NetworkMetricsTick` and `EthereumMetricsTick`.
The library `tomlify-j0.4` we use in config generation script requires special handling of number fields to convert them from float to integer.
We already support `Port` properties and in this PR we added support of ones which key ends with `MetricsTick`.
Closes: https://github.com/keep-network/keep-core/issues/1946

Fix handling of Metric number fields in config script

---

configs/config.toml.SAMPLE
pkg/chain/ethereum/connect.go

Given the current trends of gas prices, it makes sense to increase the `DefaultMaxGasPrice` to `70Gwei`. As for today, Etherscan indicates `60Gwei` is the safe price and `75Gwei` is the proposed price, both with ~20 seconds expected mining time of a TX.

DefaultMaxGasPrice updated to 70Gwei

---

solidity/contracts/libraries/staking/GrantStaking.sol

`escrow` is already an address and we get nothing from casting `address` to `address`.

Removed redundant casting operation

---

infrastructure/kube/keep-dev/eth-account-info-configmap.yaml
infrastructure/kube/keep-dev/keep-client-0-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-1-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-2-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-3-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-4-statefulset.yaml
infrastructure/kube/keep-test/eth-account-info-configmap.yaml
infrastructure/kube/keep-test/keep-client-0-statefulset.yaml
infrastructure/kube/keep-test/keep-client-1-statefulset.yaml
infrastructure/kube/keep-test/keep-client-3-statefulset.yaml
infrastructure/kube/keep-test/keep-client-4-statefulset.yaml
infrastructure/kube/keep-test/keep-network-ropsten-relay-request-cronjob.yaml
infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/provision-keep-client.js

As per https://github.com/keep-network/keep-core/issues/1968 keep client no longer requires ethereum account address to be provided in the config file. 
In this PR we update provisioning script not to set ethereum address in a config file. We also updated kube's configs for keep-dev and keep-test to remove ethereum addresses.
Depends on: https://github.com/keep-network/keep-core/pull/1970

Client provisioning without eth account address

---

solidity/contracts/TokenStaking.sol
solidity/contracts/libraries/operator/Groups.sol
solidity/contracts/libraries/staking/MinimumStakeSchedule.sol
solidity/contracts/stubs/MinimumStakeScheduleStub.sol
solidity/contracts/stubs/TokenStakingStub.sol
solidity/test/random_beacon_operator/TestSlashing.js
solidity/test/token_stake/TestMinimumStake.js
solidity/test/token_stake/TestPunishment.js
solidity/test/token_stake/TestStakingGrant.js

We are deploying a new staking contract version but we want to maintain the same minimum KEEP stake schedule. To make it happen, instead of using staking contract deployment time as a schedule start, we now define a constant in `MinimumStakeSchedule` with a value equal to the time of deploying KEEP token. On the other hand, we want the slashing schedule (1% for the first 3 month and 50% for the next 3 months) start with the time of deploying the new `TokenStaking` contract. I renamed `TokenStaking.minimumStakeScheduleStart` to `TokenStaking.deployedAt` and updated `Groups.sol` to use the new name.
The most problematic part were unit tests. Since we now use a fixed point in the past as a minimum stake schedule start, I had to introduce `TokenStakingStub` for some tests with a fixed minimum …

Minimum stake schedule starts at the moment of deploying KEEP token

---

solidity/contracts/StakingPortBacker.sol
solidity/test/token_stake/TestStakingPortBacker.js
solidity/test/token_stake/TestTokenStake.js

Modified `StakingPortBacker` to allow for copying stake only one time even if the copied stake has been recovered. This behavior was expected based on the documentation on `copyStake` which says:
> "(...)  the relationship can only be copied once (...)".
This scenario would be the most problematic in the situation when `StakingPortBacker` owner force-undelegates the stake after 3 months of not paying the loan back and recovers the stake after the undelegation time and the malicious staker copies the stake immediately before `StakingPortBacker` owner has a chance to withdraw tokens (gas auction).

Allow to copy stake only one time even if it's been recovered

---

solidity/contracts/TokenStaking.sol

It is important to be careful with the amount of KEEP tokens added to the stake since a top-up cannot be canceled. The only way to have those tokens back is to undelegate and recover the stake.

Added a note to docs that a top-up can not be cancelled

---

solidity/contracts/Authorizations.sol
solidity/contracts/libraries/staking/Locks.sol

Updated documentation around `AuthorityVerifier` to be explicit about the
fact it's not some 3rd party contract we cannot trust but that it's
something provided by us, with reasonable gas consumption and never
reverting on the check.

Improved documentation around AuthorityVerifier

---

solidity/contracts/TokenStaking.sol
solidity/contracts/libraries/staking/MinimumStakeSchedule.sol

During the review of https://github.com/keep-network/keep-core/pull/1977 @nkuba and @Shadowfiend commented about not hardcoding the schedule start in the library. This is addressed in this PR. 
Instead of hardcoding schedule start in `MinimumStakeSchedule` library, we can pass it as a parameter. It's a little cleaner given that we don't have an alternative function for unit tests. It's a little more expensive gas-wise but we can live with it.
Having this value passed in the constructor is not possible given the contract size constraints. 
We also use ISO8601 format for schedule start date now.

Pass minimum stake schedule start as a parameter to the library

---

docs/run-random-beacon.adoc

Added in log rotation to the docker run command so that only 300mb of logs are stored at a time.  Logs over time, especially when run with `debug` will create GB of log files.

Added Log rotation to docker run command

---

solidity/contracts/GasPriceOracle.sol
solidity/contracts/KeepRandomBeaconOperator.sol
solidity/contracts/stubs/GasPriceOracleConsumerStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorCallbackStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorDKGResultStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorGroupSelectionStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorInitializationStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorMisbehaviorStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorPricingDKGStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorPricingRewardsWithdrawStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorPricingStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorRewardsStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorServicePricingStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorSlashingStub.sol
solidity/contracts/stubs/KeepRandomBeaconOperatorStub.sol
solidity/migrations/2_deploy_contracts.js
solidity/migrations/3_initialize.js
solidity/test/TestGasPriceOracle.js
solidity/test/helpers/initContracts.js
solidity/test/random_beacon_operator/TestManageServiceContracts.js
solidity/test/random_beacon_service/TestSelectOperator.js

Our 60Gwei gas price ceiling set in https://github.com/keep-network/keep-core/pull/1914 is not enough given the current gas price trends. 👨‍🌾 👩‍🌾 . 60Gwei ceiling we considered a bold move one month ago is not even 50% of today's current average gas price of 200Gwei, not even speaking about average 367Gwei price yesterday.
Until we come up with a pricing model taking gas price fluctuations into account we need to have a way to update gas price ceiling. That's what's implemented here.
`GasPriceOracle` is an ownable contract allowing the owner to modify the current gas price value with respect to 6 hours governance delay. The oracle notifies all subscribed contracts when the change is finalized and lets them pull the most recent gas price.
When working on this change I had to drop …

Gas price ceiling updates

---

solidity/contracts/StakeDelegatable.sol
solidity/contracts/TokenStaking.sol
solidity/test/token_stake/TestTokenStake.js

`ownerOperators` mapping in `StakeDelegatable` was quite a problematic append-only data structure.
The first issue was that this mapping was not cleared up when a stake was recovered. The reason for that was to maintain a historical mapping between owner and operator so that the owner may withdraw rewards after recovering the stake even if it lost the operator address (operator address is a parameter to withdraw function).
Another issue was that this mapping maintained no longer up-to-date information in case the stake ownership was transferred with `transferStakeOwnership` function in `TokenStaking`. Clearing up this mapping would involve writing a loop and compering operator address bytes. This is problematic because of the contract size constraints as well as there is a tiny …

Replace StakeDelegatable.ownerOperators mapping with an event 

---

cmd/start.go
config/config.go
configs/config.toml.SAMPLE
go.mod
go.sum
pkg/diagnostics/diagnostics.go
pkg/metrics/metrics.go

~~Depends on https://github.com/keep-network/keep-common/pull/43~~
Refs https://github.com/keep-network/keep-core/issues/1930
Enables the diagnostics module which exposes information useful for debugging and diagnostic client's status. 
Diagnostics module exposes the following information:
- list of connected peers along with their network id and ethereum operator address
- information about the client's network id and ethereum operator address 
Diagnostics module can be enabled in the config TOML file:
```
[Diagnostics]
Port = 8002
```

Expose peers list as JSON via Diagnostics package

---

pkg/chain/ethereum/connect.go
pkg/net/libp2p/channel.go

Here we improve some logging:
- We add log info when starting to fetch the relay chain config
- We log the `UnregisterTopicValidator` error on the debug level because actually it doesn't indicate anything wrong

Improve log messages around the chain config and channel filter

---

solidity/contracts/stubs/OldTokenStaking.sol
solidity/migrations/2_deploy_contracts.js

`StakingPortBacker` is deployed and linked to a proper version of old staking contract based on the network ID.
For 'ropsten', we link to contract `0x8117632eC1D514550b3880Bc68F9AC1A76c9C67B` 
https://ropsten.etherscan.io/address/0x8117632eC1D514550b3880Bc68F9AC1A76c9C67B
For 'mainnet', we link to contract `0x6D1140a8c8e6Fac242652F0a5A8171b898c67600` 
https://etherscan.io/address/0x6D1140a8c8e6Fac242652F0a5A8171b898c67600#code
For any other network, we deploy `OldTokenStakingStub` and link `StakingPortBacker` to it.

Deploy StakingPortBacker

---

solidity/contracts/KeepRandomBeaconOperator.sol
solidity/test/random_beacon_operator/TestRelayEntryTimeout.js
solidity/test/random_beacon_operator/TestSlashing.js

We were allowing to request a new entry if the previous timed out and this fact has not been reported. This could lead do group members avoiding slashing by submitting a new entry before someone can report the timeout (gas auction).
It is fixed now by requiring to report entry timeout before a new entry can be requested. All clients monitor the entry - those participating and not participating in the signing group - so entry timeout is reported as soon as possible and there is no risk for blocking the beacon.

Require to report timeout if it happened before requesting new entry

---

infrastructure/gcp/keep-test/google-functions/keep-faucet/deploy-faucet.sh
infrastructure/gcp/keep-test/google-functions/keep-faucet/issue-grant.js
infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json
infrastructure/gcp/keep-test/google-functions/keep-faucet/package.json

From the main commit:
> Because of how HDWalletProvider works, nonces are cached by a local
> provider, which also affects calls to `getTransactionCount`. This means
> if for some reason a bad nonce is cached, it's impossible to recover
> without kicking the function altogether.
>
> Instead, the grant process has been reworked to recursively invoke
> itself with a higher nonce whenever a `nonce too low` or `replacement
> transaction underpriced` error is reported.
>
> Also cleaned up error handling, success handling, and separated request
> and response handling from the grant issuance itself.
A few other small adjustments are also bundled in here.

Threaded Pipes: Adjust Ropsten to better deal with nonce issues

---

solidity/dashboard/src/services/tbtc-rewards.service.js
solidity/dashboard/src/services/token-staking.service.js
solidity/dashboard/src/services/tokens-page.service.js

If we want to get past events eg. by all operators, and pass an empty array to indexed param eg. `{filter: { operator: [] }}` to the [`getPastEvent`](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#getpastevents), all emitted events will be returned. To avoid this, before calling `getPastEvent` with an empty array for the indexed param, we check that the filter param is not an empty array and then call ` getPastEvent` function.

Fix fetching past events

---

pkg/net/libp2p/authenticated_connection.go

When working on Gosec integration (https://github.com/keep-network/keep-core/pull/1996) we updated the authenticated connection handshake code to log connection close errors on ERROR level. This is not perfect, since when there is a lot of nodes trying to connect we observe a bunch of errors:
```
2020-09-01T16:30:44.976Z	ERROR	keep-net-libp2p	could not close the connection:
[Multiple errors: close tcp4 10.0.3.9:3001->78.141.221.231:1024: use of closed network connection]
```
A quick investigation shows that those nodes decided to drop the connection on their side so we are trying to close a connection that is already closed. Logging it on ERROR level is not a perfect solution but we also shouldn't ignore it. We decided to log this problem on DEBUG level for now and open an issue (#2029) …

Log connection close failures on debug level

---

infrastructure/kube/keep-dev/keep-client-0-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-1-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-2-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-3-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-4-statefulset.yaml
infrastructure/kube/keep-test/keep-client-0-statefulset.yaml
infrastructure/kube/keep-test/keep-client-1-statefulset.yaml
infrastructure/kube/keep-test/keep-client-2-statefulset.yaml
infrastructure/kube/keep-test/keep-client-3-statefulset.yaml
infrastructure/kube/keep-test/keep-client-4-statefulset.yaml
infrastructure/kube/keep-test/keep-network-ropsten-relay-request-cronjob.yaml

The provisioning script used in init containers recently moved to
reading Ethereum key and account information from a keyfile rather than
from the environment; however, the corresponding Kubernetes stateful set
and cron job configurations were not updated to mount the keyfile for
the initcontainer (it was already being mounted for the container
proper).
The initcontainer now has the keyfile mounted properly. In the process,
moved volumes to the top of the spec, since they are now used in both of
the subsequent sections.
This state is currently deployed on keep-test for client-2 and client-3,
as well as the relay requester.

Voluminous Containers: Fix initcontainers that require keyfile

---

go.mod
go.sum
pkg/chain/gen/abi/GasPriceOracle.go

Updated `keep-common` to the most recent released version.
I have also took the opportunity to check-in `GasPriceOracle` generated Go code. We keep all the generated code in version control. `GasPriceOracle` is a new contract that hasn't been added yet to the generated Go resources.

keep-common updated to v1.2.0

---

solidity/dashboard/package-lock.json

The most recent versions are:
- `@keep-network/keep-core`: 1.3.0-rc.1
- `@keep-network/keep-ecdsa`: 1.2.0-rc.3
- `@keep-network/tbtc`: 1.1.0-rc.1

Updated dashboard lockfile with the newest keep-* and tbtc

---

infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json

Faucet's `package.json` depends on `>1.3.0-rc <1.3.0` but the lock file
was on `1.2.4-rc.1`. Updated that dependency to the most common version
of `1.3.0-rc.1`.

Updated locked keep-core dependency for faucet

---

.pre-commit-config.yaml
infrastructure/gcp/keep-test/google-functions/keep-faucet/.eslintrc
infrastructure/gcp/keep-test/google-functions/keep-faucet/issue-grant.js

Three bits here:
- The faucet now has a proper `eslintrc`, based on the common Keep config.
- The faucet (and as a bonus the dashboard) now have linting pre-commit configurations (/cc @r-czajkowski ).
- The faucet now handles the newer error structures we get from web3 (this was an oversight from a web3 version bump).
See #1551.

Linty faucet: Improved linting pre-commits, linting config for faucet, and a fix

---

solidity/dashboard/src/components/TokenOverview.jsx

The `open wallet` icon should be in `owned` card instead of `granted`, since this icon refsto tokens in the user's wallet. And `grant` icon should be in `granted` card insted of `owned.`
Fix:
bug:

Replace icons on the Overview page

---

solidity/dashboard/src/components/PendingUndelegation.jsx

Closes: #1901 
We should update `delegationStatus` field instead of `delegatedStatus` when subscribing to the `Undelegated` event on the `Operations` page.

Fix subscription to a `Undelegated` event on the Operator page

---

solidity/dashboard/src/services/staking-port-backer.service.js

Delegation amount (BN) has to be compared with `BN(0)` and not just `0`. Otherwise, comparison will not be correct and we can see 0 amount delegations in the copy-stake flow. 
We used the operator address from a "new" delegation but fetched delegation details from the "old" staking contract, hence 0 KEEP.
Scenario: Create grant from 0xAAA to 0xBBB. From 0xBBB delegate KEEP to 0xCCC. From 0xBBB click on the banner "Upgrade my stake". You will see a screenshot below:

Fixing displaying 0 KEEP amount delegations in the copy-stake flow

---

solidity/dashboard/src/components/DelegatedTokensTable.jsx

It is confusing clicking at the ADD KEEP button when a user won't be able to add KEEP anyway.

Disabling ADD KEEP button when no KEEP is available

---

configs/config.toml.SAMPLE
pkg/chain/ethereum/connect.go

Source: https://etherscan.io/chart/gasprice
The last weeks brought an extreme gas price increase on mainnet, even to 500 Gwei average price. The default value of 70 Gwei could not be enough.
The `MaxGasPrice` can be still configured in the config file, here we just update the default value to keep it aligned with the reality.

DefaultMaxGasPrice used by client set to 500 Gwei

---

solidity/dashboard/src/components/copy-stake-steps/Step1.jsx
solidity/dashboard/src/pages/CopyStakePage.jsx
solidity/dashboard/src/pages/TokensPageContainer.jsx
solidity/dashboard/src/reducers/copy-stake.js
solidity/dashboard/src/sagas/copy-stake.js
solidity/dashboard/src/sagas/web3.js

Hide the copy stake banner when no delegations are available on the old token stake contracts. We do not want to confuse users with displaying them a banner when they don't have any old delegations in the first place.

Hiding a copy stake banner when no old delegations available

---

solidity/dashboard/src/services/slashed-tokens.service.js
solidity/dashboard/src/services/tokens-page.service.js

Closes: #1992
We should skip `UnauthorizedSigningReported\RelayEntryTimeoutReported` events if they were not emitted in the same transaction as the `TokenSlashed / TokenSeized` events because it means that these punishment events are not related to the provided operator.

Fix fetching slashed tokens

---

solidity/dashboard/src/pages/TokensPageContainer.jsx

The dapp subscribes to the `StakeDelegated` event and updates data based on that event. If the `StakeCopied` event was emitted with a `StakedDelegated` event, we do not want to update grant data or KEEP token balance, since a copied delegations are from already staked tokens.

Skip data updates if its a copied delegation

---

solidity/dashboard/src/components/AddETHModal.jsx

Added validation for 0 ETH account balance when bonding ETH. When a user has no EHT on its balance, we will notify him about it.
Incorrect message will be replaced with: "Account ETH balance should be greater than 0"

Validating for 0 ETH account balance

---

solidity/dashboard/src/hooks/useEtherscanUrl.js

This hook relied on the existence of the web3 provider, so it always returned a ropsten link during hardware wallet connection pop-up. Here we updated this custom hook and currently relies on the `@keep-network` package, since for a given build only support a single network ID.

`useEtherscanUrl` hook fix

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

1.3.2 release with the fix from https://github.com/keep-network/keep-core/pull/2051

Bumping up token dashboard version to 1.3.2

---

docs/run-random-beacon.adoc

7 days is no longer an up to date value - stake initialization takes 12 hours now.

Updated stake initialization time to 12 hours in docs

---

solidity/dashboard/src/sagas/token-grant.js
solidity/dashboard/src/sagas/web3.js

Set `args` param to an empty array when calling `withdraw` function from a `ManagedGrant` contract  via [`sendTransaction`](https://github.com/keep-network/keep-core/blob/master/solidity/dashboard/src/sagas/web3.js#L111) helper.

Fix releasing tokens from a managed grant

---

docs/run-random-beacon.adoc

Bison Trails and Figment Network bootstraps are active now and ready for work!

Adding back mainnet bootstraps from Bison Trails and Figment Network

---

solidity/dashboard/src/sagas/web3.js

Ref: https://github.com/keep-network/keep-core/pull/2058#discussion_r490433685 
Set the default value to `{}` for the `options` param in the `createTransactionEventChannel` function.

Set the default value for a  `options` param in the `createTransactionEventChannel`

---

docs/run-random-beacon.adoc

Added information about gas costs of operations the beacon client is performing. It is important that the operators understand the cost of running the client and can estimate the required ETH based on their stake, current gas price, and the expected traffic in the network.

Information on the gas cost of operating the client

---

scripts/install.sh
scripts/macos-setup.sh
solidity/package-lock.json
solidity/package.json

I went through the `local-setup` installation process on a fresh machine, which found a few more gaps I'd missed in our scripts:
- A few stray references to `truffle` instead of `npx truffle`.
- Some unused dependencies.
- A reliance on `coreutils`.
Those changes are reflected here.

Funky fresh: Additional adjustments to repo setup for fresh machines

---

solidity/dashboard/src/components/ChooseWallet.jsx
solidity/dashboard/src/components/LedgerModal.jsx
solidity/dashboard/src/components/MetaMaskModal.jsx
solidity/dashboard/src/components/SelectedWalletModal.jsx
solidity/dashboard/src/components/TrezorModal.jsx
solidity/dashboard/src/components/Web3ContextProvider.jsx
solidity/dashboard/src/connectors/abstract-connector.js
solidity/dashboard/src/connectors/index.js
solidity/dashboard/src/contracts.js

Closes: #1956
This PR improves UX while connecting with wallet. Here we added loading indicators when the dapp fetches the wallet addresses and connects with a wallet. We also display the `install metamask` button only in case the user does not have the extension installed.
<details>
<summary>Screenshoots</summary>
no MetaMask ext:
wrong netowork error:
mm connecting:
ledger loading wallet addresses:
ledger select address:
trezor loading wallet addresses:
trezor select address:
</details>

Metamask pop up

---

solidity/contracts/Rewards.sol
solidity/test/rewards/TestRewards.js
solidity/test/rewards/rewardsData.js

Instead of allocating yet unallocated rewards in the last interval with 100% interval weight, we are going to use the last defined interval's weight which should flatten the rewards curve.
Instead of:
We would have:

Flattening the rewards curve

---

solidity/contracts/Rewards.sol
solidity/test/rewards/TestBeaconBackportRewards.js
solidity/test/rewards/TestBeaconRewards.js
solidity/test/rewards/TestRewards.js

Depends on #2103
We had a problem with `firstIntervalStart` property - it had to be set in a way that `firstIntervalStart + termLength` would be in the future. Otherwise, someone could call `allocateRewards(0)` before we fund the contract properly and the allocation for the first interval would not be the same as we'd want it to be.
Here we are making `Rewards` contract `Ownable` for only one purpose - the owner has to mark the contract as properly funded calling `markAsFunded` function. Only from then, rewards can be allocated.
Setting the contract as funded does not stop it from being funded even more in the future.
The expected order of operations is as follows:
- contract is deployed,
- contract is funded with the expected …

Fund properly before allocating rewards

---

solidity/contracts/Rewards.sol
solidity/contracts/stubs/NewRewardsStub.sol
solidity/test/rewards/TestRewardUpgrades.js

This PR presents an alternative approach for Rewards upgrades. Compared to https://github.com/keep-network/keep-core/pull/2102, it's less graceful but allows reallocating tokens quicker.
`KeepRandomBeaconOperator` and `BondedECDSAKeepFactory` may get upgraded to the improved versions. When this happens, we want to incentivize stakers to move to the new contracts and do not lock the entire unallocated signer subsidy in rewards contract backing old operator contract versions.
The approach presented in #2102 is more graceful. Rewards tokens that would normally be returned to the unallocated pool would instead be sent to the new rewards contract. This would gracefully bleed out the old rewards contract's reward tokens as the creation of new keeps (or beacon groups) dwindles over time as the …

Make rewards upgradeable

---

docs/run-random-beacon.adoc

There are problems with this machine, we are going to disable it for now.
bootstrap-1.core.keep.test.boar.network and two GCP bootstraps are still there.

Disabling bootstrap-2.core.keep.test.boar.network

---

solidity/contracts/Rewards.sol
solidity/test/rewards/TestRewardUpgrades.js

We were not properly checking whether the interval in which the upgrade was initiated ended before the upgrade was finalized. There was a unit test checking it but it was giving a false-positive given that the interval we were initiating on was 0 and it was not allocating any previous intervals.
We now have a separate `require` making sure the allocation condition holds as well as we have another unit test for non-zero interval.
I have also improved a comment in the code saying that the intervals must receive their reward before tokens are transferred out of the contract on upgrade. The right word to use here is "allocated", not "receive".

Make sure upgrade initiated interval ends before finalizing the upgrade

---

solidity/contracts/Rewards.sol
solidity/test/rewards/TestRewardUpgrades.js

Depends on https://github.com/keep-network/keep-core/pull/2114
We do not decrease `dispensedRewards` value when `finalizeUpgrade` is called to make the contract semantics easier and more transparent.
Additionally, we improve invariants defined in this contract by adding two that should always hold and clarifying the one already existing that is guaranteed to hold only right after `receiveApproval` is called.
Starting with invariants, we have two:
- `token.balanceOf(address(this)) >= totalRewards.sub(dispensedRewards)` should always hold,
- `token.balanceOf(address(this)) == totalRewards.sub(dispensedRewards)` should hold right after `receiveApproval` is called.
In regards to `finalizeUpgrade`, two options were considered:
**Option …

Dragons and invariants: Do not decrease dispensed rewards on finalizing upgrade

---

solidity/contracts/BeaconBackportRewards.sol
solidity/contracts/Rewards.sol

Depends on https://github.com/keep-network/keep-core/pull/2115
The most important update here is the fix to `@dev` docs for `_getKeepAtIndex` and `_getCreationTime`.
Docs on those abstract functions stated that the implementation is required to revert if the identifier is invalid or not in the expected range. The implementation in `BeaconBackportRewards` and `BeaconRewards` does not revert and after some investigation, it's been concluded that additional checks are not really needed and we may save some gas on not having them. 
`_getKeepAtIndex` is used in:
* `_findEndpoint`
* `_find`
`_findEndpoint` starts the search with lower bound set to 0 and upper bound set to `_getKeepCount() - 1`. It is guaranteed that values of `lb` and …

Docs stronger than ever: small fixes to Rewards contract documentation

---

solidity/contracts/BeaconBackportRewards.sol

`lastInterval` was not used anywhere.

Removed unused internal constant from BeaconBackportRewards

---

solidity/contracts/stubs/KeepRandomBeaconOperatorBeaconRewardsStub.sol
solidity/test/rewards/TestBeaconBackportRewards.js
solidity/test/rewards/TestBeaconRewards.js

In this PR we are changing 2 things in tests:
- Beacon KEEP rewards for the period starting in Sep 2020 are reduced of 200k which was allocated for the period of May - Sep 2020.
- We pass a creation group timestamp in tests to avoid future failures when the intervals will be over.

Modifications in beacon rewards tests

---

pkg/beacon/beacon.go

Closes https://github.com/keep-network/keep-core/issues/2121
In this PR we are changing logging level from Error to Warning. Event already registered is not an error and this scenario might happen in certain Ethereum client deployments where nodes are behind a load-balancer.

Logging "relay entry requested event with previous entry.." as warning

---

pkg/beacon/beacon.go

Closes https://github.com/keep-network/keep-core/issues/2122
If the relay entry has been already submitted to the chain and there is no other entry in progress (current request start block is 0), then we should log a Warning instead of an Error.

Replacing error with a warning when there is no entry in progress

---

pkg/beacon/beacon.go
pkg/beacon/relay/registry/groups.go
pkg/beacon/relay/registry/groups_test.go

Closes https://github.com/keep-network/keep-core/issues/2120
A node might run into situation when there is a slight delay with syncing to the recent state of the chain. It might result in error loggin "Group does not exist", even though it was just added to the chain. In order to avoid described scenario, we can skip checking the latest added group if it is a "stale group".

Failed to check if stale for group public key

---

solidity/contracts/PhasedEscrow.sol
solidity/contracts/stubs/TestPhasedEscrowBeneficiaries.sol
solidity/package.json
solidity/test/TestPhasedEscrow.js

Two contracts implemented here:
`PhasedEscrow` - a token holder contract allowing contract owner to set beneficiary of tokens held by the contract and allowing the owner to withdraw the tokens to that beneficiary in phases.
`CurveRewardsEscrowBeneficiary` A beneficiary contract that can receive a withdrawal phase from a `PhasedEscrow` contract. Immediately stakes the received tokens on a designated `CurveRewards` contract.
This allows us to adjust rewards strategies over time if strictly necessary.

Phased Escrow: Escrow contract that allows phased release

---

solidity/contracts/Rewards.sol

Refs #1783
Finalizing a rewards upgrade can get blocked if the latest interval is allocated before the finalization. Fix this by only allocating intervals on finalization as required.
Send deallocated rewards or new funding to the new rewards contract if the upgrade has been finalized.

Improve rewards upgrade handling

---

solidity/contracts/Rewards.sol
solidity/test/rewards/TestRewardUpgrades.js

Depends on: https://github.com/keep-network/keep-core/pull/2136
Adding tests around:
- deallocation of rewards
- rewards allocation just before finalizing rewards contract upgrade.

Rewards deallocation tests

---

solidity/contracts/BeaconRewards.sol
solidity/contracts/Rewards.sol
solidity/contracts/stubs/RewardsStub.sol
solidity/test/rewards/TestBeaconRewards.js
solidity/test/rewards/TestRewards.js

This PR is a continuation of https://github.com/keep-network/keep-ecdsa/pull/588
Adding the functionality to report termination of multiple keeps with one call. This should save transactions cost.
We decided to move batch processing of rewards receiving and terminations to the main `Rewards.sol` contract.

Batch processing rewards and terminations

---

solidity/contracts/PhasedEscrow.sol
solidity/contracts/stubs/TestPhasedEscrowBeneficiaries.sol
solidity/test/TestPhasedEscrow.js

In this PR we are adding 4 staker rewards beneficiary contracts. Each beneficiary contract can receive a withdrawal phase from a `PhasedEscrow` contract. Immediately transfers the received tokens to a designated `*RewardsEscrowBeneficiary` contract.
- `BeaconBackportRewardsEscrowBeneficiary`
- `BeaconRewardsEscrowBeneficiary`
-  `ECDSABackportRewardsEscrowBeneficiary`
- `ECDSARewardsEscrowBeneficiary`

Adding staker rewards escrow beneficiary contracts

---

solidity/contracts/PhasedEscrow.sol
solidity/contracts/stubs/TestPhasedEscrowBeneficiaries.sol
solidity/test/TestPhasedEscrow.js

We removed ECDSA rewards related beneficiaries contracts and moved them
to keep-ecdsa repository. The contracts require references to ECDSA
rewards contracts that are defined and dpeloyed in keep-ecdsa
repository. We should define beneficiaries there as well.
Refs https://github.com/keep-network/keep-core/pull/2149

Moved ECDSA rewards related beneficiaries contracts

---

solidity/contracts/PhasedEscrow.sol
solidity/test/TestPhasedEscrow.js

`withdrawFromEscrow` pulls all funds from a non-phased `Escrow` passed as a parameter. For `withdrawFromEscrow` to succeed, the `PhasedEscrow` has to be set as a beneficiary of the non-phased `Escrow`.
This PR is targeted to `solidity/v1.4.0` release branch and will have to be later backported to `master`.

Added PhasedEscrow.withdrawFromEscrow function

---

solidity/contracts/PhasedEscrow.sol
solidity/test/TestPhasedEscrow.js

This PR is backporting changes from `solidity/v1.4.1` version done on ` releases/solidity/v1.4` release branch in PR https://github.com/keep-network/keep-core/pull/2155. 
Quoting the referenced PR:
> `withdrawFromEscrow` pulls all funds from a non-phased `Escrow` passed as a parameter. For `withdrawFromEscrow` to succeed, the `PhasedEscrow` has to be set as a beneficiary of the non-phased `Escrow`.

Backport: Added PhasedEscrow.withdrawFromEscrow function

---

solidity/contracts/PhasedEscrow.sol
solidity/test/TestPhasedEscrow.js
solidity/test/token_stake/TestTopUps.js

Added receiveApproval function to token escrow pulling all of the
approved tokens. We will use this functionality to update staker rewards
for the interval 3.

Allow PhasedEscrow to receive tokens via approveAndCall

---

cmd/start.go
configs/config.toml.SAMPLE
go.mod
go.sum
pkg/beacon/relay/registry/groups_test.go
pkg/chain/chain.go
pkg/chain/ethereum/balance_monitor.go
pkg/chain/ethereum/connect.go
pkg/chain/ethereum/ethereum.go
pkg/chain/local/local.go
solidity/scripts/lcl-client-config.js

Closes https://github.com/keep-network/keep-core/issues/2163
Closes #2171
Refs: https://github.com/keep-network/keep-ecdsa/issues/551
Depends on: https://github.com/keep-network/keep-common/pull/51
Depends on: https://github.com/keep-network/keep-common/pull/59
Here we implement a simple balance monitor and enable it for the operator account balance. The monitoring routine checks the balance every 10 minutes and display a log error in case the balance falls below a threshold value passed from the config file.

Operator balance monitoring

---

docs/run-random-beacon.adoc

Three beacon mainnet bootstrap nodes from Staked.us staking provider.
I have also sorted bootstraps by providers in the same order as they are presented for ECDSA nodes to keep docs consistent.

Added Staked beacon mainnet bootstrap nodes

---

solidity/dashboard/src/components/UndelegateStakeButton.jsx

Closes: #2147 
The 2-month undelegate time began. The last moment to trigger undelegation in 2 weeks period was at `2020-10-26 12:43`.

Update confirmation modal text

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package.json

Release notes to come in the release notes page.
This bundles the work in https://github.com/keep-network/keep-core/milestone/26?closed=1.
We should merge after things are deployed. Leaving as a draft in the meantime.

Bump token dashboard release to v1.4.0

---

solidity/dashboard/Dockerfile

Closes: #2188 
To get the current app version we added the `.env` file that contains `REACT_APP_VERSION` env variable. This env variable is provided by `create-react-app` under the hood and used in `Footer` component. For the `create-react-app` be able to inject env variable the .env file is needed during the build process and we missed the `COPY .env* /app/` in Dockerfile. This missed snippet of code should have been added in https://github.com/keep-network/keep-core/commit/e014af0bb2a1affff857a0ce037947bbdf6a85f4.

Fix dapp build process via docker

---

solidity/dashboard/Dockerfile

This PR is a backport of `v1.4.1` fix done on `releases/mainnet/token-dashboard/v1.4` release branch in PR #2189.
To get the current app version we added the `.env` file that contains `REACT_APP_VERSION` env variable. This env variable is provided by `create-react-app` under the hood and used in `Footer` component. For the `create-react-app` be able to inject env variable the .env file is needed during the build process and we missed the `COPY .env* /app/` in Dockerfile. This missed snippet of code should have been added in https://github.com/keep-network/keep-core/commit/e014af0bb2a1affff857a0ce037947bbdf6a85f4.

[Backport] Fix dapp build process via docker

---

solidity/dashboard/src/components/ProgressBar.jsx
solidity/dashboard/src/components/TokenGrantOverview.jsx

The button should be disabled when there are no tokens to withdraw.
<details>
<summary>Available to Withdraw label  bug</summary>
</details>

Fix `withdraw tokens` btn

---

solidity/dashboard/src/components/ProgressBar.jsx
solidity/dashboard/src/components/TokenGrantOverview.jsx

This PR is a backport of `v1.4.1` fix done on `releases/mainnet/token-dashboard/v1.4` release branch in PR #2190. 
The button should be disabled when there are no tokens to withdraw.
<details>
<summary>Available to Withdraw label  bug</summary>
</details>

[Backport] Fix `withdraw tokens` btn

---

solidity/dashboard/src/components/Web3ContextProvider.jsx

This is a temporary solution to prevent a situation when a user changed an account but data has not been updated. After migrate to redux the dapp fetches data only once and updates data based on emitted events. This solution doesn't support a case where a user changed an account. We are going to address it in a follow-up work.

Refresh a dapp on `accountChanged` event

---

solidity/dashboard/src/services/rewards.js

If the beneficiary has multiple operators, we should call `getWithdrawableRewards` one time in the given interval since `ECDSARewards` contract stores rewards per beneficiary not per operator.
https://github.com/keep-network/keep-ecdsa/blob/4fcb922ecaf319c0c4c14c2a9c5ee96b56756c31/solidity/contracts/ECDSARewards.sol#L155-L164

Fix fetching ecdsa available rewards

---

solidity/dashboard/src/services/rewards.js

This PR is a backport of v1.4.1 fix done on releases/mainnet/token-dashboard/v1.4 release branch in PR #2193.
If the beneficiary has multiple operators, we should call `getWithdrawableRewards` one time in the given interval since `ECDSARewards` contract stores rewards per beneficiary not per operator.
https://github.com/keep-network/keep-ecdsa/blob/4fcb922ecaf319c0c4c14c2a9c5ee96b56756c31/solidity/contracts/ECDSARewards.sol#L155-L164.

[Backport] Fix fetching ecdsa available rewards

---

solidity/dashboard/src/components/Web3ContextProvider.jsx

This PR is a backport of v1.4.1 fix done on releases/mainnet/token-dashboard/v1.4 release branch in PR #2196.
This is a temporary solution to prevent a situation when a user changed an account but data has not been updated. After migrate to redux the dapp fetches data only once and updates data based on emitted events. This solution doesn't support a case where a user changed an account. We are going to address it in a follow-up work.

[Backport] Refresh a dapp on `accountChanged` event

---

solidity/dashboard/src/sagas/subscriptions.js

There was a typo in the event name. `TopUpCompleeted` -> `TopUpCompleted`.

Fix subscription to TopUpCompleted event

---

solidity/dashboard/src/sagas/subscriptions.js

This PR is a backport of v1.4.1 fix done on releases/mainnet/token-dashboard/v1.4 release branch in PR #2198.
There was a typo in the event name. `TopUpCompleeted` -> `TopUpCompleted`.

[Backport] Fix subscription to TopUpCompleted event

---

solidity/dashboard/src/components/Timer.jsx
solidity/dashboard/src/pages/rewards/TBTCRewardsPage.jsx
solidity/dashboard/src/utils/rewardsHelper.js

This PR implements a timer on the tBTC Rewards page that shows when the next rewards will be released.

Implement timer for tBTC Rewards interval

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/dashboard/src/rewards-allocation/rewards.json

See https://github.com/keep-network/keep-core/milestone/30?closed=1
Releasing `token-dashboard/v1.5.0` with the support of Merkle tree-based reward distributor. 
Rewards allocation, as updated in `rewards.json` comes from https://github.com/keep-network/keep-ecdsa/pull/644.

Token Dashboard release v1.5.0

---

solidity/contracts/PhasedEscrow.sol
solidity/test/TestPhasedEscrow.js

Possibly replaces #2225.
BatchedPhasedEsrow` is a token holder contract allowing contract owner to
approve a set of beneficiaries of tokens held by the contract, to
appoint a separate drawee role, and allowing that drawee to withdraw
tokens to approved beneficiaries in phases.
This contract is not the ultimate solution for a secure escrow with a
separate role withdrawing tokens. Notably, it does not limit the amount
or frequency of withdrawals so compromised drawee can drain the escrow
funds to one of the selected approved beneficiaries. The escrow owner
should proceed with caution and do not transfer all funds to
`BatchedPhasedEscrow`. Instead, funds should be transferred in tranches,
depending on how drawee spends them.
`CurveRewards` and `LPTokenRewards` contracts from `keep-ecdsa` …

BatchedPhasedEscrow

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

8f4e51a is a commit for `token-dashboard/v1.6.0` tag.
This bundles work in https://github.com/keep-network/keep-core/milestone/38?closed=1.
Release notes to come in the release notes page.

KEEP Token Dashboard release v1.6.0

---

solidity/dashboard/src/components/ProgressBar.jsx

Closes: #2243
Set two decimal places for the percentage value of the circular progress bar
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Set two decimal places for the value of the progress bar

---

go.mod
go.sum

The code in v1.3.0 tag is the same as in the previously referenced
commit hash. Instead of referencing some commit we are just referencing
a release version now.

Updated keep-common dependency to v1.3.0

---

solidity/dashboard/src/components/LiquidityRewardCard.jsx
solidity/dashboard/src/css/liquidity-page.less

Liquidity rewards empty pool ui changes
Issues changed/fixed by this PR:
- gray out liquidity info when the % of the pool is equal to 0
- change text of the button "add more lp tokens" to "deposit lp tokens" when the % of the pool is equal to 0
- enable 'withdraw all' button to allow the user to withdraw the lp tokens when there are no rewards yet

Liquidity rewards empty pool

---

SECURITY.adoc

This outlines both the versions that are supported for vulnerabilities at this
time, as well as the requested process for disclosing vulnerabilities to the
team.
Goes hand-in-hand with keep-network/website#325.

Add SECURITY.md with vulnerability disclosure policy

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards allocation computed in keep-network/keep-ecdsa#664 to KEEP Token Dashboard.

tBTC rewards allocation: 2021-01-01 -> 2021-01-08

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of #2278 
Adding tBTC rewards allocation computed in keep-network/keep-ecdsa#664 to KEEP Token Dashboard.

[Backport] tBTC rewards allocation: 2021-01-01 -> 2021-01-08

---

solidity/dashboard/src/actions/messages.js

Closes: #2277 
Fixed Etherscan link of successful transaction. The link did not
include the transaction hash because to the constructor of `Message`
object did not assign the `txHash` property to the Message object. This
commit fixes this issue by assigning the `txHash` property to the
`Message` object in constructor.
**Fix**

Fix Etherscan link of successful transaction

---

pkg/beacon/relay/state/machine.go
pkg/net/libp2p/channel.go

Here we introduce some improvements for state machine and broadcast channel buffers. The main motivation behind those changes is to minimize the number of dropped messages and hence increase the delivery rate. Specifically, we are touching those buffers:
- `receiveBuffer` living in the state machine. We change its size because the current value of `64` elements may be not
sufficient due to the DKG commitment phase which sends two types of messages. Giving the fact the group size is currently `64` members, each group member's state machine could receive `128` messages during the commitment phase. If those messages are not processed quickly enough, the `64` elements buffer will overflow easily and subsequent messages will be dropped by the broadcast channel handler. Aligning the receiver …

Improvements around state machine and broadcast channel buffers

---

solidity/dashboard/src/components/LiquidityRewardCard.jsx

Remove `value` property from `formattedApy` in the condition that checks if `formattedApy` is infinite.
This bug in some scenarios caused apy to be printed as >Infinity% instead of ♾️ sign.

Fix infinity APY

---

.github/workflows/npm.yml

The action will be used to publish prerelease packages to the NPM package registry. It will be executed on a push to master if there are any changes to solidity contracts or dependencies.
Refs: https://github.com/keep-network/keep-ecdsa/pull/659/

GitHub action for NPM package publication

---

.circleci/config.yml

We can't build dashboard right after keep-core migration as we also have dependencies for keep-ecdsa and tbtc. So we first need to migrate all three projects and only after that can execute dashboard building.
The flow would look like:
- approve `build-test-migrate-publish-keep-test` execution
- kick off migrations and package publication for dependencies: `keep-ecdsa` and `tbtc` projects
- approve `build-publish-dashboard-keep-test`.

Separated dashboard build for keep-test

---

solidity/dashboard/src/reducers/liquidity-rewards.js

When someone withdraw the tokens from the pool, then the share of the total pool shows wrong value and it is needed to refresh the page.
How to reproduce the bug:
1. Log in in Chrome as a user who have some tokens in the pool (for example KEEP + ETH)
2. Log in in Firefox as a user who have some tokens int he pool (for example KKEP + ETH)
3. Withdraw all tokens as Firefox user
4. After 5-10 secs the Chrome user % of the total pool will update and will show the wrong value. After refresh it shows correct value.
This PR fixes the bug above, so the user doesn't have to refresh the page.

Fix share of the total pool when withdrawing

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

78d158f is a commit for token-dashboard/v1.7.0 tag.
This bundles work in https://github.com/keep-network/keep-core/milestone/33?closed=1.
Release notes to come on the release notes page.

KEEP Token Dashboard release v1.7.0

---

solidity/dashboard/src/components/LiquidityRewardCard.jsx
solidity/dashboard/src/contracts.js
solidity/dashboard/src/pages/liquidity/LiquidityPage.jsx
solidity/dashboard/src/reducers/liquidity-rewards.js
solidity/dashboard/src/sagas/liquidity-rewards.js

This PR adds support for calculating the APY value for each `LPRewards` contract without a connected wallet.

Calculate APY w/o connected wallet

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

bdee794 is the commit hash for `token-dashboard/v1.7.1`
This bundles a fix from https://github.com/keep-network/keep-core/pull/2289.

KEEP Token Dashboard release v1.7.1

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/dashboard/src/connectors/index.js

The previous version of web3 (1.2.7) doesn't support the breaking changes of
version 9.0.0 of the MetaMask extension described in
MetaMask/metamask-extension#8077.

Bump web3 dependency to v1.3.1

---

solidity/dashboard/src/constants/constants.js
solidity/dashboard/src/sagas/liquidity-rewards.js
solidity/dashboard/src/sagas/subscriptions.js
solidity/dashboard/src/services/liquidity-rewards.js

We can compute weekly rewards based on data in LPRewards contract
instead of hardcoded values -> `LPReward.rewardRate * 7 days in seconds`

Fetch liquidity reward per week from contract

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

c97a6fd68b562d7c7016a8b600849e53b68615a4 is the commit hash for `token-dashboard/v1.8.0`.
This bundles work from https://github.com/keep-network/keep-core/milestone/41?closed=1

KEEP Token Dashboard release v1.8.0

---

solidity/dashboard/src/services/liquidity-rewards.js

Store in the `LPRewardsToWrappedTokenCache` address of the wrapped token instead of the web3 contract instance. In case the web3 provider has changed. This PR also fixes the `No "from" address...` error on staking in `LPRewards`.

Fix creating the wrapped token of the LPRewards

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

238cefa2a625a373a6ae5c4fab44cdad75b7efb9 is the commit hash for `token-dashboard/v1.8.1`.
This bundles work from https://github.com/keep-network/keep-core/milestone/42?closed=1.

Releases/mainnet/token dashboard/v1.8.1

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json

Closes: #2300 
This v1.3.3 version is a hot fix to address breaking changes in the
MetaMask API provided in v.9.
Details:
https://github.com/ChainSafe/web3.js/pull/3864
https://github.com/MetaMask/metamask-extension/issues/8077#issuecomment-765004856

Bump web3 dependency to v1.3.3

---

solidity/dashboard/src/services/liquidity-rewards.js

Get reward pool per week value based on rewardRate() method from the
LPRewardsContract instead of hardcoding the value.

Fix reward pool per week for saddle pool

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

fd41a60b76a4e87769907fac36199f96cfc6ee4d is the commit hash for `token-dashboard/v1.9.0`
This bundles work from https://github.com/keep-network/keep-core/milestone/43?closed=1.

Releases/mainnet/token dashboard/v1.9.0

---

scripts/macos-setup.sh

The [manual setup doc](https://github.com/keep-network/local-setup/blob/master/docs/manual-setup.adoc#title) details that "If you are not on macOS or you don’t have Homebrew, you need to install:", and then lists `jq`, but the `macos-setup.sh` script doesn't install `jq` for you.
I also confirmed that `jq` is indeed necessary for the project via bricking by not having it XD
This PR adds a brew line to install it similar to how the rest of the dependencies are installed!

Add jq to the macos Setup Script

---

go.mod
go.sum
pkg/chain/ethereum/connect.go
pkg/chain/ethereum/ethereum.go
pkg/chain/ethereum/utility.go
pkg/chain/gen/cmd/KeepRandomBeaconService.go
pkg/chain/gen/cmd/TokenGrant.go
pkg/chain/gen/cmd/TokenStaking.go
pkg/chain/gen/contract/KeepRandomBeaconOperator.go
pkg/chain/gen/contract/KeepRandomBeaconService.go
pkg/chain/gen/contract/TokenGrant.go
pkg/chain/gen/contract/TokenStaking.go

Depends on: https://github.com/keep-network/keep-common/pull/65
Regenerated contract bindings in order to take advantage of the new subscriptions model introduced in `keep-common`. Also, adjusted the code which uses those subscriptions to work with the new approach.

Regenerate contract bindings to leverage new subscriptions model

---

.circleci/config.yml
.github/workflows/client.yml
pkg/beacon/beacon_test.go

and tBTC release processes in order to reduce human involvment and make
the processes faster and less error prone. A part of this task is
migration from CircleCI jobs to GitHub Actions. This commit creates a
GitHub Action workfow for building and testing Go client.

Create GH Actions workflow for build&test of Go client

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json

37a513e3f7fcade6567d543fa2952aaf2488834b is the commit hash for token-dashboard/v1.10.0
This bundles work from https://github.com/keep-network/keep-core/milestone/45?closed=1

KEEP Token Dashboard release v1.10.0

---

scripts/start_dashboard.sh

Calling `npm link` multiple times in one directory, for whatever reason,
unlinks all links and then only links the executed command. So:
```
npm link foo
npm link bar
```
will link foo, unlink `foo`, and then link `bar`. This leaves you with only
`bar` linked. To link both, we flatten the command:
```
npm link foo bar
```
tagging @Shadowfiend for review since he also reviewed the nearly-identical https://github.com/keep-network/local-setup/pull/59

Flatten the `npm link` commands into one line

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/dashboard/src/contracts.js

This PR fixes KEEP-only pool contract import in the KEEP token dashboard.

Fix KEEP-only pool contract import

---

.circleci/config.yml
.github/workflows/client.yml

We restricted branches for which Go build and test workflow gets
executed. Currently execution duplicates with workflow executed in CircleCI.
We defined `rfc-18/` prefix. For branches with that prefix, jobs will be
executed in GH Actions instead of Circle CI.
Refs: https://github.com/keep-network/keep-core/blob/master/docs/rfc/rfc-18-release-management.adoc
Refs: https://github.com/keep-network/keep-core/pull/2318

Run Go workflow only on `rfc-18/**` branches

---

scripts/install-celo.sh
scripts/install.sh

It is better to inform a user that a provided priv key is needed when operating on non-local networks only, ex. Celo Alfajores

Adding info that an account priv key is for non-local network only

---

docs/run-random-beacon.adoc

Updated contracts addresses in test environment documentation. The
contracts were migrated in `@keep-network/keep-core@1.6.1-rc.0` and are
currently backed by nodes running in keep-test environment.
Circle CI job: https://app.circleci.com/pipelines/github/keep-network/keep-core/8335/workflows/822c0377-8380-44e2-b60b-b348e4f016ba

Updated docs pointing to ropsten contracts

---

go.mod
go.sum
pkg/chain/ethereum/connect.go
pkg/chain/gen/cmd/KeepRandomBeaconService.go
pkg/chain/gen/cmd/TokenGrant.go
pkg/chain/gen/cmd/TokenStaking.go
pkg/chain/gen/contract/KeepRandomBeaconOperator.go
pkg/chain/gen/contract/KeepRandomBeaconService.go
pkg/chain/gen/contract/TokenGrant.go
pkg/chain/gen/contract/TokenStaking.go

Depends on: https://github.com/keep-network/keep-common/pull/64
Updated the `keep-common` dependency version to use the new `ethlike` package and regenerated contract bindings. This change is one of the steps which prepares the codebase to be ready for supporting new chains.

Incorporate the `ethlike` package

---

.github/workflows/contracts.yml

and tBTC release processes in order to reduce human involvment and make
the processes faster and less error prone. A part of this task is
migration from CircleCI jobs to GitHub Actions. For keep-core part of
the workflow responsible for testing and linting of Solidity build
was already developed as a GitHub Actions workflow. This commit
introduces four changes to the workflow, to make the implementation
similiar to analogous workflow in keep-core.
Those changes are:
1. Added triggering of workflow on push and pull request events for
'rfc-18/*' branches
2. Updated versions of actions
3. Added step that builds solidity contracts
4. Name of 'test' step changed to 'build-and-test'

Unification of GH Action solidity workflows between keep-core and keep-ecdsa

---

.circleci/config.yml
.github/workflows/client.yml

and tBTC release processes in order to reduce human involvment and make
the processes faster and less error prone. A part of this task is
migration from CircleCI jobs to GitHub Actions. This commit enhances the
workflow for building and testing Go with a step publishing the created
image to the Google Container Registry.
For now only keep-test configuration is implemented. Implementation for
other environments will be done at later stage of work on RFC-18.

Create GH Actions workflow for publish of Go client

---

solidity/test/token_stake/TestStakingGrant.js

This can be caused by OZ library that adds a split of a second when increasing the time programatically which results in amounts that are slightly less than expected.

Fixing TestStakingGrant test that fails occasionally

---

solidity/dashboard/src/pages/OverviewPage.jsx
solidity/dashboard/src/pages/liquidity/LiquidityPage.jsx

URL change for the "Get KEEP tokens" links.
Routes users to the ETH<>KEEP pairs on [Balancer](https://balancer.exchange/#/swap/ether/0x85eee30c52b0b379b046fb0f85f4f3dc3009afec) and [Uniswap](https://app.uniswap.org/#/swap?inputCurrency=ETH&outputCurrency=0x85eee30c52b0b379b046fb0f85f4f3dc3009afec)

Change swap links to the ETH<>KEEP pairs

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

KEEP Token Dashboard v1.10.2 release branch. This release will bundle the work from https://github.com/keep-network/keep-core/milestone/46?closed=1

releases/mainnet/token dashboard/v1.10.2

---

solidity/dashboard/src/css/tooltip.less

Fix the spacing issue with the tooltip in Overview page by overwriting the
styles imposed by <h> tag.
Closes: #2202

Fix tooltip style problems in Overview page

---

solidity/dashboard/src/css/rewards-page.less
solidity/dashboard/src/pages/rewards/EmptyStatePage.jsx

Removes the second skeleton row of the Rewards empty state page to show CTA on smaller screens. Closes #2205.

Fix below-fold CTA issue on Rewards empty state page

---

solidity/dashboard/src/sagas/subscriptions.js

Closes: #2339 
In some cases Wallet Balance in the **Overview** page was not displayed properly.
<details>
<summary>Recreating the issue</summary>
I managed to recreate the issue on Ropsten. To do that you must have 2 accounts.
1. Log in on account 1 on Google Chrome
2. Log in on account 2 on Firefox
3. Delegate some tokens to another account with account 1
4. Create token grant for account 1 using account 2
5. After a while the wallet balance of the account #1 will change even though we didn't withdraw the tokens from the grant yet. The issue disappear after refreshing the page.
</details>
There was a problem with `arithmeticOperation` variable in `subscriptions.js` file. We define it in a while loop without setting a value and assign some value later in the if statement. The problem is …

Fix the problem with displaying KEEP tokens in the Overview page

---

token-tracker/src/truth-sources/token-grant.js

When calculating KEEP balances for a grant address, we need to filter out addresses that ended up having zero KEEP amount.

Filtering out grants that ended up having 0 balance

---

.circleci/config.yml
.github/workflows/contracts.yml
solidity/tenderly.yaml

and tBTC release processes in order to reduce human involvement and
make the processes faster and less error prone. A part of this task is
migration from CircleCI jobs to GitHub Actions. This commit enhances
the workflow for building and testing Solidity with a job migrating
contracts and publishing them to the npm registry. Contracts also get
pushed to Tenderly and uploaded to Google Cloud Storage. For now, only
keep-test configuration is implemented. Implementation for other
environments will be done at a later stage of work on RFC-18.
The `migrate-and-publish-ethereum` job is configured to execute only if
workflow is started by a push or workflow_dispatch event on `master` or
`rfc-18/*` branch. The `rfc-18/*` …

Move migration and publishing of contracts (Ethereum) to GH Actions

---

.circleci/config.yml
.github/workflows/contracts.yml

and tBTC release processes in order to reduce human involvement and 
make the processes faster and less error prone. A part of this task is
migration from CircleCI jobs to GitHub Actions. This PR enhances 
the Solidity workflow with a job building Solidity initcontainer and 
publishing it to the Google Container Registry. For now, only keep-test
configuration is implemented. Implementation for other environments 
will be done at a later stage of work on RFC-18.
The `build-and-publish-initcontainer` job is configured to execute 
after successful execution of `migrate-and-publish-ethereum`. As 
`build-and-publish-initcontainer` requires artifacts from 
`migrate-and-publish-ethereum`, they are passed between jobs using …

Move building and publishing of Solidity initcontainer to GH Actions

---

solidity/dashboard/src/components/LiquidityRewardCard.jsx
solidity/dashboard/src/css/liquidity-page.less
solidity/dashboard/src/pages/liquidity/LiquidityPage.jsx

Adds a warning to the KEEP-TBTC pool that informs the users that incentives for
this pool has been removed. Also blocks the possibility to add lp tokens to
KEEP-TBTC pool.
Also removes APY and % of the share pool from KEEP-TBTC pool.

Add "incentives removed" warning to the KEEP-TBTC pool

---

solidity/dashboard/src/components/DelegateStakeForm.jsx
solidity/dashboard/src/components/FormInput.jsx
solidity/dashboard/src/constants/constants.js
solidity/dashboard/src/css/delegate-stake-form.less
solidity/dashboard/src/css/forms.less
solidity/dashboard/src/css/typography.less
solidity/dashboard/src/pages/OverviewPage.jsx
solidity/dashboard/src/pages/delegation/index.js
solidity/dashboard/src/utils/minimum-stake-schedule.js
solidity/dashboard/src/utils/token.utils.js

Closes: #2185 
This PR makes some UI changes to the staking tokens input in Overview page.
Main changes:
- remove progress bar with available KEEP tokens below the input
- fix the ui problem with higher number of KEEP tokens written inside input that would cover the Max Stake button
- add a tooltip that will inform user that the min stake is about to decrease to 50,000 soon
- change the order of the Wallet Tokens page and Granted Tokens page on the top menu of Delegations page
- some UI changes based on [Figma](https://www.figma.com/file/Su61MwHLrQn3ld24q85pMx/Token-Dashboard-dApp?node-id=8642%3A13364)
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Staking keep token form redesign

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

KEEP Token Dashboard `v1.11.0` release branch. This release will bundle the work from https://github.com/keep-network/keep-core/milestone/36?closed=1.

releases/mainnet/token dashboard/v1.11.0

---

token-stakedrop/README.adoc

Some updates to the documentation so that the information on how
KEEP token balances are resolved is more precise.

Updates to token stakedrop documentation

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json

The dashboard is built and published automatically for keep-test on master merge. It's using versions provided in `package.json`. With this commit, we're hardcoding the versions of contracts deployed already to ropsten and used in keep-test environment. Once a change to the dashboard is merged to master (with these versions) it's published to the keep-test bucket and we can deploy it to keep-test environment.
Following packages are used:
keep-core@1.8.0-pre.6 -- https://github.com/keep-network/keep-core/actions/runs/686297746
keep-ecdsa@1.7.0-pre.8 -- https://github.com/keep-network/keep-ecdsa/actions/runs/690005293
tbtc@1.1.2-pre.0 -- https://github.com/keep-network/tbtc/actions/runs/698185957

Pin dashboard dependencies versions on ropsten

---

solidity/contracts/token-distribution/TokenDistributor.sol
solidity/test/token-distribution/TokenDistributorTest.js
solidity/test/token-distribution/testData.json

To prevent reusability of the signatures in other contracts that require
signature of an address we included the contract's address in the message
to sign to increase the uniqueness of the message.
In order to claim an airdrop, users have to sign a message with the destination address.
However: the signature is not somehow tied to the deployed TokenDistributor contract and
could be re-used, either in another instance of the same contract or in another contract that
uses a similar signature.
A user signs a message to claim the Keep distribution. An attacker notices the signature
and reuses it in a different contract that requires a signature of an address. The results can
be unexpected for the user that produces the signature because they do not want for their
signature to be re-used in a …

TokenDistributor: Sign deployed contract address along with destination address

---

.github/workflows/dashboard-testnet.yml

Step building and publishing the Token Dashboard image was missing the
specification of build context.

Fix building of Token Dashboard image

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json

We pined versions in the dashboard to a specific packages deployed on
ropsten to make sure the dashboard is working fine with the contracts
supported by keep-test nodes.

Pin dependencies versions in dashboard

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#757 to KEEP Token Dashboard.

tBTC reward allocation 2021-03-26 -> 2021-04-02

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2407
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#757 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-03-26 -> 2021-04-02

---

docs/run-random-beacon.adoc

Updated addresses of contracts from the latest migration to ropsten that
is supported by nodes running in keep-test environment.
The migration:
https://github.com/keep-network/keep-core/actions/runs/686297746

Updates to run client guide after ropsten migrations

---

solidity/dashboard/src/__tests__/saga/rootSaga.test.js
solidity/dashboard/src/contracts.js
solidity/dashboard/src/sagas/index.js
solidity/dashboard/src/services/liquidity-rewards.js

The APY on the Liquidity rewards page should be fetched w/o connected wallet.
The saga which fetches APY should start in the root saga before the
login/logout flow.

Fix fetching APY w/o connected wallet

---

solidity/dashboard/src/services/token-staking.service.js

This PR fixes fetching operators of owner. In the `getOperatorsOfOwner` function we used `getContractDeploymentBlockNumber` in wrong way.

Fix fetching operators of owner

---

solidity/dashboard/src/pages/rewards/RandomBeaconRewardsPage.jsx

The saga that fetches the Beacon rewards expects object with `address`
property in a payload.

Fix fetching Random Beacon rewards

---

solidity/test/geyser/TestKeepTokenGeyser.js
solidity/test/helpers/numbers.js
solidity/test/token_stake/TestStakingGrant.js
solidity/test/token_stake/TestTokenStakingEscrow.js

Some tests are failing occasionally due to a value not exactly as expected. There is a time factor so the value may slightly diverge from expectations. With these updates, we're checking if values are close to the expected ones within a specific range.
Sample CI execution that had failures: 
https://github.com/keep-network/keep-core/runs/2113275081
https://github.com/keep-network/keep-core/runs/2352840657
Refs https://github.com/keep-network/keep-core/pull/2354.

Fix tests that fail occasionally with values close to expected

---

solidity/dashboard/src/services/token-staking.service.js

The paid-back delegations from `StakingPortBacker` contract should be
displayed as delegations from liquid tokens, not from a grant. So we
need to filterout paid back delegations while fetching delegations from
a grant. Otherwise, the delegations will be duplicated and be displayed
under `Wallet Tokens` and `Granted Tokens` tab on the `Delegations`
page.

Fix displaying paid-back delegations

---

solidity/dashboard/src/services/token-staking.service.js

When fetching paidBackDelegations we used the old way of getting the `fromBlock`
number which was changed in 221fea5fd9da01e933e1b1f854243478cdb857c2 commit.

Fix fetching paid back delegations

---

.github/workflows/client.yml
.github/workflows/contracts.yml
.github/workflows/dashboard-testnet.yml

and tBTC release processes in order to reduce human involvement and to
make the processes faster and less error prone. We've migrated most of
CircleCI jobs to GitHub Actions. Now we want to introduce branch
protection rules on master, requiring the passing of particular jobs
before merging PR to master. Those jobs are:
* client-build-test-publish
* client-scan
* contracts-build-and-test
* contracts-lint
* dashboard-build-and-publish
What's more, we want to execute workflows containing those jobs only if
there were changes in particular paths. GitHub Actions allows for
specifying those paths by using `on.<event_name>.paths` syntax.
Unfortunately, such configuration for the `pull-request` event clashes
with the …

Use path-filter action in workflows to support required checks in PRs

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#770 to KEEP Token Dashboard.

tBTC reward allocation 2021-04-16 -> 2021-04-23

---

.github/workflows/contracts.yml
.github/workflows/dashboard-testnet.yml

In previous PRs/commits we've implemented functionality allowing for
skipping of particular jobs triggered by `pull_request` event if the PR
doesn't introduce changes to specified files/paths. This wa done to
allow setting such jobs as required for PR merge (PR can be merged if a
required job is Passed os Skipped).
When job is being set in GitHub settings as required for PR merge, it's
name must be specified - usually that name is a `job_id`, but when
`matrix` strategy is being used in the job, the name will consist of
`job_id` and matrix value (e.g. `contracts-lint (12.x)`. Unfortunately
we discovered that appending of the `job_id` with matrix value
happens when job is being executed, but does not happen for jobs that
are being skipped. This means that we cannot set neither job …

Don't use matrix in jobs required for merging PR which can be skipped

---

solidity/test/token_stake/TestTokenStakingEscrow.js

The test TokenStakingEscrow was ocassionally failing because
value differs in time and it can happen that it's not exactly the
expected one but it's very close.
After the change 1% margin is applied when comparing the
values.
Sample execution where the test was failing:
https://github.com/keep-network/keep-core/runs/2378321057

Fix test occasionally failing due to value close to expected

---

solidity/dashboard/src/components/ExplorerModeAddressForm.jsx
solidity/dashboard/src/components/FormInput.jsx

The helper text is not giving enough context as to what an address
is/what this will do. Also here we moved a tooltip over above the form
input instead of over it for better readability. Based on the comments
posted in #2442.

Improve helper text in explorer mode address form

---

.github/workflows/contracts.yml

We're no longer pushing migrated contracts artifacts to GCP Bucket as
the artifacts are being published to NPM registry. In the repos using
artifacts of keep-core we will rework the code to pull the contracts
addresses from the NPM packages instead of the bucket. It gives us
flexibility to execute migrations for different environment in modules
in pararell. Additionally we will no longer overwrite contracts data
with the latest run of the workflow.

Stop pushing contracts artifacts to GC Bucket

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#778 to KEEP Token Dashboard.

tBTC reward allocation 2021-04-30 -> 2021-05-07

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2455
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#778 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-04-30 -> 2021-05-07

---

scripts/install-celo.sh
scripts/install.sh
scripts/start_dashboard.sh

This PR refactors local installation scripts to utilize changes introduced in https://github.com/keep-network/keep-core/pull/2450.
Changes:
- use npm links between local modules to obtain migrated contracts instead of referring to the path where the artifacts sit,
- introduce contracts only flag to installation script to let skip go client installation (useful for dashboard installation),
- update the dashboard start script to utilize the changes to modules installation scripts.
Follow-up PRs in other repositories are expected to be created.

Local installation scripts refactoring

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#791 to KEEP Token Dashboard.

tBTC reward allocation 2021-05-07 -> 2021-05-14

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2469
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#791 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-05-07 -> 2021-05-14

---

solidity/docs/README.md

Closes: #2334 
This README file is a part of the abandoned Solidity API docs CI build so is no longer valid. More context here: https://www.flowdock.com/app/cardforcoin/tech/threads/-9kWxCim5nVgKG4TttURbggBKgO

Fix broken links in solidity/docs

---

solidity/dashboard/src/constants/constants.js

Closes: #2454 
On the Liquidity page the links that point to Uniswap are broken due to
their update from v2 to v3. This commit will fix it and links redirect
correctly to the v2 pools.

Fix uniswap broken links

---

solidity/dashboard/src/components/Footer.jsx

Closes: #2462 
Using the `moment` lib to get current year instead of hardcoded value.

Update copyright in the footer

---

.github/workflows/npm.yml

`NPM` workflow will be used to publish the contracts needed for the
setup of development environment to NPM registry. Before the change we
were not compiling the contracts before publishing, which was a problem,
because this way not all the files needed by the downstream workflows
were being published. As a result of contracts compilation system will
generate `*.json` files needed by the later workflows. We will then
place them in the `artifacts` directory. By the `package.json`
configuration this directory is being picked by the publish step along
with the `contracts/**/*.sol` files.
Apart from this change, couple of small updates were introduced to `NPM`
workflow, mainly update to higher versions of used external actions.
Corresponding changes in `keep-ecdsa` project: …

Compile contracts before publishing

---

solidity/package-lock.json
solidity/package.json

`-dev` suffix will be used for the versioning of the `keep-core` module
built with the purpose of being used on development environment.
Packages with the `-dev`-suffix will be pushed to the NPM registry by
the `NPM` GH Actions workflow.
Note that packages meant for the test environment (Ropsten) will be
versioned independently, based on the suffix provided during manual
triggering of the `Main` workflow in `ci` project.

Use `-dev` suffix in the versioning of the `keep-core` module

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#795 to KEEP Token Dashboard.

tBTC reward allocation 2021-05-14 -> 2021-05-21

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2479
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#795 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-05-14 -> 2021-05-21

---

solidity/dashboard/src/components/Modal.jsx

This PR fixes the bug which prevented modal window's title from being displayed after changes from #2444

Fix bug with modal window's title not displaying

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

The v1.14.0 has been released.

Bump the KEEP Token Dashboard version to v1.15.0-pre

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#812 to KEEP Token Dashboard.

tBTC reward allocation 2021-05-28 -> 2021-06-04

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2488
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#812 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-05-28 -> 2021-06-04

---

.github/workflows/client.yml
.github/workflows/contracts.yml
.github/workflows/dashboard-testnet.yml

The `keep-network/ci` repository storing the config files used by the
`load-env-variables` action is no longer private. This means that we
no longer need to authenticate curl with the token allowing access to
the repository.
See also:
https://github.com/keep-network/keep-ecdsa/pull/818
https://github.com/keep-network/tbtc/pull/803
https://github.com/keep-network/tbtc-dapp/pull/397

No longer set CI_GITHUB_TOKEN for load-env-variables action

---

.github/workflows/client.yml
.github/workflows/contracts.yml
infrastructure/kube/keep-dev/keep-client-0-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-1-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-2-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-3-statefulset.yaml
infrastructure/kube/keep-dev/keep-client-4-statefulset.yaml
infrastructure/kube/keep-dev/keep-network-relay-request-cronjob.yaml
infrastructure/kube/keep-test/keep-client-0-statefulset.yaml
infrastructure/kube/keep-test/keep-client-1-statefulset.yaml
infrastructure/kube/keep-test/keep-client-2-statefulset.yaml
infrastructure/kube/keep-test/keep-client-3-statefulset.yaml
infrastructure/kube/keep-test/keep-client-4-statefulset.yaml
infrastructure/kube/keep-test/keep-network-ropsten-relay-request-cronjob.yaml
solidity/truffle-config.js

Workflows have been refactored so that Celo-related artifacts could be
deployed in the chain of automatic execusions triggered by the manual
dispatch of the `Main` workflow in the `ci` project (with `environment`
set to `alfajores`).
Similar changes have been introduced to keep-core and tbtc
workflows. See:
https://github.com/keep-network/keep-ecdsa/pull/823
https://github.com/keep-network/tbtc/pull/804

Refactor workflows to add deployment of contracts migrated on Celo

---

README.adoc
solidity/dashboard/README.md

We no longer use CircleCI to test/build the `keep-core` code. We need to
replace the CircleCI build status badge in the projec'ts README with the
similiar badges for GitHub Actions builds.
Two badges have been introduced in place of the old one:
* Contracts (showing status of the last `Solidity` workflow executed on
`master` branch and triggered by the push event),
* Go client (showing status of the last `Go` workflow executed on
`master` branch and triggered by the push event).
The badges are displayed using `shields.io` tool, which was already used
for the Discord badge.
Also a badge was added in the README of the Token Dashboard:
* Token Dashboard / Testnet (showing status of the last `Token Dashboard
/ Testnet` workflow on `master` branch and triggered by the push event).
This time …

Replace the CircleCI build status badge with GHA badges

---

.github/workflows/client.yml
.github/workflows/contracts.yml
.github/workflows/dashboard-mainnet.yml
.github/workflows/dashboard-testnet.yml
.github/workflows/docs.yml
.github/workflows/npm.yml
README.adoc
docs/development-process.adoc
docs/development/README.adoc
docs/development/local-keep-network.adoc
docs/run-random-beacon.adoc
solidity/dashboard/README.md
solidity/dashboard/src/components/resources/DocumentationSection.jsx
solidity/dashboard/src/components/resources/TerminologyDataTable.jsx
solidity/dashboard/src/services/rewards.js

Use of the `master` and `slave` terms in the computer industry is
widespread, but has been recently discouraged, as it was brought to
attention that the terms may be considered offensive.
GitHub has already moved their default repositories from the `master`
to `main` in many places. We're planning to do the same for our
repositories, this however requires some changes in the code.
After the proposed changes get merged to the `master` branch, the
repository should be ready for the migration from `master` to `main`.
To migrate from `master` to `main`:
1. Do a local branch rename with `git branch -m master main`
2. Push the renamed branch `git push -u origin main`
3. In the Github repo settings, rename the default branch: Settings ->
Branches -> Default branch -> (pencil icon) -> (change …

Migrate from `master` to `main` branch

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2533
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#862 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-07-02 -> 2021-07-09

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2540
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#866 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-07-09 -> 2021-07-16

---

.github/workflows/dashboard-testnet.yml

We are adding a new functionality of coverage pools to the Keep Network.
The contracts required for its support are stored in the
`coverage-pools` repo and are deployed to the npm registry thanks to the
`coverage-pools/.github/workflows/contracts.yml` workflow.
In this PR we are updating the workflow building Token Dashboard to
use those published `coverage-pools` contracts.

Resolve coverage-pools contracts

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2546
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#869 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-07-16 -> 2021-07-23

---

.github/workflows/dashboard-testnet.yml

Change introduced for better understandability of parameter's meaning.
Refs:
https://github.com/keep-network/keep-ecdsa/pull/864
https://github.com/keep-network/tbtc/pull/814
https://github.com/keep-network/tbtc.js/pull/127
https://github.com/keep-network/upstream-builds-query/pull/3
https://github.com/keep-network/coverage-pools/pull/157

Rename `-solidity-version` parameter suffix with `-contracts-version`

---

.gitignore
scripts/install-celo.sh
scripts/install.sh

This PR adds a small change - `artifact` folder is removed before copying contract artefacts.
Also the `artifacts/` directory is added to `.gitignore`.

Remove artifact folder before copying

---

.github/workflows/client.yml
.github/workflows/contracts.yml
.github/workflows/dashboard-testnet.yml
.github/workflows/npm.yml

We've moved custom actions used in the Keep/tBTC Continuous Integration
from separate repositories to `ci` repository (under `actions` folder).
We now need to update all the actions' invokations.
Note that temporarily we call the actions on the feature branch - this
is only for testing purposes and will be changed to `@v1` once
tested.
Refs:
https://github.com/keep-network/ci/pull/11
https://github.com/keep-network/keep-ecdsa/pull/868
https://github.com/keep-network/tbtc/pull/816
https://github.com/keep-network/tbtc-dapp/pull/400
https://github.com/keep-network/tbtc.js/pull/128
https://github.com/keep-network/coverage-pools/pull/167
TODO:

Update custom actions paths after moving actions to `ci`

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2552
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#875 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-07-23 -> 2021-07-30

---

.github/workflows/contracts.yml

We've changed the names of the secrets and need to update the workflow
configs accordingly. The change of secret name was introduced to
differentiate between WS and HTTP urls.
Refs:
* https://github.com/keep-network/keep-ecdsa/pull/872
* https://github.com/keep-network/tbtc/pull/818
* https://github.com/keep-network/local-setup/pull/104

Change value of the CHAIN_API_URL

---

infrastructure/kube/keep-test/keep-client-0-service.yaml
infrastructure/kube/keep-test/keep-client-0-statefulset.yaml
infrastructure/kube/keep-test/keep-client-1-service.yaml
infrastructure/kube/keep-test/keep-client-1-statefulset.yaml
infrastructure/kube/keep-test/keep-client-2-service.yaml
infrastructure/kube/keep-test/keep-client-2-statefulset.yaml
infrastructure/kube/keep-test/keep-client-3-service.yaml
infrastructure/kube/keep-test/keep-client-3-statefulset.yaml
infrastructure/kube/keep-test/keep-client-4-service.yaml
infrastructure/kube/keep-test/keep-client-4-statefulset.yaml
infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/keep-client-config-template.toml
infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/provision-keep-client.js

Here we expose metrics on `keep-core` testnet nodes. This is required by the monitoring system.

Expose metrics on `keep-core` testnet nodes

---

.github/workflows/dashboard-testnet.yml

Here we change the Keep Dashboard testnet job to publish static files to the GCS bucket instead of building and pushing a Docker image. This change is a part of our shift from Kubernetes to GCS as a hosting platform for static websites/dapps.

Publish Keep Dashboard to GCS bucket on testnet

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2575
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#890 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-08-13 -> 2021-08-20

---

go.mod
go.sum
pkg/chain/ethereum/balance_monitoring.go

We want to use a retry mechanism for single executions of the balance check.
The retries will be performed during the period of retry timeout, logging a warning on each error. When the timeout is hit an error will be logged and retries stopped. The next balance check will be triggered at the next tick.
The same changes were introduced in keep-ecdsa client in https://github.com/keep-network/keep-ecdsa/pull/905
Reference changes in keep-common: https://github.com/keep-network/keep-common/pull/82

Balance monitoring retries

---

.github/workflows/client.yml
.github/workflows/contracts.yml
.github/workflows/dashboard-testnet.yml

The purpose of this PR is to set a cron job that would run tests and builds on a daily basis (at midnight) so the results can be displayed on Meercode dashboard.

Adding cron for daily tests and builds on Meercode

---

docs/run-random-beacon.adoc

We update guides with addresses of the contracts that were recently
migrated on ropsten and are backed by keep-test nodes.
Job that migrated contracts:
https://github.com/keep-network/keep-core/actions/runs/1182831560

Updated guides with latest ropsten contracts

---

solidity/dashboard/src/sagas/coverage-pool.js

There is a bug that causes the Pending Withdrawal to disappear when another user
complete his own withdrawal. The pending withdrawal for current user was not
visible in such case unless he refresh the page. This PR fixes that.

Fix bug when updating data after withdrawal is completed

---

solidity/dashboard/src/components/AuthorizeContracts.jsx
solidity/dashboard/src/components/ConnectWalletBtn.jsx
solidity/dashboard/src/components/Tooltip.jsx
solidity/dashboard/src/components/coverage-pools/LearnMoreBanner.jsx
solidity/dashboard/src/components/coverage-pools/MetricsSection.jsx
solidity/dashboard/src/css/banner.less
solidity/dashboard/src/css/buttons.less
solidity/dashboard/src/css/timeline.less
solidity/dashboard/src/css/tooltip.less
solidity/dashboard/src/pages/OverviewPage.jsx

Fixes: #2591 
Styling improvements for cov pools:
</details>

Cov pools improvements

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2607
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#915 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-09-10 -> 2021-09-17

---

.github/workflows/dashboard-testnet.yml
solidity/dashboard/package-lock.json
solidity/dashboard/package.json

The `tbtc-v2` contracts intended to be used for building of Token
Dashboard will be published to the NPM registry under name with the
`-dev` suffix. We need to update the dependencies configuration in
`package.json` and `package-lock.json` dashboard files to use those
published packages.
For deployment of Dashboard on Testnet we're not using the dependencies
configured in the `package-lock.json`, instead we specify the exact version
we want to use when running the deployment workflow.
Ref: https://github.com/keep-network/keep-core/pull/2571

Update dashboard dependendencies to tbtc-v2 project

---

solidity/dashboard/src/components/coverage-pools/PendingWithdrawals.jsx

Updates the cooldown time and progress bar for pending withdrawal without the need to refresh the page.
<details>
<summary>Example</summary>
https://user-images.githubusercontent.com/40306834/134727454-27e58481-ba03-414a-b60a-eb03c75a5434.mov
</details>
Also changes the color of the time available for claiming tokens to red, when there is less than 1 day to claim the tokens.
<details>
<summary>Example</summary>
</details>

Pending withdrawal cooldown update without refresh

---

.github/workflows/dashboard-mainnet.yml

We need to call the `issues.createComment` command using `github.rest.`
context, because the Octokit context available via github no longer has
REST methods accessible directly
(https://github.com/actions/github-script#breaking-changes-in-v5).
Also, we need to use `v5` of the `github-script` action, which supports
the new changes.

Fix adding comments to dashboard PRs

---

solidity/dashboard/src/rewards-allocation/rewards.json

Backport of: #2619
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#918 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-09-17 -> 2021-09-24

---

solidity/dashboard/src/components/coverage-pools/ClaimTokensModal.jsx
solidity/dashboard/src/components/coverage-pools/InitiateDepositModal.jsx
solidity/dashboard/src/components/coverage-pools/WithdrawalInfo.jsx
solidity/dashboard/src/css/modal-with-timeline.less

Add space above close button in modals with timeline
Examples:

Fix space issue with modals

---

solidity/dashboard/package-lock.json
solidity/dashboard/package.json
solidity/dashboard/src/components/KeepOnlyPool.jsx
solidity/dashboard/src/components/LiquidityRewardCard.jsx
solidity/dashboard/src/constants/constants.js
solidity/dashboard/src/contracts-artifacts/SaddleTBTCMetaPool.json
solidity/dashboard/src/contracts.js
solidity/dashboard/src/css/liquidity-page.less
solidity/dashboard/src/pages/liquidity/LiquidityPage.jsx
solidity/dashboard/src/reducers/liquidity-rewards.js
solidity/dashboard/src/sagas/liquidity-rewards.js
solidity/dashboard/src/sagas/utils.js
solidity/dashboard/src/services/liquidity-rewards.js

Depends on: #2571 
This PR updates the Liquidity page by adding info banners to the KEEP only and TBTC/Saddle cards indicating the
incentives for these pools have been removed. Also it adds a new card for the tbtcv2/Saddle pool.
<details>
<summary>Screenshots</summary>
</details>

Liquidity page updates

---

.github/workflows/dashboard-format.yaml

Filtering applied in `dashboard-detect-changes` job was creating output
called `dashboard`, whereas the `dashboard-code-format` job was executng
conditionally if (non-existing) `path-filter` output was true or if the
triggering event was different than PR. This way the
`dashboard-code-format` job was never executed for the Pull Requests.
The naming of the output in `dashboard-detect-changes` has been changed
to `path-filter`, which makes it consistent with other workflows.

Fix broken path filtering in dashboard-format.yaml

---

solidity/dashboard/src/components/KeepOnlyPool.jsx

In the 09a87bc7ddfdeb70bcd64574048999bda31379d7 commit we didn't take
into account that KEEP-only pool component uses the same functions to
deposit/withdrawal. This commit will adjust these functions to the
changes made in the above commit.

Fix KEEP-only pool

---

solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/contracts/libraries/Groups.sol
solidity/random-beacon/contracts/test/GroupsStub.sol
solidity/random-beacon/test/Groups.test.ts
solidity/random-beacon/test/RandomBeacon.Callback.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/RandomBeacon.Relay.test.ts
solidity/random-beacon/test/functions/index.ts
solidity/random-beacon/test/utils/dkg.ts

This change reduces the complexity of the code by expecting misbehaved to be
an array of uint8 members indices.
This PR also has some follow-up changes from https://github.com/keep-network/keep-core/pull/2666.
Gas usage for this PR:
```
·-----------------------------------------------|---------------------------|-------------|-----------------------------·
|              Solc version: 0.8.6              ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 30000000 gas  │
················································|···························|·············|······························
|  Methods                                                                                                              │
·····················|··························|·············|············ …
```

Change misbehaved from bytes to uint8[]

---

solidity-v1/dashboard/package-lock.json

GitHub is no longer allowing for referencing the dependencies using
`git://` protocol. Instead we can use `git+https://`.
WIthout the change, `npm ci` executed in GitHub Actions workflows
results with ` The unauthenticated git protocol on port 9418 is no
longer supported.` error.
More info:
https://github.blog/2021-09-01-improving-git-protocol-security-github/.
Ref:
https://github.com/keep-network/keep-ecdsa/pull/927
https://github.com/keep-network/tbtc/pull/839
https://github.com/keep-network/tbtc.js/pull/144

Don't use unauthenticated git protocol

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/contracts/libraries/Groups.sol
solidity/random-beacon/contracts/test/GroupsStub.sol
solidity/random-beacon/test/utils/dkg.ts

Set of follow-up updates after merging #2676 and #2677. No more changes
planned in this PR, the rest of follow-up comments will be addressed in separate PRs.
I strongly encourage to review this PR commit-by-commit.
d717c08 addresses [follow-up comment](https://github.com/keep-network/keep-core/pull/2676#pullrequestreview-793582051) from #2676:
> Second, I think we should rename `misbehaved` to `misbehavedMembersIndices`
and clearly state it should be a set of member indices in range [1, 64]. We do have
`submitterMemberIndex` and `signingMemberIndices` so let's keep it consistent. 
`signingMemberIndices` field has been renamed to `signingMembersIndices` to
clearly indicate indices come from multiple members and are not indices of
a single member.
`misbehaved` field been renamed to …

Clarification renames of DKG result properties, documentation improvements

---

solidity/random-beacon/contracts/libraries/DKG.sol

Depends on #2679
This PR addresses a [follow-up comment](https://github.com/keep-network/keep-core/pull/2676#pullrequestreview-793582051) from #2676:
> First, in the previous version, it was enough to validate the length of `bytes`. 
Now, we need to make sure elements are not duplicate. We should add validation
to `DKG.validate` function. In most cases, it should be super-cheap as there
should be few elements in `misbehaved`. We can iterate and check `a[i-1] < a[i]`.
For bitmap version, it was enough to validate its length. Since we changed the
bitmap to an array of `uint8` member indexes to save gas on further steps of
DKG (challenging and approving the result), we now need to validate if this
array has the correct format. First, we need to ensure it has the correct length just
like for …

Validate `misbehavedMembersIndices` submitted in DKG result

---

solidity-v1/dashboard/src/__tests__/utils/coverage-pools.utils.test.js
solidity-v1/dashboard/src/components/coverage-pools/IncreaseWithdrawalModal.jsx
solidity-v1/dashboard/src/components/coverage-pools/PendingWithdrawals.jsx
solidity-v1/dashboard/src/components/coverage-pools/ReinitiateWithdrawalModal.jsx
solidity-v1/dashboard/src/components/coverage-pools/WithdrawalInfo.jsx
solidity-v1/dashboard/src/constants/constants.js
solidity-v1/dashboard/src/css/increase-withdrawal-modal.less
solidity-v1/dashboard/src/css/withdraw-modal.less
solidity-v1/dashboard/src/pages/coverage-pools/CoveragePoolPage.jsx
solidity-v1/dashboard/src/sagas/coverage-pool.js
solidity-v1/dashboard/src/utils/coverage-pools.utils.js

Changes:
- Change modal Overview section based on existing withdrawal status
<details>
<summary>Examples</summary>
<br>
For "pending" status:
For "available to withdraw" status:
</details>
- Change the way token amount is displayed when there is existing withdrawal that has "pending" or "available to withdraw" status
<details>
<summary>Example</summary>
<br>
</details>
- added new method `getPendingWithdrawalStatus` and tests for it

Improve modals based on withdrawal status

---

solidity-v1/dashboard/src/components/KeepOnlyPool.jsx
solidity-v1/dashboard/src/constants/constants.js
solidity-v1/dashboard/src/pages/liquidity/LiquidityPage.jsx

This PR updates cards on the Liquidity page.
Main changes:
- zero out KEEP-only pool APY,
- convert the TBTC/ETH pool to a `incentives removed` pool.

Update liquidity cards

---

solidity-v1/dashboard/src/components/coverage-pools/ExchangeRate.jsx
solidity-v1/dashboard/src/utils/token.utils.js

This PR updates the `ExchangeRate` component based on the users' usability studies.
Main changes:
* always keep 3 decimal places in exchange rate no matter what (so for example `1.000`; `1.100`; `1.110`; `1.111`)
* remove tilda completely,

`ExchangeRate` component updates

---

solidity/dashboard/src/components/KeepOnlyPool.jsx
solidity/dashboard/src/constants/constants.js
solidity/dashboard/src/pages/liquidity/LiquidityPage.jsx

Backport of: #2701
This PR updates cards on the Liquidity page.
Main changes:
- zero out KEEP-only pool APY,
- convert the TBTC/ETH pool to a `incentives removed` pool.

[Backport] Update liquidity pools cards

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts

This PR modifies `random-beacon` so that it [pays rewards to a DKG result submitter]( https://github.com/keep-network/keep-core/blob/96d328de2c5c54ab7ef88c06c40a198ceba8d2d4/solidity/random-beacon/contracts/RandomBeacon.sol#L454)(but only after the result was approved, not on the result submission itself) and [DKG result timeout notifier](https://github.com/keep-network/keep-core/blob/96d328de2c5c54ab7ef88c06c40a198ceba8d2d4/solidity/random-beacon/contracts/RandomBeacon.sol#L443)

DKG: rewards for result submission and timeout notification

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/contracts/libraries/Relay.sol
solidity/random-beacon/contracts/test/RandomBeaconStub.sol
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/RandomBeacon.Pool.test.ts
solidity/random-beacon/test/RandomBeacon.Relay.test.ts
solidity/random-beacon/test/utils/operators.ts

Refs https://github.com/keep-network/keep-core/issues/2715
We do not need to use an interface because we use real `SortitionPool`
in tests to see what are the real gas costs. Additionally, cleared up some
linter warnings in tests. Warnings were not related to the changes in
this PR but they were annoying in PR diff and when linting the whole code.

Eliminated ISortitionPool from RandomBeacon contract

---

.gitignore
solidity/random-beacon/.prettierignore
solidity/random-beacon/.solhintignore
solidity/random-beacon/hardhat.config.ts
solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

This PR removes the use of `hardhat-dependency-compiler` plugin that was added in https://github.com/keep-network/keep-core/pull/2684 to force compilation of sortition-pools to use it in our tests.
It is no longer needed since we use the sortition-pools in our code and it's automatically compiled.
After merging, it may be needed to remove the `contracts/hardhat-depenedency-compiler` folder from your repo, since it was generated by the plugin (it used to be ignored by git before).

Remove hardhat-dependency-compiler

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/utils/groups.ts

This PR modifies the random beacon so that anyone can call the `approveDkgResult` function and receive the DKG submission reward if the submitter does not do that on time.
The submitter has `resultSubmissionEligibilityDelay` blocks after the end of the challenge period to approve the result.
If they are late, anyone can approve the result and receive the reward.  
Additional modification: when the balance of the maintenance pool is not enough, the reward submitter receives whatever tokens there are on the maintenance pool.

Allow anyone to approve the DKG result if the submitter is late

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/contracts/libraries/Authorization.sol
solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts

Refs #2715
This parameter says what delay needs to pass between the time
authorization decrease is requested and the time that request
gets approved. It will protect against free-riders earning rewards
and not being active in the network.
Moved `minimumAuthorization` parameter to `Authorization` library
next to `authorizationDecreaseDelay`. The library will contain
all functions related to updating authorization and sortition pool.

Added governable authorization decrease delay parameter

---

solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/utils/dkg.ts

Instead of expecting 48 signatures on the result we now expect just
33 which is the group threshold. Also, we expect that at least 90%
of the group members were active during the DKG. This change allows
to go down with DKG `submitDKGResult` gas costs. For 64 signatures,
the average gas cost is 1124329. For 33 signatures the average gas
cost is 815350.
Expecting more signatures than 33 does not make the protocol any more
secure. Even if we have 64 signatures supporting the result, an
adversary must not corrupt 33+1 members.

Expect 33 signatures on the DKG result

---

solidity/random-beacon/package.json
solidity/random-beacon/test/RandomBeacon.Callback.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/RandomBeacon.Relay.test.ts
solidity/random-beacon/test/fixtures/index.ts
solidity/random-beacon/test/functions/index.ts
solidity/random-beacon/yarn.lock

Common utils functions are defined in @keep-network/hardhat-helpers
package and used across our codebase. Here we switch to use these
helpers instead duplicating the code.

Use @keep-network/hardhat-helpers

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/Relay.sol

Removed fields `tToken` and `sortitionPool` from the `Relay` library in order to lower the size of the `RandomBeacon` contract.
I decided to move the transfer of T tokens from `requestEntry`  to `RandomBeacon` as we already have all the operations on T tokens in RandomBeacon and not in libraries.
Size of the `RandomBeacon` contract: `17.352` -> `17.150` 
Gas usage:
-  `submitRelayEntry`:  `424651` -> `423625`
- `requestRelayEntry`:  `124672` -> `124640`

Remove fields from relay library

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts

This PR adds the parameter `ineligibleOperatorNotifierReward`.
The initial value assigned in the constructor of `RandomBeacon` is `0`.
The delay between change initiation and finalisation is `12h`.
There are no restrictions on what the value of this parameter can be.

Added governable parameter ineligibleOperatorNotifierReward

---

solidity-v1/contracts/cryptography/BLS.sol
solidity/random-beacon/contracts/libraries/BLS.sol
solidity/random-beacon/contracts/libraries/Groups.sol
solidity/random-beacon/test/Groups.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts

This PR:
- adds a description to the `addCandidateGroup` function that clarifies we can have at most one candidate (not activated) group.
- fixes some typos
- updates confusing test descriptions suggesting we can have more than one candidate group
- removes tests where there are two candidate groups (the library allows it, but the code using the library does not).  
Note: `addCandidateGroup` is called in `submitDkgResult`.
[Here](https://github.com/keep-network/keep-core/blob/001ca97953b23a16954e6ebae26f7e07e2c00532/solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts#L959) is the test checking we cannot `submitDkgResult` when there is another one in progress.

Clarified there can only one candidate group - description and tests

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#929 to KEEP Token Dashboard.

tBTC reward allocation 2021-10-29 -> 2021-11-05

---

solidity/dashboard/src/rewards-allocation/rewards.json

Depends on: #2693 
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#932 to KEEP Token Dashboard.

tBTC reward allocation 2021-11-05 -> 2021-11-12

---

solidity/dashboard/src/rewards-allocation/rewards.json

Depends on: #2710 
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#933 to KEEP Token Dashboard.

tBTC reward allocation 2021-11-12 -> 2021-11-19

---

solidity-v1/dashboard/src/rewards-allocation/rewards.json

Backport of: #2710
Depends on: #2682
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#932 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-11-05 -> 2021-11-12

---

solidity-v1/dashboard/src/rewards-allocation/rewards.json

Backport of: #2711
Depends on: #2712
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#933 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-11-12 -> 2021-11-19

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/test/StakingStub.sol
solidity/random-beacon/package.json
solidity/random-beacon/test/RandomBeacon.Pool.test.ts
solidity/random-beacon/test/fixtures/index.ts
solidity/random-beacon/yarn.lock

Refs https://github.com/keep-network/keep-core/issues/2715
See https://github.com/keep-network/sortition-pools/pull/135
See https://github.com/keep-network/sortition-pools/pull/136
See https://github.com/keep-network/sortition-pools/pull/137
This is a preparation for T staking contract integration but will also allow
to use `selectGroup` for challenges given that in the most recent version this
function is not protected by `onlyOwner` modifier.
Sortition pool does not longer expose `isEligibleFunction`. Everyone who
has the minimum required authorization for Random Beacon on T staking contract
will be able to join the pool. Removed `RandomBeacon.isEligible`.
I have also updated `RandomBeacon.registerOperator` and
`RandomBeacon.updateOperatorStatus`. `SortitionPool` contract does no longer …

Updated `sortition-pools` dependency to the most recent one

---

solidity/random-beacon/.solhintignore
solidity/random-beacon/contracts/DKGValidator.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/contracts/test/RandomBeaconStub.sol
solidity/random-beacon/test/DKGValidator.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/fixtures/index.ts
solidity/random-beacon/test/utils/dkg.ts
solidity/random-beacon/test/utils/groups.ts

The previous version was:
In `submitDkgResult` we:
- perform static validation of result (lengths, ranges, sizes)
- check if t+1 signatures signing the result are valid,
- check if all operators who signed the result are in the sortition pool,
- if signatures are not valid or at least one operator is not in the sortition
pool, the result is rejected.
Then, there is some time to challenge the result and the result is not accepted
until the challenge period is over. The sortition pool is locked for the entire
challenge period.
In `challengeDkgResult` - called by anyone only when something is wrong with the
result - we:
- call sortition pool and check if group members passed in `submitDkgResult` are
what the sortition pool returns,
- if the expected member list does not match the actual …

Moved DKG result signature validation to challengeDkgResult 

---

solidity/random-beacon/test/RandomBeacon.Relay.test.ts

Groups termination is in `main`. Uncommenting a couple of tests that were waiting for group termination functionality.

Uncommenting tests because group termination is implemented

---

solidity/random-beacon/test/DKGValidator.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/utils/dkg.ts

This PR adds:
- more unit tests for DKG validator.
- refactors some existing tests.
- unit tests for DKG result containing random bytes as signatures.
Note the last testcase for `validateSignature` reverts instead of returning a boolean value when the signatures are random bytes and signers addresses cannot be recovered from them. This revert will be caught in the try-catch during `challengeDkgResult`.

Added more tests for validation

---

solidity/random-beacon/contracts/DKGValidator.sol

This PR modifies validation of DKG result during challenge: instead of getting addresses of all operators from sortition-pool, we just get addresses of the operators that signed the result. 
When running tests in `RandomBeacon.GroupCreation.test.ts` the average gas consumption for `challengeDkgResult` decreased from `1201940` to `1160869`.

Modified signature validation: get only signer addresses on challenge

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/test/fixtures/index.ts

Spreadsheet with cost calculations: https://docs.google.com/spreadsheets/d/1JgRCj6srYCHANA8tmgR1XgvsE3eFrYzwSiaTRGkUI5M/edit?usp=sharing
This is enough to store relay entry, the block at which the entry
was produced and emit an event.
Default mining check interval in the client is 60 sec which is about
4 Ethereum blocks. 20 blocks eligibility delay is a bit more
operator-friendly leaving space for at least 4 gas price bumps.
This is especially important for DKG result submitter who needs
to approve the result to claim the reward.
It also means that the time before soft relay entry timeout is
hit, increased from 160 to 320 minutes.
There is no validation in `submitDkgResult` function and we need to
ensure malicious DKG results are caught and eliminated no matter
what. The best approach …

Updating initial values of RandomBeacon parameters

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/contracts/libraries/Relay.sol
solidity/random-beacon/contracts/libraries/Submission.sol
solidity/random-beacon/contracts/test/SubmissionStub.sol
solidity/random-beacon/test/Submission.test.ts

This PR removes unnecessary TODO related to performance of `approveDkgResult`.
The cost of approveDkgResult is `213813` on average and `247436` max.
Some unused constants and functions are removed as well.

Removed unused code from random beacon

---

solidity/random-beacon/contracts/RandomBeacon.sol

The value of `403200` blocks set via the `groups.setGroupLifetime(403200)`
represents ~10 weeks, not 10 months (assuming 15s block time). Updating
the comment to reflect correct value.

Fix comment describing value set via `setGroupLifetime`

---

solidity/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#937 to KEEP Token Dashboard.

tBTC reward allocation 2021-11-26 -> 2021-12-03

---

solidity-v1/dashboard/src/rewards-allocation/rewards.json

Backport of: #2759
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#937 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2021-11-26 -> 2021-12-03

---

solidity-v1/dashboard/src/rewards-allocation/rewards.json

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#940 to KEEP Token Dashboard.

tBTC reward allocation 2021-12-03 -> 2021-12-21

---

solidity-v1/dashboard/src/components/WalletOptions.jsx

There was a bug with Tally and MetaMask - if "use Tally as default wallet"
option in Tally was checked, then the app automatically connected to Tally 
wallet when we picked MetaMask, but displayed the MetaMask logo next to user 
address, which might be confused for some users.
We decided to block the possibility to connect to MM in such case and print
proper message, that tells user to uncheck the "use Tally as default wallet"
option if he wants to connect to MetaMask.

Block MM connection when Tally is injected by default

---

.github/workflows/contracts-v1.yml
.github/workflows/dashboard-v1-format.yaml
.github/workflows/dashboard-v1-testnet.yml
.github/workflows/npm-v1.yml
.github/workflows/submitter-testnet.yaml

We have CI workflows scattered across various repositories. We try to keep their implementation as similar as possible. In this PR and the ones listed below we introduce a couple of changes which unify used solutions and fix small mistakes, such as:
* making tagging of published packages consistent
* passing `NPM_TOKEN` secret as variable instead of passing it by writing to file
* handling caching of npm/yarn dependencies via `setup-node` action
* adding `workflow_dispatch` job trigger where it's missing
* using Node.js in version 14.x instead of 12.x where possible
Related PRs in other repositories:
* https://github.com/keep-network/keep-ecdsa/pull/941
* https://github.com/keep-network/tbtc/pull/842
* https://github.com/keep-network/tbtc.js/pull/145
* …

Unify CI workflows

---

solidity-v1/dashboard/package-lock.json
solidity-v1/dashboard/package.json
solidity-v1/dashboard/src/constants/constants.js

The link for TBTC v2 + mBTC pool was wrong and pointed out to tBTC v1. This
commit fixes that.
Old link: [https://app.mstable.org/#/mbtc/pools/0xb61a6f928b3f069a68469ddb670f20eeeb4921e0](https://app.mstable.org/#/mbtc/pools/0xb61a6f928b3f069a68469ddb670f20eeeb4921e0)
New link: [https://mstable.app/#/mbtc/pools/0xc3280306b6218031e61752d060b091278d45c329](https://mstable.app/#/mbtc/pools/0xc3280306b6218031e61752d060b091278d45c329)

Fix link for TBTC v2 + mBTC pool

---

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml

Bump docker image version from 1.16.0 to 1.16.1
ref: https://github.com/keep-network/keep-core/pull/2782

Bump docker image version to v1.16.1

---

solidity-v1/dashboard/src/constants/constants.js

Backport of: #2782 
The link for TBTC v2 + mBTC pool was wrong and pointed out to tBTC v1. This
commit fixes that.

[Backport] Fix link for TBTC v2 + mBTC pool

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/Relay.sol
solidity/random-beacon/contracts/test/RandomBeaconStub.sol
solidity/random-beacon/contracts/test/RelayStub.sol
solidity/random-beacon/test/RandomBeacon.Callback.test.ts
solidity/random-beacon/test/RandomBeacon.Relay.test.ts
solidity/random-beacon/test/system/e2e.test.ts

Depends on https://github.com/keep-network/keep-core/pull/2768
In case the soft timeout has not passed yet, there is no point to calculate
the slashing factor in `submitRelayEntry`. Also, because there is no slashing,
passing group members is not necessary and computing group members hash
to compare it with the value stored in groups registry is not necessary.
This is a competing approach to the one in #2772 aiming at making minimal
changes to the codebase. It's up to @nkuba and @dimpar to decide with
which approach we want to continue.
Gas usage is pretty much the same but the contract has a little bit less bytecode
in this version:
In #2772:
```
|  RandomBeacon            ·     (was: 22.630) now 22.549  │
···························|··············
|  RandomBeaconStub        ·     (was: …
```

Gas-optimized version of submitRelayEntry when soft timeout has not passed

---

solidity/ecdsa/contracts/Wallet.sol
solidity/ecdsa/contracts/WalletFactory.sol
solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

Refs #2758
We avoid redeployment of the wallet contracts by using the clone factory
which saves gas during the deployment process.
Proxy delegates calls to a Wallet and therefore does not affect Wallet state.
This means that we only need to deploy the wallet contract once.
The same mechanism was used in https://github.com/keep-network/coverage-pools for Auctions.

Clone factory for ECDSA wallets

---

solidity/random-beacon/contracts/DKGValidator.sol

This PR modifies the way group members are validated during DKG result challenge: instead of calculating hash, group members are iterated and compared one by one.
After this change `challengeDkgResult` seems to be cheaper in the optimistic case, but slightly more expensive in the pessimistic.
It is also faster in case the lengths of received and actual members are different. 
Iterating:
- optimistic (first operator mismatch): 1142513
- pessimistic (last operator mismatch): 1167251
Hashing (note the cost the same in both cases):
- optimistic: 1160070
- pessimistic: 1160070
Note: I could only test it via `challengeDkgResult` function and not dedicated `DKGValidator` tests (for some reason gas reporter doesn't show the output from `DKGValidator` - maybe because those are `view` functions?)

Modified validation of group members: iterate instead of hashing

---

solidity/random-beacon/contracts/DKGValidator.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/contracts/libraries/Groups.sol
solidity/random-beacon/contracts/test/GroupsStub.sol
solidity/random-beacon/test/DKGValidator.test.ts
solidity/random-beacon/test/Groups.Expiration.test.ts
solidity/random-beacon/test/Groups.Termination.test.ts
solidity/random-beacon/test/Groups.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/Utils.test.ts
solidity/random-beacon/test/utils/dkg.test.ts
solidity/random-beacon/test/utils/dkg.ts

Refs https://github.com/keep-network/keep-core/issues/2756
A hash of group members that actively took part in DKG can be calculated off-chain and passed to the contract's `submitDKGResult()`. This way we skip filtration of the misbehaved members. However, this change requires additional validation during the DKG challenge phase to verify that hash. The reasoning is that the dkg challenge will be done less frequently compared to dkg result submission which overall should save gas. 
```
|  approveDkgResult                ·     185804  ·     247404  ·     205493  │
|  challengeDkgResult              ·     333403  ·    1175701  ·     978235  │
|  submitDkgResult                 ·     306979  ·     479157  ·     395381  │
|  submitRelayEntry (no slashing)  ·     192118  ·     241745  · …
```

Passing members hash

---

solidity-v1/dashboard/package-lock.json
solidity-v1/dashboard/package.json
solidity-v1/dashboard/src/components/Chip.jsx
solidity-v1/dashboard/src/components/DataTable.jsx
solidity-v1/dashboard/src/components/DelegatedTokensTable.jsx
solidity-v1/dashboard/src/components/ProgressBar.jsx
solidity-v1/dashboard/src/components/ResourceTooltip.jsx
solidity-v1/dashboard/src/components/Tooltip.jsx
solidity-v1/dashboard/src/components/Undelegations.jsx
solidity-v1/dashboard/src/components/UpgradeToTButton.jsx
solidity-v1/dashboard/src/components/coverage-pools/MetricsSection.jsx
solidity-v1/dashboard/src/components/coverage-pools/PendingWithdrawals.jsx
solidity-v1/dashboard/src/components/modal/staking/ConfirmRecovering.jsx
solidity-v1/dashboard/src/components/modal/staking/ViewTransactionSuccessModal.jsx
solidity-v1/dashboard/src/components/modal/staking/claim/TokensClaimed.jsx
solidity-v1/dashboard/src/components/modal/threshold/GrantTokensWithdrawn.jsx
solidity-v1/dashboard/src/components/threshold/AllocationProgressBar.jsx
solidity-v1/dashboard/src/components/threshold/UpgradeTokensTile.jsx
solidity-v1/dashboard/src/constants/tooltips.js
solidity-v1/dashboard/src/css/add-to-calendar.less
solidity-v1/dashboard/src/css/tooltip.less
solidity-v1/dashboard/src/hooks/useCurrentDate.js
solidity-v1/dashboard/src/hooks/useUpdateInitializedDelegations.js
solidity-v1/dashboard/src/hooks/useUpdatePendingUndelegations.js
solidity-v1/dashboard/src/pages/grants/TokenGrantsPage.jsx
solidity-v1/dashboard/src/pages/threshold/ThresholdUpgradePage.jsx
solidity-v1/dashboard/src/reducers/staking.js
solidity-v1/dashboard/src/reducers/token-grant.js
solidity-v1/dashboard/src/sagas/subscriptions.js

Some overall bug fixes 🐛 ❌  for the T Migration and keep staking
Changes:
- fix percentage calculations for the progress bar in `staked` tab when there is pending undelegation
- creates `useCurrentDate` hook, that returns current date in unix timestamp updated every seconds
- semi-fix of the bug that caued the need to refresh the page after executing a transaction that updates the status of Delegation or Undelegation. Now, you don't have to refresh the page, but you still have to go to another page and then comeback to the previous one to fetch the data again
- fix updating staked value after recovering tokens, which was not updated at all because of a typo in action name
- display ">99%" and "<1%" in AllocationProgressBar when there is really small amount of (for example) unstaked grant …

Migration and staking bugfixes 🐛 ❌ 

---

solidity-v1/dashboard/.gitignore
solidity-v1/dashboard/.prettierignore

An `external/npm/@keep-network/keep-core/artifacts` directory is created
every time the `threshold-network/solidity-contracts` dependency is
installed. This is due to a workaround in
`threshold-network/solidity-contracts` which allows us to use contracts
which come from different repos and share the same name. Creation of
the `external` folder is a by-product of that. We don't need to track
changes in that folder or run prettier on its files.

Ignore `external` directory in git and prettier

---

solidity/random-beacon/contracts/DKGValidator.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/DKG.sol
solidity/random-beacon/test/DKGValidator.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts

We do not need to read members hash from the groups lib, because the dkg result under
challenge has to be the same one that was submitted. Otherwise, the challenge call will be reverted. We can read the members hash from the dkg result instead, which simplifies code.

Fetching members hash from dkg result

---

solidity-v1/dashboard/src/pages/rewards/TBTCRewardsPage.jsx
solidity-v1/dashboard/src/rewards-allocation/rewards.json
solidity-v1/dashboard/src/services/rewards.js
solidity-v1/dashboard/src/utils/rewardsHelper.js

Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#950 to KEEP Token Dashboard.
This PR also adjusts the `tBTC Rewards` page to [the proposal](https://forum.keep.network/t/proposal-to-extend-stakedrop-rewards-for-an-additional-4-months/351) that extends stakedrop rewards for an additional 4 months. We will have two more allocations so to simplify calculating the period of the reward we hardcoded the `merkleRoot` in the `ExtendedECDSARewards.intervalsDates` array. After generating the new merkle tree we must add the `merkleRoot` hash to a given interval.

tBTC reward allocation 2021-12-21 -> 2022-01-22

---

solidity-v1/dashboard/src/pages/rewards/TBTCRewardsPage.jsx
solidity-v1/dashboard/src/rewards-allocation/rewards.json
solidity-v1/dashboard/src/services/rewards.js
solidity-v1/dashboard/src/utils/rewardsHelper.js

Backport of: #2804
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#950 to KEEP Token Dashboard.
This PR also adjusts the `tBTC Rewards` page to [the proposal](https://forum.keep.network/t/proposal-to-extend-stakedrop-rewards-for-an-additional-4-months/351) that extends stakedrop rewards for an additional 4 months. We will have two more allocations so to simplify calculating the period of the reward we hardcoded the `merkleRoot` in the `ExtendedECDSARewards.intervalsDates` array. After generating the new merkle tree we must add the `merkleRoot` hash to a given interval.

[Backport] tBTC reward allocation 2021-12-21 -> 2022-01-22

---

solidity-v1/dashboard/src/components/modal/threshold/ThresholdLoadingModal.jsx
solidity-v1/dashboard/src/sagas/keep-to-t-staking.js
solidity-v1/dashboard/src/sagas/web3.js

While a transaction is pending we should display a modal indicating that
fact with a link to the transaction details.

Display `transaction is pending` modal

---

solidity-v1/dashboard/package-lock.json
solidity-v1/dashboard/package.json

We recently published first `-dev` suffixed npm package for
`@keep-network/tbtc` (`1.1.2-dev.0`). Now we're updating dependencies in
KEEP dashboard to reflect that change.
We're also updating incorrectly configured dependency to `keep-core`
package - we want to only include `-dev` packages in the smver range.

Update `keep-core` and `tbtc` dependencies

---

.github/workflows/npm-v1.yml

This change adds an additional environment tag for packages published
during `Publish package` step. This adds a convenient reference to the
latest version of the `@keep-core/solidity-v1` package for development
environment. We also add a new condition for triggering `NPM v1`
workflow - from now on the workflow will be executed also after changes
to the workflow get merged to the `main` branch.

Add `development` tag to the published npm package

---

solidity/ecdsa/yarn.lock

The `package.lock` and `yarn.lock` in `solidity/ecdsa/` got mismatched
after merge of https://github.com/keep-network/keep-core/pull/2792,
causing failure of `yarn install --frozen-lockfile`. In this PR we
update `yarn.lock` to match `package.json`.

Fix mismatched yarn.lock

---

docs/scripts/package-lock.json
docs/scripts/package.json
go.mod
go.sum
infrastructure/eth-networks/scripts/package-lock.json
infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json
infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/package-lock.json
solidity-v1/dashboard/package-lock.json
solidity-v1/package-lock.json
solidity/ecdsa/yarn.lock
solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

All old and recent dependabot updates gathered into one PR to avoid having to rebase constantly. Also, the change from https://github.com/keep-network/keep-core/commit/fd6dd1908741acc8be8bf7e514a8ea30bae4f4ab required special attention. I reverted it and updated `go-ethereum` to `v1.10.15` in https://github.com/keep-network/keep-core/pull/2817/commits/132ecaee8986d09c55a6244b6210e53297efa966. The change in `go.sum` removing `golang.org/x/mod` from there introduced in https://github.com/keep-network/keep-core/commit/fd6dd1908741acc8be8bf7e514a8ea30bae4f4ab  made our build fail with:
> [gobuild 23/24] RUN go generate ./pkg/gen:
#30 0.506 /go/pkg/mod/golang.org/x/tools@v0.1.1/internal/imports/mod.go:21:2: missing go.sum entry for module providing package golang.org/x/mod/module (imported by …

Dependency bumps: all in one batch

---

solidity-v1/dashboard/src/lib/keep/index.js

Fix creating a contract instance from the hardhat artifact. In some
cases, the artifact doesn't include `receipt` object and
`transactionHash` so we need to set the `deployedAtBlock` to `1`. This
is not an ideal solution because we should fetch past events from the
deployment block- some node providers (eg. Alchemy) block requests if
the block range is greater than 2k.

Fix creating a contract instance

---

.github/workflows/dashboard-v1-mainnet.yml
solidity-v1/dashboard/Dockerfile

This PR changes docker image build process for Token Dashboard that came up during the v1.17.0 release.
`@threshold-network/solidity-contracts` dependency has `postinstall` script that works perfectly fine locally but fails inside a docker image building. We don't need to execute this script in docker as it's used for the deployment of contracts, but here we are expecting final artifacts to be provided. This is a solution proposed by @r-czajkowski 🙇🏻‍♂️ 
Another change we add here is docker image build executed as part of GitHub actions, to confirm that the build works and won't surprise us on mainnet release.

Dashboard docker image build updates

---

solidity-v1/dashboard/src/actions/index.js
solidity-v1/dashboard/src/actions/keep-to-t-staking.js
solidity-v1/dashboard/src/reducers/threshold-authorization.js
solidity-v1/dashboard/src/sagas/subscriptions.js
solidity-v1/dashboard/src/services/threshold-authorization.service.js

There was a bug when the stake that was undelegated and recovered displayed in
the tables in Applications->Threshold page. This PR fixes that.
Main changes:
- fixed a bug that caused undelegated and recovered stakes to be displayed in 
Application -> Threshold page
- updates the threshold auth data after doing an undelegation so this way user 
don't have to refresh the page to see the actual changes

Fix displaying undelegated stakes in app->threshold

---

solidity-v1/dashboard/src/actions/index.js
solidity-v1/dashboard/src/actions/keep-to-t-staking.js
solidity-v1/dashboard/src/reducers/threshold-authorization.js
solidity-v1/dashboard/src/sagas/subscriptions.js
solidity-v1/dashboard/src/services/threshold-authorization.service.js

Backport of: https://github.com/keep-network/keep-core/pull/2846
There was a bug when the stake that was undelegated and recovered displayed in
the tables in Applications->Threshold page. This PR fixes that.
Main changes:
- fixed a bug that caused undelegated and recovered stakes to be displayed in
Application -> Threshold page
- updates the threshold auth data after doing an undelegation so this way user
don't have to refresh the page to see the actual changes

[Backport] Fix displaying undelegated stakes in app->threshold

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/contracts/libraries/EcdsaAuthorization.sol
solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/package.json
solidity/ecdsa/test/WalletRegistry.Parameters.test.ts
solidity/ecdsa/test/WalletRegistry.Pool.test.ts
solidity/ecdsa/test/WalletRegistry.RandomBeacon.test.ts
solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts
solidity/ecdsa/test/fixtures/index.ts
solidity/ecdsa/test/utils/operators.ts
solidity/ecdsa/yarn.lock

Refs: #2834 
Introduced two authorization-related parameters in the WalletRegistry contract:
- minimum authorization
- authorization decrease delay
`Authorization` library will be further developed to enable integration with Threshold `TokenStaking` contract. Changes introducing governable parameters are included separately in this PR to keep the diff size sane.
Side note: after looking at `WalletRegistryGovernance`, I've decided to open https://github.com/keep-network/keep-core/issues/2847 to improve how governance contract works for Random Beacon and ECDSA.

Authorization parameters for WalletRegistry contract

---

solidity-v1/dashboard/src/actions/index.js
solidity-v1/dashboard/src/actions/keep-to-t-staking.js
solidity-v1/dashboard/src/reducers/threshold-authorization.js
solidity-v1/dashboard/src/sagas/subscriptions.js

Update threshold auth data after creating a delegation, so it updates 
immediately without refreshing

Update threshold auth data after staking

---

solidity/ecdsa/.eslintrc
solidity/ecdsa/README.adoc
solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/contracts/api/IWalletOwner.sol
solidity/ecdsa/contracts/test/WalletRegistryStub.sol
solidity/ecdsa/deploy/03_deploy_wallet_registry.ts
solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/tasks/index.ts
solidity/ecdsa/tasks/initialize-wallet-owner.ts
solidity/ecdsa/test/WalletRegistry.Parameters.test.ts
solidity/ecdsa/test/WalletRegistry.RandomBeacon.test.ts
solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts
solidity/ecdsa/test/WalletRegistry.WalletOwner.test.ts
solidity/ecdsa/test/WalletRegistry.Wallets.test.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts
solidity/ecdsa/test/fixtures/index.ts
solidity/ecdsa/test/utils/dkg.ts
solidity/ecdsa/test/utils/wallets.ts
solidity/ecdsa/tsconfig.json

Wallet Owner has to be notified when a requested wallet gets created. We handle this with a callback function that submits to the Wallet Owner a keccak256 hash of the wallet's public key. 
It is required that the Wallet Owner contract implements IWalletOwner interface:
```solidity
interface IWalletOwner {
/// @notice Callback function executed once a new wallet is created.
/// @dev Should be callable only by the Wallet Registry.
/// @param publicKeyHash Keccak256 hash of the wallet's public key. It is
///        considered an unique wallet identifier.
function __notifyWalletCreated(bytes32 publicKeyHash) external;
}
```
Refs https://github.com/keep-network/keep-core/issues/2833

ECDSA Wallets: Callback to the Wallet Owner after wallet creation

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml
solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/api/IWalletOwner.sol
solidity/ecdsa/contracts/api/IWalletRegistry.sol
solidity/ecdsa/contracts/libraries/Wallets.sol
solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts
solidity/ecdsa/test/WalletRegistry.WalletOwner.test.ts
solidity/ecdsa/test/WalletRegistry.Wallets.test.ts
solidity/ecdsa/test/data/ecdsa.ts
solidity/ecdsa/test/fixtures/index.ts
solidity/ecdsa/test/utils/dkg.ts
solidity/ecdsa/test/utils/wallets.ts

We want to store a public key of the wallet so it can be used by the wallet owner (Bridge) for transactions handling. The Bridge will use both compressed and uncompressed public keys. We store the longer one (uncompressed) that can be easily converted to the compressed format.
We also renamed `publicKeyHash` to walletID as this reflects better what this property is. Using the name `publicKeyHash` was confusing in the external owner contract as there may be another key hash in use, but this is an implementation detail of what hashing function we use for identification.
Please notice that gas costs went up:
BEFORE:
|  WalletRegistry.approveDkgResult | 210844 | 225949 | 214789 │
AFTER:
|  WalletRegistry.approveDkgResult | 257700 | 257940 | 257830 |
Depends on …

ECDSA Wallets: Store uncompressed public key

---

solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/deploy/05_deploy_wallet_registry_governance.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts
solidity/ecdsa/test/fixtures/index.ts

Refs https://github.com/keep-network/keep-core/issues/2847
2-week critical governance parameter does not make sense for ECDSA `WalletRegistry`
given that wallets will have to remain active for months. We could swallow it for
the `RandomBeacon` but for `WalletRegistry` 2 weeks does not make any sense and 2
months is not enough.
One option would be to eliminate governance contracts completely and just deploy
`TimeLock` contract. On the other hand, `TimeLock` updates are more complex to set
up than simple calls to the existing governance contract, and the structure of
update* functions in `WalletRegistry` is more complicated.
Here we introduce just one governable delay for parameter updates and eliminate
the separation between critical/standard parameters given it creates a false
assumption …

ECDSA: Use the same governance delay for all parameters

---

solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/test/RandomBeaconGovernance.test.ts

Refs https://github.com/keep-network/keep-core/issues/2847
See https://github.com/keep-network/keep-core/pull/2862
Depends on #2865; Keeping as a draft until #2865 is merged.
There is one governance delay for all governable parameters and now, this delay
can be updated by governance contract owner. The same rules apply as for other
parameters: start the update process, wait for the delay period, finalize the
update.
It is possible that two updates can happen at the same time. If one of these
updates is governance delay, it is possible that the finalization of another update
may take longer than initially expected. This is acceptable - governance needs
to take it into account. What is more, the contract guarantees the change does
not happen earlier than the delay but it does not guarantee …

Allow to update delay in RandomBeaconGovernance

---

solidity/ecdsa/contracts/api/IWalletRegistry.sol

This change expose `getWalletCreationState` function in `IWalletRegistry` interface. This function can help the wallet's owner to determine the moment when a new wallet can be created.

Expose `getWalletCreationState` function

---

solidity-v1/contracts/PhasedEscrow.sol
solidity-v1/contracts/stubs/TestPhasedEscrowBeneficiaries.sol
solidity-v1/test/TestPhasedEscrow.js

`PlainTransferEscrowBeneficiary` is a beneficiary contract that can
receive a withdrawal order from `PhasedEscrow` and `BatchedPhasedEscrow`
contracts. It immediately sends the received tokens to the recipient
set by the beneficiary deployer.
The recipient does not have to implement any custom functions, it can
be a smart contract or EOA - beneficiary is executing a plain ERC20
transfer.

PlainTransferEscrowBeneficiary for PhasedEscrow and BatchedPhasedEscrow

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/test/WalletRegistry.Parameters.test.ts
solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts
solidity/ecdsa/test/fixtures/index.ts
solidity/ecdsa/test/utils/dkg.ts
solidity/random-beacon/contracts/RandomBeacon.sol

Closes #2857
Group members who were misbehaving during DKG (inactive or disqualified) are marked as ineligible for rewards for a certain, governable, period of time.
Added governable parameter to `WalletRegistry` indicating that time. The new governable parameter will also be used for reward ineligibility period for operators who missed their turn during DKG result submission or that failed a heartbeat (this is covered in https://github.com/keep-network/keep-core/issues/2839).

Mark operators misbehaving during ECDSA DKG as ineligible for rewards

---

.github/workflows/dashboard-v1-testnet.yml
solidity-v1/dashboard/README.md

We're adding a step that configures git to use `https://` protocol
instead of `git://` when downloading files.
We need this step because the `@keep-network/tbtc` which we update in next
step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
downloads one of its sub-dependencies via unathenticated `git://`
protocol. That protocol is no longer supported. See
https://github.blog/2021-09-01-improving-git-protocol-security-github/.

Configure git to don't use unauthenticated protocol

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/api/IWalletRegistry.sol

Refs: #2864 
This change exposes `closeWallet` function that allows the wallet owner to send a signal about wallet closure to the ECDSA registry. The scope of this change is just about exposing the function to unblock the work on the `Bridge` side. Actual implementation should be provided by a follow-up PR.

Closing wallets on ECDSA registry side

---

solidity/ecdsa/contracts/api/IWalletOwner.sol

Refs: #2839
Refs: https://github.com/keep-network/tbtc-v2/issues/139
Here we expose `__ecdsaWalletHeartbeatFailedCallback` function in the `IWalletOwner` interface that will be used to notify the wallet owner about a heartbeat failure detected on a specific wallet.

Callback for wallet's hearbeat failure

---

solidity/ecdsa/test/WalletRegistry.Authorization.test.ts

This PR is a follow-up to the comments from #2850.
Added two unit tests:
- Make sure `WalletRegistry.registerOperator` does not add operator into the sortition pool.
- Make sure `WalletRegistry.joinSortitionPool` reverts for stake below the minimum. Note that the only situation possible when such a scenario occurs is when there was a slashing in the meantime and the authorization that was previously above the minimum dropped.

WalletRegistry authentication unit test improvements

---

solidity-v1/dashboard/src/rewards-allocation/rewards.json
solidity-v1/dashboard/src/utils/rewardsHelper.js

Backport of: #2843
Adding tBTC rewards merkle tree computed in https://github.com/keep-network/keep-ecdsa/pull/953 to KEEP Token Dashboard.

[Backport] tBTC reward allocation 2022-01-22 -> 2022-02-22

---

solidity-v1/dashboard/src/components/InactiveButExternalLiquidityRewardCard.jsx
solidity-v1/dashboard/src/pages/liquidity/LiquidityPage.jsx

Changes:
- add banner with the information that rewards were moved to T, user can withdraw current rewards and he can deposit the tokens in Saddle dApp to earn incentives in multiple tokens
- add more info link that redirects to forum: https://forum.keep.network/t/repurpose-saddle-tbtc-pool-liquidity-incentives-and-move-incentives-to-t/404
- add Go to Pool button that redirects straight to the pool in Saddle dApp: https://saddle.exchange/#/pools/tbtcv2/deposit
- allow user to withdraw the incentives if he has any
- change column height in Masonry Layout for Liquidity Cards page to make TBTCv2 + mBTC pool land on top of the third column.
<p align="center">
</p>

External tBTCv2 + SaddleV2 pool 

---

solidity-v1/dashboard/src/components/InactiveButExternalLiquidityRewardCard.jsx
solidity-v1/dashboard/src/pages/liquidity/LiquidityPage.jsx

Backport of: #2890 
Based on [https://forum.keep.network/t/repurpose-saddle-tbtc-pool-liquidity-incentives-and-move-incentives-to-t/404](https://forum.keep.network/t/repurpose-saddle-tbtc-pool-liquidity-incentives-and-move-incentives-to-t/404) we are changing the status tBTCv2 + SaddleV2 pool to inactive but external meaning, that the incentives will be removed in the KEEP dashboard site, but user can still earn rewards by depositing the tokens in the Saddle dApp.
Changes:
- add banner with the information that rewards were moved to T, user can withdraw current rewards and he can deposit the tokens in Saddle dApp to earn incentives in multiple tokens
- add more info link that redirects to forum: https://forum.keep.network/t/repurpose-saddle-tbtc-pool-liquidity-incentives-and-move-incentive …

[Backport] External tBTCv2 + SaddleV2 pool

---

solidity/random-beacon/README.adoc
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/BeaconInactivity.sol
solidity/random-beacon/contracts/libraries/Inactivity.sol
solidity/random-beacon/test/RandomBeacon.Relay.test.ts
solidity/random-beacon/test/fixtures/index.ts
solidity/random-beacon/test/utils/inacvitity.ts

The goal of the inactivity claim is to have the group punish operators
who are constantly inactive and not contributing to the work by
excluding them from sortition pool rewards.
The goal of the wallet heartbeat failure - present only in ECDSA - is to
transfer funds to another wallet from the one who failed the heartbeat.
Inactivity claim in ECDSA will be only about excluding operators from
rewards and will not require moving funds.
For this reason, we need to keep these two actions separate and properly
named:
- inactivity claim: exclude operators from rewards
- heartbeat failure: move funds to another safe wallet (just ECDSA)
I went ahead and removed the logic for rewarding operators who
submitted the claim from a special pool of rewards. This action should
refund ETH to the submitter …

Replaced Random Beacon failed heartbeat with operator inactivity claim

---

.github/workflows/dashboard-v1-testnet.yml
solidity-v1/dashboard/README.md
solidity-v1/dashboard/package-lock.json

Restore fix for `The unauthenticated git protocol on port 9418 is no longer
supported.` that was overwritten.
The fix is described in #2683

Restore unauthenticated git protocol fix

---

solidity-v1/dashboard/package-lock.json
solidity-v1/dashboard/package.json
solidity-v1/dashboard/src/components/modal/wallets/LedgerModal.jsx
solidity-v1/dashboard/src/connectors/ledger.js

The package that we use for Ledger - `@ledgerhq/hw-transport-u2f` have been deprecated.
We migrate from `@ledgerhq/hw-transport-u2f` to the newer and safer `@ledgerhq/hw-transport-webusb`
Mozilla Firefox does not support WebUSB at this moment so we remove the possibility to log in directly from Ledger Live on Firefox (and other browsers expect Chrome).
More info: [https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md](https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md)
Main changes:
- install `@ledgerhq/hw-transport-webusb` and uninstall deprecated `@ledgerhq/hw-transport-u2f` package
- install `react-device-detect` library which help with detecting what device and what browser does user use
- display proper message in Ledger Login window, that …

Ledger packages migration

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/BeaconInactivity.sol

Instead of passing storage pointer to the entire `Group`, we can pass just
group public key. This is simpler and reduces the gas consumption for
`notifyOperatorInactivity` function. Gas before (min, max, avg):
`597459, 851499, 732914`. Gas after: `596684, 850727, 732141`.
I have also improved some code documentation.
Documentation of the data that needs to be signed by each group member
was not entirely correct. It is fixed now. I have also clarified comment
on why we are using a group public key instead of an integer ID.

Beacon inactivity claim improvements

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/libraries/EcdsaDkg.sol
solidity/ecdsa/contracts/libraries/Wallets.sol
solidity/ecdsa/deploy/04_deploy_wallet_registry.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts

The contract size increased from 16.859 to 19.181 which should still be enough for adding the remaining functionality (inactivity, heartbeats, closing wallet) but the gas cost of DKG dropped by ~20k units of gas.
Before vs after comparison:
```
submitDkgResult     ·     269513  ·     305282  ·     297796   │
submitDkgResult     ·     253126  ·     282468  ·     276413   │
approveDkgResult    ·     281679  ·     345023  ·     290260   │
approveDkgResult    ·     260958  ·     322070  ·     269305   |
challengeDkgResult  ·     352034  ·    1823098  ·    1356153   │
challengeDkgResult  ·     328853  ·    1802020  ·    1334557   │
```
Individual comparisons for inlined `Wallets` and `EcdsaDkg` libraries are available in commit descriptions.

ECDSA: unlink the libraries

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/libraries/EcdsaInactivity.sol
solidity/ecdsa/contracts/libraries/Wallets.sol
solidity/ecdsa/contracts/test/WalletRegistryStub.sol
solidity/ecdsa/deploy/04_deploy_wallet_registry.ts
solidity/ecdsa/test/WalletRegistry.Inactivity.ts
solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts
solidity/ecdsa/test/utils/inactivity.ts
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/test/RandomBeacon.Relay.test.ts

Refs https://github.com/keep-network/keep-core/issues/2839
The function lets the wallet signing group operators notify about operators who are
inactive in the group. Using this function, a majority of the wallet signing
group can decide about punishing specific group members who constantly fail
to do their job. If the provided claim is proved to be valid and signed by
a sufficient number of group members, operators of members deemed as inactive are
banned from sortition pool rewards for the duration specified by
`sortitionPoolRewardsBanDuration` parameter. The sender of the claim must be one
of the claim signers. This function can be called only for registered wallets.
TODO (in a separate PR):

`notifyOperatorInactivity` for Wallet Registry

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/test/RandomBeaconStub.sol
solidity/random-beacon/test/RandomBeacon.Callback.test.ts
solidity/random-beacon/test/RandomBeacon.Relay.test.ts

The functions are not necessary for the RandomBeaconStub as we can use
existing functions to obtain required data.

Remove functions from RandomBeaconStub

---

solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/test/fixtures/index.ts
solidity/ecdsa/test/utils/operators.ts

We need to make our tests more robust by using unique addresses for each role that is related to staking and operator registration. 
This requires configuring a hardhat network with more than 500 accounts so each address is unique and doesn't overlap.
Thanks to that the tests are more reliable and reduce the possibility to give false-positive results.
In the Random Beacon we introduce this change in https://github.com/keep-network/keep-core/pull/2903.

ECDSA Wallets: Use unique accounts for staking and operator registration roles in tests

---

.github/workflows/npm-ecdsa.yml
.github/workflows/npm-random-beacon.yml
solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

Some time ago we temporarily changed `@keep-network/random-beacon`
dependency in `solidity/ecdsa/package.json` from
`>2.0.0-dev <2.0.0-ropsten` to `../random-beacon`. This was only a
tempoorary change, to allow for passing of checks in PR2856. Now we want
to set the dependency to again point to the latest package meant for the
development environment. We discovered, that using
`>2.0.0-dev <2.0.0-ropsten` range to do that is not ideal (if one of the
packages in the range is tagged 'latest', but there are newer packages
which seem to fit the range, those newer packages won't be recognize as
fitting the range). As an alternative, we propose to refer to the latest
package by using following dependency configuration:
```
"@keep-network/random-beacon": "development"
```
This will always point …

Use `development` tag to configure dependency between packages

---

solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/test/utils/operators.ts

To be more clear about accounts configuration for tests we defined
testConfig object that holds the config and those config are reused in
operators registration. Additionally we validate on hardhat test start
if the parameters are configured properly.
This is a follow-up for https://github.com/keep-network/keep-core/pull/2909#discussion_r839449135

Clarify test accounts configuration

---

solidity/random-beacon/.eslintrc
solidity/random-beacon/.prettierignore
solidity/random-beacon/test/BeaconDkgValidator.test.ts
solidity/random-beacon/test/Groups.Expiration.test.ts
solidity/random-beacon/test/Groups.Termination.test.ts
solidity/random-beacon/test/RandomBeacon.Authorization.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
solidity/random-beacon/test/RandomBeacon.Relay.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts
solidity/random-beacon/test/system/e2e.test.ts
solidity/random-beacon/test/utils/dkg.test.ts
solidity/random-beacon/test/utils/dkg.ts
solidity/random-beacon/tsconfig.json

This PR updates configuration for typescript to require typings and discourage `any` usage.
See: 
- https://www.typescriptlang.org/tsconfig#noImplicitAny
- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md#no-explicit-any

Random beacon no any

---

solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/deploy/02_deploy_reimbursement_pool.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts

This PR is a follow-up of review comments to #2795:
- [Reordered inactive operators gas offsets in ECDSA governance contract](https://github.com/keep-network/keep-core/commit/2817ffed2d23919ef8bb2ff312cc8a037b28adac): Reordered fields, events, and functions with no single change in the logic so that gas offset info is next to each other.
- [Send 100 ETH to reimbursement pool only for hardhat tests](https://github.com/keep-network/keep-core/commit/bb9005443dc2b6aef9ce869977a843d99785caeb): Deployment scripts are used for testing and for real deployment. We do not want to send any ETH from deployer account when deploying to mainnet. This is needed only for tests.
- [Improved test names for wallet registry governance](https://github.com/keep-network/keep-core/commit/e6e9ae03c37c10d6eac28a5e5a …

Follow-up: Notify operator inactivity refund

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/hardhat.config.ts
solidity/random-beacon/package.json
solidity/random-beacon/test/BeaconDkgValidator.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/RandomBeacon.Rewards.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts
solidity/random-beacon/test/fixtures/index.ts
solidity/random-beacon/yarn.lock

See https://github.com/keep-network/sortition-pools/pull/156
Previously, `SortitionPool.withdrawRewards` could be called directly and
the beneficiary address was fetched from the staking contract based on
the operator address.
This is no longer going to work - T `TokenStaking` contract does not store
operators but staking providers - operator is now a per-application role.
We now expect `SortitionPool.withdrawReward` call to be proxied through the
application `RandomBeacon` contract that will fetch the beneficiary address
from T `TokenStaking`.
This PR is also adding unit tests for `RandomBeacon.withdrawIneligibleRewards`.
This function was not covered with unit tests previously.

RandomBeacon: withdrawRewards

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/api/IWalletRegistry.sol
solidity/ecdsa/test/WalletRegistry.Wallets.test.ts

This change adds `isWalletMember` function to the ECDSA wallet registry. That function allows checking whether the given operator is a member of the given wallet signing group. In order to make a successful check, the tested operator address must actually belong to a sortition pool operator, and the passed wallet members identifiers must be equal to the hashed identifiers held by the contract.
This feature is required by the tBTC v2 wallet moving funds process. Specifically, the `Bridge` contract must make sure the moving funds commitment is made by an actual wallet member.

Check wallet membership

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/deploy/01_deploy_sortition_pool.ts
solidity/ecdsa/package.json
solidity/ecdsa/test/WalletRegistry.Rewards.test.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts
solidity/ecdsa/test/fixtures/index.ts
solidity/ecdsa/yarn.lock

See https://github.com/keep-network/sortition-pools/pull/156
~~Depends on https://github.com/keep-network/keep-core/pull/2919; I am planning no more changes in the code but keeping it as a draft until #2919 is merged.~~
Previously, `SortitionPool.withdrawRewards` could be called directly and
the beneficiary address was fetched from the staking contract based on
the operator address.
This is no longer going to work - T `TokenStaking` contract does not store
operators but staking providers - operator is now a per-application role.
We now expect `SortitionPool.withdrawReward` call to be proxied through the
application `WalletRegistry` contract that will fetch the beneficiary address
from T `TokenStaking`.
This PR is also implementing `withdrawIneligibleRewards` function
on the …

ECDSA: withdraw sortition pool rewards

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts

Closes #2929
Instead of requiring operators to pass the value that is already
available on-chain, we just read this value from DKG library storage.

Random Beacon: read DKG seed from chain instead of passing it

---

solidity/random-beacon/contracts/BeaconDkgValidator.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/contracts/libraries/BeaconInactivity.sol
solidity/random-beacon/test/RandomBeacon.Constructor.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts

Restricted mutability of `validateFields` and `validateMembersHash` in
`BeaconDkgValidator` from `view` to `pure`.
Restricted mutability of `validateMembersIndices` in `BeaconInactivity` from
`view` to `pure`.
Added zero-address and zero-value checks to constructors.

Random Beacon: restricted function mutability, added zero-address and zero-value checks to constructors

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/libraries/EcdsaDkg.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/BeaconDkg.sol

After `notifySeedTimeout` is called we want to unlock the sortition pool and cleanup DKG state. In this PR we make it consistent for both ECDSA and Random Beacon.
`sortitionPool.unlock()` is called as part of `dkg.complete` function.

Update sortition pools unlocks and DKG complete for notifySeedTimeout

---

.github/workflows/npm-ecdsa.yml
.github/workflows/npm-random-beacon.yml

Our intention is to tag the published NPM packages with `development`
tag when changes to the contract and configuration related files get
modified and those changes land on `main` branch. The configuration of
the steps in the `npm-....yml` workflows responsible for that was wrong.
The format of the `github.ref` variable for the `main` branch is
`refs/heads/main`, not `main`.

Fix the tagging of `random-beacon` and `ecdsa` packages

---

solidity/random-beacon/contracts/Reimbursable.sol
solidity/random-beacon/contracts/test/ReimbursableImplStub.sol
solidity/random-beacon/test/Reimbursable.test.ts

Reimbursable is an abstract contract with a function `updateReimbursementPool` that should be able to be executed only by a specific role. 
Using Ownable for this contract was not necessary, especially since this causes problems when using upgradable implementations, where we should use `OwnableUpgradable` instead of `Ownable`.
With the `onlyReimbursableAdmin` virtual modifier we leave it to the implementation to check the role according to their needs.

Remove Ownable from Reimbursable

---

solidity/ecdsa/contracts/Governable.sol
solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/contracts/libraries/Wallets.sol
solidity/ecdsa/contracts/test/GovernableImpl.sol
solidity/ecdsa/deploy/08_transfer_governance.ts
solidity/ecdsa/test/DKGValidator.test.ts
solidity/ecdsa/test/Governable.test.ts
solidity/ecdsa/test/WalletRegistry.Parameters.test.ts
solidity/ecdsa/test/WalletRegistry.Rewards.test.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts
solidity/ecdsa/test/fixtures/index.ts
solidity/ecdsa/test/utils/governance.ts
solidity/ecdsa/yarn.lock

~~Depends on https://github.com/keep-network/keep-core/pull/2922~~
In this PR we modify the `WalletRegistry` to make it ready for becoming upgradable.
We removed `Ownable` with `Governable` which is a simpler solution and is consistent with `TokenStaking` contract from threshold-network.
Also, we implement `onlyReimbursableAdmin` from `Reimbursable` contract (https://github.com/keep-network/keep-core/pull/2922).

WalletRegistry and Reimbursable ownership/governance updates

---

solidity/ecdsa/deploy/02_deploy_reimbursement_pool.ts
solidity/ecdsa/test/fixtures/index.ts

Instead of funding the pool in deployment scripts we fund it in the test fixture. After all, this funding is only for unit tests.
What is interesting, this change is fixing harhat gas reporter that is now displaying gas usage summary again at the end of `yarn test`.
The gas reporter worked fine at commit 7a476f4b2f709af696e7f9461314fbe4c1c56fdd and stopped working in the very next commit, c49d2300eac14cc2f9ce89810d500f0db154136f, where the change to deployment scripts funding the pool was introduced.

Fund ETH ReimbursementPool for ECDSA unit tests in fixture and fix hardhat gas reporter

---

solidity/random-beacon/contracts/Governable.sol
solidity/random-beacon/contracts/test/GovernableImpl.sol
solidity/random-beacon/test/Governable.test.ts

See https://github.com/keep-network/keep-core/pull/2921/
This contract was originally implemented by @nkuba for ECDSA
`WalletRegistry` but we can use it also for `RandomBeacon`. First, for
consistency, second to decrease its size given we may need space for one
more function and event related to rewards.
Files are copied and not moved so that we can merge into `main`, have a
a new version of `@keep-network/random-beacon` pushed to NPM registry and
in a separate PR, import these contracts from `ecdsa` module and remove
them from there.
CONTRACTS AND TESTS WERE MOVED WITH NO CHANGES!

Governable contract copied from ecdsa to random-beacon

---

solidity/random-beacon/contracts/Reimbursable.sol

It is expected that `reimbursementPool` is initialized by the
implementing contract right after deployment. We could add a constructor
to set the variable to initial value, but we want to have upgradable
contract anyway so we would have to remove the constructor.
Unblocks https://github.com/keep-network/keep-core/pull/2947

Ignore slither unitialized variable error for reimbursementPool

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
solidity/random-beacon/test/RandomBeacon.Rewards.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts
solidity/random-beacon/test/fixtures/index.ts

~~Depends on #2946~~
`RandomBeacon` is now fully aligned with `WalletRegistry` when it comes to
how `Governable` and `Reimbursable` abstract contracts are used. This change
also allowed to reduce `RandomBeacon` contract size by a tiny bit.
Before/after:
```
|  RandomBeacon   ·     24.352  │
|  RandomBeacon   ·     24.333  │
```

RandomBeacon contract switched to use Governable

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts

Closes https://github.com/keep-network/keep-core/issues/2930
DKG seed can be read from the DKG library and there's no need passing it
as a parameter.

Reading dkg seed from the DKG library

---

solidity/random-beacon/contracts/Governable.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/contracts/libraries/BeaconDkg.sol
solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
solidity/random-beacon/test/RandomBeacon.Relay.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts
solidity/random-beacon/test/fixtures/index.ts
solidity/random-beacon/test/system/e2e.test.ts

~~Depends on #2947. Keeping as a draft until #2947 is not merged but I plan no changes to the code so it is ready for review!~~
This PR allows to go down with `RandomBeacon` contract size from `24.333 KB` to `24.130 KB`.
This is cleaning up the structure but most importantly, should add enough space for some reward-related functions (to be done in a separate PR).
It is grouping parameters together so that instead of exposing them as separate view functions, they are grouped into:
- `relayEntryParameters()`
- `groupCreationParameters()`
- `rewardParameters()`
- `slashingParameters()`
- `gasParameters()`
No changes in the logic of how `RandomBeacon` works.
I recommend reviewing this PR commit-by-commit.

Lowering the size of RandomBeacon contract: parameter function refactoring

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/package.json
solidity/random-beacon/test/RandomBeacon.Rewards.test.ts
solidity/random-beacon/yarn.lock

~~Depends on #2952; Keeping it as a draft PR until #2952 is not merged.~~
Refs https://github.com/threshold-network/solidity-contracts/issues/89
Refs https://github.com/keep-network/keep-core/issues/2935
See https://github.com/threshold-network/solidity-contracts/pull/95
See https://github.com/keep-network/sortition-pools/pull/162
See https://github.com/keep-network/sortition-pools/pull/163
`RandomBeacon.withdrawRewards` emits `RewardsWithdrawn` event informing about
the amount of tokens withdrawn in the transaction.
`RandomBeacon.availableRewards` informs about the amount of reward tokens
available for withdrawal for the staking provider.

Adjusting RandomBeacon to Threshold IApplication rewards API

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/package.json
solidity/random-beacon/test/RandomBeacon.Authorization.test.ts
solidity/random-beacon/yarn.lock

Refs https://github.com/keep-network/keep-core/issues/2935
Dependency updated to `>1.2.0-dev <1.2.0-ropsten`, with a fix on slashing
gas costs and changes to `IApplication` interface.
After upgrading the dependency, I had to fix the unit tests for `RandomBeacon`
authorizations to take into account the change of the behavior in the staking contract.
This was done in the commit 9d061aab160e93b7b0a5424b881a3b32ac54a102.
Note that the same fix was done for `WalletRegistry` in https://github.com/keep-network/keep-core/pull/2942.

Updated beacon `@threshold-network/solidity-contract` dependency

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/package.json
solidity/ecdsa/test/WalletRegistry.Rewards.test.ts
solidity/ecdsa/yarn.lock

~~Depends on #2953; Keeping it as a draft PR until #2953 is not merged.~~
Refs https://github.com/threshold-network/solidity-contracts/issues/89
Refs https://github.com/keep-network/keep-core/issues/2935
See https://github.com/threshold-network/solidity-contracts/pull/95
See https://github.com/keep-network/sortition-pools/pull/162
See https://github.com/keep-network/sortition-pools/pull/163
`WalletRegistry.withdrawRewards` emits `RewardsWithdrawn` event informing about
the amount of tokens withdrawn in the transaction.
`WalletRegistry.availableRewards` informs about the amount of reward tokens
available for withdrawal for the staking provider.

Adjusting WalletRegistry to Threshold IApplication rewards API

---

.github/workflows/npm-ecdsa.yml
.github/workflows/npm-random-beacon.yml

We want to publish the new NPM package tagged with `development` every
time changes affecting contracts get merged to `main`. We already
trigger the NPM workflows when changes are applied in couple of files,
but we missed the hardhat configuration in `hardhat.config.ts` which
can also affect the content of the exported package with the
contracts.
Similar changes in other projects:
https://github.com/keep-network/tbtc-v2/pull/230
https://github.com/keep-network/coverage-pools/pull/211

Expand NPM workflow triggers

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol
solidity/random-beacon/contracts/libraries/BeaconDkg.sol
solidity/random-beacon/contracts/libraries/Relay.sol
solidity/random-beacon/contracts/test/RelayStub.sol

This PR does not change the functionality. It is squeezing the update code of libraries to save on bytecode in `RandomBeacon`. The bytecode freed will be needed for another authorization parameter (the next PR).
I suggest reviewing this PR commit-by-commit.

Grouped together functions to update parameters in beacon libraries

---

solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol
solidity/random-beacon/test/RandomBeacon.Authorization.test.ts
solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts
solidity/random-beacon/test/fixtures/index.ts

~~Depends on #2959~~
See https://github.com/threshold-network/solidity-contracts/pull/99
Introduced authorization decrease change period parameter to the beacon
This value protect against malicious operators who manipulate
their weight by overwriting authorization decrease request, and
lowering or increasing their eligible stake this way.
Authorization decrease change period is the time period before the authorization
decrease delay end, during which the authorization decrease request can be
overwritten.
When the request is overwritten, the authorization decrease delay is
reset.
For example, if `authorizationDecraseChangePeriod` is set to 4
days, `authorizationDecreaseDelay` is set to 14 days, and someone
requested authorization decrease, it means they can not
request another decrease for …

Introduced authorization decrease change period parameter to the beacon

---

solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/test/utils/groups.ts

When converting BigNumber seed for selectGroup we need to pad the hex
string with zeros to work with expected `bytes32` in
`sortitionPool.selectGroup`.

Pad seed with zeros in tests

---

solidity/random-beacon/hardhat.config.ts
solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

Refs https://github.com/keep-network/keep-core/issues/2955
Combination of overwriting the hardhat's "test" task and requiring test fixtures `require("./test/fixtures")` resulted in hiding the gas report after the tests run. Instead of overwriting a "test" task, we can also create a new task that checks the count of needed accounts and run this check before the main "test" task.
Another addition to this PR is fetching the current market data from the Coinmarketcap. The gas report will show the current price for executing specific functions and the cost of contract deployments based on the live data. The free tier API key is good for 10000 requests per month. Execution: `COINMARKETCAP_API_KEY=<key> yarn test` For testing purposes please see …

Fixing gas reporter for random-beacon

---

solidity-v1/dashboard/src/constants/constants.js

"that was an interim link that is no longer current" -maclane
see: https://discord.com/channels/866378471868727316/870383405936820224/967854416814284810

update pre setup link

---

solidity/ecdsa/.gitignore
solidity/ecdsa/deploy/02_deploy_reimbursement_pool.ts
solidity/ecdsa/deploy/10_deploy_proxy_admin_with_deputy.ts
solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/package.json
solidity/ecdsa/test/WalletRegistry.Deployment.test.ts
solidity/ecdsa/yarn.lock

This PR includes some minor updates to the deployment scripts.
It also bumps up a version of @keep-network/hardhat-helpers to 0.5.1. Which adds more details to the WalletRegistry deployment artifact.

ECDSA deployment updates

---

solidity/ecdsa/README.adoc
solidity/ecdsa/deploy/04_deploy_wallet_registry.ts
solidity/ecdsa/deploy/09_transfer_proxy_admin_ownership.ts
solidity/ecdsa/package.json
solidity/ecdsa/test/WalletRegistry.Deployment.test.ts
solidity/ecdsa/test/WalletRegistry.Upgrade.test.ts
solidity/ecdsa/test/fixtures/index.ts

In this PR we replace a previous workaround (https://github.com/keep-network/keep-core/pull/2970) for a bug in the `hardhat-gas-reporter` plugin (https://github.com/cgewecke/hardhat-gas-reporter/issues/86).
It turned out that there is a much simpler workaround, which is based on just removing `--deploy-fixture` flag. With the flag removed it is required that we load a global snapshot of the deployment (`deployments.fixture()`) instead of loading a specific tag (`deployments.fixture(<tag>)`. Which we do anyway after one of a recent code updates.

Workaround hardhat-gas-reporter bug with removing --deploy-fixture

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

Non-RC version is now available. Updating from `4.6.0-rc.0` to `4.6.0`. Also, removed `@openzeppelin/contracts` dependency given we now use `@openzeppelin/contracts-upgradeable` in imports across ECDSA Solidity module code.
Refs https://github.com/keep-network/tbtc-v2/issues/152

ECDSA: Updated `@openzeppelin/contracts-upgradeable` to 4.6.0

---

solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

This way, the most recent version of the package will be installed.
It should also help us with resolving a potential compilation bug that
was fixed in https://github.com/threshold-network/solidity-contracts/pull/97 given that the
most recent version of Threshold contracts is installed now.
I have also updated `@openzeppelin/contracts` to the most recent
version now, 4.6.0.

Random Beacon: updated @threshold-network/solidity-contract to use 'development' tag

---

solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

This way, the most recent version of the package will be installed.
It should also help us with resolving the compilation bug that was fixed
in https://github.com/threshold-network/solidity-contracts/pull/97.
See https://github.com/keep-network/keep-core/pull/2981

Updated @threshold-network/solidity-contract to use 'development' tag

---

solidity/random-beacon/yarn.lock

We've published new `@threshold-network/solidity-contracts` for
development env. We want to update the dependency in the
`random-beacon`.

Update @threshold-network/solidity-contracts dependency

---

solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

We tried using `development` tag to always point to the latest
development package, but that was causing `An unexpected error occurred:
"expected manifest".` error when running `yarn upgrade
@threshold-network/solidity-contracts`. So we're going back to using the
version range. We may use `development` tag in the future, once we
figure out the reason behind the error that we were getting.
It is possible that the error was related to this issue:
https://github.com/yarnpkg/yarn/issues/4731.

Use range in the t-network solidity-contracts dependency

---

solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

The most recent version switched back from using `development` tag for
`@threshold-network/solidity-contracts` dependency to just a standard
`>1.2.0-dev <1.2.0-ropsten` range. This should fix potential problems on
ECDSA side as well.

Update @keep-network/random beacon dependency to the most recent version

---

solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/package.json
solidity/ecdsa/test/WalletRegistry.Deployment.test.ts
solidity/ecdsa/yarn.lock

Seting both `@openzeppelin/contracts` and `@openzeppelin/contracts-upgradeable`
dependency versions to `^4.6.0`. This version of `@openzeppelin/contracts` is
aligned with what we use in `solidity/random-beacon`.
To make this change possible, I removed `ProxyAdminWithDeputy.sol` imported from
`@threshold-network/solidity-contracts` from the list of contracts compiled by
the hardhat dependency compiler. `ProxyAdminWithDeputy` is used only in
deployment scripts and does not need to be compiled. Without this change, we
would have to pin `@openzeppelin/contracts` to version `4.5.0` given some
changes in `@openzeppelin/contracts` version `4.6.0` stops
`@threshold-network/solidity-contracts` from compiling. See
https://github.com/threshold-network/solidity-contracts/pull/97
Additionally, I had …

Update openzeppelin contracts to ^4.6.0

---

solidity/ecdsa/tasks/initialize-wallet-owner.ts

We wan to expose `initializeWalletOwner` function for tbtc-v2 to initialize the wallet owner after deploying the Bridge contract.
Refs https://github.com/keep-network/tbtc-v2/issues/250

Expose initializeWalletOwner function

---

solidity-v1/dashboard/Dockerfile

The `git://` protocol is no longer supported by Github. This means that in
certain situations installation of the package or update of its dependencies
using NPM may result in errors like `fatal: unable to connect to github.com`.
That is what happenning after executing the Dockerfile and installing some
dependencies of the token dashboard.
As a workaround, we're adding step to the Dockerfile, which configures Git to
use `https://` protocol instead of `git://` when downloading files.

Config git to use `https://` instead of `git://`

---

solidity-v1/dashboard/Dockerfile

Backport of https://github.com/keep-network/keep-core/pull/3001
The `git://` protocol is no longer supported by Github. This means that in
certain situations installation of the package or update of its dependencies
using NPM may result in errors like `fatal: unable to connect to github.com`.
That is what happenning after executing the Dockerfile and installing some
dependencies of the token dashboard.
As a workaround, we're adding step to the Dockerfile, which configures Git to
use `https://` protocol instead of `git://` when downloading files.

[Backport] Config git to use `https://` instead of `git://`

---

solidity-v1/dashboard/src/components/threshold/AuthorizeThresholdContracts.jsx
solidity-v1/dashboard/src/reducers/threshold-authorization.js
solidity-v1/dashboard/src/services/threshold-authorization.service.js

Removes stakes that are cancelled (while in initialization period) from
threshold authorization table. Also disable the `Authorize and Stake` button for
the stakes that are in initialization period (and adds tooltip informing about
why it is disabled).

Remove specific stakes from t auth data

---

pkg/net/libp2p/unicast_channel_test.go

Refs https://github.com/keep-network/keep-core/issues/3004.
This PR adds a fix for failing unit tests related to unicast channels.
Inside `TestSendReceiveUnicastChannel` we [send messages between peer 1 and peer 2](https://github.com/keep-network/keep-core/blob/333156b595e005322f06de2c8bda45cf822ff87a/pkg/net/libp2p/unicast_channel_test.go#L58).
Then [we retrieve the channel that should be created by the sent messages](https://github.com/keep-network/keep-core/blob/333156b595e005322f06de2c8bda45cf822ff87a/pkg/net/libp2p/unicast_channel_test.go#L66).
If the sent messages are received by peer 2 before the above call, it created the channel properly and sets the unmarshaller to handle the messages. In that case [the call](https://github.com/keep-network/keep-core/blob/333156b595e005322f06de2c …

Fix for unicast channel related error

---

solidity/random-beacon/hardhat.config.ts
solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

Updated @threshold-network/solidity-contracts dependency to the latest
published development package.

Update @threshold-network/solidity-contracts dependency in Beacon

---

solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

Updated @threshold-network/solidity-contracts dependency to the latest
published development package.
TODO:
Depends on https://github.com/keep-network/keep-core/pull/3052

Bump threshold contracts dependency in ECDSA

---

.github/workflows/npm-ecdsa.yml
.github/workflows/npm-random-beacon.yml
solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock
solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

The `hardhat-deploy` plugin outputs artifacts to `deployments/<network>` directory. For dApps and client builds we require the `artifcats` to be placed in the `artifacts/` directory.
Here we use a `prepare-artifacts` task that will copy the artifacts to the required dir.
The root cause of the problems we are solving here is a recent update to the `hardhat-deploy` plugin 
(https://github.com/wighawag/hardhat-deploy/issues/345).
The same change was introduced for `threshold-network/solidity-contracts` in https://github.com/threshold-network/solidity-contracts/pull/113/commits/0c843c620fa0d7e54474736933ad56d5aa3ba3ea

Prepare deployment artifacts for contracts packages publication

---

configs/config.toml.SAMPLE

The PR updates the bootstrap address in the `config.toml.SAMPLE` files.
The address that used to be there couldn't be parsed by keep-core due to bad encoding.

Updated bootstrap address in config.toml.SAMPLE

---

pkg/net/libp2p/key.go
pkg/net/libp2p/key_test.go

Closes https://github.com/keep-network/keep-core/issues/3065.
This PR adds padding to operator private key bytes inside `operatorPrivateKeyToNetworkKeyPair` if the key's D parameter is shorter than 32 bytes.
It was tested by running `TestOperatorPrivateKeyToNetworkKeyPair` multiple times and on one run the generated operator private key was 31 bytes long:
```
=== RUN   TestOperatorPrivateKeyToNetworkKeyPair
len(operatorKeyBytes) 31
operatorKeyBytes [196 130 44 41 200 24 238 164 190 40 13 34 223 51 95 159 169 84 183 203 125 149 121 51 46 73 201 238 130 122 246]
len(paddedOperatorKeyBytes) 32
paddedOperatorKeyBytes [0 196 130 44 41 200 24 238 164 190 40 13 34 223 51 95 159 169 84 183 203 125 149 121 51 46 73 201 238 130 122 246]
--- PASS: TestOperatorPrivateKeyToNetworkKeyPair (0.00s)
``` …

Added padding for operator private keys shorter than 32 bytes

---

.github/workflows/npm-random-beacon.yml
solidity/random-beacon/yarn.lock

When publishing NPM packages we upgrade the versions of dependencies. We
were missing a step of upgrading @threshold-network/solidity-contracts
in the random beacon project. Adding it here.

Upgrade @threshold-network/solidity-contracts in beacon

---

solidity/ecdsa/yarn.lock

The file was generated for upgraded dependencies and matches the one
published to NPM.

Update yarn.lock for ECDSA

---

pkg/chain/ethereum/beacon.go
pkg/sortition/chain.go
pkg/sortition/internal/local.go
pkg/sortition/internal/local_test.go

Refs #3006 
`IsOperatorUpToDate` and `UpdateOperatorStatus` functions added to sortition `Chain` and implemented for the local and Ethereum chain.
`IsOperatorUpToDate` and `UpdateOperatorStatus` are needed to monitor the status of the operator in the sortition pool. The local Go implementation mirrors the behavior of `BeaconAuthorization` Solidity library.

IsOperatorUpToDate and UpdateOperatorStatus functions added to sortition Chain

---

solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

We update @keep-network/hardhat-helpers version to 0.6.0-pre.9 as it
contains improvements introduced in https://github.com/keep-network/hardhat-helpers/pull/27
that will modify the artifact exported for proxy contracts. The new
artifact matches the artifacts produced for contracts deployed non-proxy
way, which is important for Go code generator.

Update @keep-network/hardhat-helpers version

---

pkg/chain/common/gen/Makefile
pkg/chain/ecdsa/gen/Makefile
pkg/chain/ecdsa/gen/abi/EcdsaSortitionPool.go
pkg/chain/ecdsa/gen/cmd/EcdsaSortitionPool.go
pkg/chain/ecdsa/gen/contract/EcdsaSortitionPool.go
pkg/chain/ethereum/beacon.go
pkg/chain/random-beacon/gen/Makefile
pkg/chain/random-beacon/gen/abi/BeaconSortitionPool.go
pkg/chain/random-beacon/gen/cmd/BeaconSortitionPool.go
pkg/chain/random-beacon/gen/contract/BeaconSortitionPool.go

We update the expected path where artifacts should be placed in the contract package. With the recent changes to the contracts packages exports, we expect them to be placed in `artifacts` directory in a flat directory structure.
Also for the `@keep-network/random-beacon` and `@keep-network/ecdsa` the artifact names have changed from `SortitionPool` to `BeaconSortitionPool` and `EcdsaSortitionPool`.

Update expected artifacts for generation

---

.github/workflows/npm-ecdsa.yml
.github/workflows/npm-random-beacon.yml

We want to add `--exact` flag so the version of tagged package is
resolved to an exact value. Without this flag by default the version is
resolved by adding `^`, which can cause problems when resolving versions
with `-dev`, `-goerli`, `-mainnet` suffixes.

Use upgrade --exact for NPM package publication

---

.github/workflows/client.yml
.gitignore
Dockerfile
go.sum
pkg/chain/ethereum/beacon/gen/gen.go
pkg/chain/ethereum/common/gen/Makefile
pkg/chain/ethereum/ecdsa/gen/gen.go
pkg/chain/ethereum/tbtc/gen/gen.go
pkg/chain/ethereum/threshold/gen/gen.go

We already download artifacts of deployed contracts from the NPM registry.
Here we add support for extracting addresses of contracts from the
artifacts. The address is extracted and stored in `_address/<CONTRACT>`
file and then embedded into the go code.
This solution is intended to be used for clients building for a specific environment. For example, if we set `CONTRACTS_NPM_PACKAGE_TAG` environment variable to `goerli`. It will download a package of contracts deployed on the Goerli network and extract addresses from it. The client will be built specifically for the Goerli network, without the need of configuring the addresses in a config file.
There will be a possibility to overwrite the addresses with a configuration file or environment variables.
Addresses extraction will happen on …

Extract contract addresses from artifacts

---

scripts/start_dashboard.sh

Related to https://github.com/keep-network/keep-core/pull/3100
We removed the deployment of keep-ecdsa by a mistake. This commit fixes that.

Fix start_dashboard script

---

solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

We need the latest version of hardhat helpers so the external deployment script 03_deploy_wallet_registry.js can be executed. Without the upgrade it throws an error:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="call", transaction={"from":"0x407190f04d838Ec47dad4C0e0D2a9c49d7737479","to":"0x9E3991842f115f93D59cb92aE508242FE965A662","data":"0x204e1c7a0000000000000000000000009e500a116ea139c8e72af8f7953438ad0720cdcd","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.3)
```

Upgrading hardhat helpers to 0.6.0-pre.10

---

pkg/chain/ethereum/beacon.go

This PR rolls back the removal of a check that was removed in 7d3722f79dd2ae45df78a91a92814c7134eb52b0.
The check performed during DKG result submission is needed, as two operators that belong to the same client may submit a DKG result.

Rolled back the needed check during DKG submission

---

solidity/ecdsa/contracts/EcdsaDkgValidator.sol
solidity/random-beacon/contracts/BeaconDkgValidator.sol

SortitionPool field in EcdsaDkgValidator and BeaconDkgValidator is set
only in constructor and never modified later. We can use immutable field
to save gas.

Use immutable fields for SortitionPool

---

solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/package.json

We want to use deployment scripts from external projects only for unit
tests. In other cases we want to have the artifacts to actually deployed
contracts. This is the approach we use in other projects.

Set USE_EXTERNAL_DEPLOY for ecdsa external contracts

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/contracts/libraries/EcdsaDkg.sol
solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2.sol
solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2MisplacedNewSlot.sol
solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2MissingSlot.sol
solidity/ecdsa/test/WalletRegistry.Parameters.test.ts
solidity/ecdsa/test/WalletRegistryGovernance.test.ts
solidity/ecdsa/test/fixtures/index.ts

Due to EIP150, 1/64 of the gas is not forwarded to the call, and will be kept to execute the remaining operations in the function after the call inside the try-catch.
To ensure there is no way for the caller to manipulate the gas limit in such a way that the call inside try-catch fails with out-of-gas and the rest of the function is executed with the remaining 1/64 of gas, we require an extra gas amount to be left at the end of the call to `WalletRegistry.challengeDkgResult`.
In practice, with the current version of the code, such a scenario should not be possible anyway but the extra gas requirement provides an extra layer of protection in case of any code changes. In the current version of the code, the cost of `dkg.challegeResult(dkgResult)` is about 1.6M gas units and the cost of …

Added extra gas requirement for ECDSA DKG result challenge

---

infrastructure/kube/keep-test/geth-node/eth-goerli-node.yaml

- added `type` to `spec` section in service of kubernetes defining kind of service
- added LoadBalancer IP which was previously reserved using gcloud command as regional IP

 #3012 Add LoadBalancer with static IP

---

pkg/ecdsa/retry/retry.go
pkg/ecdsa/retry/retry_test.go

This PR adds a `EvaluateRetryParticipantsForKeyGeneration` function in the new `pkg/ecdsa` package which takes in a list of chain addresses, and returns a subset of those chain addresses subject to a random seed and retry count number. 
We plan on using such a function each time key generation fails *but not due to inactivity* in order to randomly select as many operators as possible to create a signing group, hoping to avoid *just* the misbehaving operators.
We do this by first shuffling the operator set, and one-at-a-time, trying to exclude those operators. If that doesn't work, we shuffle the list of operator pairs, and one-at-a-time exclude those pairs. If that doesn't work, we try again with triplets. If that doesn't work, we're probably out of time.
tagging @lukasz-zimnoch for …

One More Once: Keygen Retry Algorithm

---

.github/workflows/client.yml
.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml
.github/workflows/contracts-v1.yml
.github/workflows/dashboard-v1-format.yaml
.github/workflows/dashboard-v1-mainnet.yml
.github/workflows/dashboard-v1-testnet.yml
.github/workflows/docs.yml
.github/workflows/genesis-testnet.yml
.github/workflows/npm-ecdsa.yml
.github/workflows/npm-random-beacon.yml
.github/workflows/npm-v1.yml
.github/workflows/submitter-testnet.yaml

New version of the action is now available. With `v2` we're sometimes
seeing problems with parallel execution of jobs. We hope that updating
to `v3` will help.

Use newer version (v3) of the `setup-node` action

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/libraries/EcdsaDkg.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/contracts/libraries/BeaconDkg.sol
solidity/random-beacon/test/RandomBeacon.Parameters.test.ts
solidity/random-beacon/test/RandomBeacon.Relay.test.ts
solidity/random-beacon/test/RandomBeaconGovernance.test.ts
solidity/random-beacon/test/fixtures/index.ts
solidity/random-beacon/test/utils/dkg.ts

See #3133 for ECDSA part.
Due to EIP150, 1/64 of the gas is not forwarded to the call, and will be kept to execute the remaining operations in the function after the call inside the try-catch.
To ensure there is no way for the caller to manipulate the gas limit in such a way that the call inside try-catch fails with out-of-gas and the rest of the function is executed with the remaining 1/64 of gas, we require an extra gas amount to be left at the end of the call to `RandomBeacon.challengeDkgResult`.
In practice, with the current version of the code, such a scenario should not be possible anyway but the extra gas requirement provides an extra layer of protection in case of any code changes. In the current version of the code, the cost of `dkg.challegeResult(dkgResult)` is about 1M gas …

Added extra gas requirement for Beacon DKG result challenge

---

.gitignore
Dockerfile
Makefile
pkg/chain/ethereum/beacon/gen/gen.go
pkg/chain/ethereum/common/gen/Makefile
pkg/chain/ethereum/ecdsa/gen/gen.go
pkg/chain/ethereum/tbtc/gen/gen.go
pkg/chain/ethereum/threshold/gen/gen.go

In this PR we extract artifacts downloading to the main Makefile, instead of doing it in the bindings generation process.
This is preparation for multi-network clients and supporting local developer machine's contracts artifacts.
Also, the execution experience was improved. To run generation and building for goerli environment you have to run `make goerli` instead of `CONTRACTS_NPM_PACKAGE_TAG=local go generate ./...`.

Extract contracts artifacts downloading to the main Makefile

---

scripts/install.sh

It happens that open zeppelin's manifest in ecdsa (.openzeppelin) is not updated properly and the error is thrown during deployment of the `WalletRegistry` as transparent proxy. Removing this folder forces a fresh installation.

Remove openzeppelin manifest for fresh installation

---

.github/actions/docker-build-push/action.yml

We have a GH composite action config that's responsible for building and
publishing Docker images. The publishing wasn't working properly due to
incorrect value passed in the `tags` property. Now we're fixing that.

Fix the publishing of Docker images

---

.github/actions/docker-build-push/action.yml

We will be using the action in the jobs that already do a `checkout` and
they modify the files pulled from the Git repository. If we do another
`checkout` in the composite action, all the changes to the filles will
be overwritten, which is not a wanted behavior.

Remove `checkout` from `docker-build-push` custom action

---

go.mod
go.sum

The letest version contains fix for addresses resolvement and defaulting
them to the ones embeded on build.
Refs https://github.com/keep-network/keep-common/pull/97

Update keep-common dependency to the latest

---

solidity/ecdsa/package.json

With `npm run deploy` used in the `deploy:test` script we were getting
`Error HH308: Unrecognized positional argument hardhat` error when
running the script.

Fix command used in `deploy:test` script

---

solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts

Several times the test checking gas usage for `challengeDkgResult` have
failed due to less gas used than expected (around 1785k gas was used).
Adjusting the gas usage margin to allow for such values.
Sample failing workflow: https://github.com/keep-network/keep-core/runs/6853425591?check_suite_focus=true.

Fix challengeDkgResult gas usage assertion

---

solidity/ecdsa/contracts/EcdsaDkgValidator.sol
solidity/ecdsa/contracts/WalletRegistryGovernance.sol
solidity/ecdsa/contracts/libraries/EcdsaInactivity.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol

Three small tweaks have been done here:
- Made `WalletRegistry` reference immutable in `WalletRegistryGovernance`. `WalletRegistry` address is set in the constructor and never changes.
- Made `RandomBeacon` reference immutable in `RandomBeaconGovernance`. `RandomBeacon` address is set in the constructor and never changes.
- Some functions in `EcdsaDkgValidator` and `EcdsaInactivity` that were marked as `view` can actually be marked as `pure`. Updated the modifier.

Tiny tweaks: immutable fields in governance contracts and pure functions

---

docs/development/README.adoc
scripts/initialize.sh

initialize.sh now handles WalletRegistry as well. We need to update docs
reflecting this.

Updating installation scripts docs

---

cmd/helpers.go
cmd/start.go

We output in the node header contract addresses to which the client is connected. This change improves debugging of clients as it reduces ambiguity.
Sample:
```
▓▓▌ ▓▓ ▐▓▓ ▓▓▓▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓    ▓▓▓▓▓▓▓▀    ▐▓▓▓▓▓▓    ▐▓▓▓▓▓   ▓▓▓▓▓▓     ▓▓▓▓▓   ▐▓▓▓▓▓▌   ▐▓▓▓▓▓▓
▓▓▓▓▓▓▄▄▓▓▓▓▓▓▓▀      ▐▓▓▓▓▓▓▄▄▄▄         ▓▓▓▓▓▓▄▄▄▄         ▐▓▓▓▓▓▌   ▐▓▓▓▓▓▓
▓▓▓▓▓▓▓▓▓▓▓▓▓▀        ▐▓▓▓▓▓▓▓▓▓▓         ▓▓▓▓▓▓▓▓▓▓▌        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓▀▀▓▓▓▓▓▓▄       ▐▓▓▓▓▓▓▀▀▀▀         ▓▓▓▓▓▓▀▀▀▀         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▀
▓▓▓▓▓▓   ▀▓▓▓▓▓▓▄     ▐▓▓▓▓▓▓     ▓▓▓▓▓   ▓▓▓▓▓▓     ▓▓▓▓▓   ▐▓▓▓▓▓▌
▓▓▓▓▓▓▓▓▓▓ █▓▓▓▓▓▓▓▓▓ ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓▓▓▓▓ …
```

Include contracts addresses in the node header

---

Dockerfile
Makefile

Depends on: https://github.com/keep-network/keep-core/pull/3126
On developer machine contracts are deployed to local geth instance. We need to use them in the client, instead of downloading a package from NPM registry.
Here we add support for local artifacts. The make command will fetch the artifacts from local directories and use them for client build.
This is useful if a developer wants to generate bindings for locally deployed contracts.
What is more, the client will embed the addresses of locally deployer contracts, so running the client locally won't require setting the addresses in the configuration file or `--developer` flags.
The directories can be provided by the caller, e.g.:
make local local_threshold_path=/other/path/threshold
If the directories are not provided default paths …

Support local artifacts in the Makefile

---

scripts/install.sh

Hardhat projects use named accounts that have assigned the default
indices to them. The index denotes an index of an account. A minimum number of
all accounts is the highest index of the named account across all the used
projects.

Adding a warning informing about a min number of required accounts

---

cmd/network.go
main.go

In https://github.com/keep-network/keep-core/pull/3090 we replaced urfave/cli with cobra for `start` command. 
In this PR we refactor `ping` comamnd to use `cobra`.
```
$ ./keep-client ping --help
The ping command conducts a simple peer-to-peer test between a bootstrap node and another peer: 
can known peers communicate over a peer-to-peer network. Both peers send a "PING" and expect to
receive a corresponding "PONG". Notably, this does not exercise peer discovery.
Usage:
keep-client ping [multiaddr]...
Flags:
-h, --help   help for ping
```

Use cobra for ping command

---

.github/workflows/client.yml

In v2 of the system we modified the structure of the components that we
build to set up the system. There have been changes in the structure of
the `keep-core` repository and the order of the execution of modules in
the CI has changed as well. In this PR/commit we upgrade the custom CI
actions to `v2`, which uses the latest module order. We also adjust
slightly the workflow triggering conditions.
Workflow executed here: https://github.com/keep-network/keep-core/runs/7784716537?check_suite_focus=true (it pushed the image to `gcr.io/keep-test-f3e0/keep-client-wip`)
Note: to make the workflow integrated in the CI flow, we need to adjust the `config.json` in the `ci` repo (https://github.com/keep-network/ci/pull/31).

Adjust `client.yml` for use in v2

---

pkg/internal/testutils/testutils.go
pkg/miner/miner.go
pkg/miner/miner_test.go

Refs #3161
Miner allows managing computationally heavy operations: stopping and resuming
them. The client needs to generate parameters for cryptographic algorithms
and generating these parameters requires a lot of CPU cycles. The generation
process may starve other processes in the client when it comes to access to
the CPU. The miner allows starting the parameter generation when no other
processes such as key generation or signing are executed on the client. This
way, the client that would normally be idle, can spend CPU cycles on
computationally heavy operations and stop these operations when CPU cycles
are needed elsewhere.

Abstraction to manage computationally-heavy operation

---

cmd/flags.go
cmd/flags_test.go
configs/config.toml.SAMPLE
docs/development/cmd-help
pkg/tbtc/node.go
pkg/tbtc/tbtc.go
pkg/tecdsa/dkg/dkg.go
pkg/tecdsa/dkg/params_pool.go
pkg/tecdsa/dkg/params_pool_test.go

Refs #3161 
There is a configurable delay between the generation of pre-parameters.
By default, the delay is 10 seconds. If pre-parameters generation takes a long
time and new parameters are generated one after another, all other client
processes are starved, without access to CPU. Adding a delay should help with
releasing some computing power for a moment.
Still testing it, so PR is in a draft. The code is ready for a review though.

Added a delay between pre-parameters generation

---

.github/workflows/client.yml

The Jerome1337/gofmt-action started reporting [false-positive problems](https://github.com/keep-network/keep-core/runs/7878381256?check_suite_focus=true) that is expected to be caused by old version of Go it is running with, as it's based on [cytophia/gofmt image that is 2 years old](https://hub.docker.com/layers/gofmt/cytopia/gofmt/latest/images/sha256-4841f8441239afcb23202626a572b43f24e1420ec9d96901f84f7b81d4e6f5aa?context=explore).
Here we switch to `setup-go` action that will checkout the version of go specified in the `go.mod` file. Then we run `gofmt` command for the installed `go` version.

Replace Jerome1337/gofmt-action with gofmt command

---

solidity/random-beacon/.eslintrc
solidity/random-beacon/package.json
solidity/random-beacon/tasks/ensure-eth-balance.ts
solidity/random-beacon/tasks/index.ts
solidity/random-beacon/tasks/send-eth.ts
solidity/random-beacon/tasks/unlock-eth-accounts.ts
solidity/random-beacon/tasks/utils/ether.ts
solidity/random-beacon/tasks/utils/index.ts
solidity/random-beacon/test/Groups.Expiration.test.ts
solidity/random-beacon/test/Groups.Termination.test.ts
solidity/random-beacon/test/Groups.test.ts
solidity/random-beacon/test/system/e2e.test.ts
solidity/random-beacon/test/utils/dkg.ts
solidity/random-beacon/test/utils/operators.ts
solidity/random-beacon/tsconfig.json
solidity/random-beacon/yarn.lock

Blocked by https://github.com/thesis/eslint-config/pull/4
We add a hardhat task that can be used to ensure addresses are funded with a minimum value of ether. This will be used in test environments setup to ensure when a client starts the operator has enough funds to run.
Sample command:
```
npx hardhat ensure-eth-balance "0.5 ether" \
0x6299496199d99941193Fdd2d717ef585F431eA05 \
0x93df7c54c41A9D7FB17C1E8039d387a2A924708c
```

Hardhat task to ensure accounts ether balances

---

go.mod
go.sum
pkg/internal/tecdsatest/tecdsatest.go
pkg/tecdsa/dkg/marshaling.go
pkg/tecdsa/dkg/member.go
pkg/tecdsa/dkg/member_test.go
pkg/tecdsa/dkg/preparams.go
pkg/tecdsa/dkg/protocol.go
pkg/tecdsa/dkg/protocol_test.go
pkg/tecdsa/key.go
pkg/tecdsa/marshaling.go
pkg/tecdsa/marshaling_test.go

Refs #3161
Depends on #3174 
The new version includes changes to the pre-parameters generator allowing to stop the generator immediately: 
https://github.com/bnb-chain/tss-lib/pull/191
The new version includes the rebranding from `binance-chain` to `bnb-chain` so I had to cover it here as well.

Updated TSS lib dependency

---

cmd/start.go

Refs: https://github.com/keep-network/keep-core/issues/3014
So far, the client exited with an error in case the appropriate storage directory for the beacon or tbtc application was missing. Here we check whether the storage directory exists, and we create a fresh one in case it is missing.

Ensure existence of the application storage directory

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml

We want to modify sortition pools used in the test environment to make joining applications easier for operators. With the changes from the forked sortition pools we will not require the sortition pool to be unlocked when an operator wants to join. Even in case, the DKG process is in progress we will let operators join.
This is just a temporary change that should be reverted in the near future.
Refs: https://github.com/keep-network/sortition-pools/pull/186

Use forked sorition pools in testnet deployment

---

scripts/start_dashboard.sh

In this PR - https://github.com/threshold-network/solidity-contracts/pull/113 - there was a change that changed the way of how we prepare the artifacts in `solidity-contracts` repo. Instead of calling `prepare-artifacts.sh` file we use hardhat helper task (please see this commit - https://github.com/threshold-network/solidity-contracts/pull/113/commits/0c843c620fa0d7e54474736933ad56d5aa3ba3ea).
This PR updates the `start_dashboard` script in Keep dashboard to do the same, since `prepare-artifacts.sh` file was removed.

Update preparation of the artifacts for `solidity-contracts` in `start_dashboard.sh` script

---

.git-blame-ignore-revs
solidity-v1/dashboard/src/lib/keep/keep-to-t-staking/index.js
solidity-v1/dashboard/src/services/tokens-page.service.js

There is a bug in Keep dashboard which blocked the user to unstake the
delegation from Keep if he unstaked all the tokens from T dashboard.
It was happening because normally user should not be allowed to unstake
when the stake is moved to T, but we were checking if it was moved there
wrongly.  Previosly we examined the "Staked" events in T contract, and
if there were any we assumed that the staked is moved. However, there
can be a situation when the operator stake the keep tokens, and then
unstake them all and we didn't check any "Unstaked" events at all.
To fix this, instead of checking all the events, we will be calling
"stakes" method from TokenStaking contract, which will return all the
tokens staked in T Network (keep, nu and T). Then we will check if keep
tokens are equal to 0 - if …

Fix blocked undelegate button

---

solidity/random-beacon/tasks/ensure-eth-balance.ts

In the commit 939c42e6a5b8a6671ea74c0e72d7885386f0ca46 we renamed `value` argument to `amount` but missed updating the `ensure-eth-balance` task to use the new argument name.

Pass `amount` to `send-eth` task

---

pkg/beacon/dkg/result/submission.go

Closing the `onSubmittedResultChan` channel is not needed in that case and is the source of the frequently observed test failure:
```
panic: send on closed channel
goroutine 49841 [running]:
github.com/keep-network/keep-core/pkg/beacon/dkg/result.(*SubmittingMember).SubmitDKGResult.func1(0xa27720?)
/go/src/github.com/keep-network/keep-core/pkg/beacon/dkg/result/submission.go:79 +0x26
github.com/keep-network/keep-core/pkg/chain/local_v1.(*localChain).SubmitDKGResult.func1(0xc00000e300?, 0x0?)
/go/src/github.com/keep-network/keep-core/pkg/chain/local_v1/local.go:290 +0x23
created by github.com/keep-network/keep-core/pkg/chain/local_v1.(*localChain).SubmitDKGResult
/go/src/github.com/keep-network/keep-core/pkg/chain/local_v1/local.go:289 +0x41e
```
It is ok to leave Go channels open as they …

Improvements for the beacon DKG result submitter

---

cmd/start.go

The changes from this PR were originally introduced in https://github.com/keep-network/keep-core/pull/3179 but disappeared from the main branch. We add it back again.
So far, the client exited with an error in case
the appropriate storage directory for the beacon
or tbtc application was missing. Here we check
whether the storage directory exists, and we
create a fresh one in case it is missing.

Ensure existence of application storage directory

---

solidity-v1/dashboard/src/components/threshold/AuthorizeThresholdContracts.jsx
solidity-v1/dashboard/src/reducers/threshold-authorization.js
solidity-v1/dashboard/src/services/threshold-authorization.service.js

Backport of: https://github.com/keep-network/keep-core/pull/3023
Removes stakes that are cancelled (while in initialization period) from
threshold authorization table. Also disable the `Authorize and Stake` button for
the stakes that are in initialization period (and add tooltip informing about
why it is disabled).

[Backport] Remove specific stakes from t auth data

---

.git-blame-ignore-revs
solidity-v1/dashboard/src/lib/keep/keep-to-t-staking/index.js
solidity-v1/dashboard/src/services/tokens-page.service.js

Backport of: [#3191 ](https://github.com/keep-network/keep-core/pull/3191)
There is a bug in Keep dashboard which blocked the user to unstake the
delegation from Keep if he unstaked all the tokens from T dashboard.
It was happening because normally user should not be allowed to unstake
when the stake is moved to T, but we were checking if it was moved there
wrongly. Previosly we examined the "Staked" events in T contract, and
if there were any we assumed that the staked is moved. However, there
can be a situation when the operator stake the keep tokens, and then
unstake them all and we didn't check any "Unstaked" events at all.
To fix this, instead of checking all the events, we will be calling
"stakes" method from TokenStaking contract, which will return all the
tokens staked in T …

[Backport] Fix blocked undelegate button when unstaking all tokens from t dahboard

---

Dockerfile

We set the entrypoint to `keep-client` only, so when running the docker
image we specify the remaining commands and arguments like `start
--config config.toml`, etc.
The current entrypoint was problematic as it required `-config /keepclient/config.toml` by default.

Set docker entrypoint to keep-client only

---

pkg/tecdsa/dkg/preparams.go

If the context passed to tss-lib `GeneratePreParamsWithContext` is done,
the interrupted function returns `nil` result. We do not want to wrap `nil`
inside `PreParams` structure so we should return `nil` early.
See #3197 
Refs #3161

Do not wrap nil inside PreParams in generateFn

---

cmd/flags.go
cmd/flags_test.go
cmd/start.go
config/_peers/goerli
config/_peers/mainnet
config/config.go
config/peers.go
config/peers_test.go
docs/development/cmd-help
go.mod
go.sum
scripts/start.sh

Depends on https://github.com/keep-network/keep-common/pull/99
The client requires a list of network peers to connect to. The list had to be configured by a user under the `ethereum.network.peers` property. To simplify running the node we will embed into the client the list of bootstrap peers supporting a given Ethereum network. 
When running the client a user can use one of the flags: `--mainnet`, `--goerli` or `--developer` to specify against which Ethereum network the client should be started. If non of the aforementioned flags is set, the client will assume `--mainnet`
If the list of peers in the config file under `ethereum.network.peers` is empty the client will resolve the default peers that were set in the client build.
The bootstrap peers configuration is expected to be provided …

Embed predefined bootstrap peers list into the client

---

pkg/generator/pool.go
pkg/generator/pool_test.go
pkg/tecdsa/dkg/dkg.go

Refs: https://github.com/keep-network/keep-core/issues/3161
The `Get` function exposed by the `generator.ParameterPool` type can hang on the `<-pp.pool` instruction in case the parameter pool is empty. Although this behavior is proper if the pool is working, it may cause deadlocks if the pool is stopped by the scheduler who is waiting for resume signals from clients which are in turn waiting for parameters that are supposed to be provided by the empty pool. Such a scenario occurred for tECDSA DKG. Here we aim to fix it by renaming `Get` to `GetNow` function which now uses a "get or fail" logic that provides an immediate result of a `GetNow` call without blocking.

Provide a cancel signal for the parameter pool getter

---

infrastructure/eth-networks/private-testnet/.gitignore
infrastructure/eth-networks/private-testnet/README.adoc
infrastructure/eth-networks/private-testnet/README.md
infrastructure/eth-networks/private-testnet/bundles/bundle-guide.adoc
infrastructure/eth-networks/private-testnet/scripts/init-provider.sh
infrastructure/eth-networks/private-testnet/scripts/new-bundle.sh

We need to generate a bundles for the parties that are joining our
Private Testnet.
The generated bundles contains a preinitialized Ethereum Account details. The account
receives a stake delegation to the `provider` account with authorized `beacon` and
`tbtc` application. This is a production-like experience for the Staking Providers,
where they will receive stakes from their customers.
We have a scripts to create a bundle and initialize the provider
account.
Please see README.md for more details.
Depends on https://github.com/keep-network/keep-core/pull/3211

Add Private Testnet bundles generator

---

cmd/cmd.go
cmd/ethereum.go
cmd/flags.go
cmd/flags_test.go
cmd/network.go
cmd/start.go
config/config.go
go.mod
go.sum
main.go
pkg/chain/ethereum/beacon/gen/cmd/BeaconSortitionPool.go
pkg/chain/ethereum/beacon/gen/cmd/RandomBeacon.go
pkg/chain/ethereum/beacon/gen/cmd/cmd.go
pkg/chain/ethereum/cmd.go
pkg/chain/ethereum/ecdsa/gen/cmd/EcdsaSortitionPool.go
pkg/chain/ethereum/ecdsa/gen/cmd/WalletRegistry.go
pkg/chain/ethereum/ecdsa/gen/cmd/cmd.go
pkg/chain/ethereum/tbtc/gen/cmd/Bridge.go
pkg/chain/ethereum/tbtc/gen/cmd/cmd.go
pkg/chain/ethereum/threshold/gen/cmd/TokenStaking.go
pkg/chain/ethereum/threshold/gen/cmd/cmd.go

With the current implementation, the `ethereum` commands fails with: `Error: unknown flag: --ethereum.url`.
We add `TraverseChildren` flag to the main command to let each of the subcommands define their flags.
The change mentioned above was not enough to make it work as the way we were reading the config with `config.ReadEthereumConfig` required flags to be provided, but the flags were defined on the parent `ethereum` command, which wasn't accessible in the context of the contract functions commands.
In https://github.com/keep-network/keep-common/pull/101 we modify the way we chain handle is initialized in the generated ethereum commands, and in this PR we align with that.
We defined a wrapper for the `cobra.Command` that also holds the Ethereum config that is used by the generated …

Updates to the CLI commands and flags

---

.github/workflows/contracts-ecdsa.yml

We no longer use `/solidity` in the name of the `keep-core` CI modules. We
already replaced the old name with the new one, but we missed one place where
the old name was still being used. This PR fixes that.

Fix getting upstream version of `random-beacon` package

---

Makefile

The client expects version and revision to be provided on build with
`-ldflags`.
Here we use the git commands to obtain the values.
Will be set to the latest tag on the branch, so when we
checked out a tag it will be set to the tag name, e.g. `v1.3.1`.
But if the current HEAD is not a tag it will produce a uniqe value
based on the latest tag, number of commits since the tag, and commit
hash, e.g. `v1.3.1-5816-g8219ddcf9`.
Read more: https://git-scm.com/docs/git-describe
Revision will be set simply to a short version of the HEAD commit hash.
Read more: https://git-scm.com/docs/git-rev-parse
The `make build` command will default to the `version` and `revision` values described above. However the values can be overwritten when calling the command by simply appending the arguments: `make …

Build client with passing the version and revision

---

.github/workflows/docs.yml

We're adding a step to the `docs.yml` workflow that publishes the comment under
the PR modifying the documents, after preview of the dosc gets published to the
GCP bucket. The comment contains a link to the `index.html` page containing the
table of contents.
Note: we need to have `./docs/index.adoc` file with right config inside to have
it working in the way I described it.
Ref: https://github.com/keep-network/keep-core/pull/3211

Add comment to PR-s modifying docs that links to the published preview

---

config/_peers/goerli
config/peers_test.go

We add a bootstrap node run by the Boar Network to the list of Goerli
peers.
To test it run `keep-client start` command with `--goerli` flag and verify if the client connects to the three bootstrap nodes.

Add Boar Network bootstrap node to Goerli peers

---

Dockerfile

The docker build was failing locally with errors:
```
(...)
=> ERROR [gobuild 24/24] RUN GOOS=linux go build -ldflags "-X main.version=$VERSION -X main.revision=$REVISION" -a -o keep-clie  1.1s
------
> [gobuild 24/24] RUN GOOS=linux go build -ldflags "-X main.version=$VERSION -X main.revision=$REVISION" -a -o keep-client ./ &&     mv keep-client /usr/local/bin:
\#32 1.096 pkg/tbtc/marshaling.go:9:2: no required module provides package github.com/keep-network/keep-core/pkg/tbtc/gen/pb; to add it:
\#32 1.096       go get github.com/keep-network/keep-core/pkg/tbtc/gen/pb
\#32 1.096 pkg/tecdsa/dkg/marshaling.go:10:2: no required module provides package github.com/keep-network/keep-core/pkg/tecdsa/dkg/gen/pb; to add it:
\#32 1.096       go get …
```

Add missing gen directories to the Dockerfile

---

solidity/random-beacon/tasks/initialize.ts

The argument that is expected by the `register` function is an operator
not owner. We fix it.

Fix random beacon registration hardhat task

---

docs/resources/docker-start-mainnet-sample
docs/resources/docker-start-testnet-sample

The container could be run in a detached mode so it's not quiting when
an user closes the terminal.

Add --detach to sample docker run commands

---

pkg/tecdsa/dkg/protocol.go
pkg/tecdsa/dkg/protocol_test.go
pkg/tecdsa/dkg/states.go

This PR is the follow-up PR to https://github.com/keep-network/keep-core/pull/3120.
Missing unit tests for `signingMember.verifyDKGResultSignatures` were added.
Additionally, made the function not return an error since it never fails and always returns a list of valid signatures.

Unit tests for DKG result signatures verification phase

---

pkg/tecdsa/signing/gen/pb/message.pb.go
pkg/tecdsa/signing/gen/pb/message.proto
pkg/tecdsa/signing/marshaling.go
pkg/tecdsa/signing/marshaling_test.go
pkg/tecdsa/signing/member.go
pkg/tecdsa/signing/message.go
pkg/tecdsa/signing/protocol.go
pkg/tecdsa/signing/protocol_test.go
pkg/tecdsa/signing/signing.go
pkg/tecdsa/signing/states.go

Refs: #3042
Here we implement the TSS round two for the tECDSA signing protocol. This round expects aggregate messages produced in TSS round one as input. Each input message consists of a public broadcast part and encrypted parts intended for specific participants. The TSS round two produces an aggregate message as output. The output message has only the encrypted point-to-point parts and, unlike the previous round output, does not contain the public broadcast part.
This PR is just a part of the entire work regarding the tECDSA signing test loop. Please refer to the description of https://github.com/keep-network/keep-core/issues/3042 for the full roadmap and the current status of the work. At this point, the next step will be introducing the third round of TSS signing.

tECDSA signing: TSS round 2

---

infrastructure/eth-networks/private-testnet/bundles/bundle-guide.adoc

We updated the default port for metrics to `9601` but missed the bundle
guide to be updated.

Update port in the Private Testnet bundle's metrics command

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml

We're switching to a different method of contracts verification on Etherscan.
Instad of veryfying contracts using `hardhat-deploy` plugin (which had problems
with verifying some contracts), we're doing that using
`@nomiclabs/hardhat-ethers` plugin. The use of new plugin was already added in a
different PR/commits. With that new plugin the contracts get verified during the
deployment step, this means that we don't need the
`contracts-etherscan-verification` job anymore in the CI workflows.
We're not removing the `hardhat-deploy` plugin, because it is still used for
contracts deployment.
Ref:
https://github.com/keep-network/keep-core/pull/3235

Remove jobs veryfying contracts on Etherscan

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml
solidity/ecdsa/deploy/01_deploy_ecdsa_sortition_pool.ts
solidity/ecdsa/deploy/02_deploy_dkg_validator.ts
solidity/ecdsa/deploy/03_deploy_wallet_registry.ts
solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock
solidity/random-beacon/deploy/01_deploy_reimbursement_pool.ts
solidity/random-beacon/deploy/02_deploy_beacon_sortition_pool.ts
solidity/random-beacon/deploy/03_deploy_beacon_dkg_validator.ts
solidity/random-beacon/deploy/04_deploy_random_beacon.ts
solidity/random-beacon/deploy/07_deploy_random_beacon_governance.ts
solidity/random-beacon/hardhat.config.ts
solidity/random-beacon/package.json
solidity/random-beacon/tasks/send-eth.ts
solidity/random-beacon/yarn.lock

@nomiclabs/hardhat-etherscan exposes verification functions for
Etherscan that are recommended by the hardhat team.
See https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-etherscan
Previously we were using `etherscan-verify` from `hardhat-deploy`
plugin, which had some problems with verification of e.g. `RandomBeacon`
and `WalletRegistry`.
TODO:
Depends on https://github.com/keep-network/hardhat-helpers/pull/31
Depends on https://github.com/keep-network/hardhat-helpers/pull/32

Use @nomiclabs/hardhat-etherscan for contract verification

---

pkg/tecdsa/signing/gen/pb/message.pb.go
pkg/tecdsa/signing/gen/pb/message.proto
pkg/tecdsa/signing/marshaling.go
pkg/tecdsa/signing/marshaling_test.go
pkg/tecdsa/signing/member.go
pkg/tecdsa/signing/message.go
pkg/tecdsa/signing/protocol.go
pkg/tecdsa/signing/protocol_test.go
pkg/tecdsa/signing/signing.go
pkg/tecdsa/signing/states.go

Depends on: https://github.com/keep-network/keep-core/pull/3242
Here we implement the TSS round five for the tECDSA signing protocol. This round expects simple broadcast messages produced in round four as input and produces a simple broadcast message as output.
This PR is just a part of the entire work regarding the tECDSA signing test loop. Please refer to the description of https://github.com/keep-network/keep-core/issues/3042 for the full roadmap and the current status of the work. At this point, the next step will be introducing the sixth round of TSS signing.

tECDSA signing: TSS round 5

---

pkg/tecdsa/signing/gen/pb/message.pb.go
pkg/tecdsa/signing/gen/pb/message.proto
pkg/tecdsa/signing/marshaling.go
pkg/tecdsa/signing/marshaling_test.go
pkg/tecdsa/signing/member.go
pkg/tecdsa/signing/message.go
pkg/tecdsa/signing/protocol.go
pkg/tecdsa/signing/protocol_test.go
pkg/tecdsa/signing/signing.go
pkg/tecdsa/signing/states.go

Depends on: https://github.com/keep-network/keep-core/pull/3243
Here we implement the TSS round six for the tECDSA signing protocol. This round expects simple broadcast messages produced in round five as input and produces a simple broadcast message as output.
This PR is just a part of the entire work regarding the tECDSA signing test loop. Please refer to the description of https://github.com/keep-network/keep-core/issues/3042 for the full roadmap and the current status of the work. At this point, the next step will be introducing the seventh round of TSS signing.

tECDSA signing: TSS round 6

---

pkg/tecdsa/signing/gen/pb/message.pb.go
pkg/tecdsa/signing/gen/pb/message.proto
pkg/tecdsa/signing/marshaling.go
pkg/tecdsa/signing/marshaling_test.go
pkg/tecdsa/signing/member.go
pkg/tecdsa/signing/message.go
pkg/tecdsa/signing/protocol.go
pkg/tecdsa/signing/protocol_test.go
pkg/tecdsa/signing/signing.go
pkg/tecdsa/signing/states.go

Depends on: https://github.com/keep-network/keep-core/pull/3246
Here we implement the TSS round seven for the tECDSA signing protocol. This round expects simple broadcast messages produced in round six as input and produces a simple broadcast message as output.
This PR is just a part of the entire work regarding the tECDSA signing test loop. Please refer to the description of https://github.com/keep-network/keep-core/issues/3042 for the full roadmap and the current status of the work. At this point, the next step will be introducing the eighth round of TSS signing.

tECDSA signing: TSS round 7

---

pkg/tecdsa/signing/gen/pb/message.pb.go
pkg/tecdsa/signing/gen/pb/message.proto
pkg/tecdsa/signing/marshaling.go
pkg/tecdsa/signing/marshaling_test.go
pkg/tecdsa/signing/member.go
pkg/tecdsa/signing/message.go
pkg/tecdsa/signing/protocol.go
pkg/tecdsa/signing/protocol_test.go
pkg/tecdsa/signing/signing.go
pkg/tecdsa/signing/states.go

Depends on: https://github.com/keep-network/keep-core/pull/3248
Here we implement the TSS round eight for the tECDSA signing protocol. This round expects simple broadcast messages produced in round seven as input and produces a simple broadcast message as output.
This PR is just a part of the entire work regarding the tECDSA signing test loop. Please refer to the description of https://github.com/keep-network/keep-core/issues/3042 for the full roadmap and the current status of the work. At this point, the next step will be introducing the ninth round of TSS signing.

tECDSA signing: TSS round 8

---

pkg/tecdsa/signing/states.go

Depends on: https://github.com/keep-network/keep-core/pull/3254
We performed benchmarks for each tECDSA signing phase. The table below shows the results for Apple M1 Max (10 cores):
| **benchmark**          | **single call duration** | **suggested phase blocks**      |
|------------------------|--------------------------|---------------------------------|
| BenchmarkTssRoundOne   |                 2.0800 s | (51 * 2.0800 / 12) * 120% ≈ 11  |
| BenchmarkTssRoundTwo   |                 1.1400 s | (51 * 1.1400 / 12) * 120% ≈ 6   |
| BenchmarkTssRoundThree |                 0.7600 s | (51 * 0.7600 / 12) * 120% ≈ 4   |
| BenchmarkTssRoundFour  |                 0.0002 s | (51 * 0.0002 / 12) * 120% ≈ 1   |
| BenchmarkTssRoundFive  | …

tECDSA signing: Phase duration tweaks

---

solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock
solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

New package of hardhat-helpers got published. It contains a change to the way how etherscan validation failures are being logged (the error gets printed, but process is not killed).

Bump `@keep-network/hardhat-helpers` to `0.6.0-pre.15`

---

pkg/tecdsa/dkg/dkg.go
pkg/tecdsa/dkg/member.go
pkg/tecdsa/dkg/member_test.go
pkg/tecdsa/dkg/protocol_test.go
pkg/tecdsa/dkg/states.go

Here we delay the moment when TSS pre-params are fetched from the pool. So far, we fetched them at the very beginning of tECDSA DKG which could drain the pool too early when, for example, some members are inactive from the start. This change moves the moment when pre-params are fetched to occur just after symmetric keys are generated and actual TSS is about to be started. Such a logic should preserve the pre-params up to the moment when two first phases (ephemeral key exchange and symmetric key generation) are done successfully so the chances that the group is healthy are higher. That should result in wiser pre-params management.

TSS pre-params: Fetch pre-params only after symmetric keys are generated

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml
solidity/ecdsa/deploy/06_deploy_wallet_registry_governance.ts

In the `Deploy contracts` step of the workflow we deploy contracts and verify them on Etherscan. We must configure `ETHERSCAN_API_KEY` variable, which is used to authenticate in Etherscan.
As part of this PR we also add Etherscan verification for `WalletRegistryGovernance` contract.

Etherscan verification fixes

---

pkg/tbtc/dkg.go
pkg/tbtc/dkg_test.go
pkg/tbtc/signing.go

The bump is useless as we now have a huge TSS pre-parameters pool and the client does not join the sortition pool until the pool is filled. Additionally, we aim for limiting the maximum number of DKG retries to a small number (probably 10) in the near future.

tECDSA DKG: Do not bump blocks delay every 100 attempts

---

solidity/ecdsa/contracts/EcdsaDkgValidator.sol
solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/libraries/EcdsaInactivity.sol
solidity/ecdsa/test/DKGValidator.test.ts
solidity/ecdsa/test/utils/dkg.ts
solidity/ecdsa/test/utils/inactivity.ts
solidity/random-beacon/contracts/BeaconDkgValidator.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/libraries/BeaconInactivity.sol
solidity/random-beacon/test/BeaconDkgValidator.test.ts
solidity/random-beacon/test/utils/dkg.ts
solidity/random-beacon/test/utils/inactivity.ts

Solidity documentation says:
> If you use `keccak256(abi.encodePacked(a, b))` and both `a` and `b` are dynamic types, it is easy to craft collisions in the hash value by moving parts of `a` into `b` and vice-versa. More specifically, `abi.encodePacked("a", "bc") == abi.encodePacked("ab", "c")`. If you use `abi.encodePacked` for signatures, authentication or data integrity, make sure to always use the same types and check that at most one of them is dynamic. Unless there is a compelling reason, `abi.encode` should be preferred.
During the course of the security review, for `EcdsaDkgValidator`, we stated that:
> Solidity does not provide `bytes64` type so the group public key is passed as `bytes` with the length enforced to `64` by the validation code. This way, both `result.groupPublicKey` …

Improvements to signature scheme

---

pkg/chain/ethereum/tbtc.go

THIS IS A WORKAROUND ONLY FOR THE EARLY STAGE OF THE CHAOSNET
Use `WalletRegistryContractName` instead of `RandomBeaconContractName`. DKG for the WalletRegistry depends on the RandomBeacon group creation. Currently the client doesn't publish a generated group to the chain as it works against a mocked chain implementation. Without a Beacon group published to the chain, the WalletRegistry's DKG cannot start. As a workaround for the first stage of the Chaosnet we use the RandomBeacon's address, as the client only wants to get to the sortition pool to select a group.

Mock WalletRegistry with RandomBeacon

---

config/peers_test.go

We don't want to execute an exact match validation as it makes adding and removing peers to/from the list hardher. We will just check for the peers that will be included in the list for sure.

Update unit test for peers to check if the list contains entry

---

pkg/net/libp2p/channel.go

Addressed the following go vet warning:
pkg/net/libp2p/channel.go:255:60: call of c.processContainerMessage copies lock value: github.com/keep-network/keep-core/pkg/net/gen/pb.BroadcastNetworkMessage contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
pkg/net/libp2p/channel.go:260:10: processContainerMessage passes lock by value: github.com/keep-network/keep-core/pkg/net/gen/pb.BroadcastNetworkMessage contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex

Do not copy the lock value in broadcast channel

---

cmd/start.go
docs/resources/client-start-help
pkg/generator/pool.go
pkg/generator/pool_test.go
pkg/metrics/metrics.go
pkg/tbtc/tbtc.go
pkg/tecdsa/dkg/dkg.go

We now expose `tbtc_pre_params_pool_size` in metrics instead of exposing pre-params pool size in diagnostics. This value fits the time series definition expected by Prometheus: streams of timestamped values belonging to the same metric and the same set of labeled dimensions. This will allow to aggregate and present this value easily in monitoring tools.
Before:
```
❯ curl localhost:9004/diagnostics
{
"client_info": {
"chain_address":"0x3365D0Ed0e526D3B1d8b417fc0fdE5b1cEF2f416",
"network_id":"16Uiu2HAm2TUrDJbpAyuVwhNRmdju6QyQG1Q4661CvCKNgtN9Z6NQ",
"revision":"c32b8b5f1",
"version":"v1.3.1-6245-gc32b8b5f1"
},
"connected_peers":[],
"tbtc":{
"preParamsPoolSize":509
}
} …
```

Pre-param metrics

---

infrastructure/kube/keep-test/keep-client/gen/data.yaml
infrastructure/kube/keep-test/keep-client/gen/schema.yaml
infrastructure/kube/keep-test/keep-client/gen/template.yaml
infrastructure/kube/keep-test/keep-client/keep-clients.yaml

We need to configure bootstrap nodes with publicly exposed announced addresses and make the service use a static IP predefined in GCP DNS config.

Set network properties for bootstrap nodes

---

solidity/ecdsa/deploy/01_deploy_ecdsa_sortition_pool.ts
solidity/ecdsa/deploy/02_deploy_dkg_validator.ts
solidity/ecdsa/deploy/03_deploy_wallet_registry.ts
solidity/ecdsa/hardhat.config.ts
solidity/ecdsa/package.json
solidity/ecdsa/test/WalletRegistry.Authorization.test.ts
solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts
solidity/ecdsa/test/fixtures/index.ts
solidity/ecdsa/yarn.lock

See #3297
Updating `sortition-pools` and `random-beacon` dependencies to the ones with Chaosnet support from https://github.com/keep-network/sortition-pools/pull/188.
Updated deployment scripts for ecdsa contracts to transfer the chaosnet owner to a named account.
Deactivated chaosnet in unit tests to avoid problems with adding operators to the pool

Chaosnet: update ecdsa contracts

---

go.mod
go.sum

The new version released has an improvement from https://github.com/bnb-chain/tss-lib/pull/203 we need to generate groups with 100 signing members locally for development.

Updated bnb-chain/tss-lib dependency to v1.3.5

---

solidity/ecdsa/tasks/initialize.ts
solidity/ecdsa/yarn.lock

~~Depends on https://github.com/keep-network/keep-core/pull/3301; Dependency update in `package.json` will be needed.~~
See https://github.com/keep-network/keep-core/pull/3297
See https://github.com/keep-network/sortition-pools/pull/188
After adding chaosnet feature to the sortition pool, we need to add an operator to the beta operators set during the operator initialization.

Hardhat task to add an operator to beta operators set for ecdsa

---

.github/workflows/npm-ecdsa.yml
solidity/ecdsa/package.json

This commit/PR adds the `tasks` folder to the list of files published in the NPM package, so that the tasks could be used by other projects. Modification of the content of the folder (on merge to `main`) will trigger a job publishing new package.
Refs:
https://github.com/keep-network/tbtc-v2/pull/411
https://github.com/keep-network/keep-core/pull/3306

Include `tasks` in the `ecdsa` package

---

.github/workflows/npm-random-beacon.yml

As the tasks stored in `solidity/random-beacon/tasks` get published in the NPM packages, we should trigger publishing of a new package when there are changes to the files in that directory (on merge to `main`).
Refs:
https://github.com/keep-network/keep-core/pull/3307
https://github.com/keep-network/tbtc-v2/pull/411

Trigger publish of a new package on changes to `tasks` folder

---

cmd/start.go
pkg/beacon/beacon.go
pkg/tbtc/tbtc.go

This PR adds modifications to the start of keep client: initializing Beacon and Tbtc is skipped for bootstrap nodes.
Bootstrap nodes are only used for network discovery and therefore do not participate in DKG.
Note that bootstrap nodes still validate connection with other peers.
The PR was tested manually.

Bootstrap node: skip initializing Beacon and Tbtc

---

solidity/random-beacon/contracts/BeaconDkgValidator.sol
solidity/random-beacon/contracts/Governable.sol
solidity/random-beacon/contracts/RandomBeacon.sol
solidity/random-beacon/contracts/RandomBeaconGovernance.sol
solidity/random-beacon/contracts/Reimbursable.sol
solidity/random-beacon/contracts/ReimbursementPool.sol
solidity/random-beacon/contracts/api/IRandomBeacon.sol
solidity/random-beacon/contracts/api/IRandomBeaconConsumer.sol
solidity/random-beacon/contracts/libraries/AltBn128.sol
solidity/random-beacon/contracts/libraries/BLS.sol
solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol
solidity/random-beacon/contracts/libraries/BeaconDkg.sol
solidity/random-beacon/contracts/libraries/BeaconInactivity.sol
solidity/random-beacon/contracts/libraries/BytesLib.sol
solidity/random-beacon/contracts/libraries/Callback.sol
solidity/random-beacon/contracts/libraries/Groups.sol
solidity/random-beacon/contracts/libraries/ModUtils.sol
solidity/random-beacon/contracts/libraries/Relay.sol
solidity/random-beacon/contracts/test/GovernableImpl.sol
solidity/random-beacon/hardhat.config.ts
solidity/random-beacon/package.json
solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
solidity/random-beacon/yarn.lock

Depends on https://github.com/threshold-network/solidity-contracts/pull/127
See https://github.com/keep-network/sortition-pools/pull/189
Fix Solidity version on 0.8.17 before the deployment.

Solidity 0.8.17

---

solidity/ecdsa/.gitignore
solidity/ecdsa/.prettierignore
solidity/ecdsa/deploy/01_deploy_ecdsa_sortition_pool.ts
solidity/ecdsa/deploy/03_deploy_wallet_registry.ts
solidity/ecdsa/deploy/04_approve_wallet_registry.ts
solidity/ecdsa/deploy/10_authorize_in_random_beacon.ts
solidity/ecdsa/deploy/11_transfer_reimbursement_pool_ownerhsip.ts
solidity/ecdsa/external/mainnet/T.json
solidity/ecdsa/external/mainnet/TokenStaking.json
solidity/ecdsa/hardhat.config.ts
solidity/random-beacon/.gitignore
solidity/random-beacon/.prettierignore
solidity/random-beacon/deploy/02_deploy_beacon_sortition_pool.ts
solidity/random-beacon/deploy/04_deploy_random_beacon.ts
solidity/random-beacon/deploy/05_approve_random_beacon_in_token_staking.ts
solidity/random-beacon/deploy/06_authorize_random_beacon_in_reimbursement_pool.ts
solidity/random-beacon/external/mainnet/T.json
solidity/random-beacon/external/mainnet/TokenStaking.json
solidity/random-beacon/hardhat.config.ts

This PR updates the script to handle mainnet contracts deployment as described in https://github.com/keep-network/keep-core/issues/3315.
```sh
export CHAIN_API_URL = <HTTP ENDPOINT URL>
export CONTRACT_OWNER_ACCOUNT_PRIVATE_KEY = <DEPLOYER PRIVATE KEY>
```
```sh
yarn deploy --network mainnet --tags ReimbursementPool
yarn deploy --network mainnet --tags BeaconSortitionPool
yarn deploy --network mainnet --tags BeaconDkgValidator
yarn deploy --network mainnet --tags RandomBeacon
yarn deploy --network mainnet --tags RandomBeaconAuthorize
yarn deploy --network mainnet --tags RandomBeaconGovernance
```
```sh
yarn deploy --network mainnet --tags EcdsaSortitionPool
yarn deploy --network mainnet --tags EcdsaDkgValidator
yarn deploy --network mainnet --tags WalletRegistry
yarn deploy --network …
```

Deployments scripts for mainnet

---

pkg/beacon/gjkr/protocol.go

Closes: https://github.com/keep-network/keep-core/issues/3292
Here we introduce a message deduplication logic for the beacon DKG. This mechanism is very similar to the one we have in ECDSA DKG. Deduplication of messages should protect against possible weird corner cases that may be
caused by duplicated messages and should make the protocol more efficient as it no longer loses time on processing duplicates.
Apart from that, we are making small improvements to the beacon DKG logging that introduces the member index in places that have not contained it so far.

Beacon DKG: Add message deduplication

---

Dockerfile

We were using alpine as a base for the binaries building which was causing some inconveniences when running the binary on ubuntu as it required `musl` library installation.
Alpine is using `musl` instead of `glibc`, so the binary build on alpine won't work right away on ubuntu.
In this PR we use a debian-based (bullseye) golang docker image to build the binaries.

Build linux binaries on debian based Docker image

---

pkg/beacon/node.go
pkg/tbtc/node.go

Hexstrings found in keep-client's logs were prepended with `0x`.

Prepend hexstrings with 0x

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml

In the `Use Sortition Pool forked contracts` step we wanted to upgrade the sortition-pool contracts to verioned stored on `test-fork` branch. Previously used command did not work correctly. Now it should do what we want.
Refs:
https://github.com/keep-network/keep-core/pull/3190
https://github.com/keep-network/sortition-pools/pull/186/files

Fix command for upgrade of forked @keep-network-sortition-pools

---

cmd/flags_test.go
pkg/tbtc/tbtc.go

We now do not take pre-params from the pool until we are sure we really need them. This means the target pool size can be much lower than the original value. This allows clients to register in the sortition pool faster.

Set default TSS pre-params target pool size to 1000

---

pkg/tbtc/dkg.go
pkg/tbtc/dkg_test.go

Even if that requirement is not forced by the on-chain contract, every ECDSA DKG participant must ensure it submits a DKG result that was signed by the quorum of the group. This way we are making sure the protocol was completed by a quorum of members that are ready to handle signature requests.
This change should soften the case when members fail at the last phase of DKG (finalization round) that is not followed by any communication round allowing for detection of such a failures. In that scenario, members who failed the last round do not produce the key material but, in the same time, are not excluded by other participants as misbehaved, so they can be selected for signing normally. As result, signature attempts including those members fail and the wallet needs more attempts in total to …

Ensure the ECDSA DKG result is signed by the quorum of group members

---

infrastructure/kube/keep-test/keep-client/gen/template.yaml
infrastructure/kube/keep-test/keep-client/keep-clients.yaml

Here we tweak the k8s manifests of the private testnet clients. Basically, this change is about:
- Setting `tbtc.keyGenerationConcurrency` to `2` in order to limit CPU competition between clients running on the same VM which often results in other processes starvation.
- Setting resource requests that reflect the actual resource consumption. Worth noting that the ultimate value of `resources.request.cpu` should be `2000m` but given the current cluster specification we can set `1500m` at most. Otherwise, we'll end up with unschedulable pods.

Tweak testnet clients Kubernetes manifests

---

pkg/beacon/node.go
pkg/sortition/sortition.go
pkg/tbtc/node.go

Two small log tweaks for Chaosnet 0
[Log problems with selecting group on warn level](https://github.com/keep-network/keep-core/commit/c75f8879285e8365120aaa747e33fe2061a8a41a)
We should consider switching this log to Errorf when the Chaosnet 0 phase is
completed and results are submitted to the chain. To let the operators join the
pool, the dev team will keep unlocking it via DKG timeout from time to time.
During the period pool is unlocked, selecting the group will not work.
[Do not log the status of sortition pool reward eligibility check](https://github.com/keep-network/keep-core/commit/91cd4075fc78b3324603edff4947c29684fd89f8)
We should uncomment this log once the rewards get allocated via the sortition
pool. We do not want to confuse the operators not meeting the requirements for …

Log tweaks

---

Makefile
cmd/flags_test.go
pkg/chain/ethereum/tbtc/gen/gen.go

The target should be used for mainnet client building. To run the build process execute:
```
make mainnet
```
The command will download contracts artifacts, generate the bindings and other go code and build the client.
`tbtc` package is not yet used by the client for the current milestone. For now, contracts from `keep-core` package are enough (key generation, signing). The contracts were not yet migrated on mainnet so the build process for mainnet cannot complete. We remove tbtc NPM package part of the code generator to let the client build for mainnet. The commit d3a67ffce6498ee75085959e87c5ded8a888695c  should be reverted when adding integration with `Bridge` contract.

Client build mainnet

---

config/_peers/mainnet
config/peers_test.go

Boar Network is running two bootstrap nodes that we want to start the
mainnet network with.

Add Boar Network's bootstrap nodes to mainnet peers list

---

pkg/net/libp2p/libp2p.go

Closes https://github.com/keep-network/keep-core/issues/3218.
This PR adds a check for the keep-client's own address on the bootstrap peer list.
If own address is found, it is ignored and the bootstrapping continues.
This change prevents a constantly appearing warning in keep-client's logs.

Made keep-client exclude own address from bootstrap peer list

---

Makefile

This is a change to Makefile to do not regenerate cmd-help as a part of the release. This is needed because of a problem with default value for key generation concurrency flag. The value depends on the machine on which the file is generated and it should default to the number of cores on the host machine. This is a temporary workaround and once we fix the problem with code generation, we should be able to switch back the order.

Run cmd-help after release when making all

---

pkg/beacon/dkg/result/signing.go
pkg/tbtc/tbtc.go
pkg/tecdsa/dkg/protocol.go

Closes https://github.com/keep-network/keep-core/issues/3355
This PR fixes some minor logging issues:
- removes unnecessary space from logs
- makes a hex-string be prepended with `0x`   
Tested the hex-string printing locally:
```
2022-10-11T19:41:35.207+0200    INFOkeep-tbtc       tbtc/tbtc.go:129   signature of message [0xd12ef03bf4a6f3d6dcc5fa8dc2d98d71b3f318d7fd5eed8deae4efaa539cab4a] requested from wallet [0x04e14cbd9eb98da739351c087c78dbbb8f6e42e670e1cd4904e41dbac6e06f41e6348b5ef743feb5f5ad91549942075449d6fbadec2691e8f24d20763580210a9c] at block [1600]
```
The `signature of message` part contains a hex-string prepended with `0x`.

Logging fixes

---

pkg/net/local/broadcast_channel.go
pkg/net/local/broadcast_channel_test.go
pkg/protocol/faststate/faststate.go
pkg/protocol/faststate/faststate_test.go
pkg/protocol/faststate/machine.go
pkg/protocol/faststate/machine_test.go
pkg/protocol/state/machine.go
pkg/protocol/state/state.go

Package `faststate` contains a generic state machine implementation that is meant to be used with interactive protocols which do not require a strict synchronization mechanism between protocol members. The synchronization is based on an signal from each participant that they are ready to proceed to the next step when, for example, they received all the necessary information from all the other participants.
This approach allows for faster execution of protocols but has strict requirements regarding the implementation of states.
The context passed to `faststate.NewMachine` must be active as long as the result is not published to the chain or until a fixed time for the protocol execution has not passed.
The context is used for the retransmission of messages and all protocol participants must …

Fast state machine

---

docs/registration.adoc

Instead of linking to the Contracts Addresses main page, we link to the subpage dedicated to Mainnet contracts Addresses. We also remove lo longer valid TODO.

Fix the link for Mainnet Contracts Addresses

---

pkg/net/net.go
pkg/protocol/state/state.go
pkg/tecdsa/signing/states.go

Refs: https://github.com/keep-network/keep-core/issues/3366
Depends on: #3385
Here we aim to abstract some common patterns used within tECDSA signing. The goal is to limit code duplication between protocols and have the generic things on the right abstraction level. Specific changes are described below.
A common scenario occurring during the work with `net.Message` and `state.BaseAsyncState` is extracting message payloads of a given type from the history, and ensuring their uniqueness using the sender as key. So far, this logic was defined in the tECDSA signing protocol code but, we noticed it should live on a higher abstraction level to avoid duplicating it across different protocols. That said, we decided to make it generic and move to the `pkg/state`. This way, specific protocols only …

Abstract common patterns used within tECDSA signing 

---

infrastructure/kube/keep-prd/monitoring/prometheus/prometheus-deployment.yaml
infrastructure/kube/keep-test/monitoring/prometheus/prometheus-deployment.yaml

1 second was too agressive, as some nodes were failing scanning due to
long response time.

Increase scan timeout to 3 seconds

---

pkg/internal/interception/interception.go
pkg/net/libp2p/channel.go
pkg/net/local/broadcast_channel.go
pkg/net/net.go
pkg/net/retransmission/retransmission.go
pkg/net/retransmission/retransmission_test.go
pkg/net/retransmission/strategy.go
pkg/net/retransmission/strategy_test.go

Refs: #3366
So far, the broadcast channel used a simple retransmission strategy that triggered a new retransmission on every new tick. Such an aggressive approach turned out to be not suitable for all use cases. Specifically, this approach tends to cause network congestion if a large amount of messages is retransmitted for a long time. To make the retransmission mechanism more flexible, here we introduce the way to customize it through strategies. We are also adding an implementation of a backoff strategy that decreases its retransmission frequency over time in an exponential way.

Introduce broadcast channel retransmission strategies

---

.dockerignore
.github/workflows/client.yml
Dockerfile

The current version of Dockerfile is split into a couple of layers. The
top layers are responsible for Go code generators. However, part of this
generation includes the extraction of addresses from three contracts:
TokenStaking, RandomBeacon, and WalletRegistry. Addresses are written in
the files that the client will later use during the startup.
But the following `COPY` command that copies the root dir to a Docker working dir
overwrites these 3 files with empty content. To mitigate the issue, we
can exclude these 3 files from the Docker context and they won't
overwrite addresses as part of `COPY ./ $APP_DIR/` command.

Fixing client docker image

---

infrastructure/kube/keep-prd/monitoring/grafana/grafana-deployment.yaml
infrastructure/kube/keep-test/monitoring/grafana/grafana-deployment.yaml

Grafana had problems with connecting to Prometheus, returning meaningless errors. Upgrading it to the latest version fixed the issue.

Upgrade grafana to v9.2.5

---

pkg/protocol/state/async_machine.go

The asynchronous state machine accepts a `ctx` parameter that is used to control both message retransmission and message handling routines. The state machine's `Execute` method sets up the message handling process by registering a buffered message handler in the broadcast channel and triggering a message processing loop that takes messages from that handler and passes them to specific states.
It may happen that the state machine completes before their `ctx` is done. In that case, the message handler remains registered in the channel until the `ctx` is canceled but, at the same time, the machine's message processing loop is stopped and no longer drains the message handler's buffer. Such a situation causes an overflow of the message handler's buffer as incoming messages are still passed to …

Async machine: Prevent dangling message handlers

---

pkg/net/libp2p/channel.go
pkg/net/libp2p/channel_test.go

Refs #3419
During the tests of the code orchestrating tECDSA signing in #3404, we realized some buffers get full and the broadcast channel keeps writing to them even though the receiver is no longer alive. This was fixed in #3418 by introducing an additional context in the asynchronous state machine that unregisters the handler if the state machine (receiver) exits sooner than the context. This has fixed the problem on the receiver side but we still need to fix the problem on the producer side. And this is what this PR is doing.
A separate goroutine controls the lifecycle of the handler. The message handler is removed from the channel if the context is done. This logic is placed in a separate goroutine because the call to `handleWithRetransmission` is blocking and we do not want to wait …

Control the broadcast channel lifecycle in a separate goroutine

---

pkg/protocol/announcer/announcer.go
pkg/protocol/announcer/announcer_test.go
pkg/tbtc/node.go
pkg/tbtc/signing.go

Closes #3419
Depends on #3422
During the tests of the code orchestrating tECDSA signing in, we noticed the announcer's buffer sometimes gets full and the messages are dropped with the famous "message handler is too slow" warning. It turns out that the problem lies in the size of the buffer used by the announcer. Before a message in which the announcer is not interested is dropped, it is buffered in this channel. This also includes retransmissions from the previous signing protocols because the retransmission cache filter is scoped to the given `Recv` handler:
```
func WithRetransmissionSupport(delegate func(m net.Message)) func(m net.Message) {
mutex := &sync.Mutex{}
cache := make(map[string]bool)
// (...)
}
```
The announcer's buffer size has been increased to 512 elements, just like the …

Increase announcer's receiver buffer to 512

---

pkg/beacon/dkg/dkg.go
pkg/beacon/dkg/dkg_test.go
pkg/beacon/dkg/result/conversion.go
pkg/beacon/dkg/result/conversion_test.go
pkg/beacon/gjkr/member.go
pkg/beacon/gjkr/protocol.go
pkg/beacon/gjkr/protocol_accusations_test.go
pkg/beacon/gjkr/protocol_reconstructions_test.go
pkg/protocol/group/group.go
pkg/protocol/group/group_test.go
pkg/protocol/group/message_filter.go
pkg/protocol/group/message_filter_test.go
pkg/tbtc/dkg.go
pkg/tbtc/dkg_test.go
pkg/tecdsa/dkg/member.go
pkg/tecdsa/dkg/protocol.go
pkg/tecdsa/dkg/result.go
pkg/tecdsa/dkg/states.go
pkg/tecdsa/signing/member.go
pkg/tecdsa/signing/protocol.go
pkg/tecdsa/signing/states.go

Refs: https://github.com/keep-network/keep-core/issues/3368
Depends on https://github.com/keep-network/keep-core/pull/3426
Adjusted the nomenclature to be about `memberIndex` not `memberID`. See: https://github.com/keep-network/keep-core/pull/3112#discussion_r933165274
We could live with this inconsistency but we start integrating with ECDSA smart contracts and the member ID means something different on-chain. In the contract, member ID is the operator ID assigned by the sortition pool.
This had to be cleaned up in the client before the integration happens.

DKG saga, part 3: Adjusted the memberID / memberIndex nomenclature

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml

The `ubuntu-latest` runner used by us to run GH Actions jobs is getting migrated
from Ubuntu `20.04` to `22.04`
(https://github.com/actions/runner-images/issues/6399). The `22.04` version does
not work with the config of the `actions/setup-python@v4` action which we use
in the jobs running slither. We were getting following failures in workflows:
```
Version 3.8.5 was not found in the local cache
Error: Version 3.8.5 with arch x64 not found
The list of all available versions can be found here:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
Based on
https://github.com/actions/setup-python/issues/555#issuecomment-1337036543, we
should update Python version to `3.9.12` or higher. Or we could configure job to
run on the hardcoded Ubuntu 20.04 runner. …

Fix slither job by upgrading Python to 13.10.8

---

Makefile
cmd/flags_test.go
go.mod
go.sum
pkg/chain/ethereum/tbtc/gen/gen.go

This PR reverts commit d03a33a630026dde1d7d7c822f725f7716aa9f8a.
We are getting ready to deploy and publish TBTCv2 contracts (Bridge) and the client requires them to generate bindings.
We bump up version of keep-common dependency to fix bindings generation for the Bridge contract.
Depends on https://github.com/keep-network/keep-common/pull/110

Generate bindings for TBTC contracts

---

.pre-commit-config.yaml
scripts/macos-setup.sh

[The Go's `lint` tool got deprecated](https://github.com/golang/lint) some time ago. It can be replaced by the `staticcheck` tool, which offers similar functionalities.
In the `keep-network/keep-core` project we've previously added a GH Action job that runs the `staticcheck` tool as part of the CI. We want now to also add it to the Go pre-commit hooks, so that developers could be informed about the problems in their code before they push it to the remote repository. In a separate PR we've adding a new custom hook to the `keep-network/pre-commit-golang` repository. In this PR we're changing the config to use that new custom hook. We're also removing deprecated `lint` hook from the config.
Apart from modifyng the `.pre-commit-config.yaml` we're also updating the `macos-setup.sh` script - so …

Add `staticcheck` to Go pre-commit hooks

---

infrastructure/kube/keep-test/keep-client/gen/template.yaml
infrastructure/kube/keep-test/keep-client/keep-clients.yaml

This PR changes the client storage size to 4096Mi to mitigate the "no space left" issue when storing data on disk.

Increasing storage size of keep-client-0 to circa 5gb

---

.github/workflows/contracts-random-beacon.yml
.github/workflows/npm-random-beacon.yml
solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

Previously we'we been using `v14` of Node.js. But there are several newer
versions available. The highest version supported by the `actions/setup-node@v3`
action is `v18`. We want to upgrade from `v14` across all our modules, because
this version started to cause some problems (failing `yarn upgrade` commands)
with some of the modules.
We're also updating version of a downstream `@threshold-network/solidity-contracts`
dependency. This is because we want to always use this version (or higher), as
that version was built on Node.js v18 and v18 is what we want to be using for
building the `random-beacon` from now as well.
In this PR we're updating workflows and dependency configs relating to `random-beacon`. The
update of `ecdsa` workflows will happen in a separate PR.
Ref: …

Upgrade version of Node used in CI to v18

---

README.adoc
solidity/ecdsa/README.adoc
solidity/random-beacon/README.adoc

The `shields.io` have changed the syntax of the endpoints generating status badges, resulting in showing false failure status when old syntax was used. Updating the READMEs to use the new syntax.
Read more: https://github.com/badges/shields/issues/8671.
Refs:
https://github.com/keep-network/keep-common/pull/112
https://github.com/keep-network/sortition-pools/pull/198
https://github.com/keep-network/tbtc-v2/pull/429
https://github.com/keep-network/coverage-pools/pull/221

Fix badges after change in shields.io syntax

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/npm-ecdsa.yml
solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock

Previously we've been using `v14` of Node.js. But there are several newer
versions available. The highest version supported by the `actions/setup-node@v3`
action is `v18`. We want to upgrade from `v14` across most of our modules,
because this version started to cause some problems (failing `yarn upgrade`
commands) with some of the modules.
We're also updating version of the downstream `@threshold-network/solidity-contracts`
and `@keep-core/random-beacon` dependencies. This is because we want to always
use this version (or higher), as that version was built on Node.js v18 and v18
is what we want to be using for building the `ecdsa` from now on as well.
Refs:
https://github.com/threshold-network/solidity-contracts/pull/132
https://github.com/keep-network/keep-core/pull/3445

Upgrade version of Node used in CI to `v18`

---

solidity/ecdsa/package.json
solidity/ecdsa/yarn.lock
solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

We can't use `@tenderly/hardhat-tenderly` in versions `1.4.x` and higher on Node.js `v14`, as those `1.4.x` versions introduce dependency to `tslog` package, which is incompatible with `v14` of Node.js (works on `v16` or higher). We use Node `v14` in some of the projects having the `@keep-network/random-beacon` and `@keep-network/ecdsa` as their dependency.
There are also some problems with deployment scripts (possibly fixable) on `@tenderly/hardhat-tenderly` in versions `1.2.x`, so we're limiting the allowed versions to `<1.2.0`.
Refs:
https://github.com/threshold-network/solidity-contracts/pull/134
https://github.com/keep-network/tbtc-v2/pull/440
https://github.com/keep-network/coverage-pools/pull/222

Change SemVer range for `@tenderly/hardhat-tenderly` dependency

---

solidity/ecdsa/contracts/WalletRegistry.sol

Closes: #3455
We need to adjust the DKG result submission timeout on the contract side to reflect the time taken by the off-chain part of the protocol. We make a direct change in the contract to cover testnet and development environments. The mainnet contract is already deployed so it requires a manual update (added that as a prerequisite to https://github.com/keep-network/tbtc-v2/issues/438)

Update the DKG result submission timeout

---

solidity/ecdsa/deploy/06_deploy_wallet_registry_governance.ts
solidity/ecdsa/hardhat.config.ts

Refs: https://github.com/keep-network/tbtc-v2/issues/456
Here we make some adjustments to increase the flexibility of testnet deployments. The main goal is to have a short test feedback cycle that will allow to check multiple scenarios using different combinations of contract's governance parameters. In order to achieve that, we must be able to change governable parameters quickly. This change sets a 60-second governance delay for testnet and passes the governance over testnet contracts to an address controlled by the dev team.

Adjust deployment scripts for testnet

---

pkg/tbtc/chain_test.go
pkg/tbtc/dkg_submit.go
pkg/tbtc/dkg_submit_test.go
pkg/tbtc/dkg_test.go

Closes: #3461
Here we add an on-chain validation of the submitted DKG result. This way, honest clients may abort the submission of an invalid result and avoid slashing.

Validate submitted DKG result

---

solidity/ecdsa/hardhat.config.ts

This PR adds the missing addresses for `governance` and `chaosnetOwner` in random-beacon hardhat configuration.
The addresses are the same as in ecdsa configuration.

Add governance and chaosnetOwner addresses for goerli

---

pkg/chain/ethereum/tbtc.go

The original estimate made by the `go-ethereum` library for the `WalletRegistry.approveDkgResult` turned out to be too low. The root cause of the problem is probably related with the reimbursement pool. To overcome that problem, we add a 20% margin to the original gas limit estimate.

Add gas limit margin for approve DKG result calls

---

go.mod
go.sum
pkg/chain/ethereum/beacon/gen/contract/BeaconSortitionPool.go
pkg/chain/ethereum/beacon/gen/contract/RandomBeacon.go
pkg/chain/ethereum/ecdsa/gen/contract/EcdsaSortitionPool.go
pkg/chain/ethereum/ecdsa/gen/contract/WalletRegistry.go
pkg/chain/ethereum/tbtc/gen/contract/Bridge.go
pkg/chain/ethereum/tbtc/gen/contract/LightRelay.go
pkg/chain/ethereum/threshold/gen/contract/TokenStaking.go

A client might experience some connectivity issues with Alchemy / Infura and will retry to reconnect. These attempts shouldn't be logged at the Error level as they don't require any actions from the operator.

Events retry log level Errof->Warnf

---

SECURITY.adoc

Depends on https://github.com/threshold-network/solidity-contracts/pull/137
This version is the same as one published in `threshold-network/solidity-contracts `repository. It may need further updates when Immunefi Bug Bounty program is established. If you have any comments to the Threshold version of `SECURITY.txt` please comment at https://github.com/threshold-network/solidity-contracts/pull/137 and I'll backport changes here.

Updating SECURITY.txt to the common Threshold version

---

SECURITY.adoc

Updated SECURITY.adoc to use adoc format for marking headers.
No changes to the text.

Use adoc formatting for headers

---

infrastructure/kube/keep-prd/tbtc-v2-monitoring/.env.secret
infrastructure/kube/keep-prd/tbtc-v2-monitoring/README.md
infrastructure/kube/keep-prd/tbtc-v2-monitoring/kustomization.yaml
infrastructure/kube/keep-test/tbtc-v2-monitoring/.env.secret
infrastructure/kube/keep-test/tbtc-v2-monitoring/README.md
infrastructure/kube/keep-test/tbtc-v2-monitoring/kustomization.yaml
infrastructure/kube/templates/tbtc-v2-monitoring/README.md
infrastructure/kube/templates/tbtc-v2-monitoring/kustomization.yaml
infrastructure/kube/templates/tbtc-v2-monitoring/tbtc-v2-monitoring-cronjob.yaml

Refs: https://github.com/keep-network/pm/issues/33
Depends on: https://github.com/keep-network/tbtc-v2/pull/535
Here we introduce Kubernetes deployment for `tbtc-v2-monitoring` component introduced in https://github.com/keep-network/tbtc-v2/pull/526. We are deploying it as a cronjob triggered every 5 minutes. The configuration structure leverages [Kustomize's bases and overlays](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#bases-and-overlays) in order to keep a clear structure and avoid duplication. That means we have:
- A base configuration of the cronjob defined in `infrastructure/kube/templates/tbtc-v2-monitoring` that is referenced by environment-specific configurations (overlays)
- A `keep-prd` production overlay defined in …

Kubernetes deployment for tBTC v2 chain events monitoring tool

---

.github/workflows/client.yml

As explained in
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/, the `set-output` and `save-state` GH Action commands will become deprecated after 31st May 2023. In our `Client` workflow we use some actions that use those commands in their code. All those actions already published new versions which do not use the problematic code. We're now updating our workflow to use the latest versions of those actions.
Ref:
https://github.com/threshold-network/token-dashboard/pull/312

Update actions using deprecated commands

---

pkg/tecdsa/signature.go
pkg/tecdsa/signature_test.go

The previous solution used to convert R and S values to string was outputing inproperly formatted hex value that was not even. With this change we ensure the values are encoded to even hex string prefixed with 0x.
Closes: https://github.com/keep-network/keep-core/issues/3489

Update signature to string formatting

---

pkg/chain/ethereum/bitcoin_difficulty.go

This PR fixes an error in the Bitcoin difficulty maintainer: the base chain pointer needs to be stored inside the Bitcoin difficulty chain.

Passed base chain pointer into maintainer

---

cmd/flags_test.go
configs/config.toml.SAMPLE

`KeyGenConcurrency` is not recognized properly when used in a configuration. The proper name is `KeyGenerationConcurrency`.
This commit replaces all occurrences of `KeyGenConcurrency` to `KeyGenerationConcurrency`.

Fix name of argument `KeyGenerationConcurrency`

---

pkg/chain/ethereum/tbtc.go
pkg/chain/ethereum/tbtc/gen/abi/WalletCoordinator.go
pkg/chain/ethereum/tbtc/gen/cmd/WalletCoordinator.go
pkg/chain/ethereum/tbtc/gen/contract/WalletCoordinator.go
pkg/tbtc/chain.go
pkg/tbtc/chain_test.go
pkg/tbtc/tbtc.go
pkg/tbtc/wallet.go

Refs #3512 
With the existing, pretty computationally-expensive tECDSA signing algorithm, [we would prefer](https://github.com/keep-network/keep-core/pull/3521#discussion_r1173652203) not to execute heartbeats at the same time as other wallet actions (sweeping, redemptions, moving funds). Moreover, we would prefer not to execute heartbeats from multiple wallets at the same time.
Such coordination is complicated off-chain for the same reason as the coordination of sweeps and redemptions. We could - as we do now - execute heartbeats at fixed hours but it does not help with coordination between heartbeats and sweeps. Also, it does not solve the problem of multiple heartbeats simultaneously.
For this reason, in https://github.com/keep-network/tbtc-v2/pull/609, the heartbeat has been made a …

Heartbea(s)t part I: The new event listener

---

config/category.go

This is needed to pass the `bitcoin.electrum` config through flags. Without that, the client exists with the `unknown flag` error.

Add missing `BitcoinElectrum` flag category for `start` command

---

infrastructure/kube/keep-test/monitoring/monitoring-ingress.yaml

We don't need to expose the Prometheus instance publicly on keep-test. We use it as Grafana's data source.
https://monitoring.test.threshold.network/prometheus/ is no longer accessible.

Make prometheus internally exposed on keep-test

---

infrastructure/kube/keep-test/keep-client/gen/template.yaml
infrastructure/kube/keep-test/keep-client/keep-client-config.yaml
infrastructure/kube/keep-test/keep-client/keep-clients.yaml

This change points the `keep-test` clients to the testnet ElectrumX instance. This allows the clients to interact with the Bitcoin testnet.

Connect `keep-test` clients to testnet ElectrumX instance

---

cmd/flags.go
cmd/flags_test.go
cmd/maintainer.go
config/config_test.go
pkg/chain/ethereum/bitcoin_difficulty.go
pkg/chain/ethereum/ethereum.go
pkg/maintainer/bitcoin_difficulty.go
pkg/maintainer/bitcoin_difficulty_test.go
pkg/maintainer/chain.go
pkg/maintainer/chain_test.go
pkg/maintainer/config.go
pkg/maintainer/maintainer.go
test/config.json
test/config.toml
test/config.yaml

This PR updates the logic of the Bitcoin difficulty maintainer, so that relay retargetting can be performed either via  `LightRelayMaintainerProxy` or directly via `LightRelay`. The decision if based on the value of the  `disableBitcoinDifficultyProxy ` flag. 
By default, this flag is set to false and `LightRelayMaintainerProxy` is used. If set to true, retargets are done directly via `LightRelay`.

Bitcoin difficulty maintainer logic update

---

pkg/tbtc/deposit.go

The `hex.DecodeString` expects an unprefixed hex string while the `d.Depositor` contains the `0x` prefix by default. To make it work, we need to trim that prefix.

Fix deposit script function

---

pkg/tbtc/deposit_sweep.go
pkg/tbtc/signing.go

Refs: https://github.com/keep-network/keep-core/issues/3512
Here we tweak some loggers used during the deposit sweep process.

Deposit sweep log tweaks

---

pkg/bitcoin/electrum/electrum.go

Refs: https://github.com/keep-network/keep-core/issues/3512
So far, the `Broadcast` method of our Electrum client tried to broadcast the transaction as a UTF string
(`client.BroadcastTransaction(ctx, string(rawTx))`). That was wrong as the client expects a hexadecimal string. Here we are fixing that by building `rawTx` as `hex.EncodeToString(transaction.Serialize())` which produces a proper hex of the raw transaction.

Fix broadcast function in Electrum implementation

---

pkg/tbtc/deposit_sweep.go
pkg/tbtc/deposit_sweep_test.go

Refs: https://github.com/keep-network/keep-core/issues/3512
The pre-signing delay was introduced to compensate the time spent for proposal validation. However, during testing, it turned out the time spent for validation is negligible thus the delay can be safely removed. Potential anomalies are supposed to be handled by the signing announcement phase so, an additional pre-signing delay is redundant. This change should speed up the deposit sweep action by approximately `2 min * N`, where `N` is the number of swept deposits.

Remove pre-signing delay from deposit sweep action

---

pkg/bitcoin/chain.go
pkg/bitcoin/chain_test.go
pkg/bitcoin/electrum/electrum.go
pkg/maintainer/bitcoin_chain_test.go
pkg/tbtc/bitcoin_chain_test.go
pkg/tbtc/deposit_sweep.go

Refs: https://github.com/keep-network/keep-core/issues/3512
The `Bridge` contract enforces that all BTC transactions produced by the given wallet form a sequence and refer to each other. If a wallet violated this rule, such transactions would not be SPV-proved to the `Bridge` and would be used to create undefeatable fraud challenges against the wallet. That leads to funds loss and wallet punishment. The current state of things is vulnerable to this problem as there are several unlikely corner cases that are not covered on the client side. 
This changeset aims to fix the aforementioned problem by introducing the `ensureWalletSyncedBetweenChains` check at the beginning of the sweep action. This check allows for the sweep action only if the wallet state on the BTC chain is correctly …

Ensure wallet BTC state is reflected on the host chain before sweeping

---

pkg/chain/ethereum/bitcoin_difficulty.go

This PR increases the gas limit for calls to `LightRelayMaintainerProxy`'s `retarget` function.
The gas limit used is the gas estimate increased by 20%. 
The transactions would revert if the default limit was used.

Increase the gas limit for retarget with refund

---

go.mod
go.sum
pkg/bitcoin/electrum/electrum_integration_test.go

Depends on: https://github.com/keep-network/go-electrum/pull/1
In this PR we update Electrum client dependency and integration tests to cover changes introduced in
https://github.com/keep-network/go-electrum/pull/1.
The go-electrum client no longer fails error unmarshaling. Also electrum
server implementations return specific error messages that we want to
compare in tests.
To run the integration test execute: `go test -v -tags=integration ./pkg/bitcoin/electrum`.
`go.mod` was pinned to a commit from a PR branch, we need to update it after the changes in https://github.com/keep-network/go-electrum/pull/1. are merged to master.

go-electrum client dependency upgrade

---

go.mod
go.sum

This is a follow-up for https://github.com/keep-network/keep-core/pull/3567.
We pin go-electrum dependency to a commit hash from master after merging the https://github.com/keep-network/go-electrum/pull/1 PR.

Pin go-electrum dependency to master branch commit

---

infrastructure/kube/keep-prd/btc-difficulty/kustomization.yaml
infrastructure/kube/keep-prd/btc-difficulty/maintainer-statefulset.yaml

We update electrum url for keep-prod to the electrumx node that is running in our cluster.
The previous blockstream's server is very unstable and keeps dropping the connection which outputs a lot of warnings in logs.

Switch btc-difficulty electrum api url

---

cmd/flags.go
config/_electrum_urls/mainnet
config/_electrum_urls/testnet
config/config.go
config/electrum.go
config/electrum_test.go
configs/config.toml.SAMPLE
pkg/bitcoin/bitcoin.go

Closes: https://github.com/keep-network/keep-core/issues/3565
Here we add some default Electrum configs that can be used for Bitcoin mainnet and testnet networks in case the Electrum `URL` is not explicitly provided in the `bitcoin.electrum` section of the configuration file. In such a case, one of the default embedded configs is picked up randomly.

Embed Electrum configs for Bitcoin mainnet and testnet

---

config/_electrum_urls/mainnet
config/_electrum_urls/testnet
config/config.go
config/electrum.go
config/electrum_integration_test.go
config/electrum_test.go
pkg/bitcoin/electrum/electrum_integration_test.go

Blockstream's servers timeout session after 60 seconds of inactivity which
is much shorter than the expected 600 seconds (see: [Electrum Protocol Docs](https://electrumx-spesmilo.readthedocs.io/en/latest/environment.html#envvar-SESSION_TIMEOUT)).
To workaround connection drops and logs pollution with warnings, we reduce the
`KeepAliveInterval` for Blockstream's servers to less than 60 seconds.
We add an integration test to check the client can establish a connection to the embedded servers.
To run it execute:
```
go test -v -tags=integration ./config -run TestEmbeddedElectrumServerConnect_Integration
```
We add more servers to the Electrum Servers list.

Electrum servers list updates

---

cmd/start.go

In this PR we improve client initialization for the start command to reduce confusion.
The node header with the fancy ASCII art will print only after all the modules are initialized successfully.

Client initialization order juggle

---

pkg/tbtc/dkg_loop.go
pkg/tbtc/dkg_loop_test.go
solidity/ecdsa/contracts/WalletRegistry.sol

❗ This will require governance transaction to the `WalletRegistry` contract deployed on mainnet. This will be tracked in a separate issue.
Benchmarks with 4 clients on Applie M1 Max with 10 cores. Each client configured with key generation concurrency set to 2.
Before the recent changes
DKG duration | Round 2 duration
-- | --
0:17:24 | 0:15:32
0:16:51 | 0:14:38
0:17:46 | 0:15:34
0:17:18 | 0:15:38
0:17:39 | 0:15:42
After the recent changes
DKG duration | Round 2 duration
-- | --
0:28:38 | 0:25:39
0:28:31 | 0:25:24
0:29:26 | 0:26:05
0:29:06 | 0:25:45
0:28:47 | 0:25:19
0:28:10 | 0:25:09
0:28:30 | 0:25:22
0:29:06 | 0:25:16
0:28:21 | 0:25:18
0:28:55 | 0:25:29
0:28:06 | 0:25:12
0:29:20 | 0:26:15
0:29:22 | 0:26:31
0:29:19 | 0:26:09

Increase single DKG attempt timeout by 50 blocks

---

cmd/start.go
config/config.go
config/electrum.go
pkg/bitcoin/electrum/electrum.go
scripts/install.sh

Unless specified in the config, mainnet client binary selects the Electrum server from one of the preconfigured nodes. It is nice to know which server was selected, even for debugging purposes. Additionally, we should log both Bitcoin and Ethereum networks used by the client. Electrum server URL is printed to the logs only if it has been auto-selected. This approach is consistent with not logging Ethereum server URL at all given we expect it is passed in the configuration.
I snaked one more change in this PR: fixed the number of accounts requirement in `scripts/install.sh`. Given the recent changes in tbtc-v2 project, at least 11 accounts are required in the local Ethereum client keystore to deploy and initialize contracts.
The `v1Redeemer` [set in tbtc-v2 …

Print Electrum URL in the logs

---

infrastructure/kube/keep-prd/btc-difficulty/kustomization.yaml
infrastructure/kube/keep-prd/btc-difficulty/maintainer-statefulset.yaml

Switch to the latest version of the keep-client released under `v2.0.0-m3` tag.
This version has two changes affecting the k8s configuration:
- `--mainnet` flag got deprecated,
- electrum protocol is now included in the URL.
We also took a chance to define the electrum url in a dedicated config map, and simplified the URL to `electrumx.bitcoin` which is how kubernetes exposes the service internally.
We switched to tcp URL, as SSL is not working due to outdated certificate.

Update btc difficulty maintainer k8s config

---

infrastructure/kube/keep-test/keep-client/gen/template.yaml
infrastructure/kube/keep-test/keep-client/keep-client-config.yaml
infrastructure/kube/keep-test/keep-client/keep-clients.yaml

We align the configuration of keep clients running in keep-test with the latest changes:
- replace `--goerli` with `--tesnet` (https://github.com/keep-network/keep-core/pull/3583)
- include protocol in electrum url (https://github.com/keep-network/keep-core/pull/3582)

Align keep-clients in keep-test with m3 changes

---

.github/workflows/client.yml

We don't want to run electrum integration test for all Pull Requests, we are concerned only by specific set of files that may get change and affect the integration.

Run electrum integration tests only on detected changes

---

config/_electrum_urls/mainnet
config/_electrum_urls/testnet
config/electrum.go
config/electrum_test.go

The blockstream's electrums servers seems very unstable and causes a lot of noise in the logs, even after our optimizations we did in ba416cedb989b0eebc8768ec7fc56de662647803.
Closes: https://github.com/keep-network/keep-core/issues/3612

Remove public Blockstream server from the list of auto-selected servers

---

solidity/random-beacon/package.json
solidity/random-beacon/yarn.lock

Upgrading OZ version might result in different gas consumption by Keep contracts which lead to failing unit tests that check the gas consumption in certain scenarios. We should pin the OZ contracts to a specific version in order to avoid randomly failing tests.
The upgrade of OZ that broke unit tests was done by our dependebot in the following commit https://github.com/keep-network/keep-core/commit/3a14b3a671a301d9de486be08b50560b623c1c1a

Pinning OZ version to 4.7.3

---

.github/workflows/npm-ecdsa.yml
.github/workflows/npm-random-beacon.yml

We want to prevent the problem with generation of artifacts during execution of the `hardhat compile` command (part of `yarn deploy`). We saw in other project that sometimes command was not not generating expected artifacts. The problem is caused by the process silently quitting, which is related to the used version of Node (as described in https://github.com/NomicFoundation/hardhat/issues/3877). We've confirmed the problem is reproducible on `v18.16.0`, now we're downgrading to `v18.15.0` to fix the issue.
Refs:
https://github.com/keep-network/keep-core/pull/3595
https://github.com/threshold-network/solidity-contracts/pull/145

Set Node.js version to `18.15.0`

---

pkg/chain/ethereum/tbtc.go

Refs https://github.com/keep-network/keep-core/issues/3563
The original estimate is too low and the call fails with out of gas problem when reimbursing the submitter.
This is an example TX submitted with the same data but gas limit (before/after):
https://etherscan.io/tx/0xe27a92883e0e64da8a3a54a15a260ea2f4d3d48470129ac5c09bfe9637d7e114
https://etherscan.io/tx/0x90a44b4c8cd810c7ec4450e429abfe136fe82fc59d220775ef8838ba0fdc09b8

Add an extra 20% gas to the sweep SPV proof transaction

---

cmd/start.go
pkg/clientinfo/diagnostics.go
pkg/clientinfo/metrics.go

Refs https://github.com/keep-network/keep-core/issues/3608
Exposing the latest block number diagnostic can be helpful to diagnose some of the problems with a node connectivity and determine if a node is catching up with the global Ethereum state.
Example output:
```
{
"chain_info": {
"latest_eth_block_number": 3525
},
"client_info": {
"chain_address": "0x407190f04d838Ec47dad4C0e0D2a9c49d7737479",
"network_id": "16Uiu2HAm4WrMWq9Gc7WsymsqgrwbaD1KeW2eH8eY63DTZHXbRsuE",
"revision": "8c444b4b9",
"version": "v2.0.0-m3-70-g8c444b4b9"
},
"connected_peers": null
}
```

Adding Ethereum latest block number diagnostic

---

pkg/bitcoin/bitcoin.go
pkg/bitcoin/bitcoin_test.go
pkg/bitcoin/script.go
pkg/bitcoin/script_test.go
pkg/bitcoin/transaction.go
pkg/chain/ethereum/tbtc.go
pkg/chain/ethereum/tbtc/gen/abi/WalletCoordinator.go
pkg/chain/ethereum/tbtc/gen/cmd/WalletCoordinator.go
pkg/chain/ethereum/tbtc/gen/contract/WalletCoordinator.go
pkg/coordinator/tbtc_chain_test.go
pkg/maintainer/wallet/local_chain_test.go
pkg/tbtc/chain.go
pkg/tbtc/chain_test.go
pkg/tbtc/deduplicator.go
pkg/tbtc/deduplicator_test.go
pkg/tbtc/node.go
pkg/tbtc/redemption.go
pkg/tbtc/tbtc.go

Refs https://github.com/keep-network/keep-core/issues/3609
Here is the first part of the client-side redemption support. In this PR, we are integrating with the recent changes introduced in the `WalletCoordinator` contract (https://github.com/keep-network/tbtc-v2/pull/633) and we are adding the ability to observe incoming redemption proposals. Here is a brief description of particular changes.
We are adding all the boilerplate code required to see redemption proposals emitted by the `WalletCoordinator` contract. This work includes:
- Updates of contract bindings
- Integration with the `tbtc` package through the `tbtc.WalletCoordinatorChain` interface and `chain/ethereum` implementation
- Implementation of tools allowing to convert between length-prefixed redeemer output scripts used by …

Redemption prototype: Observe incoming proposals

---

pkg/bitcoin/bitcoin.go
pkg/bitcoin/bitcoin_test.go
pkg/bitcoin/script.go
pkg/bitcoin/script_test.go
pkg/chain/ethereum/tbtc.go
pkg/chain/ethereum/tbtc_test.go
pkg/coordinator/tbtc_chain_test.go
pkg/maintainer/wallet/local_chain_test.go
pkg/tbtc/chain.go
pkg/tbtc/chain_test.go
pkg/tbtc/deposit_sweep.go
pkg/tbtc/deposit_sweep_test.go
pkg/tbtc/node.go
pkg/tbtc/redemption.go
pkg/tbtc/redemption_test.go
pkg/tbtc/wallet.go
pkg/tbtc/wallet_test.go

Closes https://github.com/keep-network/keep-core/issues/3609
Here we add the remaining part necessary to enable redemption support on the client side. Specific changes include:
During the work on this PR, we identified that some code can be detached from the existing `depositSweepAction` and live as an independent being that can be reused across different wallet actions. Those components are:
- The `walletTransactionExecutor` which is a thin layer encapsulating some logic necessary to sign and broadcast wallet Bitcoin transactions
- The `EnsureWalletSyncedBetweenChains` function which allows to make sure the wallet is synced between the Bitcoin and host chain before starting an action
Thanks to that change, we avoid code duplication across wallet actions.
We introduce a dedicated …

Redemption prototype: Validate proposal and broadcast Bitcoin transaction

---

.github/workflows/client.yml

The previously used version `1.2.0` was internally using the `actions/cache@v2` action, which runs on Node 12. Node 12 has been out of support since April 2022, as a result GitHub has started the deprecation process of Node 12 for GitHub Actions. They plan to migrate all actions to run on Node16 by Summer 2023 and they show deprecation warnings in Annotations when actions are run on Node 12. Read more on
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. We're upgrading the `dominikh/staticcheck-action` to `1.3.0` version, which uses `actions/cache@v3`, which runs on Node 16.

Update Staticcheck action to v1.3.0

---

cmd/coordinator.go
pkg/chain/ethereum/tbtc.go
pkg/coordinator/chain.go
pkg/coordinator/redemptions.go
pkg/coordinator/tbtc_chain_test.go
pkg/maintainer/wallet/local_chain_test.go
pkg/tbtc/chain.go

We added a CLI command to submit a redemption proposal. 
To submit a redemptions proposal run:
```
keep-client coordinator propose-redemption --wallet <wallet_address> --fee <fee>
```
Following optional flags can be used with the command:
- `--wallet <address>` - target wallet
- `--fee` - fee to use for a bitcoin transaction
The command requires `ethereum` node details to be provided in the config.
This feature can be tested against the updated Goerli `WalletCoordinator` whose address and ABI are provided by the https://www.npmjs.com/package/@keep-network/tbtc-v2/v/1.5.0-goerli.0 package.

Propose redemptions coordinator with CLI command

---

cmd/start.go
pkg/clientinfo/clientinfo.go
pkg/clientinfo/diagnostics.go
pkg/clientinfo/metrics.go

Refs https://github.com/keep-network/keep-core/issues/3608
- Added `btc_connectivity` under the `/metrics`. It shows 1 or 0 - connected or not
- Added `latest_btc_block_number` `/diagnostics` that read the latest Bitcoin block
Example output:
http://192.168.1.8:9601/diagnostics
```
{
"btc_chain_info": {
"latest_block_number": 2438768
},
"client_info": {
"chain_address": "0x04BdC8f5051f21CF6E788eA451bB81A75266b473",
"network_id": "16Uiu2HAkzBpWcRgxEY8W4vuRYCJiSAzseEpVjFtHEawqow5xvTQw",
"revision": "0f3c7b137",
"version": "v2.0.0-m3-268-g0f3c7b137"
},
"connected_peers": [
{
"chain_address": "0x407190f04d838Ec47dad4C0e0D2a9c49d7737479",
"multiaddrs": [
"/ip6/::1/tcp/3920",
"/ip4/192.168.1.8/tcp/3920",
"/ip4/127.0.0.1/tcp/3920"
],
"network_id": …
```

Adding metric and diagnostics for the Bitcoin chain

---

.github/workflows/contracts-ecdsa-docs.yml
.github/workflows/contracts-random-beacon-docs.yml

Instead of running the `contracts-docs-publish-preview` job on update of every PR, we want to run it only when PR modifies contracts or the workflow itself.
Refs:
https://github.com/keep-network/ci/pull/43
https://github.com/keep-network/keep-core/pull/3534
https://github.com/keep-network/tbtc-v2/pull/584
https://github.com/threshold-network/solidity-contracts/pull/138

Use the path filter when triggering `contracts-docs-publish-preview`

---

pkg/chain/ethereum/tbtc.go
pkg/coordinator/chain.go
pkg/coordinator/chain_test.go
pkg/coordinator/deposits.go
pkg/maintainer/spv/chain.go
pkg/maintainer/spv/deposit_sweep_proof.go
pkg/maintainer/wallet/chain_test.go

This PR modifies the `GetDepositRequest` function by adding a boolean value to the returned values.
The returned values represent: 
- deposit request which is non-nil only when the deposit request was found,
- boolean value which is true if the deposit request was found, false otherwise,
- error which is non-nil only when the function execution failed. It will be nil if the deposit request was not found, but the function execution succeeded.
This can be useful when we want to check if a deposit exists, but we do not want to issue an error when it does not
exist, i.e. we don't consider it an error.

Modified retrieval of deposit request data

---

cmd/coordinator.go
pkg/bitcoin/script.go
pkg/bitcoin/script_test.go
pkg/coordinator/redemptions.go
pkg/coordinator/redemptions_test.go

Refs https://github.com/keep-network/keep-core/issues/3614
Here we add a function allowing us to estimate the redemption transaction total fee (`coordinator.EstimateRedemptionFee`) and we integrate it with the existing `coordinator.ProposeRedemption` function.

Estimate redemption transaction fee during proposal

---

.github/workflows/contracts-ecdsa-docs.yml
.github/workflows/contracts-random-beacon-docs.yml
solidity/ecdsa/hardhat.config.ts
solidity/random-beacon/hardhat.config.ts

Having all the contracts documented in one common file turned out to be hard to render by the GitBook. We're switching to documenting each contract file in a separate Markdown file.
As the generated files will be much smaller now and GitBook has its own file `ON THIS PAGE` section, we don't need to generate Table of Contents. The one thing that we also change as part of this PR is `rsyncDelete` setting - we'll have it set to `true`, in order to delete documentation of contracts which get removed from the repo. As we're not working directly on a `main` branch, this isn't dangerous (we'll see all the deletions in the PR diff).
Refs:
https://github.com/threshold-network/solidity-contracts/pull/149
https://github.com/keep-network/tbtc-v2/pull/640 …

Split contracts API doc into multiple files

---

pkg/bitcoin/block.go
pkg/bitcoin/block_test.go

This PR adds new functions to the `BlockHeader` structure:
- `Deserialize`
- `Target`
- `Difficulty`
These functions will be needed to verify if the difficulties of block headers in the SPV proof are consistent with the difficulties stored on-chain. They will be useful to detect a situation when the relay has not been updated yet with the current Bitcoin difficulties, but the proof already have block headers with those current difficulties.

Block header structure update

---

pkg/maintainer/wallet/redemptions.go
pkg/maintainer/wallet/wallet.go

Depends on: https://github.com/keep-network/keep-core/pull/3659
Here we add automation for the redemption proposal submission logic. Every 3 hours, the maintainer will check for pending redemptions starting from the oldest wallet and will propose them for redemption by submitting a proposal to the `WalletCoordinator` contract.

Invoke automated redemptions periodically by maintainer

---

cmd/flags.go
cmd/flags_test.go
cmd/maintainercli.go
config/config_test.go
pkg/chain/ethereum/ethereum.go
pkg/maintainer/wallet/chain.go
pkg/maintainer/wallet/chain_test.go
pkg/maintainer/wallet/config.go
pkg/maintainer/wallet/redemptions.go
pkg/maintainer/wallet/wallet.go
test/config.json
test/config.toml
test/config.yaml

Here we introduce a bunch of optimizations to the wallet maintainer. All of them are related to redemptions. I recommend reviewing commit by commit. Here is a brief description of the changes.
The wallet maintainer seeks past `RedemptionRequested` events in order to propose redemptions. So far, the events lookup was not constrained to any block range which could be problematic for several Ethereum providers. This can be improved as the wallet maintainer is only interested in pending requests that are not timed out yet. That means there is no sense to fetch events that were emitted before `now - redemptionRequestTimeout` block. We reflect that by narrowing the block range of the filter thus making the call more lightweight. …

Maintainer optimizations around redemptions

---

cmd/maintainercli.go
pkg/maintainer/wallet/deposit_sweep.go
pkg/maintainer/wallet/deposit_sweep_test.go
pkg/maintainer/wallet/internal/test/marshaling.go
pkg/maintainer/wallet/internal/test/testdata/propose_sweep_scenario_2.json
pkg/maintainer/wallet/internal/test/wallettest.go

Here we change the default behavior of the wallet maintainer (and `maintainer-cli` tool) when the estimated deposit sweep fee exceeds the maximum value allowed by the `Bridge`. So far, the estimated fee was adjusted to the maximum allowed value. Now, an error is returned. That's because this is an abnormal situation and the maintainer should rather wait until the fee goes back to normal value than block the wallet in the `WalletCoordinator` with something that has no chance of being included in a block.

Return an error if estimated deposit sweep fee is too high

---

pkg/bitcoin/spv_proof.go
pkg/bitcoin/spv_proof_test.go
pkg/maintainer/spv/spv.go

This PR is a follow-up PR to https://github.com/keep-network/keep-core/pull/3649.
It adds calculations of the required number of confirmations if the proofs spans two epochs.

Handle SPV proofs spanning two epochs

---

pkg/maintainer/spv/bitcoin_chain_test.go
pkg/maintainer/spv/chain_test.go
pkg/maintainer/spv/redemptions.go
pkg/maintainer/spv/redemptions_test.go
pkg/maintainer/spv/spv.go

Refs: https://github.com/keep-network/keep-core/issues/3615
This PR adds unit tests to the SPV redemption maintainer logic.

Unit tests for SPV redemption maintainer logic

---

cmd/maintainercli.go
pkg/maintainer/spv/redemptions.go

Refs: https://github.com/keep-network/keep-core/issues/3615
Here we expose the `submit-redemption-proof` command that allows to submit a redemption SPV proof manually.

Add redemption SPV proof submission to the maintainer-cli

---

infrastructure/kube/templates/bitcoin/electrumx/electrumx-statefulset.yaml

The TCP/IP port numbers below 1024 are considered privileged ports. Normal users and processes are not allowed to use them for various security reasons.
We are running our container with non-root and after recent upgrades in the GCP cluster (Jul 7th), the ElectrumX instances stopped working due to failures in binding TCP and SSL ports:
```
ERROR:SessionManager:TCP server failed to listen on all_interfaces:80: [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied
ERROR:SessionManager:SSL server failed to listen on all_interfaces:443: [Errno 13] error while attempting to bind on address ('0.0.0.0', 443): permission denied
INFO:SessionManager:WS server listening on all_interfaces:8080
INFO:SessionManager:WSS server listening on all_interfaces:8443
```
We …

Use non-privileged ports for ElectrumX

---

pkg/maintainer/spv/spv.go
pkg/maintainer/spv/spv_test.go

#Depends on https://github.com/keep-network/keep-core/pull/3673.
This is a follow-up PR that handles a [review comment](https://github.com/keep-network/keep-core/pull/3667#discussion_r1253063238) from another PR.
Getting the number of accumulated confirmations of a transaction was moved into the `getProofInfo` function.

Return accumulated confirmations

---

pkg/maintainer/wallet/redemptions.go

While running the redemption task, the wallet maintainer fetches past `RedemptionRequested` events using a filter whose start block is calculated as:
```
startBlock := currentBlock - requestTimeoutBlocks - 1000
```
where `requestTimeoutBlocks` is computed as:
```
requestTimeoutBlocks := uint64(requestTimeout) /
uint64(chain.AverageBlockTime().Seconds())
```
However, the current `Bridge.requestTimeout` on mainnet is set to `max(uint32)` as redemptions are not yet enabled. That means the `requestTimeoutBlocks` is higher than `currentBlock` and produces a negative `startBlock` which is eventually set to `max(uint64)` due to being an unsigned type. The `startBlock` is then converted to `int64` within `go-ethereum` library which …

Wallet maintainer: Prevent against `requestTimeout` being `max(uint32)`

---

pkg/maintainer/wallet/redemptions.go

Closes: https://github.com/keep-network/keep-core/issues/3682
As described in #3682, the current logic is wrong. If the `WalletsLimit` filter is on, always the same oldest wallets will be taken into account so redemption requests targeting newer wallets can be missed by the wallet maintainer. We are fixing that by applying the `WalletsLimit` filter at a later stage.

Fix the wallets limit filter in the wallet maintainer redemptions code

---

infrastructure/kube/keep-prd/keep-maintainer/kustomization.yaml

Here we point the production instance of `keep-maintainer` to the latest public Docker image, i.e `keepnetwork/keep-client:v2.0.0-m4` which enables support for redemptions.

Use `keepnetwork/keep-client:v2.0.0-m4` for `keep-maintainer` on production

---

internal/testdata/bitcoin/transaction.go
pkg/bitcoin/electrum/electrum_integration_test.go

There are two fixes around Electrum integration tests. 
The first one is replacing the existing testing Falcrum server URL with an operational one. The old one stopped working. 
The second fix is around btc tx hashes for a given wallet. Integration tests started reporting failures around mismatched expected vs actual txs for the integration test wallet. It turned out that there was still some movement in the wallet that was used for integration
tests and the latest txs were different. Here we picked a wallet that is quite old and it seems that there is no more new movement. URL for the btc address along with txs: https://blockstream.info/address/bc1qrw5tn47ea05seyetlywltrdk06rldpk746etc9

Electrum integration tests fixes

---

infrastructure/kube/keep-prd/monitoring/grafana/dashboards/keep/keep-nodes-public.json
infrastructure/kube/keep-prd/monitoring/grafana/dashboards/keep/keep-nodes.json

- For BTC we pull the metrics from `btc_connectivity` endpoint
- For ETH we pull the metrics from `eth_connectivity` endpoint
Monitoring links: https://github.com/keep-network/keep-core/tree/main/infrastructure/kube/keep-prd/monitoring

Adding BTC and ETH connectivity panels to Grafana prd dashboard

---

internal/testdata/bitcoin/transaction.go

The recent tx that happened for this address was 3 weeks ago and no movement was recorded since then. A new tx recently appeared on the existing address which means it is still in use, hence the change.

Picking a different wallet address which hasn't recorded any tx recently

---

pkg/protocol/announcer/announcer.go
pkg/protocol/announcer/announcer_test.go
pkg/tbtc/dkg.go
pkg/tbtc/node.go
pkg/tbtc/signing_done.go
pkg/tbtc/signing_done_test.go

#Refs https://github.com/keep-network/keep-core/issues/3611.
This PR handles problems with unmarshallers not found errors during signing:
```
eep-libp2p	libp2p/channel.go:286	couldn't find unmarshaler for type [protocol_announcer/announcement_message]
keep-libp2p	libp2p/channel.go:286	couldn't find unmarshaler for type [tbtc/signing_done_message]
```
The solution is is to register the marshaller for those messages early, before the signing process begins.

Set unmarshallers early during signing

---

pkg/tbtc/signing_test.go

Refs https://github.com/keep-network/keep-core/issues/3665
It turns out that the current number of attempts is not enough and we need to bump it up so the integration tests computation has enough time to perform signing. The reason why they started failing is because the local chain has block times much shorter than the real ones. This will give much shorter timeouts to perform all the signing computations.
Credits: The fix was suggested by @lukasz-zimnoch

Increasing signing attempts to perform all signing computations

---

infrastructure/kube/keep-prd/keep-maintainer/kustomization.yaml
infrastructure/kube/keep-test/keep-maintainer/kustomization.yaml
infrastructure/kube/templates/keep-maintainer/maintainer-statefulset.yaml

The wallet maintainer bot contains a safety net which forces it to not include requests exceeding 10 BTC in the automatically submitted redemption proposals. Such requests are processed manually after confirming they are not part of a broader malicious action. The redemption mechanism proved to perform well since its release so, we can increase the limit to 15 BTC and reduce the need of manual intervention.

Increase maintainer's redemption request amount limit to 15 BTC

---

cmd/flags.go
config/config.go
docs/resources/client-start-help

We planned to remove the `--mainnet` flag, as it seemed unnecessary, as the client running without any network flag runs for mainnet by default. But from an infrastructure administrator perspective, the flag may be actually useful when running the application on multiple environments. It's much easier to maintain a common template where the administrator will have to change the value of the flag rather than set the flag for some environments and remove it for mainnet.
When running the application for **mainnet** an administrator will have two possibilities:
- add `--mainnet` flag,
- don't define any network flag.
When running the application for **testnet** an administrator will have to add `--testnet` flag.

Remove deprecation notice for --mainnet flag

---

solidity-v1/migrations/2_deploy_contracts.js
solidity-v1/truffle-config.js

The Görli testnet currently used by Threshold/Keep for development purposes is planned to become deprecated with the end of year 2023. The testnet that is planned to replace it is called
[Holešky](https://github.com/eth-clients/holesky), however it's not yet available - it's planned it will become widely accessible on Sep 15, 2023 ([source](https://everstake.one/blog/new-ethereum-testnet-holesky-all-you-need-to-know-now)). Switching our infrastructure to support new testnet is quite time consuming, so moving directly from Görli to Holešky may be quite risky, especially if there would be some delays in the date of Holešky genesis (not meeting the planned timelines is not a rare occurrence in the Ethereum space). As a solution, we decided to switch first to another testnet that is currently …

Support deployment of v1 contracts on Sepolia

---

pkg/bitcoin/electrum/electrum.go

Refs the discussion https://github.com/keep-network/keep-core/pull/3701#discussion_r1324571809
Electrum client calls sometimes are prone to timeouts or other issues.
For debugging purposes we wrap electrum client calls with a logger and measure the time it takes to complete a call.

Logs for electrum connection

---

go.mod
go.sum

Here we replace the original `bnb-chain/tss` library with our own `threshold-network/tss-lib` fork.

Use `threshold-network/tss-lib` fork

---

infrastructure/kube/keep-prd/keep-maintainer/kustomization.yaml

Here we point the production instance of `keep-maintainer` to the latest public Docker image, i.e `keepnetwork/keep-client:v2.0.0-m5` which introduces some bug fixes and improvements.

Use `keepnetwork/keep-client:v2.0.0-m5` for `keep-maintainer` on production

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml
solidity/ecdsa/deploy/09_deploy_wallet_registry_governance.ts
solidity/ecdsa/hardhat.config.ts
solidity/random-beacon/deploy/01_deploy_reimbursement_pool.ts
solidity/random-beacon/deploy/02_deploy_beacon_sortition_pool.ts
solidity/random-beacon/deploy/03_deploy_beacon_dkg_validator.ts
solidity/random-beacon/deploy/04_deploy_random_beacon.ts
solidity/random-beacon/deploy/07_deploy_random_beacon_governance.ts
solidity/random-beacon/deploy/09_deploy_random_beacon_chaosnet.ts
solidity/random-beacon/hardhat.config.ts

The Görli testnet currently used by Threshold/Keep for development purposes is planned to become deprecated with the end of year 2023. The testnet that is planned to replace it is called
[Holešky](https://github.com/eth-clients/holesky), however it's not yet available - it's planned it will become widely accessible on Oct 1, 2023 ([source](https://everstake.one/blog/new-ethereum-testnet-holesky-all-you-need-to-know-now)). Switching our infrastructure to support new testnet is quite time consuming, so moving directly from Görli to Holešky may be quite risky, especially if there would be some delays in the date of Holešky genesis (not meeting the planned timelines is not a rare occurrence in the Ethereum space). As a solution, we decided to switch first to another testnet that is currently …

Support deployment on Sepolia

---

internal/testdata/bitcoin/transaction.go
pkg/bitcoin/chain.go
pkg/bitcoin/chain_test.go
pkg/bitcoin/electrum/electrum.go
pkg/bitcoin/electrum/electrum_integration_test.go
pkg/maintainer/btcdiff/bitcoin_chain_test.go
pkg/maintainer/spv/bitcoin_chain_test.go
pkg/maintainer/wallet/bitcoin_chain_test.go
pkg/tbtc/bitcoin_chain_test.go
pkg/tbtc/chain.go
pkg/tbtc/chain_test.go
pkg/tbtc/deposit_sweep.go
pkg/tbtc/redemption.go
pkg/tbtc/wallet.go
pkg/tbtc/wallet_test.go

Here we introduce some improvements regarding two mechanisms important for wallet actions execution:
The goal of that mechanism is to determine the plain-text wallet main UTXO whose hash is registered in the `Bridge` contract. The plain-text version is necessary to construct wallet transactions on Bitcoin.
The current version of the main UTXO lookup mechanism looks just at the last five confirmed transactions targeting the wallet public key hash to determine the plain text main UTXO of the wallet. This mechanism is not ideal as it doesn't recognize the difference between true wallet transactions and arbitrary transfers to the wallet public key hash that can be made by anyone. That means it is enough to craft several arbitrary transfers to block the main UTXO lookup and prevent the given …

Hardened wallet actions

---

pkg/tbtc/signing_test.go

This PR increases the number of attempts for signing during integration tests.
The reason for this change are occasional test failures.

Increased number of attempts for signing integration tests

---

.github/workflows/contracts-ecdsa-docs.yml

As auto-generated contract API reference has been moved under https://docs.threshold.network/app-development/tbtc-v2/tbtc-contracts-api, we need to update the CI job that publishes those docs to take the new destination into account

Update auto-generated contract docs destination

---

infrastructure/kube/keep-test/tbtc-v2-maintainer/guardian-statefulset.yaml
infrastructure/kube/keep-test/tbtc-v2-maintainer/minter-statefulset.yaml

Here we update the image name to the one actually used on the `keep-test` cluster.

Update `tbtc-v2-maintainer` image name for `keep-test`

---

pkg/chain/local_v1/blockcounter.go
pkg/chain/local_v1/local_test.go
pkg/tbtc/chain.go
pkg/tbtc/chain_test.go
pkg/tbtc/coordination.go
pkg/tbtc/coordination_test.go
pkg/tbtc/deposit_sweep.go
pkg/tbtc/heartbeat.go
pkg/tbtc/node.go
pkg/tbtc/node_test.go
pkg/tbtc/redemption.go
pkg/tbtc/registry.go
pkg/tbtc/registry_test.go
pkg/tbtc/tbtc.go
pkg/tbtc/wallet.go

Refs: https://github.com/keep-network/tbtc-v2/issues/737
Here we present the first part of the changes meant to implement [RFC 12: Decentralized wallet coordination](https://github.com/keep-network/tbtc-v2/blob/main/docs/rfc/rfc-12.adoc) in the tBTC wallet client. This pull request focuses on the groundwork necessary to run the off-chain coordination layer. 
The node orchestrates the coordination layer upon startup. Specifically, it runs two separate goroutines:
- Coordination window watch
- Coordination result processor
Both goroutines are steered by the node's root context and communicate through a dedicated channel.
The coordination window watch goroutine is responsible for detecting coordination windows that occur every `900` blocks. Once a window is detected, it runs the window …

RFC 12 Implementation: Coordination layer groundwork

---

pkg/tbtc/coordination.go
pkg/tbtc/node.go

Refs: https://github.com/keep-network/tbtc-v2/issues/737
Here we add the missing case that stops coordination result processing in case a no-op proposal is issued. The no-op proposals cannot be processed as they lead to panic. By the way, we are fixing some problems with log displaying discovered during testing.

RFC 12 Implementation: Do not handle no-op proposals

---

pkg/bitcoin/electrum/electrum.go

Some time ago, we did some major changes in the Electrum client implementation. Because of that, we added some `INFO` logging around Electrum requests in order to facilitate potential debugging. As Electrum-changes are now battle-tested, we can switch those request logs to `DEBUG` level to decrease the amount of logs produced on `INFO` level.

Switch Electrum request logs to debug level

---

pkg/chain/ethereum/ethereum.go

During tests of the RFC 12 implementation, we discovered that the timeout of 10 seconds for `GetBlockHashByNumber` is sometimes too short. Here we are increasing it to 30 seconds to improve success rate.

Increase timeout for `GetBlockHashByNumber` function

---

solidity/ecdsa/contracts/WalletRegistry.sol
solidity/ecdsa/contracts/test/DkgChallenger.sol
solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts

The `challengeDkgResult` function uses several `try-catch` blocks as part of its business logic. However, the EVM has a call stack depth limit equal to 1024. A third-party contract can leverage this limitation and force the `try-catch`-ed calls to revert unconditionally, by using recursion and letting those calls be executed at depth 1025. In such a case, the control flow is passed to the `catch` clauses which may lead to undesired side effects like invalidation of a proper DKG result. To address that problem, we are adding a requirement that `challengeDkgResult` can only be called by an EOA. This prevents third-party contracts from calling `challengeDkgResult`.

Require ECDSA DKG result challenger to be an EOA

---

pkg/tbtc/coordination.go
pkg/tbtc/coordination_test.go

Refs: https://github.com/keep-network/tbtc-v2/issues/737
The currently used probability of 12.5% means that a completely idle wallet will perform a heartbeat every 4 coordination windows on average (or 8 in the worst case) so, every 3600 blocks (~12 hours assuming a coordination every 900 blocks and 12 seconds per Ethereum block).
User acceptance tests executed on our Sepolia testnet (10 live wallets) show that such a value often leads to simultaneous heartbeats for several wallets at the same time. This, in turn, can cause increased resource consumption for individual nodes and harm some signing processes. Although nothing bad happens if those are just heartbeats, this may be problematic for redemptions and deposit sweeps. To lower the risk of signing failures, we are lowering the …

RFC 12 Implementation: Reduce heartbeat probability to 6.25%

---

solidity/ecdsa/.openzeppelin/mainnet.json
solidity/ecdsa/deployments/mainnet/WalletRegistry.json

The `WalletRegistry` proxy has been upgraded to the new implementation in order to include changes from https://github.com/keep-network/keep-core/pull/3756. Here we are pushing relevant artifact updates.

Update the `WalletRegistry` deployment artifact for mainnet

---

pkg/chain/ethereum/tbtc/gen/Makefile
pkg/chain/ethereum/tbtc/gen/abi/WalletProposalValidator.go
pkg/chain/ethereum/tbtc/gen/cmd/WalletProposalValidator.go
pkg/chain/ethereum/tbtc/gen/contract/WalletProposalValidator.go

This PR fixes a compilation problem due to duplicated types that were generated by the `abigen`.
The problem is due to an error in the version of `abigen` that we use for contract code generation. 
See https://github.com/keep-network/keep-common/issues/117 for explanation.

Compilation error fix due to duplicated generated types

---

pkg/tbtcpg/deposit_sweep.go
pkg/tbtcpg/internal/test/testdata/propose_sweep_scenario_0.json

Refs: https://github.com/keep-network/tbtc-v2/issues/749
Bitcoin scripts of deposits embedding 32-byte extra data are longer (126 bytes) than the scripts of regular deposits not holding extra data (92 bytes). That means the actual virtual size of the resulting deposit sweep transaction is greater than the size assumed by the sweep fee estimator. Here we adjust the fee estimator to always take the longer script for calculations to avoid underestimation of the transaction fee. This approach is not ideal but is safe as it makes sure transactions are not rejected due to too low network fees.

Include extra data of deposits for sweep fee estimation

---

.github/workflows/contracts-ecdsa.yml
.github/workflows/contracts-random-beacon.yml
solidity-v1/truffle-config.js
solidity/ecdsa/deploy/09_deploy_wallet_registry_governance.ts
solidity/ecdsa/hardhat.config.ts
solidity/random-beacon/hardhat.config.ts

As the Goerli testnet will become deprecated with end of year 2023 and we've already migrated to Sepolia testnet, we'll no longer need the Goerli-related code past that date.
Ref: https://github.com/threshold-network/solidity-contracts/issues/150

Remove support for Goerli testnet

---

go.mod
go.sum
pkg/bitcoin/electrum/electrum.go

Closes: https://github.com/keep-network/keep-core/issues/3739
Depends on: https://github.com/keep-network/go-electrum/pull/5
Depends on: https://github.com/keep-network/keep-core/pull/3774
So far, the `GetLatestBlockHeight` function of the Electrum client was using `go-electrum`'s `SubscribeHeaders` under the hood. That caused a memory leak because `GetLatestBlockHeight` was not interested in reading from the returned `headersChan` channel. Each call to `GetLatestBlockHeight` produced a new dangling goroutine blocked on a buffered channel with one item inside.
Here we replace `SubscribeHeaders` with `SubscribeHeadersSingle` which does not create a goroutine supposed to handle future headers notifications. The `SubscribeHeadersSingle` just returns the current chain tip and ignores further …

Fix a memory leak in Electrum client

---

config/config.go
main.go
pkg/net/libp2p/libp2p.go
pkg/protocol/announcer/announcer.go
pkg/protocol/announcer/announcer_test.go
pkg/tbtc/dkg.go
pkg/tbtc/dkg_loop.go
pkg/tbtc/signing_loop.go

Closes: https://github.com/keep-network/keep-core/issues/3770
Here we are tweaking some logs, mostly related to the network layer. The goal here is to make debugging easier. We are trying to achieve that by adding additional logs that may help during that process and limiting the unuseful ones. I recommend reviewing commit by commit. A short summary of changes:
- Set libp2p pubsub logs to `warn` by default and make that customizable using the `PUBSUB_LOG_LEVEL` environment variable (https://github.com/keep-network/keep-core/commit/b725e1c1650c57336355630a8803ac163c435304)
- Log members that are not ready during DKG/signing network announcement (https://github.com/keep-network/keep-core/commit/551e57a778fdd264e29e259d03125f6fb51a27ce)
- Log distinct operators participating in DKG …

Tweak logs around network

---

pkg/bitcoin/electrum/electrum.go

This pull request backports https://github.com/keep-network/keep-core/pull/3753 to the `releases/mainnet/v2.0.0-m7` branch.

[Backport] Switch Electrum request logs to debug level

---

go.mod
go.sum
pkg/bitcoin/electrum/electrum.go

This pull request backports https://github.com/keep-network/keep-core/pull/3775 to the `releases/mainnet/v2.0.0-m7` branch.

[Backport] Fix a memory leak in Electrum client

---

pkg/tbtc/dkg.go
pkg/tbtc/dkg_loop.go
pkg/tbtc/dkg_loop_test.go
pkg/tecdsa/dkg/states.go
solidity/ecdsa/contracts/WalletRegistry.sol

This pull request backports https://github.com/keep-network/keep-core/pull/3776 to the `releases/mainnet/v2.0.0-m7` branch.

[Backport] Single-shot DKG

---

pkg/net/libp2p/channel_manager.go

This pull request backports https://github.com/keep-network/keep-core/pull/3773 to the `releases/mainnet/v2.0.0-m7` branch.

[Backport] Tweaks around libp2p pubsub seen messages cache

---

config/config.go
main.go
pkg/net/libp2p/libp2p.go
pkg/protocol/announcer/announcer.go
pkg/protocol/announcer/announcer_test.go
pkg/tbtc/dkg.go
pkg/tbtc/dkg_loop.go
pkg/tbtc/signing_loop.go

This pull request backports https://github.com/keep-network/keep-core/pull/3777 to the `releases/mainnet/v2.0.0-m7` branch.

[Backport] Tweak logs around network

---

pkg/chain/ethereum/tbtc.go
pkg/maintainer/spv/chain.go
pkg/maintainer/spv/chain_test.go
pkg/maintainer/spv/moving_funds.go
pkg/maintainer/spv/moving_funds_test.go
pkg/maintainer/spv/spv.go
pkg/tbtc/chain.go

#Refs: https://github.com/keep-network/keep-core/issues/3735.
This PR adds functionalities for creating and submitting moving funds transaction SPV proofs.
Finding the possible unproven moving funds transactions is done by retrieving `MovingFundsCommitmentSubmitted` events and looking at the recent transactions of target wallets from each event as well as the wallet public key hash from the event. It's enough to just look at one of the target wallets (e.g. the first one) and retrieve all the transactions that pay to that target wallet. The unproven moving funds transaction must match both the input - it must be the current wallet's main UTXO and all the outputs - they must match the target wallets.
Once the unproven moving funds transactions are found, they are proven.

Moving funds SPV proofs

---

pkg/chain/ethereum/tbtc.go
pkg/chain/ethereum/tbtc_test.go
pkg/tbtc/chain.go
pkg/tbtc/gen/pb/message.pb.go
pkg/tbtc/gen/pb/message.proto
pkg/tbtc/marshaling.go
pkg/tbtc/marshaling_test.go
pkg/tbtc/moved_funds_sweep.go
pkg/tbtc/node.go
pkg/tbtcpg/chain.go
pkg/tbtcpg/chain_test.go
pkg/tbtcpg/moved_funds_sweep.go
pkg/tbtcpg/moved_funds_sweep_test.go
pkg/tbtcpg/tbtcpg.go

#Refs: https://github.com/keep-network/keep-core/issues/3736.
This PR introduces functionalities that lanuches the moved funds sweep procedure and produces a proposal for it.
Once the procedure is launched we check if the wallet in question needs to perform moved funds sweep.
If it does, we look for the data of a moving funds transaction that transferred the funds to the wallet in question.
In the end, we create a proposal containing the transaction hash, outpoint index and transaction fee. 
Based on ths data, a Bitcoin moved funds sweep transaction will be contructed.

Moved funds sweep proposal handling

---

.github/workflows/contracts-ecdsa-docs.yml
.github/workflows/contracts-random-beacon-docs.yml

Previously we've been adding comments to PRs modifying Solidity contracts about available previews of the API documentation. As each push to the PR branch results in one such comment, PRs with a lot of pushes get quite busy with a lot of the similar comments. In the future it would be good to modify our commenting mechanism so that it would just leave one comment per PR and update it on each push. Until we do that we're turning off the PR commenting, to increase readability.
Ref:
https://github.com/keep-network/tbtc-v2/pull/793
https://github.com/threshold-network/solidity-contracts/pull/165

Don't add comments about API docs previews to PRs

---

pkg/tbtcpg/moving_funds.go

This PR prevents the wallet running the moving funds procedure if the wallet has unswept deposits.

Prevent moving funds if there are unswept deposits

---

pkg/chain/ethereum/tbtc.go
pkg/maintainer/spv/chain.go
pkg/maintainer/spv/chain_test.go
pkg/maintainer/spv/moved_funds_sweep.go
pkg/maintainer/spv/moved_funds_sweep_test.go
pkg/maintainer/spv/moving_funds_test.go
pkg/maintainer/spv/spv.go
pkg/tbtcpg/chain.go

#Refs: https://github.com/keep-network/keep-core/issues/3738.
This PR adds functionalities for creating and submitting moved funds sweep transaction SPV proofs.
Finding the possible unproven moved funds sweep transactions is done by retrieving `MovingFundsCommitmentSubmitted` events and looking at the recent transactions of target wallets from each event.
An unproven moved funds seep transaction must have the following format:
- the first input must refer to an unproven moved funds sweep request
- the second input (optional) must refer to the current wallet's main UTXO  
- the (single) output that pays to the wallet itself
Once the unproven moved funds sweep transactions are found, they are proven.

Moved funds sweep SPV proofs

---

infrastructure/kube/keep-prd/keep-maintainer/kustomization.yaml

Here we update the `keep-maintainer` manifest according to the recent updates performed on the cluster.

Update `keep-maintainer` Kubernetes deployment on `keep-prd`

---

infrastructure/kube/keep-prd/tbtc-v2-monitoring/kustomization.yaml
infrastructure/kube/keep-test/tbtc-v2-monitoring/kustomization.yaml
infrastructure/kube/templates/tbtc-v2-monitoring/tbtc-v2-monitoring-cronjob.yaml

New values are
- 100 BTC for mainnet deposits and redemptions
- 10 BTC for testnet deposits and redemptions

Change large deposit/redemption threshold for `tbtc-v2-monitoring`

---

pkg/tbtc/coordination.go
pkg/tbtc/coordination_test.go

Refs: https://github.com/keep-network/keep-core/issues/3802
So far, deposit sweeps were supposed to happen every 48 hours. This frequency was good for the early days of the system but starts to be insufficient now, when a significant number of deposits land every day. To optimize the deposit sweep process, we are increasing its frequency to 12 hours.

Increase deposit sweep frequency

---

pkg/tbtc/coordination.go
pkg/tbtc/coordination_test.go

Refs: https://github.com/keep-network/keep-core/issues/3802
Here we attempt to harden proposal generation by retrying the process in case of failure. Proposal generation strongly relies on 3rd party services like Ethereum RPC and Electrum servers. Temporary disruption of those services can easily nuke proposal generation and cause a coordination window miss. Retrying proposal generation after a short delay should help overcome temporary problems and increase success chance of coordination windows.

Retry upon coordination proposal failure

---

cmd/maintainercli.go
pkg/tbtcpg/deposit_sweep.go

Closes: https://github.com/keep-network/keep-core/issues/3802
Fetching deposit script type is not needed for sweep proposal generation. Doing so means making an additional Electrum call for each deposit. This makes proposal generation longer and more prone to failure.
At the same time, the script type is used only for Maintainer CLI which is not so important since we have tbtcscan and there is no way to manually trigger sweeps due to the introduction of RFC 12.
That said, we are removing script type fetch from the process.

Optimize deposit sweep proposal generator

---

cmd/maintainercli.go
pkg/tbtcpg/deposit_sweep.go

This pull request backports https://github.com/keep-network/keep-core/pull/3805 to the `releases/mainnet/v2.0.1` branch.

[Backport] Optimize deposit sweep proposal generator

---

pkg/bitcoin/electrum/electrum.go
pkg/bitcoin/electrum/electrum_integration_test.go

Electrum client exposes two methods for getting entire transactions and transaction confirmations from the Bitcoin blockchain. Those methods retry Electrum requests in case of any error. Retries are done in the exponential backoff scheme until a timeout of 2 minutes is hit.
However, when the given transaction does not exist on the chain, there is no point to retry. This can be harmful for scenarios like deposit sweep generation that need to check multiple transactions in a limited time window. If there are multiple non-existing transactions that are checked during the process, 2 minutes per such transaction is wasted.
Here we improve the situation by introducing an error type check. If the error says about not found transaction, retries are not executed.

Optimize handling of non-existing transactions in the Electrum client

---

pkg/tbtc/moving_funds.go
pkg/tbtcpg/moving_funds.go
pkg/tbtcpg/moving_funds_test.go

Here we introduce two adjustments to the moving funds proposal generator.
First, we introduce a moving funds safety margin of 24 hours. Wallets that just entered the `MovingFunds` state may have received some last minute deposits just before. Even though deposit sweep task typically occurs before the moving funds task, such deposits may not be mature enough or have enough confirmations to be swept. We know that `MovingFunds` wallets cannot receive new deposits so, it makes sense to preserve a safety margin before moving funds to give the last minute deposits a chance to become eligible for sweeping by the deposit sweep task.
Second, we slightly optimize the unswept deposit check at the beginning of the moving funds task. It's enough to find one unswept deposit to abort the moving funds …

Adjustments to the moving funds proposal generator

---

go.mod
go.sum
pkg/chain/ethereum/tbtc.go

The current logic always fetches swept deposits from the chain using Ethereum RPC server. This can be optimized. Swept deposits are final and no further changes occur regarding their state. That means swept deposits can be cached. This allows reducing network load and speeding up processed that needs to check a large number of deposits (e.g. deposit sweep and moving funds proposal generators). We use a time cache to evict unused keys over time and optimize memory consumption.

Cache swept deposits

---

pkg/tbtc/chain.go
pkg/tbtc/chain_test.go
pkg/tbtc/moving_funds.go
pkg/tbtc/moving_funds_test.go
pkg/tbtcpg/chain.go
pkg/tbtcpg/moving_funds.go
pkg/tbtcpg/moving_funds_test.go

#Refs https://github.com/keep-network/keep-core/issues/3812.
This PR modifies the safety margin validation process used during moving funds.
It is possible that a wallet may receive deposits just before it changes states to `MovingFunds`.
It is also possible another wallets in `MovingFunds` state may commit to transfer their funds to it.  
To avoid a situation where a wallet ends up with additional funds after it has already moved their own funds we must apply a safety margin. 
In https://github.com/keep-network/keep-core/pull/3810 we already added a 24-hour safety margin. 
In this PR we add a longer 14-days safety margin when the wallet is a target of a moving funds process from another wallet. We also make sure the calculated safety margin is not greater than half of the …

Harden moving funds against edge cases

---

pkg/chain/ethereum/tbtc.go
pkg/chain/ethereum/tbtc_test.go
pkg/tbtc/chain.go
pkg/tbtc/chain_test.go
pkg/tbtc/deduplicator.go
pkg/tbtc/deduplicator_test.go
pkg/tbtc/dkg_test.go
pkg/tbtc/inactivity_test.go
pkg/tbtc/node.go
pkg/tbtc/node_test.go
pkg/tbtc/registry.go
pkg/tbtc/registry_test.go
pkg/tbtc/signing_test.go
pkg/tbtc/tbtc.go
pkg/tbtcpg/chain_test.go

#Refs: https://github.com/keep-network/keep-core/issues/3797.
This PR handles archiving key material on wallet closures.
Archiving the wallet data happens in two situations:
- when the `WalletClosed` event is received
- on node start, if there are closed wallets in the node's wallet registry.
Archiving wallet's key material causes the wallet data to be moved to the `archive` directory and the wallet is removed
form the registry's cache..
Such wallets will no longer participate in the RFC-12 coordination.

Archive key material on wallet closure

---

infrastructure/kube/keep-prd/keep-maintainer/kustomization.yaml

Here we point the production instance of `keep-maintainer` to the latest public Docker image, i.e. `keepnetwork/keep-client:v2.1.0` which introduces support of SPV proofs for moving funds and moved funds sweep transactions.

Use `keepnetwork/keep-client:v2.1.0` for `keep-maintainer` on production

---

infrastructure/kube/keep-test/bitcoin/testnet/electrumx/electrumx-data-electrumx-1-pvc.yaml
infrastructure/kube/keep-test/bitcoin/testnet/electrumx/kustomization.yaml

ElectrumX on testnet started failing with `plyvel._plyvel.IOError: b'IO error: utxo/MANIFEST-7126373: No space left on device'` error. I edited PVC to increase disk size from 30Gi to 40Gi.

Increase disk size for testnet ElectrumX node
