solidity/scripts/circleci-migrate-contracts.sh
This fixes migrations, which are currently broken, and maybe also gives them a small speed boost, without removing tenderly push from the equation.
=> Migration Fixes: Land 3 fixes to the Circle migration script

pkg/beacon/relay/gjkr/member.go, pkg/beacon/relay/gjkr/protocol.go, pkg/beacon/relay/integration_test.go, pkg/beacon/relay/node.go
Refs #1075
Here are some documentation improvements and additional log messages suggested during the review of  #1274
=> Additional docs and log messages for validation of signature shares

README.adoc
Rework the README to better introduce the project and docs to a newcomer.
=> Please actually README

infrastructure/terraform/keep-test/deployment.tf, infrastructure/terraform/keep-test/variables.tf
This was done a very long time ago in a branch that's about to get closed.  I've cherrypicked the relevant commit here so we don't loose it.
Came from https://github.com/keep-network/keep-core/pull/1005
=> keep-test: Contract data bucket

pkg/beacon/relay/chain/group_ticket.go, pkg/beacon/relay/groupselection/groupselection_test.go, pkg/beacon/relay/groupselection/ticket.go, pkg/beacon/relay/groupselection/ticket_sort_test.go, pkg/beacon/relay/groupselection/ticket_submission.go, pkg/beacon/relay/groupselection/ticket_submission_test.go, pkg/chain/ethereum/ethereum.go, pkg/chain/ethereum/ethereum_test.go, pkg/chain/local/local.go, pkg/chain/local/local_test.go
Refs #1431
During the review of #1510, we agreed that the ticket value representation on the client side is not consistent and should be improved. Here we introduce some improvements which should make the code cleaner and more consistent with the on-chain part.
=> Improve off-chain tickets value consistency

cmd/start.go, go.mod, go.sum
Refs https://github.com/keep-network/keep-ecdsa/issues/336
In this PR we are pre-checking if there are any potential errors with reading/writing to the disk storage.
~~depends on `keep-commons` keep-network/keep-common#25~~
=> Handling errors when creating a new disk storage handle

solidity/contracts/statistics/KeepRandomBeaconOperatorStatistics.sol, solidity/test/random_beacon_operator/TestPricingRewardsWithdraw.js
Addressing [this comment](https://github.com/keep-network/keep-core/pull/1567#discussion_r409872195) and [this comment](https://github.com/keep-network/keep-core/pull/1567#discussion_r409873973)  in #1567
=> Document operator contract statistics functions and remove unused test code

solidity/dashboard/package-lock.json, solidity/dashboard/src/constants/constants.js, solidity/dashboard/src/contracts.js, solidity/dashboard/src/services/rewards.service.js
Closes: #1602
This PR adjusts the dapp to changes from #1567.
=> Update rewards withdrawal in KEEP token dashboard

docs/run-random-beacon.adoc
The references in the docs will be right, whee!
=> Update contracts to 0.14.0-rc

docs/run-random-beacon.adoc
Missed an address update last night.
=> Ropsten: Update TokenStaking

docs/run-random-beacon.adoc
Updated documentation with addresses of bootstrap nodes running in boar
network.
=> Added boar network bootstrap nodes addresses for Ropsten

solidity/contracts/Escrow.sol, solidity/test/TestEscrow.js
A token holder contract allowing contract owner to set beneficiary of all tokens held by the contract and allowing the beneficiary to withdraw the tokens.
=> Escrow contract

solidity/contracts/ManagedGrantFactory.sol
Enables filtering events from `ManagedGrantFactory` for a particular (original) grantee
=> Index `grantee` in `ManagedGrantCreated` event

solidity/contracts/KeepToken.sol, solidity/test/TestToken.js
We updated KeepToken to be ERC20Detailed with name `KEEP Token`, symbol `KEEP` and decimals `18`. The values will help list the token.
=> KeepToken is ERC20Detailed with name and symbol

infrastructure/kube/keep-test/eth-network-ropsten-configmap.yaml
We've been limping along on a free Infura account for some time.  Here
we're moving to a proper company account with larger limits.
~~I'll notate here when the rollout is finished.~~
Deployments are finished, this is ready now.
=> keep-test: Fresh Infura Account

solidity/dashboard/package.json, solidity/package-lock.json, solidity/package.json
Preparation for `1.1.0-rc` version.
=> Release 1.1.0-rc (Ropsten)

pkg/chain/gen/abi/KeepRandomBeaconServiceImplV1.go, pkg/chain/gen/contract/KeepRandomBeaconService.go, solidity/contracts/KeepRandomBeaconServiceImplV1.sol, solidity/test/random_beacon_service/TestPricingFees.js
DKG contribution margin, DKG fee pool, and request subsidy fee pool can be public without hurting anything. Having them public makes the system more transparent and helps with debugging (see #1736).
=> Service contract pool values and DKG contribution margin made public

solidity/contracts/KeepRandomBeaconOperator.sol, solidity/contracts/KeepRandomBeaconServiceImplV1.sol, solidity/contracts/libraries/operator/Reimbursements.sol, solidity/contracts/stubs/KeepRandomBeaconOperatorCallbackStub.sol, solidity/contracts/stubs/KeepRandomBeaconOperatorDKGMisbehaviorStub.sol, solidity/contracts/stubs/KeepRandomBeaconOperatorGroupSelectionStub.sol, solidity/contracts/stubs/KeepRandomBeaconOperatorPricingDKGStub.sol, solidity/contracts/stubs/KeepRandomBeaconOperatorPricingRewardsWithdrawStub.sol, solidity/contracts/stubs/KeepRandomBeaconOperatorServicePricingStub.sol, solidity/contracts/stubs/KeepRandomBeaconOperatorSlashingStub.sol, solidity/contracts/stubs/KeepRandomBeaconOperatorStub.sol, solidity/test/random_beacon_operator/TestDkgMisbehavior.js, solidity/test/random_beacon_operator/TestGroupSelection.js, solidity/test/random_beacon_operator/TestPricingRewardsWithdraw.js, solidity/test/random_beacon_operator/TestRelayEntry.js, solidity/test/random_beacon_operator/TestSlashing.js, solidity/test/random_beacon_service/TestPricing.js, solidity/test/random_beacon_service/TestPricingDkg.js, solidity/test/random_beacon_service/TestRelayRequestCallback.js
If callback fails make sure to return any surplus back to the customer.
=> Fix callback surplus return

solidity/test/random_beacon_service/TestRelayRequestCallback.js
One additional test case for the situation when gas estimate is higher than the actual one.
=> Added test covering surplus for gas value higher than the actual one

infrastructure/gcp/keep-test/google-functions/keep-faucet/package-lock.json, infrastructure/gcp/keep-test/google-functions/keep-faucet/package.json
Rolling the faucet forward to the latest RC.
=> Faucet: v1.2.0-rc

solidity/dashboard/src/services/token-staking.service.js
This PR fixes fetching the delegated stake from a TokenGrant.
=> Fix fetching a deleagtion from a TokenGrant

docs/run-random-beacon.adoc
Adding bootstrap peers from:
- Figment Network
- Boar Network
- Staked
- Bison Trails
We are still expecting one or two peers more from Staked, and I think not all peers here have passed their stake initialization period yet. 
We can safely use this list once we have a confirmation from everyone and we'll add the remaining peers later. Also, even if some peers are still in the initialization period, we should have all the connections established by Friday.
=> Mainnet Bootstrap Peer List

solidity/dashboard/src/connectors/abstract-connector.js
This PR increases the number of addresses to fetch from hardware wallets.
=> Increase the number of address to fetch from hardware wallets

solidity/dashboard/package-lock.json, solidity/dashboard/package.json, solidity/dashboard/src/components/AddressShortcut.jsx, solidity/dashboard/src/css/address-shortcut.less
Closes: #1771 
This PR replaces the custom implementation of the `copy to clipboard` feature with a `copy-to-clipboard` npm package. This package supports most web browsers.
=> Malfunctioning copy button

solidity/dashboard/package-lock.json, solidity/dashboard/package.json, solidity/dashboard/src/contracts.js, solidity/dashboard/src/services/tbtc-authorization.service.js
In this PR, we restore tBTC system contracts for authorization from: https://github.com/keep-network/keep-core/pull/1789/files
=> Restoring tBTC system contracts for authorization

configs/config.toml.SAMPLE, go.mod, go.sum, pkg/chain/ethereum/connect.go, pkg/chain/gen/cmd/KeepRandomBeaconOperator.go, pkg/chain/gen/cmd/KeepRandomBeaconService.go, pkg/chain/gen/cmd/TokenGrant.go, pkg/chain/gen/cmd/TokenStaking.go, pkg/chain/gen/contract/KeepRandomBeaconOperator.go, pkg/chain/gen/contract/KeepRandomBeaconService.go, pkg/chain/gen/contract/TokenGrant.go, pkg/chain/gen/contract/TokenStaking.go
See https://github.com/keep-network/keep-common/pull/36
For every submitted transaction, we check in the predefined intervals if the transaction has been mined already and if not, we increase the gas price by 20% and try to submit again.
The interval at which we check for transaction status, as well as the maximum gas price, can be configured.
=> TX gas price bids

solidity/dashboard/src/pages/TBTCApplicationPage.jsx, solidity/dashboard/src/services/tbtc-authorization.service.js
Closes: https://github.com/keep-network/keep-core/issues/1792
In this PR we add operators of an authorizer in the bonding section of tBTC application.
=> Adding operators of authorizer in bonding section

solidity/dashboard/src/components/BondingSection.jsx, solidity/dashboard/src/pages/TBTCApplicationPage.jsx, solidity/dashboard/src/services/tbtc-authorization.service.js
Refs: https://github.com/keep-network/keep-core/issues/1812
Adding functionality to withdraw all available bonds (aka unbondedValue) in the bonding section.
=> Withdraw all bonding

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
Patch release includes support for tBTC contracts (TBTCSystem) authorizations.
=> keep-prd: Token Dashboard to 1.0.3

solidity/dashboard/src/components/AddETHModal.jsx, solidity/dashboard/src/components/AvailableETHForm.jsx, solidity/dashboard/src/components/AvailableEthAmount.jsx, solidity/dashboard/src/components/BondingSection.jsx, solidity/dashboard/src/components/Icons.jsx, solidity/dashboard/src/components/WithdrawETHModal.jsx, solidity/dashboard/src/services/tbtc-authorization.service.js, solidity/dashboard/src/static/svg/diamond.svg
Closes https://github.com/keep-network/keep-core/issues/1812
In this PR we let a user to specify how much Eth he/she wants to withdraw.
=> Adding partial withdrawal with modal

solidity/dashboard/src/components/DelegatedTokens.jsx, solidity/dashboard/src/components/PendingUndelegation.jsx, solidity/dashboard/src/components/SlashedTokensList.jsx, solidity/dashboard/src/components/UndelegateStakeButton.jsx, solidity/dashboard/src/css/operator-page.less, solidity/dashboard/src/pages/OperatorPage.jsx, solidity/dashboard/src/services/token-staking.service.js, solidity/dashboard/src/utils/general.utils.js
Closes: #1632
Closes: #1719
This PR updates the operator page according to the Figma view.
=> Operator page ui updates

solidity/dashboard/src/components/AuthorizeContracts.jsx, solidity/dashboard/src/pages/TBTCApplicationPage.jsx, solidity/dashboard/src/services/tbtc-authorization.service.js
See https://github.com/keep-network/keep-ecdsa/pull/471
Closes: #1837 
This PR allows an authorizer to deauthorize a `TBTCSystem sortition pool` for a given operator.
=> Deauthorize sortition pool- dapp

CODEOWNERS
Added @nkuba as a code owner for staking contracts.
=> Added nkuba to staking contract code owners

solidity/contracts/TokenStakingEscrow.sol, solidity/test/RolesLookupTest.js, solidity/test/helpers/grantTokens.js, solidity/test/token_grant/TestManagedGrant.js, solidity/test/token_grant/TestTokenGrant.js, solidity/test/token_grant/TestTokenGrantRevoke.js, solidity/test/token_grant/TestTokenGrantStake.js, solidity/test/token_grant/TestTokenGrantWithdraw.js, solidity/test/token_stake/TestTokenStakingEscrow.js
Here we introduce an escrow allowing `TokenStaking` to deposit tokens. This is the first step on a way allowing to implement stake top-ups requested by the community. Escrow will let the staking contract to aggregate tokens and move them between contracts easily.
=> TokenStakingEscrow

solidity/dashboard/src/components/ChooseWallet.jsx, solidity/dashboard/src/components/ChooseWalletAddress.jsx, solidity/dashboard/src/components/skeletons/DataTableSkeleton.jsx, solidity/dashboard/src/services/beacon-authorization.service.js, solidity/dashboard/src/services/tbtc-authorization.service.js, solidity/dashboard/src/services/token-staking.service.js
This PR fixes React warnings that have been appearing in the console when using the dapp.
=> Fix React's warnings in web console

solidity/package-lock.json, solidity/package.json
Bumped up package version to 1.3.0-pre
=> Bumped up package version to 1.3.0-pre

infrastructure/terraform/keep-dev/variables.tf
Dmitry needs to be able to poke around in the env.  Here we apply the default IAM role for engineers in `keep-dev`, `editor`. 
```
sthompson22 ~/Projects/keep/keep-core/infrastructure/terraform/keep-dev (sthompson22/keep-dev/add-dmitry) $ terraform plan --target module.iam_members_editor --out .terraform/tfplan.out 
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
random_id.random_project_id: Refreshing state... (ID: _iQ)
google_project.a_project: Refreshing state... (ID: keep-dev-fe24)
google_project_iam_member.a_member[3]: Refreshing state... (ID: keep-dev-fe24/roles/editor/user:piotr.dyraga@thesis.co)
google_project_iam_member.a_member[0]: Refreshing state... (ID: …
```
=> keep-dev: Add Dmitry to Editor role

solidity/test/token_stake/TestStakingGrant.js
Although this path works fine, we had no unit tests covering it. Adding them now to stay safe!
=> Added test cases for escrow redelegations undelegated/cancelled

solidity/dashboard/src/components/AmountForm.jsx, solidity/dashboard/src/components/DelegatedTokensTable.jsx, solidity/dashboard/src/components/DelegationOverview.jsx, solidity/dashboard/src/pages/TokenOverviewPage.jsx
Ref: #1974
This PR allows users to top-up less than the minimum stake.
=> Allow to top-up less than the min stake- dapp

pkg/chain/gen/abi/Authorizations.go, pkg/chain/gen/abi/StakeDelegatable.go, pkg/chain/gen/abi/StakingPortBacker.go, pkg/chain/gen/abi/TokenSender.go, pkg/chain/gen/abi/TokenStaking.go, pkg/chain/gen/abi/TokenStakingEscrow.go, pkg/chain/gen/cmd/TokenGrant.go, pkg/chain/gen/cmd/TokenStaking.go, pkg/chain/gen/contract/TokenGrant.go, pkg/chain/gen/contract/TokenStaking.go, pkg/net/gen/pb/handshake.pb.go
Regenerated Go code for contracts and commands to reflect the most recent version of Solidity code.
=> Regenerated generated Go contract and command bindings

solidity/dashboard/src/config/config.json
Updating Infura's endpoint to increase total request limits in Keep Dashboard dApp.
=> New Infura endpoint

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml, solidity/dashboard/package-lock.json, solidity/dashboard/package.json
Updating Keep Token Dashboard dApp version to v1.3.4
=> Releases/mainnet/token dashboard/v1.3.4

solidity/dashboard/src/components/TokensContextSwitcher.jsx, solidity/dashboard/src/components/skeletons/CardSkeleton.jsx, solidity/dashboard/src/components/skeletons/TokenAmountSkeleton.jsx, solidity/dashboard/src/components/skeletons/TokenBalancesOverviewSkeleton.jsx, solidity/dashboard/src/pages/TokenOverviewPage.jsx
Closes: #2071 
This PR adds the loading skeletons for Overview page and for top pane on the Delegated Tokens page to improve UX.
=> Loading wrappers

docs/status-reports/tbtc-2020-09-15-to-2020-10-13.adoc
This details various issues, actions, and statistics of the technical
side of tBTC's first month.
=> One Month: Add a status report for first month of tBTC

docs/status-reports/tbtc-2020-09-15-to-2020-10-13.adoc
Cleaned-up version of #2132 without merge commits.
=> Adjust link displaytext to correct deposit size

solidity/package-lock.json, solidity/package.json
931691b updates version in `package-lock.json` to `1.4.0` and it's been tagged as `solidity/v1.4.0`
2c5f588 updates version in `package-lock.json` to `1.5.0-pre.0` for further development.
=> Release solidity/v1.4.0

solidity/dashboard/src/sagas/subscriptions.js
This PR fixes the error that appears when updating APY after Minting/Burning transaction.
=> Fix updateAPY call in subscribtions

solidity/dashboard/src/components/LiquidityRewardCard.jsx, solidity/dashboard/src/components/ProgressBar.jsx, solidity/dashboard/src/components/TokenOverview.jsx, solidity/dashboard/src/utils/general.utils.js
Closes: #2275
This PR adds the `formatPercentage` function which formats the value to the right format. Eg:
* 70.2028990 -> 70.2
* 70.299123 -> 70.29
* 70.00 -> 70
=> Round percentage value to 2 decimal places

docs/monitoring-and-alerting.adoc
The guide includes both metrics to monitor as well as recommended thresholds to
notify or alert on anomalies.
=> Monitoring and Alerting Guide: Added initial monitoring and alerting guide

solidity/migrations/2_deploy_contracts.js, solidity/scripts/keep-token-geyser-init.js
We should have deployed the `KeepVault` contract instead of
`KeepTokenGeyser`.
=> Fix deploying the KEEP-only pool contract to local network

docs/status-reports/2020-11-11-retro-geth-hardfork.adoc
Add the geth hardfork retro to the repo.
This has been shared widely in Discord and such, but never landed in the
actual repository.
=> Incidentally Retrospective

solidity/dashboard/src/components/Footer.jsx, solidity/dashboard/src/css/footer.less, solidity/dashboard/src/pages/earnings/TBTCRewardsPage.jsx
- Updates our Keep-core version to a link going out to our releases page, Closes #2313 
- Fixes our currency ticker for TBTC, Closes #2262
=> Footer Version link to releases page & update TBTC ticker

solidity/dashboard/src/components/KeepOnlyPool.jsx, solidity/dashboard/src/components/liquidity/RewardMultiplier.jsx, solidity/dashboard/src/css/liquidity-page.less, solidity/dashboard/src/pages/liquidity/LiquidityPage.jsx, solidity/dashboard/src/reducers/liquidity-rewards.js, solidity/dashboard/src/sagas/liquidity-rewards.js, solidity/dashboard/src/sagas/subscriptions.js, solidity/dashboard/src/services/liquidity-rewards.js
Closes: #2328 
Displays the reward boost for he KEEP ONLY pool:
=> Display boost for KEEP-only pool

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml, solidity/dashboard/package-lock.json, solidity/dashboard/package.json
KEEP Token Dashboard v1.12.0 release branch. This release will bundle the work from https://github.com/keep-network/keep-core/milestone/47?closed=1.
=> releases/mainnet/token dashboard/v1.12.0

solidity/dashboard/package-lock.json, solidity/dashboard/package.json
Set `keep-core` dependencies to point to Ropsten.
=> Update KEEP Token Dashboard version to v1.13.0-pre

solidity/package-lock.json, solidity/package.json
Upgraded truffle to the latest 5.3.1 to stabilize local environment running with
the latest geth 1.10.2.
=> Truffle upgrade to 5.3.1

solidity/dashboard/package-lock.json, solidity/dashboard/package.json
Bump KEEP Token Dashboard dapp to v1.14.0-pre
=> Bump KEEP Token Dashboard dapp to v1.14.0-pre

docs/run-random-beacon.adoc
Explained diagnostics and metrics exposed by Core client in docs.
=> Metrics and diagnostics docs

solidity/dashboard/src/rewards-allocation/rewards.json
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#862 to KEEP Token Dashboard.
=> tBTC reward allocation 2021-07-02 -> 2021-07-09

solidity/dashboard/src/rewards-allocation/rewards.json
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#866 to KEEP Token Dashboard.
=> tBTC reward allocation 2021-07-09 -> 2021-07-16

solidity/dashboard/src/rewards-allocation/rewards.json
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#869 to KEEP Token Dashboard.
=> tBTC reward allocation 2021-07-16 -> 2021-07-23

solidity/dashboard/src/components/Chip.jsx, solidity/dashboard/src/components/Timeline.jsx, solidity/dashboard/src/components/copy-stake-steps/Step4.jsx, solidity/dashboard/src/constants/colors.js, solidity/dashboard/src/css/commons.less, solidity/dashboard/src/css/coverage-pools-page.less, solidity/dashboard/src/css/timeline.less, solidity/dashboard/src/css/vars.less, solidity/dashboard/src/pages/coverage-pools/CoveragePoolPage.jsx, solidity/dashboard/src/pages/coverage-pools/HowItWorksPage.jsx, solidity/dashboard/src/pages/coverage-pools/index.js
~Depends on: #2542~
This PR adds the `How it works` page about coverage pools.
<details>
<summary>Screenshots</summary>
</details>
=> Cov pools how it works page

scripts/install-celo.sh, scripts/install.sh
This PR replaces links to contract artifacts with copies.
Tested with local setup deployment - all components were deployed successfully.
=> Replaced symbolic links to contract artefacts with copies

solidity/dashboard/src/rewards-allocation/rewards.json
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#875 to KEEP Token Dashboard.
=> tBTC reward allocation 2021-07-23 -> 2021-07-30

solidity/dashboard/src/rewards-allocation/rewards.json
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#890 to KEEP Token Dashboard.
=> tBTC reward allocation 2021-08-13 -> 2021-08-20

solidity/dashboard/src/__tests__/saga/coverage-pool.test.js, solidity/dashboard/src/__tests__/saga/rootSaga.test.js, solidity/dashboard/src/actions/coverage-pool.js, solidity/dashboard/src/components/ConfirmationModal.jsx, solidity/dashboard/src/lib/keep/__tests__/coverage-pool.test.js, solidity/dashboard/src/lib/keep/contracts/index.js, solidity/dashboard/src/lib/keep/coverage-pool/index.js, solidity/dashboard/src/lib/keep/index.js, solidity/dashboard/src/pages/coverage-pools/CoveragePoolPage.jsx, solidity/dashboard/src/reducers/coverage-pool.js, solidity/dashboard/src/sagas/coverage-pool.js, solidity/dashboard/src/sagas/subscriptions.js
This PR adds a warning modal about Coverage Pools Claim just before doing a deposit. The warning will show when there are open auctions in Risk Manager. 
<details>
<summary>Screenshot</summary>
</details>
=> Cov pools coverage claim warning before deposit

solidity/dashboard/src/__tests__/forms/commonValidators.test.js, solidity/dashboard/src/components/TokenAmount.jsx, solidity/dashboard/src/components/WithdrawAmountForm.jsx, solidity/dashboard/src/components/coverage-pools/AddAmountToWithdrawalForm.jsx, solidity/dashboard/src/components/coverage-pools/DepositForm.jsx, solidity/dashboard/src/components/coverage-pools/IncreaseWithdrawalModal.jsx, solidity/dashboard/src/components/coverage-pools/PendingWithdrawals.jsx, solidity/dashboard/src/css/coverage-pools-page.less, solidity/dashboard/src/forms/common-validators.js, solidity/dashboard/src/forms/form.utils.js, solidity/dashboard/src/hooks/useSetMaxAmountToken.js, solidity/dashboard/src/pages/coverage-pools/CoveragePoolPage.jsx, solidity/dashboard/src/utils/token.utils.js
Allows to write decimal places in Cov Pools forms and also prints KEEPs and CovKEEPs with decimals
=> Decimal places in Cov Pools

solidity/dashboard/src/rewards-allocation/rewards.json
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#915 to KEEP Token Dashboard.
=> tBTC reward allocation 2021-09-10 -> 2021-09-17

docs/rfc/rfc-19-random-beacon-v2.adoc
Proposal to simplify the pricing, rewards, and make timeouts more forgiving. Lessons learned on v1 of the random beacon.
=> RFC 19: Random Beacon v2

solidity/dashboard/src/rewards-allocation/rewards.json
Adding tBTC rewards merkle tree computed in keep-network/keep-ecdsa#918 to KEEP Token Dashboard.
=> tBTC reward allocation 2021-09-17 -> 2021-09-24

solidity/dashboard/src/__tests__/saga/coverage-pool.test.js, solidity/dashboard/src/components/coverage-pools/ClaimTokensModal.jsx, solidity/dashboard/src/components/coverage-pools/InitiateDepositModal.jsx, solidity/dashboard/src/components/coverage-pools/PendingWithdrawals.jsx, solidity/dashboard/src/components/coverage-pools/WithdrawalInfo.jsx, solidity/dashboard/src/css/modal-with-timeline.less, solidity/dashboard/src/lib/keep/__tests__/coverage-pool.test.js, solidity/dashboard/src/lib/keep/coverage-pool/index.js, solidity/dashboard/src/sagas/coverage-pool.js
This PR fixes displaying the data in the coverage pool modals.
=> Fix displaying data in the coverage pool modals

solidity/dashboard/src/components/coverage-pools/InitiateCovPoolsWithdrawModal.jsx, solidity/dashboard/src/components/coverage-pools/PendingWithdrawals.jsx
Small bug fixes:
- display user address in initate withdrawal modal
- adds tooltip content to claim tokens button
=> Cov pools improvements v3

solidity/dashboard/src/components/coverage-pools/ExchangeRate.jsx, solidity/dashboard/src/components/coverage-pools/IncreaseWithdrawalModal.jsx, solidity/dashboard/src/components/coverage-pools/InitiateCovPoolsWithdrawModal.jsx, solidity/dashboard/src/css/commons.less, solidity/dashboard/src/lib/keep/coverage-pool/index.js, solidity/dashboard/src/utils/token.utils.js
Accurate exchange rate KEEP/covKEEP with 3 decimals.
=> Accurate exchange rate KEEP/covKEEP with 3 decimals

solidity/random-beacon/README.adoc
Documentation describing how we ended up implementing v2 of the Random Beacon.
=> Random Beacon v2 README

docs/run-random-beacon.adoc
Contract deployed in job:
https://github.com/keep-network/keep-core/runs/4290199652?check_suite_focus=true
=> Document the address of KeepToken contract deployed on testnet

solidity/random-beacon/contracts/RandomBeacon.sol, solidity/random-beacon/contracts/libraries/DKG.sol, solidity/random-beacon/contracts/libraries/Groups.sol, solidity/random-beacon/contracts/test/TestModUtils.sol, solidity/random-beacon/test/Groups.test.ts, solidity/random-beacon/test/RandomBeacon.GroupCreation.test.ts
Made all require messages uppercase.
=> Made all require messages uppercase

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml, solidity-v1/dashboard/package-lock.json, solidity-v1/dashboard/package.json
=> Bump the dashboard version to v1.17.0-pre

.github/workflows/contracts-ecdsa.yml, .github/workflows/contracts-random-beacon.yml
This PR contains workflow configuration for ECDSA contracts located in `solidity/ecdsa` directory.
It also renames the existing random beacon workflow for consistency.
Depends on https://github.com/keep-network/keep-core/pull/2773
Refs https://github.com/keep-network/keep-core/issues/2758
=> GH Workflow configuration for ECDSA contracts

solidity/ecdsa/contracts/WalletRegistry.sol, solidity/ecdsa/contracts/test/StakingStub.sol, solidity/ecdsa/test/WalletRegistry.WalletCreation.test.ts, solidity/ecdsa/test/fixtures/index.ts
Refs #2758
Depends on #2792
Slashing submitter of a malicious dkg result during the dkg challenge call.
=> Slashing on challenge

.github/workflows/dashboard-v1-testnet.yml
Ref: #2796 
Resolve `@threshold-network/solidity-contracts` dependency version on
the CI side.
=> Update dashboard testnet GH workflow

solidity-v1/dashboard/src/components/modal/staking/ConfirmDelegation.jsx, solidity-v1/dashboard/src/components/modal/threshold/ContactYourGrantManagerWarning.jsx, solidity-v1/dashboard/src/constants/constants.js, solidity-v1/dashboard/src/css/vars.less
`Grant Manager` could be too confusing so we put an email address to
contact the grant manager.
<details>
<summary>Screenshots</summary>
</details>
=> Add grant manager email address

solidity/ecdsa/contracts/WalletRegistryGovernance.sol, solidity/ecdsa/test/WalletRegistryGovernance.test.ts
~~Depends on https://github.com/keep-network/keep-core/pull/2862; Keeping as a draft until #2862 is merged.~~
`WalletRegistryGovernance` contract controls governable parameters of
`WalletRegistry` contract. If it ever happens that the ownership of
`WalletRegistry` must be transferred to someone else, functionality to
transfer the ownership is now available.
=> Let to transfer WalletRegistry ownership to someone else

solidity/random-beacon/contracts/RandomBeaconGovernance.sol, solidity/random-beacon/test/RandomBeaconGovernance.test.ts
~~Depends on #2866; Keeping as a draft until #2866 is merged.~~
Closes Refs https://github.com/keep-network/keep-core/issues/2847
`RandomBeaconGovernance` contract controls governable parameters of
`RandomBeacon` contract. If it ever happens that the ownership of
`RandomBeacon` must be transferred to someone else, functionality to
transfer the ownership is now available.
=> Let to transfer RandomBeacon ownership to someone else

solidity/ecdsa/package.json, solidity/ecdsa/tsconfig.export.json, solidity/ecdsa/tsconfig.json, solidity/ecdsa/yarn.lock, solidity/random-beacon/.gitignore, solidity/random-beacon/package.json, solidity/random-beacon/tsconfig.export.json, solidity/random-beacon/tsconfig.json
Here we configure packages for publication to NPM registry. This is
consistent with configuration of @threshold-network/solidity-contracts
project.
=> Configure packages for publication

solidity-v1/dashboard/src/rewards-allocation/rewards.json, solidity-v1/dashboard/src/utils/rewardsHelper.js
Adding tBTC rewards merkle tree computed in https://github.com/keep-network/keep-ecdsa/pull/953 to KEEP Token Dashboard.
=> tBTC reward allocation 2022-01-22 -> 2022-02-22

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml, solidity-v1/dashboard/package-lock.json, solidity-v1/dashboard/package.json
=> Bump the dashboard version to 1.19.0-pre

.github/workflows/contracts-ecdsa.yml, .github/workflows/contracts-random-beacon.yml, solidity/random-beacon/contracts/RandomBeacon.sol, solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol
Slither 0.8.3 fixes issues with false validation failures from
https://github.com/crytic/slither/issues/1067
=> Use the latest Slither 0.8.3

solidity/ecdsa/contracts/WalletRegistry.sol
Depends on https://github.com/keep-network/keep-core/pull/2939
The latest slither release fixed problems with aliases validation. We can declare aliased libraries in a similar way we did in the RandomBeacon.
=> Declare aliased libraries in WalletRegistry

solidity/ecdsa/contracts/WalletRegistryGovernance.sol, solidity/random-beacon/README.adoc
Closes #2931
The section has been updated to reflect the most recent changes in smart contracts.
=> Random Beacon: "The Mechanism" README section updates

solidity/ecdsa/README.adoc, solidity/random-beacon/README.adoc
Described v2 ECDSA smart contract mechanism in English.
Described governable and non-governable parameters of `WalletRegistry`.
Closes: #2928
=> ECDSA README updates: The Mechanism + Parameters

solidity-v1/dashboard/src/rewards-allocation/rewards.json, solidity-v1/dashboard/src/utils/rewardsHelper.js
Adding tBTC rewards merkle tree computed in https://github.com/keep-network/keep-ecdsa/pull/958 to KEEP Token Dashboard.
=> tBTC reward allocation 2022-02-22 -> 2022-03-22

solidity-v1/dashboard/src/rewards-allocation/rewards.json, solidity-v1/dashboard/src/utils/rewardsHelper.js
Backport of: #2901
Adding tBTC rewards merkle tree computed in https://github.com/keep-network/keep-ecdsa/pull/958 to KEEP Token Dashboard.
=> [Backport] tBTC reward allocation 2022-02-22 -> 2022-03-22

infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml, solidity-v1/dashboard/package-lock.json, solidity-v1/dashboard/package.json
Depends on: https://github.com/keep-network/keep-core/pull/2999
=> Bump the dashboard version to 1.20.0-pre

solidity/ecdsa/package.json, solidity/ecdsa/yarn.lock, solidity/random-beacon/package.json, solidity/random-beacon/yarn.lock
Bumping to the latest version of the sortition pool
=> Bumping up keep-network/sortition-pools to 2.0.0-pre.13

CODEOWNERS
To protect from any accidental changes to an already audited code.
=> Update `CODEOWNERS` file

.github/workflows/npm-ecdsa.yml, .github/workflows/npm-random-beacon.yml, solidity/ecdsa/.gitignore, solidity/ecdsa/package.json, solidity/ecdsa/tasks/index.ts, solidity/ecdsa/tasks/initialize.ts, solidity/ecdsa/yarn.lock, solidity/random-beacon/.gitignore, solidity/random-beacon/package.json, solidity/random-beacon/tasks/initialize.ts, solidity/random-beacon/tasks/utils/authorize.ts, solidity/random-beacon/tasks/utils/index.ts, solidity/random-beacon/tasks/utils/mint.ts, solidity/random-beacon/tasks/utils/register.ts, solidity/random-beacon/tasks/utils/stake.ts
This PR adds an initialization task for ECDSA contracts. It exposes the code from the random beacon to be used in ecdsa https://github.com/keep-network/keep-core/pull/3110.
=> Initialization task for ECDSA contracts

solidity/ecdsa/tasks/initialize.ts, solidity/ecdsa/yarn.lock
Depends on https://github.com/keep-network/keep-core/pull/3123
The functions signatures were updated in https://github.com/keep-network/keep-core/pull/3123 so we need to align.
=> Update authorize and register calls  in ECDSA tasks

solidity/ecdsa/contracts/WalletRegistry.sol, solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2.sol, solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2MisplacedNewSlot.sol, solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2MissingSlot.sol, solidity/random-beacon/contracts/RandomBeacon.sol, solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol
Fixed some spelling errors in contracts code.
=> Fixed spelling errors

infrastructure/kube/keep-test/geth-node/eth-goerli-node.yaml
- expanded capacity for PVC to 200GB
- changed `args` view to real list
=>  #3012 Expand PV capacity

.github/workflows/client.yml, go.mod, go.sum
The argument should point to the environment for which the client should be built. The environment is used to generate contract bindings and pull addresses for contracts.
=> Pass ENVIRONMENT argument for Docker build

solidity/ecdsa/contracts/WalletRegistry.sol, solidity/random-beacon/contracts/RandomBeacon.sol, solidity/random-beacon/contracts/libraries/BeaconDkg.sol
A few more spelling error fixes.
=> Spelling errors fix

pkg/beacon/dkg/dkg.go, pkg/beacon/gjkr/protocol.go, pkg/chain/ethereum/beacon.go, pkg/chain/ethereum/tbtc.go, pkg/net/gen/gen.go, pkg/net/security/handshake/connection_handshake.go
Here we revert some formatting changes introduced by accident within 7a90edd6
=> Revert accidental formatting changes

docs/resources/client-start-help, docs/run-keep-node.adoc
Describe more about system considerations and add links.
Add more about networking.
Update output of start command's help.
=> Update Run Keep Node documentation

cmd/helpers.go, cmd/start.go, docs/run-keep-node.adoc, pkg/chain/ethereum/signer.go, pkg/chain/local_v1/signer.go, pkg/chain/signing.go
When the node starts we print usefull information in the header.
We could add the Operator adress there as well. Here we expose the
address.
So the header would look like:
```
▓▓▌ ▓▓ ▐▓▓ ▓▓▓▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓    ▓▓▓▓▓▓▓▀    ▐▓▓▓▓▓▓    ▐▓▓▓▓▓   ▓▓▓▓▓▓     ▓▓▓▓▓   ▐▓▓▓▓▓▌   ▐▓▓▓▓▓▓
▓▓▓▓▓▓▄▄▓▓▓▓▓▓▓▀      ▐▓▓▓▓▓▓▄▄▄▄         ▓▓▓▓▓▓▄▄▄▄         ▐▓▓▓▓▓▌   ▐▓▓▓▓▓▓
▓▓▓▓▓▓▓▓▓▓▓▓▓▀        ▐▓▓▓▓▓▓▓▓▓▓         ▓▓▓▓▓▓▓▓▓▓▌        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓▀▀▓▓▓▓▓▓▄       ▐▓▓▓▓▓▓▀▀▀▀         ▓▓▓▓▓▓▀▀▀▀         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▀
▓▓▓▓▓▓   ▀▓▓▓▓▓▓▄     ▐▓▓▓▓▓▓     ▓▓▓▓▓   ▓▓▓▓▓▓     ▓▓▓▓▓   ▐▓▓▓▓▓▌
▓▓▓▓▓▓▓▓▓▓ █▓▓▓▓▓▓▓▓▓ ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓ …
```
=> Print Operator address in the node header

go.mod, scripts/ubuntu-setup.sh
This PR is a follow-up for https://github.com/keep-network/keep-core/pull/3257
=> Follow-up for protobuf upgrade

cmd/helpers.go
Add client version information to the node header.
Sample:
```
▓▓▌ ▓▓ ▐▓▓ ▓▓▓▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓    ▓▓▓▓▓▓▓▀    ▐▓▓▓▓▓▓    ▐▓▓▓▓▓   ▓▓▓▓▓▓     ▓▓▓▓▓   ▐▓▓▓▓▓▌   ▐▓▓▓▓▓▓
▓▓▓▓▓▓▄▄▓▓▓▓▓▓▓▀      ▐▓▓▓▓▓▓▄▄▄▄         ▓▓▓▓▓▓▄▄▄▄         ▐▓▓▓▓▓▌   ▐▓▓▓▓▓▓
▓▓▓▓▓▓▓▓▓▓▓▓▓▀        ▐▓▓▓▓▓▓▓▓▓▓         ▓▓▓▓▓▓▓▓▓▓▌        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓▀▀▓▓▓▓▓▓▄       ▐▓▓▓▓▓▓▀▀▀▀         ▓▓▓▓▓▓▀▀▀▀         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▀
▓▓▓▓▓▓   ▀▓▓▓▓▓▓▄     ▐▓▓▓▓▓▓     ▓▓▓▓▓   ▓▓▓▓▓▓     ▓▓▓▓▓   ▐▓▓▓▓▓▌
▓▓▓▓▓▓▓▓▓▓ █▓▓▓▓▓▓▓▓▓ ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓
▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓ ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓
Trust math, not hardware. …
```
=> Add version info to the node's header

.gitignore
In this PR we cleanup `.gitignore` file. Please see the commit's descriptions for details.
=> Gitignore cleanup

infrastructure/kube/keep-test/keep-client/gen/data.yaml, infrastructure/kube/keep-test/keep-client/gen/template.yaml, infrastructure/kube/keep-test/keep-client/keep-clients.yaml
This PR contains updates to the keep-client node's configuration on keep-test.
Please see the commits descriptions for details.
=> Reconfigure keep-test nodes

cmd/start.go, pkg/beacon/node.go, pkg/clientinfo/diagnostics.go, pkg/clientinfo/metrics.go, pkg/tbtc/node.go
Depends on https://github.com/keep-network/keep-core/pull/3310
This PR contains some improvements to metrics and diagnostics that will help integrate Prometheus with the clients.
=> Improvements to client info metrics and diagnostics

solidity/ecdsa/contracts/EcdsaDkgValidator.sol, solidity/ecdsa/contracts/WalletRegistry.sol, solidity/ecdsa/contracts/WalletRegistryGovernance.sol, solidity/ecdsa/contracts/api/IWalletOwner.sol, solidity/ecdsa/contracts/api/IWalletRegistry.sol, solidity/ecdsa/contracts/libraries/EcdsaAuthorization.sol, solidity/ecdsa/contracts/libraries/EcdsaDkg.sol, solidity/ecdsa/contracts/libraries/EcdsaInactivity.sol, solidity/ecdsa/contracts/libraries/Wallets.sol, solidity/ecdsa/contracts/test/RandomBeaconStub.sol, solidity/ecdsa/contracts/test/WalletRegistryStub.sol, solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2.sol, solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2MisplacedNewSlot.sol, solidity/ecdsa/contracts/test/upgrades/WalletRegistryV2MissingSlot.sol, solidity/ecdsa/hardhat.config.ts, solidity/ecdsa/package.json, solidity/ecdsa/yarn.lock
See https://github.com/threshold-network/solidity-contracts/pull/127
See https://github.com/keep-network/sortition-pools/pull/189
See https://github.com/keep-network/keep-core/pull/3318
Fix Solidity version on 0.8.17 before the deployment.
=> Solidity 0.8.17

configs/config.toml.SAMPLE
Metrics and Diagnostics config properties were replaced by the ClientInfo.
=> Update metrics and diagnostics to clientinfo in config sample

solidity/ecdsa/deploy/03_deploy_wallet_registry.ts, solidity/random-beacon/deploy/04_deploy_random_beacon.ts
=> Leaving the default authorization decrease delay of 45 days

pkg/generator/pool.go, pkg/generator/pool_test.go
This is an alternative approach to the fix presented in #3359. Please see [this](https://github.com/keep-network/keep-core/pull/3359#discussion_r997928620) dicussion.
If the context for generating the pre-parameters has been canceled, we should not leave the generator goroutine dangling on writing to the channel.
Here is the problematic scenario detected by @tomaszslabon:
1. The pool is full (1000 parameters) and we generate one additional parameter
2. Some procedure (e.g DKG) happens - since the param generation goroutine hangs on writing to the pool it's not stopped (we have 1 goroutine hanging)
3. We resume the param generation creating another goroutine - it generates one parameter (1001st) and hangs (we have 2 goroutines hanging)
This scenario is happening again and again and we end …
=> Do not wait on writing to pool if the context got canceled

infrastructure/kube/keep-prd/monitoring/README.adoc, infrastructure/kube/keep-prd/monitoring/grafana/config/dashboards.yaml, infrastructure/kube/keep-prd/monitoring/grafana/config/datasources.yaml, infrastructure/kube/keep-prd/monitoring/grafana/config/grafana.ini, infrastructure/kube/keep-prd/monitoring/grafana/dashboards/keep/keep-nodes-public.json, infrastructure/kube/keep-prd/monitoring/grafana/dashboards/keep/keep-nodes.json, infrastructure/kube/keep-prd/monitoring/grafana/grafana-deployment.yaml, infrastructure/kube/keep-prd/monitoring/grafana/grafana-pvc.yaml, infrastructure/kube/keep-prd/monitoring/grafana/grafana-service.yaml, infrastructure/kube/keep-prd/monitoring/grafana/kustomization.yaml, infrastructure/kube/keep-prd/monitoring/monitoring-ingress.yaml, infrastructure/kube/keep-prd/monitoring/prometheus/config/config.yaml, infrastructure/kube/keep-prd/monitoring/prometheus/kustomization.yaml, infrastructure/kube/keep-prd/monitoring/prometheus/prometheus-deployment.yaml, infrastructure/kube/keep-prd/monitoring/prometheus/prometheus-pvc.yaml, infrastructure/kube/keep-prd/monitoring/prometheus/prometheus-service.yaml, infrastructure/kube/keep-prd/monitoring/storage-class.yaml, infrastructure/kube/keep-prd/monitoring/trickster/config/trickster.yaml, infrastructure/kube/keep-prd/monitoring/trickster/kustomization.yaml, infrastructure/kube/keep-prd/monitoring/trickster/trickster-deployment.yaml, infrastructure/kube/keep-prd/monitoring/trickster/trickster-service.yaml
In this PR we add a configuration of monitoring for the production environment.
The configuration is based on a couple of PRs deployed and tested on the keep-test environment:
https://github.com/keep-network/keep-core/pull/3353
https://github.com/keep-network/keep-core/pull/3357
https://github.com/keep-network/keep-core/pull/3373
The following resources are exposed:
Public Dashboard: https://public.monitoring.threshold.network
Grafana: https://monitoring.threshold.network/grafana
Prometheus: https://monitoring.threshold.network/prometheus
=> Monitoring configuration for production

config/_peers/mainnet
Here we add mainnet bootstrap nodes maintained by Staked.
=> Add Staked bootstrap nodes for mainnet

pkg/tbtc/signing_done.go, pkg/tbtc/signing_done_test.go, pkg/tbtc/signing_loop.go, pkg/tbtc/signing_loop_test.go
Consider the following scenario: three members in a signing group: Bob, Eve, and Alice. They all participate in signing and are expected to confirm they are done.
Bob finishes signing at block 1000.
Eve finishes signing at block 1001.
Alice finishes signing at block 1013.
Bob starts signaling he is done at block 1000.
Eve starts signaling she is done at block 1001.
Alice starts signaling she is done at block 1013.
This all looks good except that in the previous version of the done check, Eve was not accepting Done messages from Bob before block 1001 and Alice was not accepting Done messages from Bob and Eve before block 1013. Eve and Alice had to count on retransmissions.
Since we use a backoff strategy for retransmissions (`R _ R _ _ R _ _ _ _ R _ _ _ _ _ _ _ _ R...`), they could be …
=> Split the signing done check into a listen and a wait phases

pkg/bitcoin/block.go, pkg/bitcoin/block_test.go
This PR adds implementation of block header serialization function.
=> Block header serialization

README.adoc
=> Fix: minor typo

solidity/ecdsa/export.json, solidity/ecdsa/external/mainnet/RandomBeaconChaosnet.json
The contract was deployed to mainnet.
=> Add RandomBeaconChaosnet mainnet deployment artifact

CONTRIBUTING.adoc, README.adoc
The CONTRIBUTING file was already 99% of the way there in this repo, so I did a pass to
+ standardize line length to 80 characters
+ change `master` to `main`
+ drop some redundant words
=> Polish Pass on CONTRIBUTING.adoc

config/_peers/mainnet
The original PR was opened by @antonr-p2 here: https://github.com/keep-network/keep-core/pull/3499
There were problems with commit signing and I could not merge that PR. Given it's a PR from a fork I was not able to rebase it with my signature. 
I am submitting the original change in this PR and closing https://github.com/keep-network/keep-core/pull/3499 in favor of this one.
=> P2P bootstrap nodes for mainnet

scripts/build.sh
The build script contains now all needed elements:
1. Build of binaries,
2. Build of a docker image.
=> Client Docker image build command added to the build script

cmd/flags.go, cmd/flags_test.go, cmd/maintainer.go, config/config_test.go, pkg/maintainer/config.go, pkg/maintainer/maintainer.go, pkg/maintainer/spv/config.go, pkg/maintainer/spv/spv.go, test/config.json, test/config.toml, test/config.yaml
Refs: https://github.com/keep-network/keep-core/issues/3615.
This PR enables launching of the SPV maintainer.
=> Enable launching of SPV maintainer

pkg/bitcoin/electrum/electrum_integration_test.go
To reduce the time required for the electrum integration tests execution we run the tests in parallel.
Refs: https://github.com/keep-network/keep-core/issues/3586
=> Run electrum integration tests in parallel

pkg/maintainer/wallet/chain_test.go, pkg/maintainer/wallet/internal/test/marshaling.go, pkg/maintainer/wallet/internal/test/testdata/find_pending_redemptions_scenario_0.json, pkg/maintainer/wallet/internal/test/testdata/find_pending_redemptions_scenario_1.json, pkg/maintainer/wallet/internal/test/testdata/find_pending_redemptions_scenario_2.json, pkg/maintainer/wallet/internal/test/testdata/find_pending_redemptions_scenario_3.json, pkg/maintainer/wallet/internal/test/testdata/find_pending_redemptions_scenario_4.json, pkg/maintainer/wallet/internal/test/testdata/find_pending_redemptions_scenario_5.json, pkg/maintainer/wallet/internal/test/wallettest.go, pkg/maintainer/wallet/redemptions_test.go
Closes: https://github.com/keep-network/keep-core/issues/3614
Here we add missing unit tests for the wallet maintainer redemption code.
=> Unit tests for wallet maintainer redemptions

pkg/bitcoin/script.go, pkg/bitcoin/script_test.go, pkg/chain/ethereum/tbtc.go, pkg/maintainer/spv/chain.go, pkg/maintainer/spv/config.go, pkg/maintainer/spv/redemptions.go, pkg/maintainer/spv/spv.go, pkg/maintainer/wallet/chain.go, pkg/maintainer/wallet/chain_test.go, pkg/maintainer/wallet/redemptions.go, pkg/tbtc/chain.go, pkg/tbtc/chain_test.go, pkg/tbtc/redemption.go
Refs: https://github.com/keep-network/keep-core/issues/3615
Depends on: https://github.com/keep-network/keep-core/pull/3669
This changeset adds redemption support to the SPV maintainer.
=> Support for redemption SPV proofs

pkg/maintainer/spv/bitcoin_chain_test.go, pkg/maintainer/spv/chain_test.go, pkg/maintainer/spv/deposit_sweep.go, pkg/maintainer/spv/deposit_sweep_test.go, pkg/maintainer/spv/spv_test.go
Refs #3615
This PR adds unit tests for functionalities related to deposit sweep SPV proofs.
=> Unit tests for deposit sweep SPV proof

pkg/maintainer/wallet/deposit_sweep.go
The script type resolution requires access to transaction data stored on the Bitcoin blockchain. If the given transaction hasn't actually happened but was revealed as deposit to the `Bridge`, the maintainer will not be able to resolve the deposit script type. So far, an error was returned in that case and the maintainer stopped the entire deposit sweep task. This cannot happen as the maintainer can be blocked on deposit sweeps for a long time. Instead, the maintainer should log an error and leave the deposit type unresolved.
=> Wallet maintainer: Resolve deposit script type at the very end

pkg/chain/ethereum/tbtc/gen/abi/WalletProposalValidator.go, pkg/chain/ethereum/tbtc/gen/cmd/WalletProposalValidator.go, pkg/chain/ethereum/tbtc/gen/contract/WalletProposalValidator.go
This PR updates the bindings code for the `WalletProposalValidator` contract.
=> Regenerated bindings for WalletProposalValidator

pkg/tbtc/coordination.go, pkg/tbtc/coordination_test.go, pkg/tbtc/node.go
This pull request backports https://github.com/keep-network/keep-core/pull/3803 to the `releases/mainnet/v2.0.1` branch.
=> [Backport] Increase deposit sweep frequency

pkg/tbtc/inactivity.go
This PR contains a fix related to logs formatting.
=> Fix logging
